### ISSUE TITLE
Multiples pictures are don't displayed correctly

### ISSUE THREAD

**Issue by pyrog** [pietervdvn/MapComplete#100]
In this [example](https://www.openstreetmap.org/node/5718392307), there are 2 pictures in `wikimedia_commons` tag.
See it in [MapComplete](https://pietervdvn.github.io/MapComplete/aed.html?z=19&lat=45.898&lon=6.1238).

**Comment by pyrog** [comment]
Kick fix, nice 😎 

And it's know online 😃

**Comment by pietervdvn** [comment]
<3

Thanks for reporting it in the first place
