### ISSUE TITLE
Layout when editing tags

### ISSUE THREAD

**Issue by pyrog** [pietervdvn/MapComplete#101]
The text box is too small and key/value is split on two lines.
Last one could be written at the beginning of the line ?

Also the box/text is a bit too big.
Is it possible to use smaller font size (at least on a PC) ?

<img width="50%" alt="Capture d’écran 2020-08-25 à 15 29 45" src="https://user-images.githubusercontent.com/2158081/91180460-09d55b00-e6e8-11ea-8043-8dda2b30167d.png">

**Comment by pietervdvn** [comment]
I've improved the tag rendering already a bit (long values are shortened; and they get a new line for themselves).

**Comment by pietervdvn** [comment]
Most of the issues you pointed out have been fixed: the textbox is now full-width, the tags are on a new line

**Comment by pyrog** [comment]
Thank you Pieter 😃
