### ISSUE TITLE
Sports map - outdoor gym, crossfit etc

### ISSUE THREAD

**Issue by hermann-san** [pietervdvn/MapComplete#1015]
it would be nice to have [fitness station](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_station), outdoor gym, Street Workout, Calisthenics Park or trim trail added to a map. Either new map or on existing Sport pitch map

possible Symbol  (Public Domain lic - according to [DuckDuckgo image search](https://duckduckgo.com/?q=crossfit+symbol&t=ffsb&iar=images&iax=images&ia=images&iaf=license%3APublic&iai=https%3A%2F%2Fsvgsilh.com%2Fsvg%2F3409475.svg)
thanks!
![th-131635654](https://user-images.githubusercontent.com/7679654/182583101-7ce8e63f-f059-457c-84d5-0efa34114087.jpeg)

**Comment by pietervdvn** [comment]
Hi,

There is an unfinished 'fitness station map' on the wiki.
However, some work is needed to get this included in the 'sports'-theme, such as an icon fitting the other icons etc...

Documentation on how this can be added is over [here](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md)

**Comment by hermann-san** [comment]
Hi, do you mean the OSM Wiki? I couldn't find a theme there
https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfitness_station

Or is it a MapComplete wiki. I couldn't find that either. 
Thanks.

**Comment by pietervdvn** [comment]
On [the mapcomplete wiki page](https://wiki.openstreetmap.org/wiki/MapComplete): see 'unofficial themes'-section

**Comment by RobinLinde** [comment]
I've got a basic sports theme in the `feature/fitness-station` branch. Also testing out Netlify out on my fork, so a demo is available [here](https://feature-fitness-station--incredible-chebakia-f786f6.netlify.app/sports.html)
