### ISSUE TITLE
Cycle track details

### ISSUE THREAD

**Issue by mikeharris2017** [pietervdvn/MapComplete#1018]
Hi,
While on vacation, I saw the cycle trail beside the road and I was also using them. To improve the quality of OSM and trail improvements, I wondered, if there is the possibility to comment on existing trails. I would like to verify the surface quality and adjust it if possible, comment on changed surfaces with auto-adjustments of the track in OSM. Questions like: usable by bike category (Mountain Bike, Gravel, City, Race, cargo, etc) l, bike path on the steet ir separate, cycling on the road or in bike patchs,… In the end it should be possible to inquire where bike paths beside the main road are available and where improvements are required. 

If you need the concrete questions, please let me know and give me some time. I am happy to support you. 

Cheers,
Markus

**Comment by pietervdvn** [comment]
I'm closing this issue as non-actionable
