### ISSUE TITLE
Etymology: improve street name preprocessing

### ISSUE THREAD

**Issue by reinerh** [pietervdvn/MapComplete#1024]
When you select a street in the etymology theme, which has not yet been tagged with a Wikidata ID, MapComplete will "clean" the street name by e.g. dropping the "Straße" (street) part from the street name.
But it does not do that for "Weg" (way), which is also quite common im Germany.

Additionally it would be nice if it would already replace dashes (also common in street names) with spaces.

**Comment by pietervdvn** [comment]
Hi,

Thanks for the remark. I'm trying to get as many people involved in helping to maintain this, as I'm not able to keep up with all the requests myself.

You can add terms that should be removed yourself in the configuration file [here](https://github.com/pietervdvn/MapComplete/blob/5d9582cb30b7d2ab800df9bd744a1a280a63098e/assets/layers/etymology/etymology.json#L184). There is a category for prefixes and postfixes that should be removed, which each contain a list for every language.

Feel free to open a pull request.

**Comment by eMerzh** [comment]
since this is fixed, we can now close the issue... thanks for the contribution btw 🎉
