### ISSUE TITLE
Phone number formatting

### ISSUE THREAD

**Issue by habi** [pietervdvn/MapComplete#103]
Awesome project!
I want to add a (Swiss) phonenumber to a POI.
It's something along the lines of +41 31 333 22 11.
When I copy-paste the number from the website of the POI it's without the international prefix.
I cannot add this prefix in front of the number due to the automatic formatting in the field.

**Comment by pietervdvn** [comment]
Normally, the website should add the prefix automatically. If I paste the international phone number, it just works.

When I tried it with 031 333 222 11, I removed the 0 and typed a +4. The automatic formatting changed that to +43 13 33 22 11, after which I could insert the missing 1: +41 313 33 22 11.

Is this acceptable behaviour?

**Comment by habi** [comment]
I copy the number from the POI website, without prefix.
When I add the +4 before removing the leading zero, the cursor jumps to the end of the form field, then I type a 1 (for +41) which gets added at the end of the phone number.

If you do it in the order you mention, then it works, but when adding the +41 in front before removing the 0, then the cursor jumps around, potentially confusing the user.
I don't have a good idea on how to do the formatting properly, maybe only after the user pressed 'save'?

**Comment by pietervdvn** [comment]
At this point, the phone number is saved in the correct formatting, but is not overwritten in the textfield - so we get the best of both worlds.

(Note: this code isn't deployed yet)
