### ISSUE TITLE
nomade browser : create a dashboard for the main screen (smartphone)

### ISSUE THREAD

**Issue by JLZIMMERMANN** [pietervdvn/MapComplete#1068]
While using a smartphone a dashboard (like Symbaloo) would be welcome to let find quickly the logical theme quests that would let us easily to contribute.
 ![IMG_20220906_190003.jpg](https://user-images.githubusercontent.com/4929752/188720032-ace266ea-7c41-41fe-8862-f023303e043f.jpg)

**Comment by pietervdvn** [comment]
I do think you didn't discover the [homepage aka index](https://mapcomplete.osm.be/) yet. If not, feel free to reopen this issue.

**Comment by JLZIMMERMANN** [comment]
Indeed the index is like a long listing with pictogram and short text but not really compact.
I keep thinking that a dashboard is welcome.
