### ISSUE TITLE
Kerb map : missing picture ability

### ISSUE THREAD

**Issue by JLZIMMERMANN** [pietervdvn/MapComplete#1070]
This map is very interesting to help municipality to understand how to improve road works helping disabled people. 

This is why the option of taking pictures is really welcome to give proof of surveying. ![Screenshot_2022-09-06-22-02-15-793_com.android.chrome.jpg](https://user-images.githubusercontent.com/4929752/188728779-ef391a00-2b18-4c17-ace6-33068444e5d6.jpg)

**Comment by pietervdvn** [comment]
Oh, seems like we forgot to enable it.

I'm trying to get as much people as possible to help out with the maintanence an this is an excellent first step.

Would you mind adding the 'images'-block on the layer via a PR? You can do this by adding the string `"images"` as first entry here: https://github.com/pietervdvn/MapComplete/blob/14788c32b957bd5c613fd6057f71d08d42d5caa7/assets/layers/kerbs/kerbs.json#L60

**Comment by JLZIMMERMANN** [comment]
I have never done pull request. It means I need to have one version on my computer to modify some codes ?

**Comment by RobinLinde** [comment]
GitHub also has some documentation: https://docs.github.com/en/repositories/working-with-files/managing-files/editing-files#editing-files-in-another-users-repository
