### ISSUE TITLE
Loading problems in Open Etymology Map

### ISSUE THREAD

**Issue by DarioYiyi** [pietervdvn/MapComplete#1077]
By using Open Etymology Map there is a problem about loading process while searching for a Wikidata item. 
When you search for a name, no results appear, but only the word "Loading..." (see the image below).

This has been happening for two days with Chrome, Firefox and Edge.

![image](https://user-images.githubusercontent.com/99973662/189476412-618a7170-5c70-4ae5-8aec-afb76caa4a45.png)

**Comment by eMerzh** [comment]
Hey thanks @DarioYiyi for the report, a fix has been made in #1071 but is now deployed yet... you can use  https://pietervdvn.github.io/mc/develop/etymology.html if you need that now...

**Comment by pietervdvn** [comment]
This is a good reason to deploy to master - which I've done a few minutes ago. Fix should be live in about 30mins on mapcomplete.osm.be
