### ISSUE TITLE
Some tweaks about URLs

### ISSUE THREAD

**Issue by yopaseopor** [pietervdvn/MapComplete#108]
-First of all when you copy the URL of the quest from CustomGenerator it copies the URL of the PREVIEW TESTING quest (with test=true). To make the quest fully useful I have to change the URL deleting that manually or go to the Share tab in the test and copy that.
-Also people wish a shortener for the resulting URL. When you paste in some places people go nuts.
-It could be interesting to take the stats of https://pietervdvn.goatcounter.com/?hl-period=month&period-start=2020-07-27&period-end=2020-08-27&filter= to other level similar to https://wiki.openstreetmap.org/wiki/User:Yopaseopor#Quest_types (test) where people can access and edit that successful quest around the world.

**Comment by pietervdvn** [comment]
1. Is not relevant anymore as there is a new custom theme builder
2. It is now possible to put the JSON in a wiki page on wiki.openstreetmap.org to make the URLS shorter, e.g. [this wikipage](https://wiki.openstreetmap.org/wiki/User:Yopaseopor/velocidad) which results in [ŧhis mapcomplete](https://pietervdvn.github.io/Staging/index.html?z=16&lat=41.224&lon=1.7084&userlayout=wiki%253AUser%253AYopaseopor%252Fvelocidad#element). I have taken the liberty to create a subpage in your user space - I hope you can live with that! (Also: this feature is in staging only ATM)
3. Ideas about statistics are welcome in #29 (and are currently out of scope, but [OsmCha](https://osmcha.org/?filters=%7B%22comment%22%3A%5B%7B%22label%22%3A%22%23mapcomplete%22%2C%22value%22%3A%22%23mapcomplete%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222020-07-05%22%2C%22value%22%3A%222020-07-05%22%7D%5D%7D) can generate some statistics too. Editing 'successful quests' is pretty possible too now.
