### ISSUE TITLE
Quest : shop=vacant

### ISSUE THREAD

**Issue by JLZIMMERMANN** [pietervdvn/MapComplete#1083]
Fact : during Covid period there have been quite a lot of shops, offices and restaurants that have been closed. 

Idea : the map showing shop or restaurant could highlight the places that are vacant. 
In case of a specific map, we could let take pictures and fill a form with a description.

**Comment by pietervdvn** [comment]
Hi,

Thanks for your suggestion, but I'm not entirely sure what you want. I guess you want to improve the ['shops'-theme](mapcomplete.osm.be)?

There already is the 'delete-but-actually-mark-different'-option as 'disused': https://github.com/pietervdvn/MapComplete/blob/34ef6ce40ed80dde164f80d67b943228f74a9154/assets/layers/shops/shops.json#L238

**Comment by pietervdvn** [comment]
I'm closing this issue, as it is currently non-actionable.
