### ISSUE TITLE
highlight shop=vacant

### ISSUE THREAD

**Issue by JLZIMMERMANN** [pietervdvn/MapComplete#1093]
In the shop quest, it would be welcome to highligth and give a specific pictogram or a red dot for shop=vacant or disused:shop=* .
Here you have an example in Avignon 
![image](https://user-images.githubusercontent.com/4929752/194692373-107ce73f-a3e8-474a-9f4c-2f39c4813292.png)
It's hard to catch the POI that is not displayed.
https://mapcomplete.osm.be/shops.html?z=20&lat=43.94916&lon=4.808386&language=fr#node/1796925423

**Comment by pietervdvn** [comment]
I have added a dedicated symbol for it:

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/318bdd5e-cdf4-47da-aea3-88890807e975)

**Comment by JLZIMMERMANN** [comment]
Really great !!!
