### ISSUE TITLE
Performance Issues on UK Addresses

### ISSUE THREAD

**Issue by JamesLMilner** [pietervdvn/MapComplete#1094]
Hello! 

When checking out the UK Addresses theme locally I noticed some performance issues which are happening.

Using Chrome developer tools I took a look at which parts of the app are taking the longest to run and to try and identify potential bottle necks.

Locally we can see tasks that are running for 100s of milliseconds - this blocks rendering and causes the app to feel ‘janky’. As you pan around this causes the app to block and makes the app unresponsive.

It seems the initial set of blocking is causes by the `updateMetaTags` function which takes 100+ milliseconds (anything over 16 milliseconds will cause a frame skip).

![image](https://user-images.githubusercontent.com/8822075/194698826-d95062fb-21a2-43d7-9c59-6f2d4f75ec8d.png)

The `getClientBindingRect` function in `mouseUp` also seems to be blocking for 100+ ms. 

![image](https://user-images.githubusercontent.com/8822075/194698844-a81ce34a-6f09-45e9-ab47-ee041de03744.png)
 
If we disable `updateMetaTags` function we can see that the bottleneck seems to be `UIEventSource.setData -> ListnerTracker.ping -> TileHierachyMerger.registerTile`:

![image](https://user-images.githubusercontent.com/8822075/194698887-bf3b2bf0-b45d-4de8-8651-3dbca4924154.png)

It seems there is no issue with the underlying app as if we disable the custom layer the performance seems okay:

![image](https://user-images.githubusercontent.com/8822075/194698943-ec017ba8-55d4-4b05-8ee8-dccf97614dc8.png)

**Proposed Fixes**

From my observations, although it is not obvious from the Chrome development traces, the underlying cause seems to be because of the markers used for the icons. 

I found if you do the following things:

* Figure out how to optimise/disable updateMetaTags
* set `preferCanvas: true` in [the map construction options](https://github.com/pietervdvn/MapComplete/blob/21b3990723592574290285ee04cebcc39ea67df4/UI/Base/MinimapImplementation.ts#L209) 
* Use a circleMarkers instead of the marker, this makes it use canvas for the markers rather than HTML elements [here](https://github.com/pietervdvn/MapComplete/blob/b541d3eab49761faf710893386e9bee2801ff533/UI/ShowDataLayer/ShowDataLayerImplementation.ts#L315) 

Then the performance seems to _dramatically_ improved:

![image](https://user-images.githubusercontent.com/8822075/194703858-1f69f5fa-7232-483e-8fea-1661aa730c21.png)

You do however lose the custom markers so there is some trade off, but to me it feels worth it. If it is a concern you could look at using something like https://github.com/francoisromain/leaflet-markers-canvas, copying their implementation.

Any remaining performance issues look like they could be solved by chunking up tasks into smaller ones (Following a guide like this one: https://web.dev/optimize-long-tasks/), for example 

Hope this is helpful, let me know if you have any thoughts.

**Comment by pietervdvn** [comment]
Hi James,

An important part of the UK-adresses-theme is comparing possible addresses with already known addresses in order to show a different icon. This is an CPU intensive task. So, of course, if you disable this, the app will go faster.

Furthermore, the UK-adresses theme was a comissioned project which (on my part) is finished and is not widely used, so there is little incentive for me to make improvements (certainly because there are other performance issues which'll have more impact for all themes).

The 'setData' function is part of the core of the half-baked framework underpinning everything. As such, it is no surprise that some of them take some time.

So, I'm not gonna be making improvements here but if you or someone elsemake improvements, I'd love a PR! (Be warned that these parts are the most complicated parts of the codebase)

**Comment by JamesLMilner** [comment]
Hi Pieter,

Thanks for you update., sorry in taking so long to reply to this issue. Thanks again for all your hard work on the project. What you said makes sense, although I hope my analysis is useful if anyone else wants to pick this up. I do think there's a big benefit to be made if [leaflet-canvas-marker](https://github.com/francoisromain/leaflet-markers-canvas) was to be used for markers for any theme that uses a lot of markers :) 

I wish you all the best for the project into the future!
