### ISSUE TITLE
Quest editor is not responding as I expect sometimes

### ISSUE THREAD

**Issue by yopaseopor** [pietervdvn/MapComplete#114]
Nor the quest fo surfaces you have done is working. Now an error says 
![image](https://user-images.githubusercontent.com/5250646/91480095-bd824a80-e8a2-11ea-8dee-08e144407446.png)

**Comment by yopaseopor** [comment]
Also I discovered form is not saving the answer if it is not one of the proposed answer and you tipped it.

**Comment by pietervdvn** [comment]
Hey,

I have made another big version. The good news is that there is a way better custom theme editor - including true multilingual support. The bad news is that the format changed and the old themes are not working anymore...

**Comment by yopaseopor** [comment]
This big version is good...but it is starting to be so complicated. I return to need a complete done model to modify it. Also I think there is some mistake because a second question is not showing itself.
-Could it be possible to have in a place an easy editor with the first old customgenerator and the old quests?
-I think also there is some mistake because the other famous uest are not showing, they give me an 404 error from github.

**Comment by pietervdvn** [comment]
- Yes, there was a mistake in deployment for a while where the other quests didn't load. That has been fixed.
- The old custom generator is gone for good and will not come back, that was kind of the prototype. I know it is a bit more complicated now, but this is needed to offer all the features...

I'll have a look if I can further simplify things.

**Comment by yopaseopor** [comment]
Questions:

- After Popup contents you can fill all the mappings you want, but with conflict only the first is applying. Correct?
-Is there any place with the most used quests? I remember there was some place with stats right? It could be interesting to know what kind of quest is to tweak it and make my own more customized.

Suggestions:

- The explanations of the fields are better in the form or below every field with exact examples. The preview is changing everywhere I touch and it is breaking itself if I change from first tab to second and I don't know what field is the wrong filled or empty and is breaking the map.
- Is there any possibility/option to keep the changes undo until I clic a button or something like that? I don't know if OSM likes one changeset per change.

Issues:
- In the preview when I move by the example sometimes it is getting reset and then start from the start of the preview.
- In the fields when I move of If matches to other If matches it's getting reset and blank the first one.
- I think size icon options are not working.
- When I am in a private tab and I do a quest it tells me I have to login to OSM, but when I do, and I can modify things (so I am logged) Mapcomplete tells me I have to login, thing that it is not true because I am already logged and the button to log is not working anymore.

**Comment by pietervdvn** [comment]
1) Yes, the first match is taken. This is clarified in the explanantions
2) Yes, https://pietervdvn.goatcounter.com/ . Also linked now from the helptext

3) Agree, but they take a huge amount of room so I opted for this compromise (but I still have to do some user testing)
4) There is no 'single changeset per change'-anymore, this changed a little while back. See [the readme](https://github.com/pietervdvn/MapComplete#uploading-changes)

5) Yeah, it only update every few minutes in order to save overpass, but that indeed is very unclear. I'll change that behaviour in the coming days
6) I don't understand what you mean here
7) Correct. I too discovered that today and this is fixed
8) Correct. The userbadge was broken, this is fixed

**Comment by pietervdvn** [comment]
Note that I have made a 'staging'-version where I'll be running [new changes](https://pietervdvn.github.io/Staging/index.html?z=19&lat=50.925&lon=4.4635#element) as I'm constantly breaking MapComplete...

Also, thanks again for spotting and reporting the bugs!

**Comment by yopaseopor** [comment]
I think there's an error in Normal and Staging. When I edit working quest (like velocidad) then there are errors of parsing layouts. And when I fill all the fields to avoid these errors quest does not work anymore and always is trying to load the information.
Watching the resulting JSON I see in some parameters like icon size and stroke size  the value is for "render" and not inside "es" like the majority of the quest.

**Comment by yopaseopor** [comment]
There is some error about the Layer key in normal and staging
I can put whenever I want of title but in some parameters the only log in JSON is "Layer" . Example.

"layers": [
    {
      "id": "nameca",
      "name": "Layer",
      "minzoom": 12,
      "overpassTags": {
        "and": [
          "name=*"
        ]
      },
      "title": "Layer",
      "description": {
        "ca": "Ajuda'ns"
      },
      "tagRenderings": [],
      "icon": {
        "render": "./assets/bug.svg"

**Comment by pietervdvn** [comment]
> I think there's an error in Normal and Staging. When I edit working quest (like velocidad) then there are errors of parsing layouts. And when I fill all the fields to avoid these errors quest does not work anymore and always is trying to load the information.
> Watching the resulting JSON I see in some parameters like icon size and stroke size the value is for "render" and not inside "es" like the majority of the quest.

This is not important. If the configuration specifies `"render":"someString"`, then `someString` will be used for all languages - which'll we want for stuff like icons. Only in rare cases we'll want to have different icons based on the language.

Also, not every built-in layout is 100% correct...

**Comment by pietervdvn** [comment]
> There is some error about the Layer key in normal and staging
> I can put whenever I want of title but in some parameters the only log in JSON is "Layer" . Example.
> 
> "layers": [
> {
> "id": "nameca",
> "name": "Layer",
> "minzoom": 12,
> "overpassTags": {
> "and": [
> "name=*"
> ]
> },
> "title": "Layer",
> "description": {
> "ca": "Ajuda'ns"
> },
> "tagRenderings": [],
> "icon": {
> "render": "./assets/bug.svg"

Correct, this has been fixed in staging now.

**Comment by yopaseopor** [comment]
I have reviewed these days new features:

-Staging and Normal. When you are in a quest and you want to edit that quest CustomGenerator starts from 0, so it is impossible to edit the quest...except if you use JSON load way (thanks for creating that). Please put in normal something it will not fail. I will test Staging hard ;)
-Normal: Forms become empty when you want to do new mapping, for example, clicking + button.
-Staging and Normal: Load JSON first time goes well, but then, when I have changed something in JSON and try to load and view the fields of the form nothing has changed in second and third time.
-Staging and Normal: Name is not be written in the JSON or the  customized map . It calls       "name": "Layer",
-Staging and Normal: now I don't understand the way of work of the mapping, because before you can put =, ~, ~! and whatever value . Now it returns error. I read this: Invalid mapping in preview: the tags use an OR-expression or regex expression but are also assignable as answer.
-Staging and Normal: Could it be possible I only can "ignore" one question at a time? All the other options are correct, I can leave a field empty so there is no key then, but the "ignore step" is smarter than manual ignoring.

**Comment by pietervdvn** [comment]
Hey there again!

I'm cleaning up the code bit by bit, and it seems like I've broken the customGenerator beyond being useful... 
The good news: it should be fixed on staging. (When I've ironed out more bugs, I'll deploy on prod)

- Loading quests from the "edit this theme" button should work again
- The JSON-file automatically updates with the latest configurations in the UI. Changing something in the JSON and pressing the 'reload' should work, even multiple times
- "name":"Layers": good one! This should be fixed
- `=` is for literal key/value pairs, `~` is to use regexes (e.g. `somekey~*` to mean anything). The drawback is that `~` can not be used in a mapping which also acts as a possible answer.
- To erase a key, one has to put `key=` (with no value). For example, a typical noname-mapping is `"if": {"and":["noname=yes","name="], "then": "This object has no name"`. If the contributor were to skip the question (with the `skip this question`-button), this indicates that the contributor doesn't know (they don't know the name, but they aren't sure that the object is unnamed too). In that case, no tags are changed.  (TBH, I didn't understand your question here completely)

**Comment by yopaseopor** [comment]
I don't know if it is only my computer and my cellphone but Mapcomplete appears only in Dutch with only one possible quest, and with no Staging branch. What happened?

**Comment by pietervdvn** [comment]
I'm doing stupid things and fucking things up, that is happening ;)

**Comment by pietervdvn** [comment]
I think most of the bugs are ironed out by now, so I'm closing this issue.

If you have more problems, feel free to open a new issue.
