### ISSUE TITLE
Hailhydrant / own theme consolidates inserted values

### ISSUE THREAD

**Issue by MI-KY** [pietervdvn/MapComplete#1140]
Hi,

in some countries the diameter of hydrant couplings can be inserted with letters instead of an integer (https://taginfo.openstreetmap.org/keys/?key=couplings%3Adiameters#overview). Therefore I tried to insert a hydrant with coupling diameter "C;C;B" - three couplings with two different diameters (C & B).
When I save this hydrant the field only contains C;B instead of C;C;B.

Actually this is also ok because it is clear that there are two different coupling diameters but you loose the information what size has the third coupling.

**Comment by pietervdvn** [comment]
Hi,

This is very much an edge case. Adding an exception for this will introduce too much complexity, so I'm not gonna fix this at this time.
