### ISSUE TITLE
shops: new filter for organic products

### ISSUE THREAD

**Issue by schokagit** [pietervdvn/MapComplete#1143]
Please enhance the shops map with a filter for selecting organic products:
- organic=only: All products of the shop are organic.
- organic=yes: Some producs are organic.

Also the possibility to answer for organic products would be nice.

**Comment by pietervdvn** [comment]
Hi @schokagit 

Welcome to the repo.

For me, it is pretty hard to implement all these feature requests. However, it is possible to make these improvements yourself!

If you are familiar with json-files: you can add a question to the shop-layer [here](https://github.com/pietervdvn/MapComplete/blob/327a01cb7c0180969520940bef0208b168440c3c/assets/layers/shops/shops.json#L137).
Take a peek to the other questions on how to create this, or refer to the documentation [here](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md)

**Comment by RobinLinde** [comment]
Didn't mention this yesterday, but I already have something working in the `feature/organic` branch, which is deployed over here:https://mapcomplete-git-feature-organic-robinlinde.vercel.app/

Currently includes questions, filter and rendering for shops and food layer

**Comment by schokagit** [comment]
> working in the `feature/organic`

cool. How to get in the master branch?

**Comment by RobinLinde** [comment]
> cool. How to get in the master branch?

I've opened a PR to get it into the `develop` branch, which will eventually be merged into the `master`/production branch.

**Comment by schokagit** [comment]
What are the next steps? 
Is there a link to check the develop-branch?

**Comment by pietervdvn** [comment]
Yes, the develop branch can be previewed here: pietervdvn.github.io/mc/develop/

However, I've already merged this change into master, and it is thus live. An example shop which has biological products is here: https://mapcomplete.osm.be/shops?z=21&lat=51.20966&lon=3.232687&tab=3#node/6627750508
