### ISSUE TITLE
Can’t zoom in enough to edit (iPad Pro)

### ISSUE THREAD

**Issue by bryceco** [pietervdvn/MapComplete#115]
On my iPad Pro the message “Zoom in to view or edit the data” always appears, and I’m unable to zoom in enough for it to go away. Zoom + is grayed out.

**Comment by pietervdvn** [comment]
Weird. At which zoom level are you? Are you using the standard OSM-background layer?

Does this device have a very high DPI which already reaches the zoom level treshold early on?

**Comment by pietervdvn** [comment]
Hey,

I've deployed a potential (and very likely not working) fix [on staging version](https://pietervdvn.github.io/Staging/index.html?test=true). Could you try adding something? Note that the previous link is in test mode and doesn't actually _save_ something to OSM.

**Comment by bryceco** [comment]
It’s working now. 👍

**Comment by pietervdvn** [comment]
Cool! Thanks for reporting and thanks for testing!
