### ISSUE TITLE
Duplicate tags in tag info

### ISSUE THREAD

**Issue by KristjanESPERANTO** [pietervdvn/MapComplete#1167]
I noticed some duplicate tags in the taginfo files. E.g. in [mapcomplete_fritures.json](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/TagInfo/mapcomplete_fritures.json) are two times "`diet:vegan=yes`" - once with the following description:

`"Layer 'Fries shop' shows diet:vegan=yes with a fixed text, namely 'Vegan options are available' and allows to pick this as a default answer (in the MapComplete.osm.be theme 'Fries shops')",`

and once with this:

`"Layer 'Fries shop' shows diet:vegan=yes with a fixed text, namely 'Vegan snacks are available' and allows to pick this as a default answer (in the MapComplete.osm.be theme 'Fries shops')",`

Is that intentional?

**Comment by pietervdvn** [comment]
This is not intentional, but rather a result of reusing existing layers.

The 'fritures' layer is actually the 'restaurants-layer'. As the wording is slightly different if `cuisine=friture`, it pops up twice. I've included the condition into the description, so that should clarify these a bit.
