### ISSUE TITLE
hailhydrant / let see when hydrants have different colour

### ISSUE THREAD

**Issue by JLZIMMERMANN** [pietervdvn/MapComplete#1193]
**FACT** : hailhydrant map displays hydrant and fire extinguisher indoor and outdoor

**IDEA** : it would be welcome to see when hydrant have a specific colour
Example, in my city, underground hydrants are painted in yellow.
Tag that could be used is colour=*
![image](https://user-images.githubusercontent.com/4929752/209530268-89e10752-d41f-4258-b0bf-70280d844208.png)
![image](https://user-images.githubusercontent.com/4929752/209530312-e9491de9-0e80-472c-be8b-314fc650d0a5.png)

**Comment by pietervdvn** [comment]
The info popup already has a [question on the colour of the hydrant](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Layers/hydrant.md#hydrant-color).
