### ISSUE TITLE
Allow for crossings to be attached to ways

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1205]
Currently crossings are just added to the map as a freefloating node. But ideally they're connected to the way they're referring to. (like how in surveillance cams it can attach to a wall)

**Comment by thibaultmol** [comment]
Oh derp, you're right Robin. I was on mobile so didn't fully realize. I guess one of the reasons I thought it wasn't a thing yet, is because it doesn't display the actual road.
I can see why the blind theme doesn't show all roads. But maybe it could be an interesting feature to implement: show roads **when you're in the add dialog**

**Comment by pietervdvn** [comment]
The 'blind'-theme does set 'mapRendering' to 'null' for 'cycleway-and-roads', hence _not_ showing anything, also not in the 'add-new' dialog.

I have added some flags (`shownByDefault: false´) to keep the rendering, but to hide it on the main map.
