### ISSUE TITLE
Reviews: specific characters can't be entered

### ISSUE THREAD

**Issue by barthanssens** [pietervdvn/MapComplete#1208]
Could be machine-specific, but when I try to add a review in Windows 10 Enterprise / Chrome 107 for a shop, it seems that some characters like 'l' or 'b' can't be used in the the review text area.

I.e. writing a word with character 'b' in the review text area brings up a "select layers" sidebar, which prevents typing the intended text

**Comment by RobinLinde** [comment]
Seems to be related to the new hotkeys, it checks whether the active element is an input element, but a textarea isn't included in that. I've now opened PR #1210, changing that, [preview](mapcomplete-d0f77rh58-robinlinde.vercel.app) should be available in a few minutes.
