### ISSUE TITLE
Add a tooltip on the action buttons on the map

### ISSUE THREAD

**Issue by Flaburgan** [pietervdvn/MapComplete#1215]
It isn't clear what some icons are going to do when we click on them. For this third one, even after clicked, I have no idea what I am looking at.

![Sans titre](https://user-images.githubusercontent.com/930064/210253996-c07e8c97-ddc1-4532-b88e-1e4156a6d56b.png)

Their style should also be unified so they all are circles I guess?

**Comment by pietervdvn** [comment]
This component has dissappeared in the MapLibre port, so this issue is not relevant anymore.
