### ISSUE TITLE
Improve the welcome page UX/UI

### ISSUE THREAD

**Issue by Flaburgan** [pietervdvn/MapComplete#1216]
![image](https://user-images.githubusercontent.com/930064/210183076-b33de5f5-e3c3-4f62-8035-bf2495d36dbc.png)
![image](https://user-images.githubusercontent.com/930064/210254391-bde683ac-eb8c-4456-9dff-6a636ccb5391.png)

There are several topics / actions available on that page:
- **Explain what MapComplete is**. Important for people who don't know what it is. We have an introduction text at the top, but also an "About" at the bottom, which is hardly discoverable. I guess after the introduction text we could have a link "Learn more about the project" (or a similar label) to About (which should probably be another page, that would allow to link to it from the "full-screen" map page too).
- **Access a theme**, clicking in the list, or using the search field. This is the main action. To have the actual themes separated of the search input by the other actions (Create a theme, pro support, personal theme) should also be avoided imo.
- **Create a theme from scratch / from another theme**, for advanced users. At this point the difference between the two was not clear to me, I had to click them and explore to understand.
- **Discover the professional support** which is right in the middle. I guess it's part of the business model so it is important to make it discoverable, but it also feels at the wrong place to me.

I would suggest something like this (rough draft, the UI elements have to be styled properly):
![image](https://user-images.githubusercontent.com/930064/210257817-39b68f9e-4bad-4da6-8b29-4c7ea0b06ef5.png)

In this mockup, the main action, picking a theme, is accessible right from the beginning, but the explanation is still at the top and it is easy to discover more about the project and how it works with the "Learn more" button. The action to create a new theme (being based on another one or from scratch) still is available but less prominent. The action to reach the pro support has been removed. In my opinion, it should be very visible but in a header, next to a login button and the language selection.

With this mockup, two new pages have to be introduced. The "About", which is also what is currently displayed in the panel in the map screen, but can be a full page:
![image](https://user-images.githubusercontent.com/930064/210258358-189dec8a-9991-4ae3-a931-34f1c8c94f40.png)

And the "Create a new theme" page, which should explain the difference between the tool available for creating a theme from scratch and the option to create a theme based on another one. This page can be more technical, explain what themes actually are, the json format, etc. Everything which would be too technical for a home page but is needed to be understood before actually working on a theme.

What do you think about it?

**Comment by pietervdvn** [comment]
Looks good!

Be aware that the 'What is MapComplete'-tab is _only_ shown for advanced users (>500 changesets).

I'm also wondering how the design will look on mobile.

At last, the custom theme generator will get a big overhaul, so let's not worry to much about that for now.

**Comment by pietervdvn** [comment]
With the MapLibre-port getting merged in, this is not as relevant anymore.
