### ISSUE TITLE
Translation delay

### ISSUE THREAD

**Issue by sylvain-m** [pietervdvn/MapComplete#1226]
This is more a question than an issue.

I wanted to know how long it takes for translations on the weblate site to be taken into account.

I made several translations yesterday for a MapComplete theme, and they are not yet visible on the interface: I guess this is normal, but I would like to know how long I can expect for their integration (as I prefer to wait before sharing the map with potential contributors who do not speak English).

Thanks for the info, and congratulations for all the work around MapComplete!

**Comment by pietervdvn** [comment]
Weblate creates a Pull Request ti this repo regularly with the new translations. Someone with access to weblate can also trigger this manually.

Someone with access here then has to approve the changes, and the automated checks have to pass. (The most common issue is that a substituted piece of text is missing, e.g. `The name of this POI is {name}` would be translated as `De baam van dit pubt is {naam}`, which is flagged).

Once approved and merged, the autodeploy kicks in and the translations should be live on MapComplete.osm.be within at most an hour.

**Comment by pietervdvn** [comment]
In the mean time, I have added you as contributor on github and as admin on weblate. Thus means that you can trigger these fliws yourself and can get your translations into the live version quickly.

When you have added translations:

- in hosted weblate, go to 'manage', 'repository management', theb hit 'commit' and 'push'
- then, come to github and the pull requests here and approve and merge the pull request.

**Comment by pietervdvn** [comment]
I'm closing this issue for now;

If you have more questions, feel free to write below. Other contributors who want admin-access on Weblate, you can let me know to (e.g. via this issue or via the chat)

**Comment by sylvain-m** [comment]
Thanks for the explanation Pieter!
And thanks also for the pull request management (I must admit I'm not very comfortable with Github to manage this).
I see that my translations are already operational, so that's great! 😃

**Comment by pietervdvn** [comment]
Don't worry to much, you're not able to break the online versions.
