### ISSUE TITLE
Bug: "free to use" but "fee=yes"

### ISSUE THREAD

**Issue by paunofu** [pietervdvn/MapComplete#1237]
In cyclofix theme when you are answering bikes cleaning services the question of "How much does it cost to use the cleaning service?" if you answer "free to use" map complete adds fee=yes
![image](https://user-images.githubusercontent.com/94412187/211486278-808aaf27-2feb-4a4b-bb7e-fbd42c49a86e.jpeg)

**Comment by RobinLinde** [comment]
I've changed the text for both in Weblate, so they should be updated the next time the translations are updated. Texts should now be `This cleaning service is free to use` and `This cleaning service is paid`

**Comment by RobinLinde** [comment]
Is now fixed in master branch by PR #1239

**Comment by pietervdvn** [comment]
I've removed some of the incorrect translations in fb26181e25894197e55a9f0266bbd6f0ac854298, this should fix this issue.
