### ISSUE TITLE
Render bug with the grouped objects overlay

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1241]
There seems to be a bug with the green square box that overlays if there are too many objects in one region to display.
There seems to be a zoom level between the square box appearing and the objects appearing, where nothing is shown
(tree theme in this case)

https://user-images.githubusercontent.com/1010226/211654785-3f631826-aced-460b-b735-c2a74f4585a2.mp4

**Comment by pietervdvn** [comment]
Can reproduce here: https://mapcomplete.osm.be/trees?z=18&lat=51.21925&lon=4.402352&language=nl&background=osm

**Comment by pietervdvn** [comment]
With the maplibre port, there is no clustering anymore - so this issue became irrelevant.
