### ISSUE TITLE
Notes themes: not clear that you can upload images

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1248]
Because there isn't a visual indicator when you create a note that you can add an image after the note its created. A lot of people might not even realise that mapcomplete allows you to add a photo to a note.

**Comment by pietervdvn** [comment]
The issue here was that the feature info box of the note wasn't opened automatically, hence not giving this user interface.

This has been fixed in b4ecd963fccb8c2853e685d0e1c0c3f0386c1a06
