### ISSUE TITLE
Phone number detection used to be more tolerant?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1253]
I feel like a couple months ago I was able to give it phone numbers without +32 and it would detect it and fix it.
Or maybe I was imaginging it.

Anyway. I pasted 056521300 and it wasn't detected
![image](https://user-images.githubusercontent.com/1010226/212472116-8a4c5e3c-f40e-4283-b7b8-e572a9e1f980.png)

**Comment by pietervdvn** [comment]
This could have taken me a long time to figure out, but you also gave me the answer earlier in the chat, by asking what the 'country is loading'-meant:

![image](https://user-images.githubusercontent.com/1466478/212519637-5283655f-ecf7-4436-abc4-81d807b29f2f.png)

For some functions - notably opening hours and formatting (some) phone number, having the country is important.

Now, determining the country can be a bit tricky, but that is where [latlon2country](https://github.com/pietervdvn/latlon2country) comes in. It slices the boundaries into tiles and adds some kind of index to quickly retrieve the necessary files.

This index was broken - I incorrectly regenerated them a while ago. They are fixed now again.

**Comment by thibaultmol** [comment]
oooooh, i didn't connect the two.

Nice 👍
