### ISSUE TITLE
Expand 'access' preset with 'permissive'?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1255]
I noticed while adding a charging station (owned by a regular company, but they open it up for use outside of office hours) that I couldn't answer access=permissive trough mapcomplete. I can see why having permissive on all questions that use {access} might not be ideal. So maybe having a new {access+permissive} or something could be useful in cases like this?

**Comment by pietervdvn** [comment]
IMHO, this is publicly accessible but has opening hours.

The current options are:

- `access=yes` "Anyone can use this charging station (payment might be needed)"
- `access=customers` "Only customers of the place this station belongs to can use this charging station<br/><span class='subtle'>E.g. a charging station operated by hotel which is only usable by their guests</span>"
- `access=private` "Not accessible to the general public (e.g. only accessible to the owners, employees,...)"
- `access=key` "A <b>key</b> must be requested to access this charging station<br/><span class='subtle'>E.g. a charging station operated by hotel which is only usable by their guests, which receive a key from the reception to unlock the charging station</span>"

How would you phrase `access=permissive`?

**Comment by thibaultmol** [comment]
access=permissive: "This charging station is accessible to the public during certain hours or conditions. Restrictions might apply, but general use is allowed."
