### ISSUE TITLE
Make the link preview text that's pulled by social platforms, language adjusted

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1259]
So right now if you link 
https://mapcomplete.osm.be/charging_stations.html?language=nl
somewhere. It will show the English text when it's shown on a Facebook/Twitter/etc post.

I don't know if those preview generators differentiate with ? options. But I assume they do.
So in that case, maybe it would be nice if someone linked to a dutch version of MapComplete, it would show the dutch language in the preview.

![image](https://user-images.githubusercontent.com/1010226/212561331-9cb1ae01-fd2f-4ae6-ba1d-b5ca4bfb3d76.png)

**Comment by pietervdvn** [comment]
This is currently _not_ possible with the current architecture.

A preview is generated by the social media computer querying the server which hosts MapComplete. As github pages only serves _static_ content and does _not_ interpret the query parameters, the same result is always returned.

This would be possible if mapcomplete were hosted by a dynamic server, but this is not the case.
