### ISSUE TITLE
Add new data that is not in OSM already

### ISSUE THREAD

**Issue by joshinils** [pietervdvn/MapComplete#1268]
I'd like to individually review data on-the-ground.
Specifically the trees in Berlin. 
ref: https://github.com/streetcomplete/StreetComplete/issues/3738

I have done so in the past with a manually created and printed list of all trees and their numbers on a single street, however this was rather impractical.

Can I use another data source like https://fbinter.stadt-berlin.de/fb/berlin/service_intern.jsp?id=k_wfs_baumbestand@senstadt&type=WMS
to generate quests for trees? Or a generated .osm file from that source for upload?
Those trees mostly are not in OSM already, and I do not want to perform a blanket import for quality reasons and because they might already exist in OSM, so avoid duplicates.

Same quest(s) for the street lamps data.

**Comment by tordans** [comment]
My recommendation would be, to test out a workflow that is based on the MapRoulette integration in MapComplete.
AFAIK there is an integration in some theme somewhere.

We would have to prepare a MapRoulette Challenge first.
Ideally, we find a way to prepare tags in MapRoulette that can be used in MapComplete to prefill a given OSM Object.

There are some more infos about this in https://www.openstreetmap.org/user/Pieter%20Vander%20Vennet/diary/398782#comment52733

**Comment by pietervdvn** [comment]
Hi,

You need to make a change to MapComplete for this, see https://github.com/pietervdvn/MapComplete/blob/0b826612e93c0b120f99b6927c57c13b60c2835f/assets/themes/atm/atm.json#L59 for an example.

I currently lack the time to support you with this, so I'm gonna close this issue.
