### ISSUE TITLE
Document the electrical tags in osm wiki

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#1269]
Similar to https://github.com/pietervdvn/MapComplete/issues/985, I think it would be good to document the electrical tags on the wiki.

I find the electrical tags very useful and hope that more people use them to make it easy to find nice places to work from :)
https://github.com/pietervdvn/MapComplete/blob/master/Docs/Layers/cafe_pub.md#serviceelectricity

It seems we'd need to make something like [Tag:dog=yes](https://wiki.openstreetmap.org/wiki/Tag%3Adog%3Dyes) or [Tag:internet_access=wlan](https://wiki.openstreetmap.org/wiki/Tag%3Ainternet_access%3Dwlan).

For the 4 `service:electricity=` tags?

The reason I request this is because I was trying to add electricity tags via OSMand and was looking for the documentation on my phone and couldn't find it. Eventually I did find it here https://github.com/pietervdvn/MapComplete/blob/master/Docs/Layers/cafe_pub.md#serviceelectricity

I'd be willing to try adding them to the wiki but I haven't done this before and not sure what the process should be.

Thanks for all the hard work! 👍

**Comment by pietervdvn** [comment]
Hi RayBB,

Thanks for reaching out. I have to admit that this tagging was used without proper review.

There are two ways to approach documenting tags on the wiki:

1. Simply add it to the wiki ([Click here](https://wiki.openstreetmap.orgw/index.php?title=Key:service:electricity&action=edit&redlink=1)) and start documenting it as 'de facto tagging'

2. [Write a proposal](https://wiki.openstreetmap.org/wiki/Proposal_process) and 
write the tagging mailing list on 'how such a property should be directly'. They will be able to give a ton of feedback, point to similar tagging schemes (e.g. for campings) and debate for weeks why a certain value should be one option or another. This involves way more work, but gives more legitimacy to the tagging once it is established.



This is a bit the power of the tool-makers (such as me) to decide on tagging and has caused a lot of drama around the iD-editor as well. For some tags with a high impact (such as types of bicycle rental) I went through the entire process, smaller features (such as binoculars) I just put up on the wiki without much ado, and yet others are not documented on the wiki yet.

In either case, thanks a lot for wanting to improve this!

**Comment by RayBB** [comment]
@pietervdvn thanks for the kind and helpful response.

I don't think I have the context or patience to go through the process of writing a proposal.

However, I created the wiki page best I could. https://wiki.openstreetmap.org/wiki/Key:service:electricity

I would appreciate if you could give it a look and fix anything I might have done incorrectly.

Thanks!

**Comment by pietervdvn** [comment]
I did a small proofreading and reworded a few things - biggest difference is that I moved the mention of mapcomplete down to a new section about 'Applications'. Furthermore, I mentioned a few more tags.

Either way, thanks for documenting this!
