### ISSUE TITLE
Landing page search, catch enter key behavior

### ISSUE THREAD

**Issue by govvin** [pietervdvn/MapComplete#1270]
On the desktop, when I search for something  (I know that the behavior is supposed to be search-as-you-type) on the landing page, hitting the enter key will launch the first theme.

If you're like me, and used to traditional search box behavior, where you hit the enter key to start the search action, but not lauch the first theme displayed -- this is unexpected.

![image](https://user-images.githubusercontent.com/5821688/213835468-8ff04aaa-c5ee-461d-85dd-8dec65e26769.png)

So, in the above example, if the user types some text, and hit enter, the OSM for the blind theme is launched.

Perhaps catch the enter key, and make it do nothing?

**Comment by govvin** [comment]
Same behavior observed in mobile browsers.

**Comment by pietervdvn** [comment]
Hi,

This behaviour is intentional - I use it to quickly switch themes, so I'm gonna keep it.

**Comment by RobinLinde** [comment]
I personally feel a visual indication like this might be nice
![afbeelding](https://github.com/pietervdvn/MapComplete/assets/1395345/af4d6105-3a85-4b96-945a-23aaa725d95c)

**Comment by RobinLinde** [comment]
Made a small demo: https://mapcomplete-git-robinlinde-patch-10-robinlinde.vercel.app/
