### ISSUE TITLE
Mangrove reviews being shown in the wrong place

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#1275]
Heavy MapComplete user `Bart Hanssens` reviewed one or two places in Halle using Mangrove. Now, it sometimes seem all the places were reviewed by him. I tried finding an example, and found [this one](https://mapcomplete.osm.be/onwheels.html?test=true&z=19&lat=50.73792&lon=4.234226&language=nl&welcome-control-toggle=true&layer-cafe_pub=false&layer-food=false&layer-parking=false&layer-parking_spaces=false&layer-doctors=false#node/7832183191). I reviewed [this place](https://www.openstreetmap.org/node/5408200704/history) (now closed) some time back, and now all nearby places seem to be getting the review from that place. There's no other Iraqi fast food in town :) , so the text can help clarify that whereever it is shown, it's quite wrong.

**Comment by pietervdvn** [comment]
Can you test this in develop as well? I've recently improved this there (the search area is way smaller).

**Comment by joostschouppe** [comment]
Seems to be fixed in develop already
