### ISSUE TITLE
Quest are difficult to be shared effectively

### ISSUE THREAD

**Issue by yopaseopor** [pietervdvn/MapComplete#129]
I have very big problems with long URL's and the systems to avoid them. For example, I have this error when I try tot do that via id layer 
![image](https://user-images.githubusercontent.com/5250646/94338802-65e81380-fff5-11ea-941f-5e493917abcb.png)

I have also other errors like "Wrong URL" when I try tot do wiki trick, but (the url is correct, you can find it at:
https://wiki.openstreetmap.org/wiki/User:Yopaseopor/questcontaineronvas)
Also I have errors when I try to paste the URL's. For me is working but when I pass the link to other person it get some errors like this. "Error": could not parse the custom layout:
InvalidCharacterError:String contains an invalid character

And at last but not least, it could be interesting to make a way to send you the exact error or the message error would be more specific and selectable (now I have to do screenshots or type the errors)

https://pietervdvn.github.io/MapComplete/index.html?userlayout=wiki%3AUser%3AYopaseopor%2Fquestcontaineronvas

https://pietervdvn.github.io/MapComplete/index.html?z=19&lat=41.218&lon=1.7129&userlayout=id.

Specific quest has the full url : https://pietervdvn.github.io/MapComplete/index.html?userlayout=containeronvas#eyJpZCI6ImNvbnRhaW5lcm9udmFzIiwidGl0bGUiOnsiY2EiOiJDb250YWluZXIgb24gdmFzID8iLCJlcyI6Ir9E825kZSBlc3ThcyBjb250ZW5lZG9yPyJ9LCJzaG9ydERlc2NyaXB0aW9uIjp7ImNhIjoiUG9zYXIgY29udGVuaWRvcnMiLCJlcyI6IlBvbmVyIGNvbnRlbmVkb3JlcyJ9LCJkZXNjcmlwdGlvbiI6eyJjYSI6IlRvdHMgcmVjb3JkZW0gbGEgY2Fu529uZXRhOiBFbmNhcmEgcXVlIHNpZ3VpcyBkZSBwbOBzdGlpaWlpaWljLi4uIHBlcvIuLi5pIGVsIGNvbnRlbmlkb3IgZW4gc+06IG9uIHZhPyBBcXXtIHBvc2FyZW0gY29udGVuaWRvcnMgaSBjb21wbGV0YXJlbSBsYSBpbmZvcm1hY2nzIGRlbHMgcXVlIGZhbHRpbi4iLCJlcyI6IlBvbmRyZW1vcyBjb250ZW5lZG9yZXMgeSBjb21wbGV0YXJlbW9zIGxhIGluZm9ybWFjafNuIGRlIGxvcyBxdWUgZmFsdGVuIHBvciBjb21wbGV0YXIuIn0sImxhbmd1YWdlIjpbImNhIiwiZXMiXSwibWFpbnRhaW5lciI6IiIsImljb24iOiJodHRwczovL2Nkbi5waXhhYmF5LmNvbS9waG90by8yMDE4LzA5LzIyLzExLzQzL2ljb24tMzY5NTEwNF85NjBfNzIwLnBuZyIsInZlcnNpb24iOiIyMDIwXzA5XzI2Iiwic3RhcnRMYXQiOjAsInN0YXJ0TG9uIjowLCJzdGFydFpvb20iOjEsIndpZGVuRmFjdG9yIjowLjA1LCJzb2NpYWxJbWFnZSI6IiIsImxheWVycyI6W3siaWQiOiJjb250ZW5pZG9ycyIsIm5hbWUiOnsiY2EiOiJDb21wbGV0YXIgaW5mb3JtYWNp8yBjb250ZW5pZG9ycyIsImVzIjoiQ29tcGxldGFyIGluZm9ybWFjafNuIGNvbnRlbmVkb3JlcyJ9LCJtaW56b29tIjoxMiwib3ZlcnBhc3NUYWdzIjp7ImFuZCI6WyJhbWVuaXR5PXJlY3ljbGluZyIsInJlY3ljbGluZ190eXBlPWNvbnRhaW5lciJdfSwidGl0bGUiOnsicmVuZGVyIjp7ImNhIjoiQ29udGVuaWRvciIsImVzIjoiQ29udGVuZWRvciJ9LCJtYXBwaW5ncyI6W3siaWYiOnsiYW5kIjpbInJlY3ljbGluZ190eXBlPWNvbnRhaW5lciJdfSwidGhlbiI6eyJjYSI6IkNvbnRlbmlkb3IgamEgZXhpc3RlbnQiLCJlcyI6IkNvbnRlbmVkb3IgeWEgZXhpc3RlbnRlIn19XX0sImRlc2NyaXB0aW9uIjp7ImNhIjoiQ29tcGxldGFyZW0gbGEgaW5mb3JtYWNp8yBzb2JyZSBjb250ZW5pZG9ycyBleGlzdGVudCAsIGkgc2kgY2FsLCBlbiBwb3NhcmVtIGRlIG5vdXMiLCJlcyI6IkNvbXBsZXRhcmVtb3MgbGEgaW5mb3JtYWNp824gc29icmUgY29udGVuaWRvcmVzIGV4aXN0ZW50ZSB5IHNpIGhhY2UgZmFsdGEgcG9uZHJlbW9zIG51ZXZvcyJ9LCJ0YWdSZW5kZXJpbmdzIjpbeyJyZW5kZXIiOnsiY2EiOiJDb250ZW5pZG9yIiwiZXMiOiJDb250ZW5lZG9yIn0sImZyZWVmb3JtIjp7ImtleSI6InJlY2ljbHluZ190eXBlIn0sIm1hcHBpbmdzIjpbeyJpZiI6eyJhbmQiOlsicmVjeWNsaW5nOnBhcGVyPSIsInJlY3ljbGluZzpiZXZlcmFnZV9jYXJ0b25zPXllcyJdfSwidGhlbiI6eyJjYSI6IkNvbnRlbmlkb3IgZGUgcGFwZXIiLCJlcyI6IkNvbnRlbmVkb3IgZGUgcGFwZWwifX0seyJpZiI6eyJhbmQiOlsicmVjeWNsaW5nOlBFVD15ZXMiLCJyZWN5Y2xpbmc6Y2Fucz15ZXMiXX0sInRoZW4iOnsiY2EiOiJDb250ZW5pZG9yIGQnZW52YXNvcyIsImVzIjoiQ29udGVuZWRvciBkZSBlbnZhc2VzIn19LHsiaWYiOnsiYW5kIjpbInJlY3ljbGluZzpnbGFzc19ib3R0bGVzPXllcyJdfSwidGhlbiI6eyJjYSI6IkNvbnRlbmlkb3IgZCdlbnZhc29zIGRlIHZpZHJlIiwiZXMiOiJDb250ZW5lZG9yIGRlIGVudmFzZXMgZGUgdmlkcmlvIn19LHsiaWYiOnsiYW5kIjpbInJlY3ljbGluZzpvcmdhbmljPXllcyJdfSwidGhlbiI6eyJjYSI6IkNvbnRlbmlkb3IgZGUgcmVzdGVzIGQnb3Jn4G5pYyIsImVzIjoiQ29udGVuaWRvciBkZSByZXN0b3Mgb3Jn4W5pY29zIn19LHsiaWYiOnsiYW5kIjpbInJlY3ljbGluZzp3YXN0ZT15ZXMiXX0sInRoZW4iOnsiY2EiOiJDb250ZW5pZG9yIGRlIHJlYnVpZyIsImVzIjoiQ29udGVuZWRvciBkZSByZWNoYXpvIn19XSwicXVlc3Rpb24iOnsiY2EiOiJEZSBxdegg6XMgZWwgY29udGVuaWRvcj8iLCJlcyI6Ir9EZSBxdekgZXMgZWwgY29udGVuZWRvcj8ifSwiY29uZGl0aW9uIjp7ImFuZCI6W119fSx7InJlbmRlciI6eyJjYSI6InVuZGVyZ3JvdW5kIiwiZXMiOiJ1bmRlcmdyb3VuZCJ9LCJxdWVzdGlvbiI6eyJjYSI6IkFxdWVzdCBjb250ZW5pZG9yIOlzIHNvdGVycmF0PyIsImVzIjoiv0VzdGUgY29udGVuZWRvciBlc3ThIHNvdGVycmFkbz8ifSwiZnJlZWZvcm0iOnsia2V5IjoibG9jYXRpb24ifSwibWFwcGluZ3MiOlt7ImlmIjp7ImFuZCI6WyJsb2NhdGlvbj11bmRlcmdyb3VuZCJdfSwidGhlbiI6eyJjYSI6IkNvbnRlbmlkb3Igc290ZXJyYXQiLCJlcyI6IkNvbnRlbmVkb3Igc290ZXJyYWRvIn19XX1dLCJoaWRlVW5kZXJsYXlpbmdGZWF0dXJlc01pblBlcmNlbnRhZ2UiOjAsImljb24iOnsicmVuZGVyIjoiaHR0cHM6Ly9jZG4ucGl4YWJheS5jb20vcGhvdG8vMjAxOC8wOS8yMi8xMS80My9pY29uLTM2OTUxMDRfOTYwXzcyMC5wbmciLCJtYXBwaW5ncyI6W3siaWYiOnsiYW5kIjpbInJlY3ljbGluZzpwYXBlcj15ZXMiXX0sInRoZW4iOnsiY2EiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT1NNLUNhdGFsYW4vb3NtY2F0bWFwL21hc3Rlci9pbWcvaWNvbmVzX2NvbnRlbmlkb3JzL3BhcGVyLnN2ZyIsImVzIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL09TTS1DYXRhbGFuL29zbWNhdG1hcC9tYXN0ZXIvaW1nL2ljb25lc19jb250ZW5pZG9ycy9wYXBlci5zdmcifX0seyJpZiI6eyJhbmQiOlsicmVjeWNsaW5nOlBFVD15ZXMiXX0sInRoZW4iOnsiY2EiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT1NNLUNhdGFsYW4vb3NtY2F0bWFwL21hc3Rlci9pbWcvaWNvbmVzX2NvbnRlbmlkb3JzL2VudmFzb3Muc3ZnIiwiZXMiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT1NNLUNhdGFsYW4vb3NtY2F0bWFwL21hc3Rlci9pbWcvaWNvbmVzX2NvbnRlbmlkb3JzL2VudmFzb3Muc3ZnIn19LHsiaWYiOnsiYW5kIjpbInJlY3ljbGluZzpnbGFzc19ib3R0bGVzPXllcyJdfSwidGhlbiI6eyJjYSI6Imh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9PU00tQ2F0YWxhbi9vc21jYXRtYXAvbWFzdGVyL2ltZy9pY29uZXNfY29udGVuaWRvcnMvdmlkcmUuc3ZnIiwiZXMiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT1NNLUNhdGFsYW4vb3NtY2F0bWFwL21hc3Rlci9pbWcvaWNvbmVzX2NvbnRlbmlkb3JzL3ZpZHJlLnN2ZyJ9fSx7ImlmIjp7ImFuZCI6WyJyZWN5Y2xpbmc6d2FzdGU9eWVzIl19LCJ0aGVuIjp7ImNhIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL09TTS1DYXRhbGFuL29zbWNhdG1hcC9tYXN0ZXIvaW1nL2ljb25lc19jb250ZW5pZG9ycy9yZWJ1aWcuc3ZnIiwiZXMiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT1NNLUNhdGFsYW4vb3NtY2F0bWFwL21hc3Rlci9pbWcvaWNvbmVzX2NvbnRlbmlkb3JzL3JlYnVpZy5zdmcifX0seyJpZiI6eyJhbmQiOlsicmVjeWNsaW5nOm9yZ2FuaWM9eWVzIl19LCJ0aGVuIjp7ImNhIjoiaHR0cHM6Ly9yYXcuZ2l0aHVidXNlcmNvbnRlbnQuY29tL09TTS1DYXRhbGFuL29zbWNhdG1hcC9tYXN0ZXIvaW1nL2ljb25lc19jb250ZW5pZG9ycy9yZWJ1aWcuc3ZnIiwiZXMiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vT1NNLUNhdGFsYW4vb3NtY2F0bWFwL21hc3Rlci9pbWcvaWNvbmVzX2NvbnRlbmlkb3JzL3JlYnVpZy5zdmcifX1dfSwid2lkdGgiOnsicmVuZGVyIjoiOCJ9LCJpY29uU2l6ZSI6eyJyZW5kZXIiOiIzMiwzMixjZW50ZXIifSwiY29sb3IiOnsicmVuZGVyIjoiIzAwZiJ9LCJwcmVzZXRzIjpbeyJ0YWdzIjpbImFtZW5pdHk9cmVjeWNsaW5nIiwicmVjeWNsaW5nX3R5cGU9Y29udGFpbmVyIl0sInRpdGxlIjp7ImNhIjoiTm91IGNvbnRlbmlkb3IiLCJlcyI6Ik51ZXZvIGNvbnRlbmVkb3IifSwiZGVzY3JpcHRpb24iOnsiY2EiOiJDb250ZW5pZG9yIGRlc2NvbmVndXQiLCJlcyI6IkNvbnRlbmVkb3IgZGVzY29ub2NpZG8ifX1dLCJ3YXlIYW5kbGluZyI6MX1dLCJyb2FtaW5nUmVuZGVyaW5ncyI6W119

From wiki it is : https://pietervdvn.github.io/MapComplete/index.html?userlayout=wiki%3AUser%3Ayopaseopor/questcontaineronvas 

Error: User:yopaseopor/questcontaineronvas is invalid:
Could not download - wrong URL?

Note you cannot use any sistem like bit.ly or a simple tweet, it cuts you the link.

The only way I have found to work is making a direct link, in a blog or the same osm wiki like this https://wiki.openstreetmap.org/wiki/User:Yopaseopor#Container_on_vas.3F .  It could be interesting you can make your projects page in the wiki to afford this information directly there.

**Comment by pietervdvn** [comment]
>  https://pietervdvn.github.io/MapComplete/index.html?userlayout=wiki%3AUser%3Ayopaseopor/questcontaineronvas

This one is working just fine for me, but it uses a third party service (a proxy) to avoid some problems with cors. Maybe your browser/firewall is blocking this?

**Comment by pietervdvn** [comment]
Oh, are you trying to use google translate? Google translate is actually a service of google which loads the website in your website with some trickery.

Using mapcomplete within google translate isn't really supported and will indeed break stuff.

**Comment by yopaseopor** [comment]
> 
> 
> Oh, are you trying to use google translate? Google translate is actually a service of google which loads the website in your website with some trickery.
> 
> Using mapcomplete within google translate isn't really supported and will indeed break stuff.

No, it is the standard Chrome for Android who suggest you to use Google Translate for translating any webpage you don't watch in your cellphone's language.

This errors happen sometime. For me had worked but when the Spanish Community people used it failed.And then also failed to me. I have tested in Chrome and Firefox, also in private mode.

The way I have found to work without problems is tricking the headings in the page of the OSM wiki like this:

https://wiki.openstreetmap.org/wiki/User:Yopaseopor#Container_on_vas.3F

https://wiki.openstreetmap.org/wiki/User:Yopaseopor#Crossing_time

**Comment by pietervdvn** [comment]
It is now implemented to host a JSON on any webserver and load from there - that'll make it easier to share. Deployment of themes from a wiki page is _not_ possible anymore (see #207).

Furthermore, I'm not gonna jump through hoops to make the app work with a specific third-party translation app (Google Translate), even if it is disguised as a browser feature and especially because there is the possibility to translate themes.
