### ISSUE TITLE
manifest broken

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1293]
because of the vite change probably

**Comment by thibaultmol** [comment]
![Screenshot_20230209_182412_One UI Home](https://user-images.githubusercontent.com/1010226/217890489-528bcf0e-3af9-4529-9f3f-8e7ea9f6c61e.jpg)


Just fyi, adding develop as pwa still doesn't show favicon from the manifest

**Comment by pietervdvn** [comment]
Can you do a few refreshes? It should work now

**Comment by thibaultmol** [comment]
I have done many

**Comment by thibaultmol** [comment]
@pietervdvn fyi, I'm still having this issue

**Comment by pietervdvn** [comment]
As it turns out, the service-worker was broken as well. The service worker aggressively caches a certain version of MapComplete. As it was broken, it would effectively serve an old version, hence the earlier fix would not be applied on your phone.

I'm now merging the develop branch onto master. Would you mind to validate that it works (might need at most 2 refreshes) and close the issue if it works now?

**Comment by thibaultmol** [comment]
mapcomplete.osm.be prompt the install like it should. That's working now
yeah

I guess github.io doesn't work yet and won't work because of a github.io
limitation or something?

Cheers,

**Comment by thibaultmol** [comment]
When going to mapcomplete.osm.be. The prompt to install the pwa does come up. Installs correctly. 

GitHub.io version doesn't seem to show the prompt and if you install it, doesn't actually install as a pwa. Just a bookmark

(Retyped this comment. Cause previous one I typed half asleep it seemed XD)

**Comment by thibaultmol** [comment]
NEVER MIND, I'm not sure what I did differently. But it didn't work 5 minutes ago and now it does. Issue solved

**Comment by thibaultmol** [comment]
One question though: should the develop version maybe say (develop) in the app title to separate it from the osm.be hosted one?

If that's even possible

**Comment by pietervdvn** [comment]
> NEVER MIND, I'm not sure what I did differently. But it didn't work 5 minutes ago and now it does. Issue solved

As the servixe workers caches aggressively, you probably had the old version while the SW updated in the background.

> One question though: should the develop version maybe say (develop) in the app title to separate it from the osm.be hosted one?

That's something I did consider, just didn't get implemented yet.
