### ISSUE TITLE
Please are these well-known other map layers

### ISSUE THREAD

**Issue by yopaseopor** [pietervdvn/MapComplete#130]
I know make the option of custom WMS is complicated so I can suggest you to add other well-know renders from OSM you can find in this page at your layers:

https://leaflet-extras.github.io/leaflet-providers/preview/

I use as alternative for OSM the custom render of Openstreetmap France.
Also it would be interesting some Satellite layer (like Bing's or ESRI) or Vectorial layer to reduce the amount of data to download via mobile phone.

Is there any possibility to load the info, work offline but with location GPS and then upload the results?

**Comment by pietervdvn** [comment]
I have integrated https://github.com/osmlab/editor-layer-index instead. This is a curated list which is meant to be used in editors, so this also means that the licenses are cleared for OSM-usage too.

These layers can be tested on _staging_ and will be in the real version shortly.

> Is there any possibility to load the info, work offline but with location GPS and then upload the results?

No. This is a really cool feature, but a lot of work to implement. I hope that I can get this funded one day by someone, e.g. by an OSMF microgrant or someone who needs it (e.g. MSF)
