### ISSUE TITLE
Bug while sharing link

### ISSUE THREAD

**Issue by OliNau** [pietervdvn/MapComplete#1304]
Whenever you generate a shareable link with the "Enable the 'geolocate-me' button (mobile only)" UNchecked, the link that gets generated will not function. Instead the message "Initializing...If this message persist, something went wrong - click here to try again" will be displayed. 

Preliminary testing seems to reveal that only unchecking this last option causes problems. [This link](https://mapcomplete.osm.be/hailhydrant?z=17&lat=51.18200965953089&lon=4.4217073917388925&background=osm&layer-gps_location_history=false&layer-gps_track=false&fs-userbadge=false&fs-search=false&fs-welcome-message=false&fs-layers=false&fs-add-new=false&fs-geolocation=false&language=en) for example, shows the problem.

**Comment by pietervdvn** [comment]
Fixed! Thanks for reporting
