### ISSUE TITLE
Bug while entering dates in the layers menu

### ISSUE THREAD

**Issue by OliNau** [pietervdvn/MapComplete#1308]
When entering a date in the layers menu by clicking on the "dd/mm/jjjj" menu item (for example in the [Notes theme](https://mapcomplete.osm.be/notes.html?z=19&lat=50.88529&lon=4.719403&language=en#filters) ), there is some very weird behaviour. 

1. The days and months are being registered as expected. 
2. The year however seems to continuously override only the last digit.
3. When a date has already been entered, and the user clicks on the dd/ portion to enter a new date/override an old date, the first keystroke is thrown away, to reset the date. This is unexpected, you would think the first keystroke would be immediately registered.
4. When overriding an old date, sometimes you keep continuously overriding the last digit of the day/month you are entering, sometimes you proceed correctly, sometimes you proceed but can only edit the last digit of the day or month, etc.
5. Entering a zero seems to often reset the date.
6. You can enter integers consisting of more than 4 numbers in the year (/jjjj) part.

Entering dates via the keyboard seems to be quite buggy. The calendar, however, works just fine.

Thank you!

**Comment by pietervdvn** [comment]
Hi,

The 'Data Picker' is a standard HTML-data-picker. The implementation is thus provided by the browser and is browser-specific. As such, the issue tracker of the browser you use would be more appropriate to report a bug.

**Comment by OliNau** [comment]
Hi Pieter,

Thank you for your comment. Are you sure this is browser specific? Because this input field looks the same on the three different browsers I tried (Firefox, chrome, edge) and displays the same weird behaviour. 

For clarity, I added a video showing the input field.

https://user-images.githubusercontent.com/19350388/217848556-a4660da0-9110-4ba9-8989-684b40dc3e7b.mp4
