### ISSUE TITLE
I would like a "clock" theme

### ISSUE THREAD

**Issue by vasilisvg** [pietervdvn/MapComplete#1314]
Would it be possible to add a Clock theme, where we could document all outside clocks that display the local time? Municipal clocks, church clocks, clocks on shops, etc. It would be very handy for my [Pix Clock](https://codeberg.org/vasilis/pix-clock) project, but I’m sure there are more use cases.

**Comment by pietervdvn** [comment]
Hi, that would be a fun extra theme to have!

As it is described on the [wiki](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dclock) and is a nice POI-category, it would fit right into MapComplete.

Personally, I'm not taking any requests for themes (I'm rather focusing on the underlying platform + there are too much good ideas), but you can either create it yourself or hope that another contributor picks it up.

In case that you want do it yourself, you can either try the bug-ridden [custom theme generator](https://pietervdvn.github.io/mc/legacy/070/customGenerator.html) or you can try to craft your own JSON file. All documentation can be found [here](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md) - you can sideload a theme by using a special URL, so no need to install. Have a look around in `assets/layers/*` and `assets/themes/*` for examples.

For questions, fee free to pass by in our [chat channel on matrix](https://app.element.io/#/room/#MapComplete:matrix.org)

**Comment by RobinLinde** [comment]
I've made a basic version, available [here](https://mapcomplete-git-theme-clocks-robinlinde.vercel.app/clock.html?z=14&lat=52.36637&lon=4.896211&language=en). Could probably still benefit from some more icons and other details, but should be a nice start

**Comment by pietervdvn** [comment]
@RobinLinde Whelp, that was quick! I don't see any obvious issues when testing the theme, so feel free to open a PR.
