### ISSUE TITLE
Unable to tap a fixed camera 

### ISSUE THREAD

**Issue by Kalepom** [pietervdvn/MapComplete#1335]
Hi,
I was using the Surveillance theme on my mobile phone. I manage to tap and edit a dome camera, but not a fixed camera. When I tried to tap on it, it showed me the pin to add a new POI.

**Comment by pietervdvn** [comment]
This is partly because the 'direction indicator' has set to ignore taps; but even then it is a bit weird.

Workaround for now: disable the 'direction indicator'-layer.

**Comment by pietervdvn** [comment]
Fixed by disabling the direction overlay

**Comment by tuxayo** [comment]
What was this overlay for? I guess it's not deployed at mapcomplete.osm.be so I don't see the difference.

**Comment by riQQ** [comment]
*Surveillance under Surveillance*: https://mapcomplete.osm.be/surveillance.html
