### ISSUE TITLE
Etymology - Handle optional prefixes when multiple can be combined

### ISSUE THREAD

**Issue by Codain** [pietervdvn/MapComplete#1340]
In France (but probably also in other countries), names can contain multiple prefixes and it is difficult to list all combinations. For instance the following can be considered as valid prefixes for a school:

- École
- École publique
- École publique de
- École publique du
- École primaire publique
- École primaire publique de
- École primaire publique du
- École secondaire publique
- École secondaire publique de
- École secondaire publique du
- École de
- École du
- ...

Purpose of this issue is to propose the ability to have some basic patterns such as those in regular expressions. The previous example would then be condensed into something like the following:

`École( primaire| élémentaire| secondaire)?( publique| privée)?( de| du| de la| des)?`

Which would avoid tens of rows to maintain only for this single tree of prefixes.

**Comment by pietervdvn** [comment]
Seems like 'french' had the longest list by now; indeed more maintainable like this!

Please, test [the develop version](pietervdvn.github.io/mc/develop/etymology) extensively for the coming days and report any errors.
