### ISSUE TITLE
Show the current tags on the feature being edited

### ISSUE THREAD

**Issue by StyXman** [pietervdvn/MapComplete#1348]
Sometimes map features are not properly tagged, and maybe answers to the questions asked can be retrieved from other tags. So please show or give the possibility to show the tags that the feature already has.

**Comment by pietervdvn** [comment]
Hi,

MapComplete is geared towards non-technical users, which have never heard of "tags" before.

How do you see this feature? Would all users see those tags? Or only starting from a certain number of changesets? If so, how much? Should the concept of tags be explained to them?

It's also possible to tap the 'osm-icon' on the top right of the info box, this will take you to the entry on OSM itself.

**Comment by StyXman** [comment]
I guess the OSM icon is enough for me. Thanks.
