### ISSUE TITLE
Fields from clipboard appears empty

### ISSUE THREAD

**Issue by yopaseopor** [pietervdvn/MapComplete#135]
In normal and staging. When you make a complex quest may you use the clipboard copying the same message or key sometimes. When you do that it does not work. Well, you will see the field full with your text and seems correct but when you change to the Load JSON tab, it will not work and that field will be empty. And also when you visit your map result.

Also Load JSON tab does not work with JSON copied from clipboard.

I have tried to do this json quest
[opening_covid_19.zip](https://github.com/pietervdvn/MapComplete/files/5381027/opening_covid_19.zip)

**Comment by pietervdvn** [comment]
Hi,

I had a look at this, there is a lot going on here.

- There are errors in the json files (e.g. unclosed strings, commas at wrong places, ...). I've added a warning in such cases
- There was an error in loading from JSON were the tag renderings weren't loaded; this is addressed
- I've addressed a bug where the options and the opening hourss picker weren't working together very well

I've made an [updated version on the wiki](https://wiki.openstreetmap.org/w/index.php?title=MapComplete/covid&action=edit); ([live](https://pietervdvn.github.io/MapComplete/index.html?userlayout=wiki:MapComplete%2Fcovid)), where I've changed a few things:

- I've removed showing all 'amenity' and all 'tourism' - this flat out crashes my browser for it is too much - around 3500 POI [where I live](https://overpass-turbo.eu/s/Z5Y))
- I've added the fancy Opening Hours rendering, for both the covid and the normal hours. There is special syntax for this in 'value to show': `{opening_hours_table(opening_hours:covid19)}`
- Please, do not use an extra mapping for the freeform field, e.g. "The name of this shop is {name}" doesn't have to be put into a mapping. If the key is specified, the 'Value to show' is hidden if that key is not there.
- Maybe add an english translation too? This helps me to debug + makes it easier for me to publish one of your themes as 'official'

**Comment by pietervdvn** [comment]
Example rendering:

![image](https://user-images.githubusercontent.com/1466478/96325948-e4503800-102c-11eb-891f-e686bb389797.png)

**Comment by yopaseopor** [comment]
I explain me:
-The quest was not finished. It was a test. A big test. As you see there was the query in positive and also in negative to restrict the type of amenities and tourism (I think in a nearly future these tags will be changed and business will be with its own tag rather than amenity or tourism.
-The quest was not translated in English because it was not finished. As I realized JSON would not changed correctly I have stopped the quest, I have saved the JSON and wait for your your answer.
-You know I'm not in control about the functionality and the complete understanding of the fields. Sometimes I have tried to full all the fields to test how is it going all.
-Now the quest works I will translate all to English. Also I have unified in wiki page unofficial quest from my user so everybody in wiki can "publish" and review ideas about doing a quest.

**Comment by pietervdvn** [comment]
Hey,

No problem - I understand this was all unfinished. Don't take my words to personal, it was really late when I wrote this and it might not all have been very thought out.

Some of the new features (esp. the opening hours) are _very_ new (as in: yesterday night) so it was impossible for you to have known about them.

Part of the reason I ask to also include all the texts in english is that I can understand better what you are doing and can help you better.

**Comment by yopaseopor** [comment]
Don't worry. I know you don't want to offend me. I know it is not personal, we try to do the best, you the best tool , I the best quest (complex, complete, useful...) test.

The new feature is awesome and I was asking if is there any possibility to show different icons when it is open or when it is closed using new opening hours code.

Also I want to understand better the other new features about images and other codes you put as an example near to new opening hours code.

**Comment by pietervdvn** [comment]
> The new feature is awesome and I was asking if is there any possibility to show different icons when it is open or when it is closed using new opening hours code.

Not yet

> Also I want to understand better the other new features about images and other codes you put as an example near to new opening hours code.

Basically, it allows to add an additional 'add picture' button, e.g. to make pictures of the entrance (image:entrance, image:entrance:0,), the toilets (image:toilets), ... 

Another one allows to display live data from 3rd party API's (example will follow soon)
