### ISSUE TITLE
Display also Mapillary images

### ISSUE THREAD

**Issue by pyrog** [pietervdvn/MapComplete#136]
See this box on [OSM](https://www.openstreetmap.org/node/6778853677), on [MapComplete](https://pietervdvn.github.io/MapComplete/index.html?z=19&lat=45.17197&lon=5.739291&quests=bookcases&tab=4) and [Book Exchange](https://book-exchange.zottelig.ch/?location=45.1714883%2C5.7392908).

**Comment by pyrog** [comment]
Thank you very much 😃

**Comment by pietervdvn** [comment]
It was on my todo list for quite some time, and it turned out to be pretty straightforward ;)

It is live on the [test URL](https://pietervdvn.github.io/Staging/index.html?z=19&lat=45.172&lon=5.738795&quests=bookcases&tab=4); it'll be on the real version soon.
