### ISSUE TITLE
Create information architecture for menu's

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1363]
Basic structure

**Comment by pietervdvn** [comment]
# Theme button

> Everything related to the current open theme

- About the theme (the current 'welcome-screen')
  + explore the map 
  + search a location
  + explore the map around my current location
  + switch language?
- Probably: filtering of features + background layer selection
- Optionally: switch to another theme
- Share-window (as it is _this_ theme we are sharing and building the context for)
- Statistics-window (this is _theme_ related and should thus probably _not_ go into the menu!)

# Menu

> Everything related to the logged in user and MapComplete

- User settings
- About MapComplete
  + What is MapComplete
  + Link to 'Help to translate-setting'
  + Link to source code
  + Link to issue tracker
  + Link to libera pay
  + Link to Mastodon
  + Link to osmcha showing _all_ changes made, not just theme related
- Copyright information
  + small intro on OSM (which links to osm.org/copyright)
  + Overview of contributors
  + Overview of used icons and images (this is actually theme-related, but fits better here)
- Link to privacy page (this is currently a tab in the information panel)

# Other tools

The current menu has a bunch of tools. I'm making a checklist here: they are marked 'done' if they are mentioned above

- [ ] Go back to the overview with all thematic maps
- [x] Support MapComplete financially (LiberaPay)
- [x] File a bug (issue tracker)
- [ ] See latest edits made with <theme> (OsmCha for theme)
- [x] Mastodon link
- [ ] Open iD-editor here
- [ ] Open JOSM
- [ ] Open Mapillary
- [x] Help to translate (which actually links to the settings)

# Open questions

Should we still offer a button to go back to the index? If so, where?

Where should links to other tools at the same location go (Open Mapillary/JOSM/iD here)?

Should the osmCha-button be retained for the theme? Where?

**Comment by tordans** [comment]
https://docs.google.com/spreadsheets/d/1niAMR48eFTCg31hayc8d6DksfFizcNI4fBA9yIgij2I/edit#gid=0

**Comment by pietervdvn** [comment]
This has been implemented by now and is not relevant anymore.
