### ISSUE TITLE
Main page translation

### ISSUE THREAD

**Issue by Kalepom** [pietervdvn/MapComplete#1366]
Hi,
When landing on the main page, the default language is English for the page and the themes
![Capture En](https://user-images.githubusercontent.com/12937457/227463932-2c30fa60-dd85-466e-83bf-45dc12928696.PNG)
I tried to toggle to French, with the menu on the top right of the page. Only the page was in French, themes remain in English. 
![Capture Fr](https://user-images.githubusercontent.com/12937457/227464210-d0c3827c-ffec-4efe-8d35-d0b4c8a08639.PNG)
It's only when I log-in with my OSM account that the page and the themes are in my language.
![Capture logged](https://user-images.githubusercontent.com/12937457/227464372-606037ef-85f7-488e-9449-eab308fa0004.PNG)

**Comment by pietervdvn** [comment]
This is due to the port to svelte. I fixed this in the MapLibre branch (where other big refactorings have happened), but it'll take a while till it hits production.

**Comment by thibaultmol** [comment]
(was about to make an issue about this. cause noticed that search is also effected.
If I search for 'rest' I don't get the Restaurant theme to show up

**Comment by pietervdvn** [comment]
This issue has been fixed a while ago, I'm closing it now.
