### ISSUE TITLE
Suggest people add datestamps to their pictures

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#137]
Inspired by https://forum.openstreetmap.org/viewtopic.php?pid=805098#p805098

It is useful to know when the picture of a feature was taken
If you use OpenCamera, that is easy to do
We could try and nudge people to do that (in particular heavy users)

**Comment by pietervdvn** [comment]
Imgur has a timestamp, the changeset has a timestamp too. It's thus a bit useless to add an additional timestamp.

**Comment by joostschouppe** [comment]
Oh I cehcekd and couldn't find a timestamp on imgur. But it does make sense that the changeset where the tag was added is the moment the picture was made

**Comment by pietervdvn** [comment]
It's beneath the title on imgur - it is _not_ in the description.

**Comment by pietervdvn** [comment]
From an image url, e.g. https://i.imgur.com/I9t6B7B.jpg: change the url to https://imgur.com/I9t6B7B (thus: drop the `i. before imgur
