### ISSUE TITLE
Use a different image host - IMGUR will change its terms of service

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1384]
After flawlessly serving MapComplete for over 3 years, [IMGUR announced that they will start `deleting old and inactive content`](https://help.imgur.com/hc/en-us/articles/14415587638029/).

This means that:

- [ ] A new host for the images should be found
- [ ] MapComplete should show images for that host and upload images to that host
- [ ] All images should be moved and retagged in OSM

**Comment by pietervdvn** [comment]
I sent an email to panormax asking if they want to host these pictures

**Comment by thibaultmol** [comment]
I'll be providing a zip (or whatever) of all current imgur links that can be found in taginfo (with the corresponding metadata (that mapcomplete adds to the imgur description)

**Comment by pietervdvn** [comment]
Link to all the images is here: https://raw.githubusercontent.com/thibaultmol/OSM-image-archiver/main/Snapshot%20of%20all%20IMGUR%20urls%20as%20of%202023%2004%2020.txt

A backup of the metadata is here: https://github.com/pietervdvn/MapComplete-data/tree/main/ImageLicenseInfo

**Comment by riQQ** [comment]
See also #1451

**Comment by nemobis** [comment]
Those 18k images can also be uploaded to Wikimedia Commons, if they're licensed under CC-0. See https://commons.wikimedia.org/wiki/Commons:Bots . I can help with the wiki side of things but this is best done by someone who knows how to retrieve the necessary metadata.

One downside is that they might get deleted if they're deemed to be derivatives of copyrighted work. (I'll check a sample in a moment.)

Discussion now cross-linked from https://wiki.openstreetmap.org/wiki/Talk:Photo_linking#Ephemeral_hosters

**Comment by nemobis** [comment]
After my very scientific analysis of a sample of 20 images, I think probably less than 5 % would be problematic for Wikimedia Commons, and they could be easily double checked after the upload if the type of object is added to the file description or categories (especially graffiti).

| Image URL | Comments |
|---|---|
| https://i.imgur.com/CZ9mHve.jpg  | Plants, infra |
| https://i.imgur.com/K46dnWj.jpg  | Plants, infra |
| https://i.imgur.com/HqgO0XO.jpg  | Infra, readable car plate |
| https://i.imgur.com/7QXHrSf.jpg  | Infra |
| https://i.imgur.com/FLW2NXI.jpg  | Infra |
| https://i.imgur.com/NvGnFba.jpg  | Memorial (1953), likely FOP (Poland) |
| https://i.imgur.com/yc63hZI.jpg  | Plants, infra |
| https://i.imgur.com/WP4KXTK.jpg  | Plants |
| https://i.imgur.com/lCaS2zr.jpg  | Plants, partial building; credited to a Facebook user |
| https://i.imgur.com/BOpul2l.jpg  | Copyrightable sign, likely fop (Germany) |
| https://i.imgur.com/KBFa2fd.jpg  | Readable copyrightable sign (de minimis) and building, likely FOP (Germany) |
| https://i.imgur.com/e9SXx2R.jpg  | Infra, copyrighted sign (work of a living artist), likely not FOP (Belgium) |
| https://i.imgur.com/vG3ec.jpg    | Buildings, copyrightable signs, likely FOP (Thailand) |
| https://i.imgur.com/nnUxbUD.jpg  | Infra, plants, de minimis partial memorial, likely FOP (Germany) |
| https://i.imgur.com/4GrjMRt.jpg  | Copyrightable street art, potentially not FOP |
| https://i.imgur.com/pQbVsc8.jpg  | Infra |
| https://i.imgur.com/tEBP5sA.jpg  | Plants, buildings de minimis |
| https://i.imgur.com/fMR6UFk.jpg  | Infra, plants |
| https://i.imgur.com/84ji9IB.jpg  | Infra |
| https://i.imgur.com/F3dXiSfl.jpg | Monument, likely FOP (Germany?) |

**Comment by pietervdvn** [comment]
The big problem with Wikimedia is that the API is quite hard to use. Additionally, the deletion policy is somewhat unclear and ad-hoc (I had a picture of a statue removed in the past and had troubles with images that my mom took, which all got deleted)

Please also see #1451, which I'll use as main tracker for this issue for now on.

**Comment by nemobis** [comment]
Thanks for the update. Personally I'm only interested in an image migration which preserves open data in the long run, so I'm not concerned about the images which don't respect copyright. I guess I'll submit these URLs [for preservation on Internet Archive](https://wiki.archiveteam.org/index.php/Imgur) and in the future, if MapComplete produces semi-free datasets, Wikimedia Commons can always consider trying an export limited to the subset of freely licensed images.

**Comment by thibaultmol** [comment]
@nemobis most likely they'll be uploaded to Panoramax (like Mapillary, but fully open source and selfhosted. So we're independent from Meta shutting down Mapillary at some point. Who knows.).
see https://github.com/pietervdvn/MapComplete/issues/1451
But that instance hasn't been setup yet.
Panoramax instances have a standard way of exporting their data so it's possible in the end to do that continuously with the right scripts I suppose. (although Panoramax will be 'all' streetlevel images. I'm sure they were will be a 'uploaded by' section in the metadata which will say mapcomplete or similar applications like it)

**Comment by ygra** [comment]
> The big problem with Wikimedia is that the API is quite hard to use. Additionally, the deletion policy is somewhat unclear and ad-hoc (I had a picture of a statue removed in the past and had troubles with images that my mom took, which all got deleted)

Wikimedia Commons also likes images to have some metadata, so they can be found and used. So at least categories should be set and perhaps some Wikidata properties. The latter could be automatically determined from the OSM object, the former can be a bit more finicky since not all categories that might exist, actually exist (e.g. there is *Playgrounds in Tübingen* (beneath *Playgrounds in Baden-Württemberg*, *Playgrounds in Germany* and *Playgrounds*), but for certain things like substations not every level exists. When going that route, themes may have to supply suitable Wikimedia Commons categories for objects, otherwise they may be subject to deletion. Uncategorized images that are also not used on any Wikimedia project generally seem candidates for deletion. (https://commons.wikimedia.org/wiki/Commons:Deletion_policy#Reasons_for_deletion – especially the combination »not useful for education« and »poor quality« may be perilous and potentially debatable, since photos taken with MapComplete may sometimes be more akin to quick snapshots than good photos of the objects.)

**Comment by Discostu36** [comment]
> The latter could be automatically determined from the OSM object,

Sadly this is not possible because it is in violation of the ODBL

**Comment by nemobis** [comment]
> Sadly this is not possible because it is in violation of the ODBL

While license incompatibility causes headaches, I wouldn't jump to the conclusion. If somebody is seriously interested in such an import, the matter can be discussed on the Wikimedia side. See also https://meta.wikimedia.org/wiki/Wikilegal/Database_Rights .

**Comment by Discostu36** [comment]
This is not a conclusion I jumped to. I had a concept for an app that uploads images for OSM objects to Wikimedia and automatically does the categorizing etc. But this means that data from the OSM database would be transfered to Wikimedia Commons image description pages, where it would then be licensed under CC BY-SA 4.0. OSMF told me this is not legally possible.

Details: https://github.com/Discostu36/OSM-Photos/issues/30#issuecomment-1317282204

**Comment by nemobis** [comment]
Il 26/09/23 08:43, Michael ha scritto:
>   OSMF told me this is not legally possible.

Wikimedia Foundation doesn't necessarily recognise the OSMF's idea of 
the sui generis database rights, which tend to be on the restrictive 
side. Also that message is clearly not intended to be an authoritative 
legal opinion: it says "not inbound compatible with CC-BY license" while 
Commons metadata is CC BY-SA + CC-0; it also addresses the hypothetical 
case of "systematically generating a description" which is not 
necessarily what would be needed here.

I don't know about your app idea (sounds interesting but may need some 
rework), but a scope-limited bot is something that can be more 
concretely discussed when asking for approval on the relevant Wikimedia 
wiki. There's not much point speculating about it outside Wikimedia 
projects.
