### ISSUE TITLE
Permission to create a theme

### ISSUE THREAD

**Issue by Auiithar** [pietervdvn/MapComplete#1388]
I want a custom built theme

**Comment by thibaultmol** [comment]
See
https://github.com/pietervdvn/MapComplete#creating-your-own-theme

**Comment by pietervdvn** [comment]
You can create your own theme - see above linked documentation. If the theme is finished, feel free to send it over for reciew after which w3 might include it.

I'm closing this issue as it is low effort and not actionable.
