### ISSUE TITLE
Not operator for search queries

### ISSUE THREAD

**Issue by openbrian** [pietervdvn/MapComplete#1402]
In the overpass query builder there's & and |.  It would be nice to have a ! ("not") operator.

Here's an example.

building=yes & !(building=government | building=office)

Yes this can be done with building!~^(government|office)$, but in terms of a user experience, AND OR NOT is easier to use than regular expressions.

**Comment by pietervdvn** [comment]
While I understand that this is easier to use, this is extremely hard to code and to translate into an optimized overpass-query.

Alternatively, you can use `foo=bar & building!=government & building!=office`.
