### ISSUE TITLE
minimize login widget (especially for smartphones)

### ISSUE THREAD

**Issue by maphouse** [pietervdvn/MapComplete#1408]
The widget isn't a problem on desktop, but on smartphones it stands out unnecessarily and blocks the map.

I think it could be minimized to the size of the icon itself (like the other widgets). Besides, a login is prompted upon map data contribution anyway.

![image](https://github.com/pietervdvn/MapComplete/assets/4475249/c1598b9f-d5a1-4688-9781-07b4df429bc4)
![image](https://github.com/pietervdvn/MapComplete/assets/4475249/a9f3cc56-2d93-46b3-9613-7dbfafba7b39)

**Comment by pietervdvn** [comment]
This request has become irrelevant as the maplibre version does not have a login widget on the home screen.
