### ISSUE TITLE
Question form is borked

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#142]
In https://pietervdvn.github.io/Staging/charging_stations.html?z=15&lat=50.75307&lon=4.253168
when I try to choose "24/7 opened (including holidays)" for "When is this charging station opened?" I cannot save UNLESS I also pick whether or not it's open on PH
Almost all cases of opening_hours=24/7 do NOT have a PH clarification. So i wouldn't make this obligatory.
If I DO pick "PH open", then the bullet at "24/7 openen" is unticked, and the free tect value is filled with "; PH open"

**Comment by pietervdvn** [comment]
Possibly related: if selecting 'skip this question' results in a single textfield, the field doesn't show up. Something is broken...

**Comment by pietervdvn** [comment]
And questions with only options are broken too...

**Comment by pietervdvn** [comment]
Should be fixed
