### ISSUE TITLE
Enhancements to dog/pets layout. 

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#1421]
I think [`amenity=animal_shelter`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Danimal_shelter) and associated sub-tags would be helpful for those looking to adopt rescue animals or find a safe space for strays or injured animals they have found.

For those looking to going on holiday [`amenity=animal_boarding`]( https://wiki.openstreetmap.org/wiki/Tag:amenity%3Danimal_boarding) may also be a helpful pet-centric amenity to have on the map. 

As far as amenities at the "bin" scale, I've just mapped an [`amenity=watering_place`](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwatering_place) which might be attractive to some pet owners.

**Comment by pietervdvn** [comment]
Hi,

Thanks for reporting this!

I'm currently not taking theme requests - there are simply to much good and fun theme ideas.

I'd however invite you to create this theme yourself - you can find documentation here. I'll gladly merge a pull request containing these changes!

**Comment by pietervdvn** [comment]
I'm centralizing all ideas to #1967, so I'm closing this issue
