### ISSUE TITLE
Maplibre: back button on Android doesn't work

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1430]
If I've clicked on an object and it opens the screen with the questions. 
I was very used to close that window with the back button in Android (technically I'm using swipe gestures on my phone. But probably the same)

I guess currently there is no js hook for it, so doing back just means you're going back in urls instead

**Comment by pietervdvn** [comment]
Fixed in 1ec76b66b5551c722efef25663bbb051e5e0d6cb

**Comment by thibaultmol** [comment]
Thx, can confirm it fixed my issue
