### ISSUE TITLE
Email alexATosm-berlin.de does not work

### ISSUE THREAD

**Issue by ViHo030** [pietervdvn/MapComplete#1435]
Hi there,
the email adress does not work. please fix.
Thanks
V.

**Comment by thibaultmol** [comment]
Works for me. Did you by accident leave a space in front of the email address?
![Uploading Screenshot_20230603_100122_Chrome.jpg…]()

**Comment by thibaultmol** [comment]
![Screenshot_20230603_100122_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/0b572a59-8c58-4fac-8f74-bd2198718fa7)

**Comment by ViHo030** [comment]
Sorry, tried ist multiple times, always comes back.

 
 

Gesendet: Samstag, 03. Juni 2023 um 10:02 Uhr
Von: "Thibault Molleman" ***@***.***>
An: "pietervdvn/MapComplete" ***@***.***>
Cc: "ViHo030" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pietervdvn/MapComplete] Email alexATosm-berlin.de does not work (Issue #1435)


 

Works for me. Did you by accident leave a space in front of the email address?

**Comment by thibaultmol** [comment]
Can you copy and paste the url in your browser when you're looking at the object you want to add the email address to?

Also: are you trying to add an actual email@example.com? Or are you trying to add email AT example.com

Because if you're trying the latter, that doesn't work. That's the proper way to format the emailadres

**Comment by riQQ** [comment]
I think they found this email address somewhere in MapComplete and are trying to send an email.

**Comment by thibaultmol** [comment]
Can't find that email in taginfo. So it's not on an osm object

**Comment by riQQ** [comment]
It's here, so not an official MapComplete theme:
https://mapcomplete.osm.be/theme?z=15&lat=52.47525&lon=13.44245&userlayout=https%3A%2F%2Ftordans.github.io%2FMapComplete-ThemeHelper%2FOSM-Berlin-Themes%2Fman_made-walter_well-status-checker%2Ftheme.json&language=de&welcome-control-toggle=true#welcome

This theme is developed here: https://github.com/tordans/MapComplete-ThemeHelper

@tordans can you have a look, please.

**Comment by pietervdvn** [comment]
> https://tordans.github.io/MapComplete-ThemeHelper/OSM-Berlin-Themes/man_made-walter_well-status-checker/icons/pumpe_Freyer.png

The second response of OP (with redacted email addresses) was because they did answer to this Github issue via email (which makes it all very confusing as this is about emails). That reply contains my email address, partly redacted. I did however clean up their response to hide away this clutter.

**Comment by pietervdvn** [comment]
The email address that OP complains about is the email address that is linked in the custom theme: `alex@osm-berlin.de` .  
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/d75096c3-d638-4d87-b7c8-17331a10341e)

@tordans : this one is for you ;)

**Comment by tordans** [comment]
Thanks for letting me know. I fixed the email-address in https://github.com/tordans/MapComplete-ThemeHelper/commit/a61e4a2c9dde3f03a229cf045ea0c3f09913863b.

Another good place to add issues about this custom theme is https://github.com/tordans/MapComplete-ThemeHelper/issues

---

FYI some backstory: This custom theme is linked from https://www.giessdenkiez.de/ which shows "all" street trees from Berlin ("official" data source) and all emergency water pumps (OSM data) which can be used to give water to trees.
<img width="795" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/086b41e1-02fe-490c-b898-de6ead8fadf8">


--- 


> Perhaps you can use the 'Transfer Issue'-functionality to move this issue away form this repo?

That only works inside the same github org, unfortunatelly.

**Comment by ViHo030** [comment]
Thanks. Got it now.

 
 

Gesendet: Samstag, 03. Juni 2023 um 11:48 Uhr
Von: "Thibault Molleman" ***@***.***>
An: "pietervdvn/MapComplete" ***@***.***>
Cc: "ViHo030" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pietervdvn/MapComplete] Email alexATosm-berlin.de does not work (Issue #1435)


 

Can you copy and paste the url in your browser when you're looking at the object you want to add the email address to?

Also: are you trying to add an actual ***@***.***? Or are you trying to add email AT example.com

Because if you're trying the latter, that doesn't work. That's the proper way to format the emailadres
