### ISSUE TITLE
Pumps Date Problem

### ISSUE THREAD

**Issue by ViHo030** [pietervdvn/MapComplete#1436]
Hi there,
am new and not sure if this is the right place for my question, but Email wouldnt work. Signed on to check the Waterpumps in my greater neighborhood. I look one up, e.g. on 31st of May 2023 I checked WaterPump 33 (Pankow Straßenbrunnen 33) map says it needs checking. Today (3rd June 2023) I wand to "submit" my entry and the map says, it has been checked on 19th of March 2023... How come? Takes out the joy!
Thanks
V.

**Comment by thibaultmol** [comment]
If you click on the pump you're talking about you should then see a open street map icon. If you click on that, you'll see the actual object in Openstreetmap and there you can see the history of who edited it

**Comment by thibaultmol** [comment]
If the data in Openstreetmap is wrong then that's not really a map complete issue. 

Openstreetmap is collaborative pretty by thousands of people around the world. Sometimes people make edits that are incorrect. If you think you can edit it to be more accurate, you can just do that

**Comment by ViHo030** [comment]
Hi, 

 

Thats not the problem. The Problem is, that I do look for one unchecked pump. and when I want to submit my findings, it says, pump has been checked months ago. Happened twice out of two.

 
 

Gesendet: Samstag, 03. Juni 2023 um 10:31 Uhr
Von: "Thibault Molleman" ***@***.***>
An: "pietervdvn/MapComplete" ***@***.***>
Cc: "ViHo030" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [pietervdvn/MapComplete] Pumps Date Problem (Issue #1436)


 

If you click on the pump you're talking about you should then see a open street map icon. If you click on that, you'll see the actual object in Openstreetmap and there you can see the history of who edited it

**Comment by thibaultmol** [comment]
I'm confused what your problem is. Someone else much have marked it as checked before you. Like I said, you can check who did it by clicking on the osm logo when you've clicked on the object and see who did that

**Comment by tordans** [comment]
@ViHo030 you are using the custom water pump theme, right? I have a look at the code soonish.

**Comment by pietervdvn** [comment]
I think OP's problem is that they loaded the data a few months ago, checked a pump. Now that they want to update information, they click the pump (which triggers an update) and suddenly see a version that _has_ been checked.

**Comment by tordans** [comment]
@ViHo030 here is an update to the Theme that might address the issue: https://mapcomplete.osm.be/theme?z=15&lat=52.5687&lon=13.507&userlayout=https%3A%2F%2Ftordans.github.io%2FMapComplete-ThemeHelper%2FOSM-Berlin-Themes%2Fman_made-walter_well-status-checker%2Ftheme.json&language=de

I assume the issue we have here is, that we use the `check_date` tag to mean "the pump status OK/broken" was checked. However, that is a convention that is inofficial. It is also valid to use `check_date` when the existence of the pump was checked or other attributes.

- The label how shows "please check" whenever the status is missing
- The label is orange if there is (any) check_date on the pump but not a status


| Before | After |
|--------|--------|
| <img width="852" alt="before" src="https://github.com/pietervdvn/MapComplete/assets/111561/8138d767-31b5-4b35-a4cd-dc188449f821">  | <img width="851" alt="after" src="https://github.com/pietervdvn/MapComplete/assets/111561/70021732-6480-4b03-8c05-babce2edf922"> | 

---

It might also be that there is a date-time issue as well, but that would be very annoying to debug, so I hope this will solve the issue or most of it.

Please let me know!

**Comment by ViHo030** [comment]
Wow....I am a very ordinary person, and just wanted to contribute to the map. Did not know, what kind of traffice I create, when I ask a question. Sorry for that. 
I think the commentary from pietervdvn sounds right to the problem I tried to discrieb, but please feel free to ignore my issue. Thanks to all who tried, I will go about town and try the water pumps and will enter my findings one way or another. Enjoy your Sunday

**Comment by tordans** [comment]
@ViHo030 thank for reporting you issues. Its always great to hear people using the stuff one builds :-). The few people in Berlin that monitor the water pump data are very glad new people join and help keeping the data up2date! — A good place for further water pump tickets is https://github.com/tordans/MapComplete-ThemeHelper/issues.
