### ISSUE TITLE
Upload pictures to Panoramax instead of Imgur

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1451]
With a libre solution for streetview images coming to life (and Imgur potentially removing unused pictures), it is time to switch to a different image provider.

- [x] Load linked images from Panoramax in MapComplete
- [x] Implement an SDK for Panoramax
- [x] Select a default host to upload to
- [x] #2189
- [x] Have 'nearby pictures' also show Panoramax images
- [x] Actually implement uploading to Panoramax + redo the upload flow
      - This will fix #1466, #1472, #1492
      - Also see #1496 to improve discoverability of 'drag&drop' (on desktop)
- [x] Update the mastodon-bot to download from panoramax

**Comment by pietervdvn** [comment]
# Why Geovisio and not Mapillary?

## Why Geovisio

1. Geovisio is open-source; Mapillary is not
2. Geovisio can be selfhosted, which means there will be a range of hosts to choose from. Even if none would suit MapComplete, one could be setup
3. Some form of federation should get implemented (but this is still far away)
4. Funded by the French IGN/OSM
5. Comes from people within the OSM-ecosystem -> big chance a server with "login with OSM" will be setup

## Why not geovisio?

1. It is a very young (and thus immature project)
2. There is no easy to use SDK (yet)
3. Still some uncertainties

## Why Mapillary?

1. It has been around for years and is well-known


One could argue that Mapillary has a big community of contributors. This is absolutely true - but also irrelevant as we still support _showing_ pictures from Mapillary. It's just that pictures from MapComplete will be contributed to a different project.

## Why not Mapillary?

1. It is closed-source
3. It is owned by Meta (aka Facebook inc.)
4. Even though it has been around, the API often does change significantly
5. No "login with OSM" - even though this _used to_ exist
6. Big chance of enshittification

# Totals

Geovisio: 5 pro - 3 con = 2 points
Mapillary: 1 pro - 6 con = -5 points

**Comment by thibaultmol** [comment]
Might be good to mention here as well:
Currently Openstreetmap in general (regardless if it was added using Mapcomplete) has 26421 imgur urls.
I have a backup of all most all of them in this repo: https://github.com/thibaultmol/OSM-image-archiver
Only 18 of those 26421 are currently not working.
It seems like the imgur deletion policy, while potentially very aggressive, hasn't actually resulted in many deletions for these urls.
(It's assumed they mainly used it for NSFW images and very very very old images). So openstreetmap Imgur urls are safe for now. (and as I mentioned: the backup of the images can be found on my github repo)

**Comment by pietervdvn** [comment]
Api reference: https://panoramax.openstreetmap.fr/api/docs/swagger#/Editing

BE test instance: https://panoramax-test.thibaultmol.link/

**Comment by pyrog** [comment]
> ## Why Geovisio
> 3. Some form of federation should get implemented (but this is still far away)

Already working 😄 

> 5. Comes from people within the OSM-ecosystem -> big chance a server with "login with OSM" will be setup

Already working for the French OSM instance.

> ## Why not geovisio?

4. Don't have yet a search engine on metadata like Wikimedia Commons

Apps like [OSM hydrant](https://www.osmhydrant.org/fr/#zoom=19&lat=46.675578&lon=5.554034) can't display images of i.e. https://www.openstreetmap.org/node/6187978703


> ## Why not Mapillary?

6. Don't have yet a search engine on metadata like Wikimedia Commons

> ## Why not Wikimedia Commons
> 1. Very hard to interface with, AFAIK there is no simple-to-use library

Not so difficult to upload pictures.

> 2. Unclear whether they are the place for street-level imagery

A thousands of images of point of interests are uploaded  in Commons

> 3. Needs a ton follow-up in case that someone marks an image for deletion

The author of the picture get message in his Wikimedia account.

> 4. No login with OSM

Both OSM and Commons use OAuth 2 ?
So the app could store both tokens.


I would also like to share a few thoughts: 
- One could setup a "proxy" that upload picture to the chosen platform, and return it's id.
This proxy hide all the complexity and more platforms could be added later without modifying the application.
- Same suggestion with a library.

- Storing permanently or temporarily pictures is not an issue.
The code is the same for the application point of view.

- Some users prefer one platform, some others.
So leave the choice to the user (if possible).

- Getting accurate coordinates isn't so easy.
The application could store the OSM object id in the picture metadata before uploading it.
It could also store categories (i.e. fire_hydrant, guidepost, drinking water…)
- **geovisio** is best known as **Panoramax**

**Comment by pyrog** [comment]
I would also like to share a few thoughts: 
- One could setup a "proxy" that upload picture to the chosen platform, and return it's id.
This proxy hide all the complexity and more platforms could be added later without modifying the application.
Any applications could use it (MapComplete, StreetComplete,Every Door, Organic Maps, Osmand…).
Picture could be uploaded to several platform.

- Same suggestion with a library.

- Storing permanently or temporarily pictures is not an issue.
The code is the same for the application point of view.

- Some users prefer one platform, some others.
So leave the choice to the user (if possible).

- Getting accurate coordinates isn't so easy.
The application could store the OSM object id in the picture metadata before uploading it.
It could also store categories (i.e. fire_hydrant, guidepost, drinking water…)
- **geovisio** is best known as **Panoramax**

**Comment by opk12** [comment]
> ## Why not Wikimedia Commons
> 
>     2. Unclear whether they are the place for street-level imagery
It is out of project scope and not allowed by the policy, as replied at issue 99 ([comment](https://github.com/pietervdvn/MapComplete/issues/99#issuecomment-2336671711)).

**Comment by matkoniecz** [comment]
Note that Wikimedia Commons is fine with photos such as "specific bicycle parking" or "shop interior" taken by smartphone.

It is not place to dump automatically taken aerial imagery that may be blurry and not picturing anything specific, but photo of say specific non-notable bicycle parking is fine. See https://wiki.openstreetmap.org/wiki/Wikimedia_Commons and https://wiki.openstreetmap.org/w/index.php?title=Wikimedia_Commons&diff=1998496&oldid=1890095 and https://commons.wikimedia.org/wiki/Commons:Village_pump/Archive/2016/11#%22realistically_useful_for_an_educational_purpose%22_-_how_broadly%2Fnarrowly_it_is_defined%3F

**Comment by thibaultmol** [comment]
![image](https://github.com/user-attachments/assets/164288d2-f527-45b7-8ac3-20440120fcf9)
(there are some bugs still, but lot's of progress has been made)

**Comment by thibaultmol** [comment]
btw, about the `Have 'nearby pictures' also show Panoramax images` I added to the TODO: you probably want to check the metacatalog for panoramax so you get all images from all instances:

(maybe also query the mapcomplete because the sync from mapcomplete to the metacatalog only happens every 5 minutes)

**Comment by pietervdvn** [comment]
> it to check the metacatalog for panoramax so you get all images from all instances:

This is included

**Comment by pietervdvn** [comment]
As I moved the "image move" into a separate issue, I'm closing this issue now.

**Comment by pietervdvn** [comment]
Also see #2189 , #2178 which forced our hand and #1384 which can be considered a duplicate

**Comment by pyrog** [comment]
Thank you very much ❤️

**Comment by Zverik** [comment]
Regarding the authorization, check out https://gitlab.com/panoramax/server/api/-/issues/227 haha
