### ISSUE TITLE
Introduce `clsx` package

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1461]
I propose to introduce the `clsx` package to handle Tailwind classes.
https://www.npmjs.com/package/clsx

(Side node: There is also a [classnames](https://www.npmjs.com/package/classnames) which is used often, but the clsx package is more performand from what I researched, so I am using this everywhere…)

This package would make places like `class={(options.extraClasses??"") + ' button text-ellipsis'}` nicer to read like `class={clsx(options.extraClasses, 'button text-ellipsis'}`

---

If this sounds good I can create a PR do add it an refactor a few places. @pietervdvn

**Comment by pietervdvn** [comment]
Looks really nice! I'd love to have a PR with this!

**Comment by tordans** [comment]
I had another look at this. Lets try a different library first. I always wanted to try one of those specific tailwind merge libraries but was hesitant due to imagined performance issues. However, https://www.npmjs.com/package/tailwind-merge looks really nice

- twMerge should be used for components that expose a classes prop that can have TW-Class-conflicts
- twJoin does what clsx does and just joins the classes with a nicer UI

twMerge does a lot of fancy caching, so that should be fast as well (details in the link below).

I asked about a performance comparison in https://github.com/dcastil/tailwind-merge/discussions/252; in case that does
