### ISSUE TITLE
Etymology: undo or delete a tag

### ISSUE THREAD

**Issue by Kalepom** [pietervdvn/MapComplete#1462]
In Etymology, if I notice any erroneous information, I can't delete it. You can only change the Wikidata tag to another. If I can't change to the correct value, would it be possible to delete data?

**Comment by pietervdvn** [comment]
This is now possible:

- Click the "edit"-pencil
- Clear the text field
- The 'save' button will turn into an 'erase value' button
- Click this button to remove the value
