### ISSUE TITLE
Multiple questions don't work 

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1471]
I have the setting enabled to show all questions at once, might have something to do with it.

If i click open these two questions at once and then try to answer either of them. It seems to reset rather than submit the answer

**Comment by thibaultmol** [comment]
https://imgur.com/a/VGCBRt6

**Comment by pietervdvn** [comment]
What happens here is that _no_ tag is added on `does not have an integrated artwork` (or rather, it _removes_ the tag).

As no (non-empty) mapping matches, it doesn't register as being 'known' and as such won't trigger.

**Comment by thibaultmol** [comment]
Right ok, but this technically a bug right? (it should 'close' the question dialog when i press save.
