### ISSUE TITLE
Search results doesn't center map 

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1474]
If I'm typing in a location or a set of coordinates into the search box on map complete. I expect the location to be the center of the map. Yet that doesn't seem to be the case. It's close but not in the middle.

Which then also results in the problem if you paste a set of coordinates, and zoom in. You're not zooming in on those exact coordinates

**Comment by thibaultmol** [comment]
With the new crosshair, I can confirm it is indeed centered now

**Comment by thibaultmol** [comment]
wait no... it still doesn't....
If you search for "51.22183254271627, 4.405045890931653" (green circle) for example. You land on "51.221951900067495, 4.405352099999959" (red pin) instead

![annotely_image(10)](https://github.com/pietervdvn/MapComplete/assets/1010226/285d7233-2e4c-461f-8764-47d3c963c67c)

**Comment by pietervdvn** [comment]
Seems to be working correctly nowadays.
