### ISSUE TITLE
Maplibre version: point moves upon creation

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#1477]
When I add a new point in the charging stations theme, the detailed location popup shifts the location of the object always to the south of the point I clicked, always within the circle you can move it (which is centered correctly). This might be related to the map background shifting from the default basemap to the Digitaal Vlaanderen imagery

This happened both on Android mobile and Windows laptop, especially in Firefox but maybe also in Chrome (can't recall)

**Comment by pietervdvn** [comment]
The maplibre component does initiliaze on `0,0`, code then detects that it is out of range and jumps back to the correct range (which also draws a pinkish circle).

I though I already improved this, can you do a hard refresh (hold the refresh arrow) and see if it still persists?

**Comment by joostschouppe** [comment]
Yes, I just tried this. It does NOT happen by default now, but only if I change background maps in the location fine-tuner interface

**Comment by thibaultmol** [comment]
(i also do this actually, now that you mention it. I 80% of the time use aerial for precise picker. So that explains why we're both having it)

**Comment by pietervdvn** [comment]
For some reason, it behaves correctly if the MapLibre background layer is used, but _not_ if a different background layer (e.g. aerial imagery is used)... :thinking:

**Comment by thibaultmol** [comment]
Can confirm that this indeed fixes the issue for me as well

**Comment by pietervdvn** [comment]
Still an issue if using a png-background layer

**Comment by pietervdvn** [comment]
Seems like this is finally fixed
