### ISSUE TITLE
"Move this point" in ghostbikes

### ISSUE THREAD

**Issue by Kalepom** [pietervdvn/MapComplete#1486]
Hi, 
In the ghostbikes theme, I wanted to move a point, but the minimap don't show up in the right panel, and I'm unable to do so. (or am I missing something?)
![Capture](https://github.com/pietervdvn/MapComplete/assets/12937457/ce6a036d-a786-418f-b833-55423caf6ca7)

**Comment by pietervdvn** [comment]
That seems to be a bug.

**Comment by thibaultmol** [comment]
Might be related to https://github.com/pietervdvn/MapComplete/issues/1481
ALTHOUGH I usually find that both the minimap and the big map go blank at the same time

**Comment by pietervdvn** [comment]
I forgot to pass in the initial coordinate into the little map that should move it... oops.

Fixed now, thanks for reporting!
