### ISSUE TITLE
Most unofficial themes on OSM wiki broken

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#1494]
Most of the unofficial themes don't work with the new MapComplete version. 

Is there a migration guide planned to help authors manage the transition? 

Is there an as yet [undocumented](https://github.com/pietervdvn/MapComplete/blob/3df5727f40a29d190394c71cf99896261f78474d/Docs/URL_Parameters.md) URL Parameter to force the legacy version in the interim?

**Comment by pietervdvn** [comment]
There is a piece of code which 'updates' them (I use it to migrate the official themes in bulk).

I've added a special case to fix most of the themes; I've also removed a few themes from the wiki as some of them are in official themes now. I've also pulled in a few questions into the official MapComplete.

Not all of the remaining unofficial themes work (but those have been broken for a long time now), but most work again.

**Comment by InsertUser** [comment]
That's great.
