### ISSUE TITLE
Drag and drop images

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1496]
It would be nice if on desktop you could drag an image from your system's file explorer to an object to add it. (instead of having to go the other way round and open a file picker from mapcomplete directly.

I would assume the UX would be the same as other websites that support drag and drop images. Once the image is being dragged on top of the viewport, it would show a box like this while the mouse is held down with the file being dragged. 

![image](https://github.com/pietervdvn/MapComplete/assets/1010226/e2f7ba6c-d3f1-4d48-8f60-c301939570f3)

**Comment by pietervdvn** [comment]
Drag and drop has been possible for a while, it simply wasn't very visible.

Dragging an image into the view will now let it glow.

**Comment by thibaultmol** [comment]
hmmm, recently tried this again. Doesn't seem to work for me
