### ISSUE TITLE
(hidden theme) mapcomplete-changes broken since maplibre?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1498]
I know it's a hidden theme, but yeah. Just letting you know

**Comment by pietervdvn** [comment]
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/8f7fc235-4b21-4284-827d-8a2a07248b09)

Still works on my machine, but I have to admit that it is slow. I have to admit that this is very low on my list of priorities.

**Comment by thibaultmol** [comment]
Oh yeah. It is indeed just very slow. If you want to close it cause you'll never get to it (improving the speed). That's fair
