### ISSUE TITLE
Tree theme: doesn't show wik

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1500]
With the trees theme: It seems like if the wikidata has `instance of cultivar` it doesn't show up in the search results. 

https://www.wikidata.org/wiki/Q120441606

So for example this can't be found

**Comment by pietervdvn** [comment]
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/130d6881-bbeb-404a-9024-caf2d79bd29d)

Searching for this term finds the entry just fine, I cannot reproduce this.

Is it possible that the weird 'forward' or 'backward' tick is causing issues?

**Comment by thibaultmol** [comment]
Oh yeah, I don't know why I used those instead of regular ' ' 's

I guess if I search

> Acer campestre 'Anny´s Globe' 

it does work
but

> Acer campestre Anny

doesn't work, which might have been the main reason why I was confused it didn't work yesterday.

**Comment by pietervdvn** [comment]
The backticks are an issue of the Media-Wiki-api-search functionality. As I have no power over this and this is relatively niche, I will not fix this.
