### ISSUE TITLE
Language selection no longer being stored as URL parameter

### ISSUE THREAD

**Issue by maphouse** [pietervdvn/MapComplete#1506]
This used to be the case, and was useful for sharing custom renderings of particular themes to people (filtered cyclofix in a particular language). Lang parameter no longer seems to be stored in URL, possibly since migration to maplibre.

It would be useful to restore this features, especially for embedding mapcomplete into a website.

**Comment by pietervdvn** [comment]
Note to self:

- Determine flow to setup language on initial visit (URL-parameter, OSM-language, browser language)
- Sync with cloud if available

**Comment by pietervdvn** [comment]
I thought that this URL-parameter still worked, but apparently, it was broken.

You can find the documentation on how it [behaves here](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/URL_Parameters.md#language)

Note that the URL-parameter is not added to the address by MapComplete, but if it is set it _will_ override the language (unless the contributor is logged in and selected a language before)
