### ISSUE TITLE
Stuck on "creating point" sometimes

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1510]
Sometimes after adding a point you get stuck on this screen. Can't say exactly what triggers it to happen or not happen sometimes.
It does create the object and uploads it successfully. If I close the screen, I can continue working as normal. 
![Screenshot_20230714_173411](https://github.com/pietervdvn/MapComplete/assets/1010226/d8854b77-0411-4534-93d7-1b6643e7a329)

**Comment by pietervdvn** [comment]
Hey @thibaultmol , are you still experiencing this?

**Comment by pietervdvn** [comment]
Probably not an issue anymore.

**Comment by thibaultmol** [comment]
Whoops, forgot to reply. Yeah haven't had this for a while now
