### ISSUE TITLE
No map displayed 

### ISSUE THREAD

**Issue by Karsten-stgt** [pietervdvn/MapComplete#1516]
When opening on Firefox 115.2.1 on my mobile (Android 13), no maps are displayed. 
![Screenshot_20230722_192511_Firefox](https://github.com/pietervdvn/MapComplete/assets/85083089/d5028c6e-e8ce-4dd3-b225-0ac668a73b72)
![Screenshot_20230722_192654_Firefox](https://github.com/pietervdvn/MapComplete/assets/85083089/2b3d1210-3a31-4c83-8070-6a64c24d5319)

**Comment by pietervdvn** [comment]
This was fixed by sending over €25 to MapTiler
