### ISSUE TITLE
Waste theme: underground waste_disposal: zoom and survey:date

### ISSUE THREAD

**Issue by pelderson** [pietervdvn/MapComplete#1519]
Underground [amentity=waste_disposal](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_disposal) systems only show up at zoom 18 and higher. This should be at least from zoom 12 or 13 onwards. 
In addition, because I regularly survey these waste_disposals in my communality, I would like survey:date to be set (with a question/date picker defaulting to the current date). 
The tags I set using JOSM or ID are: 

- access=residents
- amenity=waste_disposal
- fee=yes
- location=underground
- survey:date=2021-08-03
- waste=trash

PS Our communality now also has underground recycling containers for glass and paper. For those I would suggest to add the underground? question.

Thanks!

**Comment by riQQ** [comment]
Zoom was adjusted in #1520

**Comment by RobinLinde** [comment]
Location question is sort of there, although it's not asked explicitly.
[demo](https://github.com/pietervdvn/MapComplete/assets/1395345/e3874795-8dff-4f6e-b701-fa31ee5c48fa)

Survey date question was added in #1522

**Comment by pelderson** [comment]
Tested the changes. I think you were right, zoom 14 is much better suited. 
Also, the icon is a pretty big standard bin image. I think the smaller one, as shown for a recycling station for residual waste (BTW, isn't that a contradiction?), would be much better for this layer.
I can do a PR for the zoom, but I don't know how to change images for the layer icon!

**Comment by RobinLinde** [comment]
Solved in #1530
