### ISSUE TITLE
Bug in Weblate translation request?

### ISSUE THREAD

**Issue by kjonosm** [pietervdvn/MapComplete#1528]
With every update these 5 translation request wrongly show up on weblate despite being already translated into German for several months:

<img width="395" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/51236777/c65e1189-0933-4d02-814c-5b0da54ce62d">

Is there something wrong in the source strings?

**Comment by pietervdvn** [comment]
This is a bug in the script syncing the translation files. Thanks for pointing this out!

Hopefully, it will be the last times you'll translate those five strings!
