### ISSUE TITLE
panning the map doesn't (always) result in showing items in new area

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#1531]
Expected result after panning the map: the relevant features in the area are shown.
Observed result: features are not (always) shown, "There are no relevant features" in the current view" message is shown. For now, I've only experienced this in the notes theme:

![image](https://github.com/pietervdvn/MapComplete/assets/17066627/c9e64ae3-5302-4a4f-b6bb-aa8831222b58)

reloading the page results in showing the features:
![image](https://github.com/pietervdvn/MapComplete/assets/17066627/2fdc066b-0acd-4dfd-b832-4c5e2968cab8)

**Comment by pietervdvn** [comment]
Might be related to #1529

**Comment by pietervdvn** [comment]
Seems to work nowadays.
