### ISSUE TITLE
Get fancy domain name

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1536]
Domain name | Provider | Cost/5year | Cost/10 year |
------------|----------|-----------|---------------|
mapcomplete.org | GoDaddy |   | €207 |
 | | Namecheap.com | |  €115 |
 | | domain.com | $70 | |
mapcomplete.net | namecheap.com | | €128 | 
 | | domain.com | $75 |  |
mapcomplete.app | namecheap.com | | €136.88 |
 | | domain.com | €95 | |
 | | GoDaddy | €95 | |
mapcomplete.world | domain.com | $140 | |
 | | namecheap | | €250
 | | godaddy | | €412
mapcomplete.all | not a valid TLD | |

**Comment by InsertUser** [comment]
I think someone on the Mastodon feed was suggesting mapcomplete.me. Currently [showing][1] as $9.99 (normally $20.99) at Hover. 

[1]: https://www.hover.com/domains/results?utf8=%E2%9C%93&q=mapcomplete.me
