### ISSUE TITLE
Writing Maxspeed attribute omits recommended space between value and unit

### ISSUE THREAD

**Issue by stephennewberry** [pietervdvn/MapComplete#1538]
I used this feature a bit today and noticed speeds are saved in the format of "50mph" without a space. The OSM wiki recommends a space: "50 mph" as shown here: https://wiki.openstreetmap.org/wiki/Key:maxspeed

**Comment by pietervdvn** [comment]
Fixed in 94e07d5b13f86837d02cb6d0906a501a1bdd35fc
