### ISSUE TITLE
Advertising Theme - Spelling Error: "Expres" is mispelled

### ISSUE THREAD

**Issue by TheLimifiedLime** [pietervdvn/MapComplete#1542]
One of the options for a question in the advertising theme has a spelling mistake. The question is "What kind of message is shown?" and it is the 7th option which spells "expres" instead of "express". I believe that it is [this line responsible](https://github.com/pietervdvn/MapComplete/blob/7bcefe527ce080b3f7b7c48fdd1a828289b126c3/assets/layers/advertising/advertising.json#L722C1-L723C1).

**Comment by TheLimifiedLime** [comment]
I also just realized that this may be handled on the [according weblate string](https://hosted.weblate.org/translate/mapcomplete/layers/en/?offset=1&q=context%3A%3D%22advertising.tagRenderings.message_type.mappings.6.then%22).

**Comment by TheLimifiedLime** [comment]
Went ahead and fixed on Weblate.

**Comment by riQQ** [comment]
Will be integrated with #1540.
