### ISSUE TITLE
Ability to 'close' a feature

### ISSUE THREAD

**Issue by scetron** [pietervdvn/MapComplete#1544]
MapComplete displayed a particular feature that required more information; however, this feature (which happens to be a bicycle store) has since permanently closed. It would be nice to be able to 'close' the amenity.

**Comment by pietervdvn** [comment]
I presume you are using "cyclofix". I've enabled the delete button on the 'bike_shop' layer just now, so this will be possible in ~1h

**Comment by scetron** [comment]
Thanks very much for making the connection and the quick turn around.
