### ISSUE TITLE
Move from OAuth 1.0a to OAuth 2.0 for OSM logins

### ISSUE THREAD

**Issue by mmd-osm** [pietervdvn/MapComplete#1548]
OSM's OAuth 1.0a is in the process of being deprecated, as discussed at https://github.com/openstreetmap/operations/issues/867. No timeline has been set, but we do not expect to shut off OAuth 1.0a this year. It would be good to move to OAuth 2.0 well before this time.

**Comment by pietervdvn** [comment]
Hi,

This has come up with the security scan as well, so it is on the roadmap to do.

**Comment by pietervdvn** [comment]
This is now implemented, thanks to the fact that the `osm-auth`-library supports OAUth 2.0 too. 

I'll leave this in the dev branch for about a week, I'll merge into production in about two weeks.
