### ISSUE TITLE
ATM not presented when part of a bank

### ISSUE THREAD

**Issue by ppsoo** [pietervdvn/MapComplete#1551]
First, thanks for the efforts you spent on these thematic maps, which I highly appreciate and use.

I observed the following issue, while completing the few ATMs in the closer vicinity I'm living at: 
+ OSM encompasses individual ATMs 
    --> these ATM are also presented when using MapComplete / theme ATMs.
+ when OSM encompasses a bank with the has-ATM property (like [this](https://www.openstreetmap.org/node/275379177))
   --> the ATM is not presented when using MapComplete / theme ATMs.

<img width="642" alt="Bildschirmfoto 2023-09-01 um 12 44 10" src="https://github.com/pietervdvn/MapComplete/assets/28809346/edb58e0e-86c1-4e96-9374-e58a16abdf6e">

This results in less ATMs than could be presented.

<img width="991" alt="Bildschirmfoto 2023-09-01 um 12 45 34" src="https://github.com/pietervdvn/MapComplete/assets/28809346/2c0fbf58-d003-482e-a17b-8599cb5a1ded">

It seems to me that has-ATM property of banks is not processed.

**Comment by pietervdvn** [comment]
Hey,

The object you linked is _not_ an `amenity=bank`, but a `amenity=post_office`.

I have added a question about ATMs to post offices and enabled this layer in the 'ATM'-theme.

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/e80851bc-ce35-4c35-a498-fc0e4f93bd61)

This will be available on https://dev.mapcomplete.org/atm within an hour (if nothing goes wrong) (and will become available on the production instance soon)

**Comment by ppsoo** [comment]
In fact it's a bank, though called Postbank. Postbank is [owned by Deutsche Bank since 2010](https://en.wikipedia.org/wiki/Deutsche_Postbank). In addition to offering banking services, all  these locations also offer the service to handle letters and parcels etc.

Thanks anyhow.

**Comment by lukask99** [comment]
This issue not only applies to banks and post offices, but also to shops in which ATM's can be located, at least in The Netherlands. See for instance https://www.openstreetmap.org/node/2715769065
