### ISSUE TITLE
Cyclestreet theme: show colored lines when zoomed out

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1559]
Currently the theme just doesn't render anything if zoom out past z 18.
I get that it doesn't make sense to display the pencil icons everywhere beyond that zoom level. but it would be nice to atleast see the actual cyclestreets lit up in a color when zoomed out

**Comment by pietervdvn** [comment]
The cyclestreets should show up at higher zoomlevels:
![Uploading Screenshot_20230904-192310.png…]()

**Comment by pietervdvn** [comment]
![Screenshot_20230904-192310](https://github.com/pietervdvn/MapComplete/assets/1466478/0791f0c1-d076-4faa-8c8f-963339515f29)

**Comment by thibaultmol** [comment]
Not sure what happened last time i tried.

I guess also question: is there a way to disable the icons? so you just see the lines?

**Comment by pietervdvn** [comment]
Cannot reproduce the main issue, so I'm closing this.

No, there is currently no way to disable the icons (unless the theme would be changed)
