### ISSUE TITLE
Add a full redirect

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1560]
The URLs to our custom theme from https://www.giessdenkiez.de/ `https://mapcomplete.osm.be/theme?userlayout=https%3A%2F%2Ftordans.github.io%2FMapComplete-ThemeHelper%2FOSM-Berlin-Themes%2Fman_made-walter_well-status-checker%2Ftheme.json&language=de#node/760002906` are broken due to a missing redirect to the new domain.

https://github.com/tordans/MapComplete-ThemeHelper/pull/3/files (https://github.com/tordans/MapComplete-ThemeHelper/issues/2) fixes this for the future, but existing URLs should not break.

Can there be redirects to the new URLs? Those could be JS redirects (they don't need to be true 301 redirects).

**Comment by RobinLinde** [comment]
Currently there are redirects created for every file using [this script](https://github.com/pietervdvn/MapComplete/blob/develop/scripts/generateRedirectFiles.ts), but they don't include any URL parameters, so using JS might be better, and shouldn't be too hard to do

**Comment by pietervdvn** [comment]
I think the window of usefulness for this has moved on, so I'm closing this issue.
