### ISSUE TITLE
Etymology: streets with the same name in different towns

### ISSUE THREAD

**Issue by Kalepom** [pietervdvn/MapComplete#1562]
Hello, 
In the Etymology theme, when I answer a question about a street, it is also applied to a street of the same name in the next town. 
Perhaps the information should only be propagated to contiguous streets, or the increment radius of an answer should be reduced.

**Comment by pietervdvn** [comment]
Hi,

The trick here is to find the right balance. Parallel streets might not touch (and writing an algorithm that detect 'contiguous streets' takes quite a bit of time).

I can reduce the application range, but then extremely long streets with the same name will take more time to map.

How far away is the street that did receive etymology unintentionally?

**Comment by Kalepom** [comment]
It was the village next door. I'd say it was about 5 km away.
