### ISSUE TITLE
When logged in, no additional questions

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1579]
Both on stable and dev.
Chrome android and firefox linux

If i'm not logged in, I see:
![Screenshot 2023-09-23 at 08-07-21 Charging stations](https://github.com/pietervdvn/MapComplete/assets/1010226/6e4a39fc-a9ca-4945-bf8e-f8e1ffa52974)

When i'm logged in, I see:
![Screenshot 2023-09-23 at 08-05-34 Charging stations](https://github.com/pietervdvn/MapComplete/assets/1010226/7712985a-5591-42e1-92a8-ed2c2a1b54e6)

**Comment by pietervdvn** [comment]
Probably the same root issue as #1580

By any chance, do you have 'show all questions at once' enabled?

**Comment by pietervdvn** [comment]
Confirmed: same root issue as #1580

Root cause: there is some code calculating - for multi-answer questions - which of them are already checked. However, this code would also run for _non_ multi-answer questions, crashing stuff.

**Comment by thibaultmol** [comment]
> Probably the same root issue as #1580
> 
> By any chance, do you have 'show all questions at once' enabled?

Yep
