### ISSUE TITLE
App goes white after closing the object dialog

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1580]
reprod on chrome android and firefox linux (BUT only when using a phone res through dev tools. So that the object dialog goes full screen).
https://imgur.com/HLYVVEX

**Comment by thibaultmol** [comment]
Related to this.

If I for ex open 
https://dev.mapcomplete.org/aed.html?z=18.1&lat=51.04564&lon=3.409414#node/11187907241
(firefox linux).
and then refresh. The url changes (the node/11187907241 goes away) and the right sidebar goes blank. The buttons on the main screen (left in this screenshot) no longer do anything).
if I THEN refresh, it goes back to normal
![Screenshot 2023-09-23 at 08-46-26 Defibrillators](https://github.com/pietervdvn/MapComplete/assets/1010226/ccd9d90d-ff24-4e42-b3aa-3aaa90dc8362)

**Comment by pietervdvn** [comment]
Thanks! I could reproduce the issue, it's now fixed.
