### ISSUE TITLE
"zoom to your location" button on theme-menu:intro needs clarification

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1583]
When the location hasn't been established yet, and you click that button. Nothing happens, it should maybe add an event in the queue when the location is established that it then closes the dialog and moves the map.

Currently if you press it and location hasn't been established, there is also no visual indicator WHY nothing happens if you press the button

**Comment by thibaultmol** [comment]
Seems like if the permission is never granted. The button just disappears?

Also: i installed the dev as pwa and i never get a permission request for location.

(And it would be nice if there was a popup with a text explaining the error of the icon in the bottom right
![Screenshot_20230925_180433_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/d533009c-2493-411b-9864-3d186cd5710d)

**Comment by pietervdvn** [comment]
Yes, if the user refuses to use geolocation, no use to show the button.

If you install it as PWA, you have to give permission via the browser; that's not something I can fix

**Comment by thibaultmol** [comment]
> Yes, if the user refuses to use geolocation, no use to show the button.

In that case, it might still have been the user accidentally not giving the permission. So instead of the button disappearing when you click it. Maybe it should say "no geo location permission given"

> If you install it as PWA, you have to give permission via the browser; that's not something I can fix

also fair: BUT again, user needs to be made aware of this (I actually assumed that at this point an installed PWA would have been able to give a permission prompt.)
