### ISSUE TITLE
Login if pwa is installed

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1591]
There's a problem if you have the PWA installed but aren't logged in yet (or were logged out and you need to log back in).

Both if you are on the webpage itself in chrome:

https://github.com/pietervdvn/MapComplete/assets/1010226/d2551778-0493-42da-aa48-ff153a4ba314

or if you're in the pwa and starting an auth session.

https://github.com/pietervdvn/MapComplete/assets/1010226/2097c068-5e74-451f-bee4-13a859a251a6

In both cases it never finishes the handshake

Workaround: temp turn of 'open supported links' in the pwa settings. But yeah, very much a workaround

**Comment by riQQ** [comment]
Offtopic: could you please upload images to GitHub (e.g. via the image button in the edit box) so everything is in one place? Thank you.

**Comment by thibaultmol** [comment]
The videos were too big to upload to GitHub, hence why i just imgur.  I'll just compress them and put em here maybe

**Comment by pietervdvn** [comment]
I did test the flows on Fennec, Brave and Firefox and this seems to work as expected now. It seems that the browsers have improved here.
