### ISSUE TITLE
Unable to create new items or make changes

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1593]
As mentioned to Pieter yesterday:
I can't seem to create any new objects or edit them.
Also debug info is turned off, but still displays.

I did recently revoke oauth1.0 auths on my osm account. Mapcomplete still has the 2.0 auth.
I don't know if it's related but happened around the same time
![Screenshot_20230926_235943_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/81746aff-613a-4d5e-9956-6e4984db7a55)

**Comment by thibaultmol** [comment]
![Screenshot_20230927_100639](https://github.com/pietervdvn/MapComplete/assets/1010226/c4d3ccec-9bbc-4eb3-a40d-95a5e61ea5aa)

**Comment by pietervdvn** [comment]
Oeps, this is a stupid mistake by me!

**Comment by thibaultmol** [comment]
Can confirm the issue is fixed (and the problem where I couldn't get gps location to work is also fixed) thx!
