### ISSUE TITLE
Location stops working on second session

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1596]
First time you load the page and it asks for location permission, it works. But after second load, it breaks

Steps to repro:
- Open a MapComplete theme
- It asks for location perm, you grant it
- it successfully gets your location and the button changes 
- you reload the page
- it still has the location permission but no longer actually gets your location (the button doesn't change and the location button at the right bottom also doesn't work)

https://github.com/pietervdvn/MapComplete/assets/1010226/6eccdd26-fe22-4042-98af-d9a471b85c0b

Tested on dev. Chrome mobile and chrome desktop (firefox didnt work because it only granted temporary permissions anyway for me)-

**Comment by pietervdvn** [comment]
Again an oopsie on my part... Fix in progress
