### ISSUE TITLE
Recognize "51.05021/3.34573" as valid coordinates in search

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1599]
I know there's probably a lot of these types of edgecases.
But Maybe this one could be added.
"51.05021/3.34573" doesn't work
"51.05021 3.34573" does work

**Comment by thibaultmol** [comment]
TIL this is not a Nominatim problem, it is indeed a problem with the website parser itself. (but osm's website has the same problem)

https://github.com/osm-search/Nominatim/issues/2776

https://github.com/openstreetmap/openstreetmap-website/issues/4285

**Comment by pietervdvn** [comment]
Included in #2156
