### ISSUE TITLE
Background imagery goes white after osm object created

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1606]
I've had this multiple times , not 100% reproducible but very common to happen.
You select an imagery layer. add object. wait till it's added to osm. Then that (and any other) imagery layer becomes white  until you refresh the page again.

https://github.com/pietervdvn/MapComplete/assets/1010226/d26ba37e-85b8-4a42-941b-d468111a64bc

**Comment by pietervdvn** [comment]
Is this still happening?
