### ISSUE TITLE
FR: CTRL + ENTER to confirm a text box in MapComplete

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1608]
I understand that you maybe don't want ENTER to actually submit a text box, but I think it would be quite nice to do CTRL + ENTER to submit a text field on an object

**Comment by pietervdvn** [comment]
This is implemented in the 'studio'-branch, so a few weeks of patience and you'll get this

**Comment by pietervdvn** [comment]
The studio branch has actually landed; `Enter` does submit a question.
