### ISSUE TITLE
Adding new "points" on existing objects?

### ISSUE THREAD

**Issue by chrneumann** [pietervdvn/MapComplete#161]
Use case for the climbing map: Adding a new point would only make sense for e.g. unmapped boulders. Existing cliffs, climbing gyms etc. can not be mapped if they don't have a tag that fits the layer. I guess it's not that easy to implement adding a layer to an existing object? E.g. to a building which has not been tagged yet as sport=climbing? Maybe one should make this clear to the user, i.e. that one should not just add a new point "over" an existing object, e.g. a building. I guess that is more harm (for OSM editors who have to fix it) than the new data is worth it? Maybe user should be asked to add a bug note to the map instead (which is not that obvious how to do)?

**Comment by pietervdvn** [comment]
I've had a similar problem with the theme [Fietsstraten](https://pietervdvn.github.io/MapComplete/fietsstraten.html?z=15&lat=51.026&lon=3.1262&background=osm). The Fietsstraten theme shows all streets with a tag 'cyclestreet=yes' and allows to mark additional streets with it.

I've solved it there by having a layer with _all_ streets, which only pops up on zoom level 18 (min_zoom does that). You can do something similar: add a layer with all cliffs which only shows up. As you're already using the Roaming Renderings, they should automatically show up on the cliffs once they are marked as being a climbing cliff - if the conditions for the Roaming Renderings are set up right.

BTW: I saw the 'kletterspots.de' - AWESOME!!!!! I already love it!

**Comment by chrneumann** [comment]
Ah nice, great idea. Will try this, thanks :)

I will do some user testing, and at some point, create a merge request for the layer. Might take some time ;) But the code is online:
https://github.com/chrneumann/MapComplete/tree/feature/climbing-layer
https://github.com/chrneumann/MapComplete/tree/kletterspots-develop (The kletterspots.de instance with some tweaks)
