### ISSUE TITLE
GRB theme: map goes black when zooming into data

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1613]
Reprod on both stable and dev. 
- Open GRB Theme
- zoom in till you get to see data
- Sections of the map go black. 

if you reload when that happens, it's fine. it's specifically zooming from no data to seeing data.

https://github.com/pietervdvn/MapComplete/assets/1010226/82f9758a-5f59-4282-9cbc-541d4c54160d

**Comment by pietervdvn** [comment]
THis was a subtle bug in how ways were rendered, should be fixed by 055e5a801b60276cdfcf31870fae29e6af30521b

**Comment by pietervdvn** [comment]
Or maybe not, I can still repro

**Comment by pietervdvn** [comment]
I haven't seen this in a while, so closing.
