### ISSUE TITLE
Black on black icon and icon not loading

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1615]
On the charging theme, stable (0.33.6) i noticed an icon not load and also noticed how black icons there aren't actually visible cause they're just black on black
![Screenshot_20231001_161149_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/66784ab0-3bd6-426f-a9c6-2122e008a22e)
![Screenshot_20231001_161143_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/fc0cd9ca-a4d4-48b2-8416-0570a12a2536)

Not at home, so can't use devtools to check why.
I'm also not sure if this bug has been here for a while and i just hadn't gotten to reporting it

**Comment by thibaultmol** [comment]
![Screenshot_20231001_195512_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/ffed4933-430a-4e5a-9856-750cf52f16b3)
Another screenshot of icons not loading

**Comment by thibaultmol** [comment]
I think this issue itself is fixed? Can't repro on fennec

**Comment by thibaultmol** [comment]
@pietervdvn

**Comment by pietervdvn** [comment]
Indeed, I fixed this a whole while back but forgot to close this issue.
