### ISSUE TITLE
Incorrect error when trying uploading images that are too large

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1617]
If you're trying to upload image that are too large for the Imgur upload api to handle, you can get an error. But the error message the user gets doesn't reflect that THAT is the problem.

also: maybe there's a difference between what imgur SAYS their upload is and what it actually is.
Because of my three images two of them are actually 19,xxx MB.
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/97260b67-7183-4f0e-9892-aff35bc1634f)

https://drive.proton.me/urls/QY39DC9CN0#ESM4IHDAuAt5 (zip file with the images)

https://github.com/pietervdvn/MapComplete/assets/1010226/cbbed155-3456-48c9-9b3b-436f337c3859

~Pretty sure this was possible a couple weeks ago. But somehow now trying to upload multiple image at once triggers some kind of bug.
Reprod on both mobile chrome and desktop firefox. Both stable and dev~

**Comment by pietervdvn** [comment]
Can you please send the those images you selected + the OSM-id of this vending machine? You can zip the images and put them in this issue.

**Comment by thibaultmol** [comment]
@pietervdvn updated the issue to reflect the actual problem. (I discovered it when zipping the files). If I compressed them, there were no longer a problem

**Comment by thibaultmol** [comment]
Also: It might be worth mentioning squoosh.app in that new error message.
it's a free and fully local (using mozjpeg'c library running in browser using webassembly) to compress images nice and quick without leaving your device: https://squoosh.app
