### ISSUE TITLE
Save all tag/value changes once per node to OSM - not piecewise

### ISSUE THREAD

**Issue by sfkeller** [pietervdvn/MapComplete#162]
Hi, Nice webapp I long waited for. 

But I'd strongly suggest not to  upload to OSM each value a user "saves" it. Upload all changes to a node at once.

Reason is, that although this is technically possible, this IMHO isn't how the API was meant: It involves an unnecessary overhead of metadata, it increments the node version each value update, and it floods changeset statistics without good reason.

I tested this suboptimal behavior here: https://www.openstreetmap.org/node/4493830580/history or https://www.openstreetmap.org/node/7297009485/history .

So "Save" could be renamed to "Ok" - and "Save" is shown at bottom or at the end the tag/question list. I'm aware that this involves some programming. But it's worth to be compliant to the best practices of the OSM API.

**Comment by pietervdvn** [comment]
Hey Sfkeller,

Welcome to the repo - and indeed I'm quite fond of it too ;)

The decision to send of every change immediately, is based on _user design_ and not a technical issue. The design aims to be as easy to use as possible. I do not want to burden the user with an extra click to 'save' - it is an extra step that might be forgotten about, they might not see the 'save' button, ...  From the users perspective an extra button doesn't make sense - and I will veto an extra button.

Furthermore, I could fall back to tricks such as saving to local storage for a few seconds, or only when the user leaves the object, ... However, these all have their drawbacks (mostly that they are more unreliable).

But you are right that it is suboptimal. Is there some other implementation possible that meets the requirements?

**Comment by simonpoole** [comment]
There is no need to do anything exotic at all: don't close the changeset and instead check before upload if it is still open (and open a new one if closed, but that normally won't be the case).

**Comment by simonpoole** [comment]
The other dimension of brokeness is that there us no way for the user to declare what they are using as a source. Making the edits very unauditable and depending on the subject prone to being reverted.

**Comment by pietervdvn** [comment]
> There is no need to do anything exotic at all: don't close the changeset and instead check before upload if it is still open (and open a new one if closed, but that normally won't be the case).

This is already the implemented behaviour (even better: the CS-number is saved and reused if the app is opened again); the original issue was about the version numbers on the original nodes which get bumped (all within the same changeset)

> The other dimension of brokeness is that there us no way for the user to declare what they are using as a source. Making the edits very unauditable and depending on the subject prone to being reverted.

The app is setup to go out and survey, just like StreetComplete. If there is anything I can do to improve this without bothering the user, let me know.

**Comment by simonpoole** [comment]
> 
> 
> > There is no need to do anything exotic at all: don't close the changeset and instead check before upload if it is still open (and open a new one if closed, but that normally won't be the case).
> 
> This is already the implemented behaviour (even better: the CS-number is saved and reused if the app is opened again); the original issue was about the version numbers on the original nodes which get bumped (all within the same changeset)

Stefan was complaining both about version increase and additional changesets.

> > The other dimension of brokeness is that there us no way for the user to declare what they are using as a source. Making the edits very unauditable and depending on the subject prone to being reverted.
> 
> The app is setup to go out and survey, just like StreetComplete. If there is anything I can do to improve this without bothering the user, let me know.

We had exactlly the same issue with StreetCOmplete, in particular massive copying of street names from google, the fix was to require the user to actually be nearby the object they were changing.

**Comment by pietervdvn** [comment]
> Stefan was complaining both about version increase and additional changesets.

There is at most one CS created per hour per theme, so the number of changesets should not be a problem. The version increase is still something to improve, but I don't know what the best course of action would be here.

 > We had exactlly the same issue with StreetCOmplete, in particular massive copying of street names from google, the fix was to require the user to actually be nearby the object they were changing.

In StreetComplete, the user is _nudged_ to be close to the location. If not, they get a popup which asks 'Are sure and didn't copy anything?' - together with the option to 'not show the popup anymore in the current session'.
This is something I could add as well if the user gave their location.

It also seems like this problem was mainly with the StreetComplete quest 'what is the name of this place'. We could add certain restrictions on certain questions in MapComplete if these questions turn out cause problems.

However, I think that it is more useful to directly contact the offenders using the messaging system; adding new points (in MapComplete) is blocked if the user has unread messages - in case that some user is sending feedback.

**Comment by sfkeller** [comment]
I'm happy to discuss issues about misuses from the user side - but here, I'd like to stick to the issue in the title. 
I see that the CS isn't closes - but the increase of the version for every single added tag isn't good for many reasons (like change detectors). 
This is really something which happens currently by design of the software which asks about a tag and writes it as can be seen here: https://www.openstreetmap.org/node/7297009485/history
This means that if 5 tags are added per quest, the version of every single element is being increased systematically 5 times (except for a skipped question).

**Comment by pietervdvn** [comment]
Yes, I know; that is indeed the current design as it makes local storage and all these shenigans obsolete.

The remaining question now is: what is a decent way forward to fix this pragmatically? My concerns are usability (thus: _no_ extra buttons to click for the user) and reliability (no weird tricks which can cause answers to get lost or extra servers that can go down).

Does the API support reusing a version number?

**Comment by sfkeller** [comment]
> Does the API support reusing a version number?

No, it does not for obvious reasons.

Bundling changes to one on more than one tag on an OSM element (or on an resource or entity in informatics terms) really is the job on the API users side.

**Comment by pietervdvn** [comment]
I have improved the uploading somewhat. Uploading now only happens:

- If the webpage looses focus or is closed
- After 30 seconds of inactivity
- If the popup is closed, and no popup is opened again

While the version number of a node can still be bumped a few times per CS, this should rather be the exception then the rule now. Furthermore, it will be only one extra bump instead of one bump per answered question.

> Actually, @simonpoole offered a solution not to close the changeset and instead check before upload if it is still open.

No, he didn't - that behaviour was already implemented long before this issue was opened.

**Comment by pietervdvn** [comment]
This approach works, but is still a bit too aggressive and might be tuned further

**Comment by pietervdvn** [comment]
Turns out that mobile phones are quite aggressive in closing tabs (and don't show the 'are you sure to exit'-dialog), so I'm sticking with the behaviour that uploads on focus loss
