### ISSUE TITLE
Multiple changesets created?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1620]
I can't repro. But what I was doing was adding a clock, wall mounted. Then realized after creating it that it shouldn't have been wall mounted. so I changed it to pole mounted. And then the moving button did light up, which it shouldn't have because way-connected nodes can't be moved with mapcomplete.

I think it's related to that, why after reloading the theme multiple times (because the moving interface was not loading the background imagery) it must created multiple changesets, creating multiple clocks in the process.

5 clocks were created in osm, 4 of which are just loose nodes and one is connected to the way. They're all on the exact same location.

I'm leaving the clocks up for the next 48 hour in case you need to see them to identify things. But I will delete them after that. And fix the remaining one

https://www.openstreetmap.org/changeset/142005361
https://www.openstreetmap.org/changeset/142005346
https://www.openstreetmap.org/changeset/142005331
https://www.openstreetmap.org/changeset/142005277

![Screenshot_20231001_231228](https://github.com/pietervdvn/MapComplete/assets/1010226/6cedc88e-8ebb-46c6-a088-d37cc0af0c70)
![Screenshot_20231001_231200](https://github.com/pietervdvn/MapComplete/assets/1010226/e4745184-df48-4bb7-816e-51d8f6c1cbeb)

https://www.openstreetmap.org/node/11232593239
https://www.openstreetmap.org/node/11232589969
https://www.openstreetmap.org/node/11232568797
https://www.openstreetmap.org/node/11232588239

**Comment by pietervdvn** [comment]
When the upload is completed, the changes are flushed from memory. However, if you reload _while_ uploading, they might be saved and the upload might be re-attempted.

Furthermore, the 'move-point' was fixed previously, so I'm closing this now.
