### ISSUE TITLE
The meat icon that is not displayed on the map (vending)

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1622]
I'm not sure if this is intentional but the meat icon that you can set in the vending machine theme doesn't show up next to the node on the map.
Example
https://mapcomplete.org/vending_machine.html?z=12.1&lat=51.01799&lon=3.33651#node/11211866862
![Screenshot_20231002_072623_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/fd914c32-e40e-4ccf-880f-5a6663f8a2b7)
![Screenshot_20231002_072635_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/4c89cf93-b3b3-41c8-8dc5-e5938742a99d)

**Comment by RobinLinde** [comment]
Should be fixed in #1643, though I might have missed the white circle background...
![image](https://github.com/pietervdvn/MapComplete/assets/1395345/9013da6a-35a0-40fe-8179-ceae38284b30)

**Comment by pietervdvn** [comment]
Seems to be fixed!
