### ISSUE TITLE
Scrolling horizontally through images goes in steps?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1624]
I don't know if this is intentional, but if you're horizontally scrolling through the image carousel (SHIFT + Scroll),
then even if your mouse scrolling speed is relatively consistent, it will scroll the carousel in chunks, each with it's own deceleration and acceleration in the ui scrolling speed.
I'm probably doing a bad show of explaining it.
But like in this video: I'm scrolling on my mouse, but what I think is happening is that mapcomplete's ui is taking the scroll speed for a certain period of time, and doing that scroll. Then once that's done, again it looks at the scroll speed and does another scroll.
While I THINK it should just continue scrolling as long as it's receiving scrolling from the mouse until maybe some kind of minimum threshold.

https://github.com/pietervdvn/MapComplete/assets/1010226/9b654d96-a74e-4ffe-bca5-550cf3117296

This is a stupid and small issue, but yeah, wanted to report it anyway

**Comment by pietervdvn** [comment]
This is actually intentional, as to have one image in view at the same time.

**Comment by thibaultmol** [comment]
I understand where you're coming from, but I think this implementation just doesn't feel right. It's hard to explain, but the 'snapping' it currently does is just based on mouse acceleration. Not dependant on the actual content inside.
You know how when you turn an old nob on a dishwasher and it snaps between each position. I think it should be like that somehow.
