### ISSUE TITLE
Share button in the left top of the object dialog is gone in dev

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1625]
I feel like this happened quite recently, (maybe related to the recent CSP change(?)

But I noticed that the share button is no longer there, while in stable it's still there.

![Screenshot_20231002_102808](https://github.com/pietervdvn/MapComplete/assets/1010226/939e0a06-21ea-4f06-9d23-323d220388bb)
![Screenshot_20231002_102815](https://github.com/pietervdvn/MapComplete/assets/1010226/dbf26e00-2ec2-4fcc-8a85-b5c33cfe4d1c)

**Comment by pietervdvn** [comment]
I cannot reproduce it (tested on Fennec and Ungoogled chromium) on mobile, the share-icon shows up both on dev and prod.

Note that some browsers don't support sharing

Can you tell me which browser you are using?

**Comment by thibaultmol** [comment]
Sorry, should have mentioned that.

Firefox on desktop: [Firefox 118](https://whatismybrowser.com/w/5GYYKZ6)

**Comment by pietervdvn** [comment]
Wow, as far as I know, firefox does _not_ implement the share-api on desktop. Does it actually _do_ something if you click the share icon?

**Comment by thibaultmol** [comment]
Yeah, on Linux it opens the kde plasma share menu

**Comment by pietervdvn** [comment]
Ah, right. I guess your on Kubuntu then?

The firefox which comes with Kubuntu has a plugin preinstalled which does some integrations, such as the share menu.

Can you have a look in the debug settings if `supports_sharing` says `yes`?
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/2d206835-fe08-4d84-8245-b5f2169bb24d)

**Comment by thibaultmol** [comment]
Today i'm not able to get the share button to show up in Stable either.
it says `supports_sharing | no` now, but maybe it did in a previous version of stable. 
I'm on Garuda, kde plasma, and I do have the 
https://addons.mozilla.org/en-US/firefox/addon/plasma-integration/
addon installed, but I'm not sure if that's related or not.

**Comment by pietervdvn** [comment]
> Today i'm not able to get the share button to show up in Stable either.

Which is expected, as I merged dev into stable yesterday.

**Comment by pietervdvn** [comment]
I'm using `window.navigator.share !== undefined` to detect if sharing is enabled

**Comment by pietervdvn** [comment]
I tested with FF on a virtual KDE. The share button does show up, but seems to be dysfunctional - it triggers an "Operation not supported" when clicked. I'm afraid this is an upstream issue.
