### ISSUE TITLE
mapcomplete is stuck loading

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1628]
I've had this once before but couldn't repro. now I can repro (until I deleted the cookies and data).
so it's a real repro.
![Screenshot_20231002_121036](https://github.com/pietervdvn/MapComplete/assets/1010226/589e8cff-03aa-4173-b584-9d664011fd3b)
![Screenshot_20231002_121027](https://github.com/pietervdvn/MapComplete/assets/1010226/0a842bc0-bb65-4045-a0fd-0277094935a2)

Atleast I managed to capture some devtools screenshots.

So it's just stuck on this: (multiple tabs open with different themes, all the same issues. refreshing doesn't fix it. Dev was not affected, only on stable. Clearing data,cache and cookies fixed it)
There was no recent deployment according to /actions, and it's been working fine today before this happened.
![Screenshot_20231002_121041](https://github.com/pietervdvn/MapComplete/assets/1010226/fa7bb6a0-d130-4212-98ca-5f66e216a069)

**Comment by pietervdvn** [comment]
Fixed in f2375f4

This only affected people if a pending change was present
