### ISSUE TITLE
Vending machine icon doesn't get highlighted

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1629]
This might apply to other themes as well, but I noticed that the vending machine icons on the map, don't get highlighted when they're opened in the object dialog.
![Screenshot_20231002_134034](https://github.com/pietervdvn/MapComplete/assets/1010226/b93b3645-7e39-4960-87a5-993b5230ff5e)
becomes
![Screenshot_20231002_134037](https://github.com/pietervdvn/MapComplete/assets/1010226/4720a602-76df-4105-8a7e-e3d60a8feede)

But vending machine theme the logo doesn't change:
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/ea31a57b-a5b0-4ea0-9b42-060c4fb370b5)

**Comment by thibaultmol** [comment]
Surveillance Camera theme also doesn't

**Comment by thibaultmol** [comment]
There's a low pulsing glow around the icon now. Guess this can be considered fixed? Although it does mean that like in the images for the cyclofix theme.. there is a consistency problem between some of the POI icons. @pietervdvn is this something you do want to see fixed so it's more consistent? if not, you can close this

**Comment by pietervdvn** [comment]
I'm not gonna bother with this inconsistency
