### ISSUE TITLE
FR: New edit option for bus routes

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#1633]
The transit editor allows users to change the tags on a route in typical MapComplete fashion and has a link back to the feature on OpenStreetmap.org but doesn't allow any way to change the actual route. There is a new route editor specifically for bus routes called [Relatify] that does allow editing of bus routes in the browser with a fairly simple interface. This is limited to PTV2 routes without hail and ride sections (some other known limitations are listed in the [plan]). 

Would it be possible to include a link to the route on Relativity alongside the link to the relation on OSM? 

In the comments to the [diary][1] post announcing the tool the creator mentions that individual relations can be loaded using a URL along the lines of  `https://relatify.monicz.dev/?relation=123&load=1`.

[Relatify]: https://wiki.openstreetmap.org/wiki/Relatify
[plan]: https://github.com/Zaczero/osm-relatify
[1]: https://www.openstreetmap.org/user/NorthCrab/diary/401755#comment55018

**Comment by RobinLinde** [comment]
Implemented in #1643
