### ISSUE TITLE
Add fruit to vending machine layer

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1634]
Example: https://www.lembifruit.be/lembi-shop
I guess the icon could be an apple basically.

Technically, strawberries are also fruit... But I feel like those are usually separate. So maybe adding strawberries as it's own thing is also a valid thing to add?

(I know of multiple vending machines that only do strawberries. But this one is both strawberries and other fruits like apples)

**Comment by thibaultmol** [comment]
(also maybe adding website= to vending machines is a possibility? I'm noticing more of the having websites)

**Comment by RobinLinde** [comment]
Fixed in #1643
