### ISSUE TITLE
No 360° images in the street view imagery picker

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1638]
I just noticed that the streetview imagery picker never seems to show 360 imagery.
I assume because it's difficult to show a thumbnail for it? but it is a bit unfortunate because sometimes it's the only imagery available in an area.

**Comment by pietervdvn** [comment]
The 360° images are deliberately hidden, as they take a lot of screen real estate and often show way more then just the relevant object. To display them, they should either be squeezed or scrolled, resulting often in having the part _not_ showing the object in view.

As such, I'm not gonna be showing them.

**Comment by thibaultmol** [comment]
I know it's probably complex. But maybe you get enough info from Mapillary so that you could actually see "the object is in that direction, so we'll show the 360 image in that direction, as the thumbnail"

But nvm that idea, cause I don't think the coordinates of the imagery would be accurate enough, causing most of those directions to be wrong.

So yeah, fair enough
