### ISSUE TITLE
Camera direction symbol always north

### ISSUE THREAD

**Issue by cascafico** [pietervdvn/MapComplete#1639]
No matter which is OSM direction value, when editing it the symbol always points north.
![camdir](https://github.com/pietervdvn/MapComplete/assets/6792869/e8bb2a48-b14a-4672-a8ac-bd2d1b142a0f)

**Comment by thibaultmol** [comment]
Which url are you using to access Mapcomplete?
What browser are you using?

i'm unable to reproduce this.

**Comment by cascafico** [comment]
https://mapcomplete.org/surveillance?z=15.2&lat=45.95365&lon=13.46312#node/9891394639
Google Chrome Versione 87.0.4280.66 (Build ufficiale) (a 64 bit)

**Comment by thibaultmol** [comment]
That's quite an old version of Chrome. Something probably changed that makes it not work on old versions.

I tested it on
Google Chrome Version 117.0.5938.132 (Official Build) (64-bit) 
and I'm also not able to reproduce it. So it's probably just related to old versions of chromium.

**Comment by pietervdvn** [comment]
Sorry, but I'm not gonna be fixing small issues for browsers that are three years old. There are more important things to fix.
