### ISSUE TITLE
Double description on imgur uploads

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1646]
I think it might related to selecting multiple images at once for upload to an object.
(Chrome Android)

![Screenshot_20231008_185923_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/62102e97-0d8a-4488-a9ba-120e85153534)
![Screenshot_20231008_185903_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/97a62da5-3910-482d-9a60-6b51473fe1b3)

**Comment by thibaultmol** [comment]
Interestingly these images were also not actually added to the osm node... not sure what happened here.

Can't repro

**Comment by pietervdvn** [comment]
I'm closing this as not reproducable

**Comment by thibaultmol** [comment]
Uploaded multiple images last weekend and also didn't have multiple descriptions, so is probably fixed
