### ISSUE TITLE
Low performance causes white background

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1649]
Background went white after selecting several objects too quickly in a row while zooming/panning around on at least the Artwork and Defibrillators theme (likely any theme). Also high cpu(?) usage.
It looks like it threw some errors on GET.

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/2faaed6a-c28b-45e8-a1cd-e6690b7fc0f5)
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/d0ee82fd-8a9e-4b07-b5ed-552befa7f9e3)

Related: #1606

**Comment by thibaultmol** [comment]
that does explain why I mainly have it on my phone and rarely on my pc

**Comment by pietervdvn** [comment]
Is this still happening? I suspect that a previous update of MapLibre might have fixed this.

**Comment by thibaultmol** [comment]
Hmm, was having it last night. But going to clear data and cache to double check if it's still happening

**Comment by danieldegroot2** [comment]
https://mapcomplete.org/artwork.html?z=14.4&lat=52.650708556002314&lon=-7.253656784100485#node/9392570918
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/74bf6b65-5234-4a10-abc3-6caa543677cb)

After clicking on a few artworks, switching tabs a few times, clicking on a new artwork caused the background to go white. Not much more cpu usage though.
In any case there are now quite a few of these dialog messages in the web console
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/46ce90b9-9e2b-4001-8b31-ed3916722e75)
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/c46e8609-74ff-46a4-b3d2-223f9e8f7d24)
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/a2b77873-9385-45c2-95ff-1a15769120d6)

Fortunately it fixes itself when refreshing cache.

**Comment by thibaultmol** [comment]
I used GRB but it happens on any, including trees/lighting etc.

https://github.com/pietervdvn/MapComplete/assets/1010226/90f8441e-76da-47b2-9470-843b32dde68f

**Comment by pietervdvn** [comment]
I suspect this is an upstream issue, see https://github.com/maplibre/maplibre-gl-js/issues/4029

**Comment by pietervdvn** [comment]
I finally figured this one out! It turned out to be #2024 and should be fixed now (by destroying unused maps better and by recovering the main map in case of emergency)
