### ISSUE TITLE
Some background layers seem to be broken

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1652]
Currently it seems these background layers are broken (remain light-brown without any content).
Note, Stamen is pushing [some changes](https://stamen.com/stamen-x-stadia-the-end-of-the-road-for-stamens-legacy-map-tiles/).

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/7054f07b-0a52-4cdf-8074-ebfca37cf774)

**Comment by pietervdvn** [comment]
Americana was broken due to a too strict CSP policy

I have swapped the Stamen and Carto background layers for their Vector counterparts (if available, `Watercolor` is still a .jpg-layer).

The Occitan, Breton and Basque style are broken due to missing CORS-headers on their side.

**Comment by pietervdvn** [comment]
I've asked OSM-fr to fix this https://forum.openstreetmap.fr/t/technical-help-needed-cors-headers-are-not-set-for-osm-breton-occitane-and-basque-style/18160

**Comment by pietervdvn** [comment]
All layers work again or are swapped out

**Comment by thibaultmol** [comment]
> I've asked OSM-fr to fix this https://forum.openstreetmap.fr/t/technical-help-needed-cors-headers-are-not-set-for-osm-breton-occitane-and-basque-style/18160

Seems like not everything is/was fixed?
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://wms.openstreetmap.fr/tms/1.0.0/orthohr/16/33987/23444. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 502.`

**Comment by danieldegroot2** [comment]
Americana seems broken again.
