### ISSUE TITLE
Hide create point marker when no longer needed

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1655]
The create point marker eventually distracts users from the map and it seems there is no way to remove it (at least on live version).

Hide create point marker popup -appears when clicking on map- after some time, when pressing `ESC` Escape, and/or similar.

Also, it might be better to only animate it when hovering over it.

Furthermore, I'm unsure if right-clicking should activate this popup at all. Currently it just duplicates the left click action (right-click is usually used for some options menu either of the browser or the map). It may be better if it does nothing and there is an option to change the available hotkey(s) if needed.

**Comment by pietervdvn** [comment]
This marker will soon be removed in favor of a fixed button in the bottom left. See the develop branch.

> Furthermore, I'm unsure if right-clicking should activate this popup at all. 

Yes. Some themes show polygons (e.g. a nature reserve). If a contributor wants to add a bench in this nature reserve, they need right-click or long press to be able to add something.

**Comment by thibaultmol** [comment]
Oh, that explains the change in dev.... Hmmm ...
I understand why the change was needed, but not a big fan? Could it maybe also activate the 'create point marker popup' if you long press? (Regardless of if it's inside of a polygon or not)

**Comment by danieldegroot2** [comment]
> Some themes show polygons (e.g. a nature reserve). If a contributor wants to add a bench in this nature reserve, they need right-click or long press to be able to add something.

Is there some way for users to know they can do this?

**Comment by thibaultmol** [comment]
So is there a plan to bring long press and or right click to create an object coming to all themes then? (default behavior)

for mobile I somewhat get it, but on desktop having right click be able to create objects would be much better I think. 

(I understand the decision to change left click, though. To be clear. I have myself also accidentally pressed the map and then have that point marker on the map without I need it.

**Comment by pietervdvn** [comment]
This issue is now obsolete, as we switched to the 'add new button' on the bottom left.
