### ISSUE TITLE
Defibrillators theme is missing levels selector

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1656]
As Defibrillators are also common inside buildings, the indoor level selector should be available also here.
(like in the Artworks theme, among others)

**Comment by pietervdvn** [comment]
It is? 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/f88dbaea-b5a7-4cd9-bd4c-39c2ba972be3)


Note that the elevator (to filter based on a floor) is _only_ present if there are AEDs on multiple levels.

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/737ab0ee-9248-412c-b12f-84d40c30028f)

**Comment by danieldegroot2** [comment]
Ah, okay. Thanks for the clarification.
