### ISSUE TITLE
Add maxstay to Parking theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1657]
I know it's already a tag in Charging Stations theme, but it would also be useful in the Parking theme. (I assume it's just a copy and paste thing, but I don't know exactly which parts to copy and paste, so hence I just made this issue)

**Comment by thibaultmol** [comment]
@pietervdvn do you prefer that I copy and paste it or add it to questions.json?

**Comment by pietervdvn** [comment]
If there is a generic phrasing that works for both, use 'questions.json'

**Comment by RobinLinde** [comment]
Fixed in #2300
