### ISSUE TITLE
Missing space between amount and unit

### ISSUE THREAD

**Issue by riQQ** [pietervdvn/MapComplete#1658]
This happens e.g. in the maxspeed theme.
![Screenshot of max-speed layer showing max-speed of element](https://github.com/pietervdvn/MapComplete/assets/3404787/85e73f72-7b78-48ad-a800-adf3533d8a75)

**Comment by pietervdvn** [comment]
Fixed in 94e07d5b13f86837d02cb6d0906a501a1bdd35fc

**Comment by riQQ** [comment]
Duplicate of #1538
