### ISSUE TITLE
openStreetmap image layer not available anymore?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1664]
Send the neversion of the stable launched: it seems like the regular open street map carto image layer is no longer available.
(I still use it over maptiler sometimes because it shows more things)

**Comment by thibaultmol** [comment]
@pietervdvn I'm not seeing it in dev?
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/8849c45c-7e57-41f4-9b20-b535a4e0c26d)

**Comment by pietervdvn** [comment]
I've exceptionally added this into master directly. Dev is now synced with it, so it should show up.
