### ISSUE TITLE
Notes theme doesn't have precise location picker

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1665]
Now that you can no longer click on the map, it is actually not possible to precisely put the note on the right location unless you know that it's in the center of the screen and still that's kind of hard to determine

**Comment by pietervdvn** [comment]
I've added a 'precise location input' to the note layout.

I've also created the option (on dev) to enable a cursor in the center of the map. You have to enable this in the settings _and_ be zoomed in to z>=17; this should help to pick a correct location right away.

**Comment by thibaultmol** [comment]
@pietervdvn  is the current build borked somehow?
Do you wise constantly getting stuck in things aren't loading buttons are also a unresponsive.
(I'm on dev, have deleted all the data and refreshed multiple times)

Always displaying a cursor for pro users like me would indeed be a great solution

**Comment by thibaultmol** [comment]
Can confirm the cursor works and is very handy!
