### ISSUE TITLE
Not enough contrast on some icons

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1666]
A lot of the icons that are used in the cyclofix theme don't actually seem to have enough contrast it is going to be able to tell what they are
![Screenshot_20231015_094333_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/38c2d8ca-2461-44ac-911d-8687f993d046)

**Comment by pietervdvn** [comment]
Fixed in some studio commit
