### ISSUE TITLE
Pattern overlayed on imagery makes it impossible to look at

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1667]
![Screenshot_20231015_095759_Chrome](https://github.com/pietervdvn/MapComplete/assets/1010226/ff7f0c9b-d451-4fc0-baa0-75cc9c2460b9)
Maybe it's best to disable that for aerial imagery because it's impossible to see what's there

**Comment by pietervdvn** [comment]
This has been resolved by reordering the layers a bit in MapTiler cloud.
