### ISSUE TITLE
Dev is currently broken on some themes

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1669]
https://dev.mapcomplete.org/hailhydrant.html?z=20&lat=51.23155251860942&lon=4.4208669379252115#background
is just stuck on 'loading data'. 
Firefox stable linux (mobile chrome also acting up)
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/44cd318f-ef97-4b26-8c20-c99916264dd6)

![Screenshot_20231015_212954](https://github.com/pietervdvn/MapComplete/assets/1010226/358770c7-8e2a-4f0f-8408-65c679e5cb2c)
(it's just stuck on 'loading data').
i've already cleared data many times.

Tested it in an inprivate window, so it's def not an addon that's causing it.
It only happens after i've logged in, and then I see that exception in the logs

**Comment by pietervdvn** [comment]
I forgot to add this new image (cross.svg) into the repository, hence the entire app crashes when it loads it.

As such, if you zoomed to zoom level 17 or above while it is loading, it will display "loading" forever.

**Comment by riQQ** [comment]
Fixed with f2b8c0db0f80bf503f2b4332d66cbede0736f82a
