### ISSUE TITLE
View full res (zoomable) of each image on an object from within MapComplete

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1672]
I know you can right click or hold down(mobile) on an image to then open it in a browser or download it. But I think it might be beneficial if you could just fullscreen/zoom/something within mapcomplete seeing as the full image is being loaded anyways.

**Comment by pietervdvn** [comment]
This has been implemented a little while ago, simply click the image for a popup where you can zoom in and download.
