### ISSUE TITLE
Dragging opening hours over multiple days doesn't work

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1674]
If you were to click and drag from A to B, it should give me 16:00 till 02:00 next day. But it can't do that atm
![annotely_image(8)](https://github.com/pietervdvn/MapComplete/assets/1010226/e58e5255-2620-4b55-a140-51e8f4fcbd50)

Firefox 118.0.2 on linux

**Comment by pietervdvn** [comment]
The way to add opening hours like this is to create a block for the evening and to create a block for the next day, early in the night.

Implementing different behaviour is really tricky and will hamper usability.
