### ISSUE TITLE
Fix visualizing of opening hours that cover multiple days

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1675]
If you enter these opening hours using the visual editor, it works. But if you just give it this string, it will render it incorrectly:
`Tu-Th 16:00-00:00; Fr 16:00-02:00; Sa 14:00-02:00`
![Screenshot_20231017_100200](https://github.com/pietervdvn/MapComplete/assets/1010226/38379ef1-9167-471b-a2ed-adecb618dafe)
![Screenshot_20231017_100217](https://github.com/pietervdvn/MapComplete/assets/1010226/08bec54f-4ceb-454a-81f2-5c2ac85ed6f8)

One of these images was after I entered it through the visual editor, the other is when I just paste the string in the text field and have it render the opening hours

Related: https://github.com/pietervdvn/MapComplete/issues/1674

Firefox 118.0.2 on linux

**Comment by pietervdvn** [comment]
The way to add opening hours like this is to create a block for the evening and to create a block for the next day, early in the night.

Implementing different behaviour is really tricky and will hamper usability.
