### ISSUE TITLE
New cursor doesn't match precise location picker (on mobile)

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1677]
I think in the code there might be a mismatch between the viewport resolution and screen resolution.
So (only on mobile) if you put the cursor at a clearly defined location and then try to create a new object, you'll see the location picker is slightly lower (because it's using the viewport resolution, which has a lower height. So doing that /2 will give a lower value.)

**Comment by thibaultmol** [comment]
Hmmm. Cleared local data but still happening?


https://github.com/pietervdvn/MapComplete/assets/1010226/4acefc36-1c3c-4d84-95d3-1538249368cb

**Comment by pietervdvn** [comment]
Oh, _that_ bug again...

This is separate from the 'cursor is not in the middle', which was a CSS issue in combination with URL bars that hide.

This is a straight-up bug with the map moving to where it shouldn't.

**Comment by pietervdvn** [comment]
I haven't seen this behaviour in a while, so I guess this is fixed? If not, reopen the issue.

**Comment by thibaultmol** [comment]
Can confirm, don't think I've experienced this in a good month or more now
