### ISSUE TITLE
Object IDs in path names.

### ISSUE THREAD

**Issue by chrneumann** [pietervdvn/MapComplete#168]
For SEO-reasons I'm currently experimenting with ids in the path name instead of the URL fragment, e.g.
http://localhost:1234/@way_51869455/?layout=nature&test=true&lat=50.23271&lon=8.622035&background=osm

The idea is to support urls with pre defined object aliases like
http://localhost:1234/alias-for-object/?layout=nature&test=true&lat=50.23271&lon=8.622035&background=osm

or even 
http://localhost:1234/alias-for-object/
where some default / pre defined zoom, lat, and lon are applied.

These URLs can be used in a site map or other links and could show up in search engine results (still there is more work needed).

Kinda experimental, wanted to share the idea though. I will start to use it for frankfurt-vegan.de
https://github.com/chrneumann/MapComplete/tree/feature/id-in-pathname

(The big downside is that this doesn't work with all the static htmls / needs some webserver support).

**Comment by pietervdvn** [comment]
Hey Christophe!

Please cease all your experimenting and pull in the latest master branch. It is already implemented there

**Comment by pietervdvn** [comment]
Example:

https://pietervdvn.github.io/MapComplete/cyclofix.html?lat=50.84817&lon=4.351701#node_3023196290

**Comment by pietervdvn** [comment]
There even is a fancy 'Share'-icon on browsers which support the share API:

![signal-2020-12-01-113208](https://user-images.githubusercontent.com/1466478/100729413-062d3080-33c9-11eb-87a9-4a584eed3ee4.png)
![signal-2020-12-01-113245](https://user-images.githubusercontent.com/1466478/100729417-075e5d80-33c9-11eb-887b-578943e24b22.png)

**Comment by chrneumann** [comment]
> Example:
> https://pietervdvn.github.io/MapComplete/cyclofix.html?lat=50.84817&lon=4.351701#node_3023196290

Not sure what you refer to. The node's id is in the fragment, not in the path?

**Comment by chrneumann** [comment]
btw, it's Christian ;)

**Comment by pietervdvn** [comment]
Ah, I missed the 'for SEO reasons'.  I thought you only wanted to share URLs. Must have be to early in the morning. ;)

First of all, I'm not very fond of 'needing webserver support' as I don't like running computers - it complicates things, they go down easily. Keeping the tool completely static on my side is how I'd prefer it. That said, this pretty much is my only objection to adding it in the path; and if there is code in the repo to support this use case, that is totally fine - as long as the 100% static version works .

That too is the reason I put the id in the fragment, as it works elegantly for the static use case.

Would Search Engine Optimization also work with having the ID as query parameter? Just out of curiousity...

I'm gonna have a look at your code a bit more detailed - I already skimmed it and it looked good at first sight. 

> btw, it's Christian ;)

Oops, again, to early today - and I shouldn't do to much at the same time ;)

**Comment by chrneumann** [comment]
Google for examples seems to ignore the fragment, and it seems to be considered bad practice to use it like this. But yeah of course, hard to do it with static only htmls (or at least I don't know how). Maybe one could have this configurable. But I will first experiment with the implementation, see if it at all accomplishes what I intended :)

**Comment by pietervdvn** [comment]
Cool!

Ignoring the fragment would be kinda logical, as fragments are mostly used to indicate e.g. where on the page someone is - typically it links to a (sub)title.

The current implementation stems from a kind of hack. Originally, the fragment was used to trigger a new URL in the browser history. Clicking the 'back'-button would then remove the fragment again, which the code listens to to remove the popup again - behaviour much needed to make the back button on android work.

At a certain moment, I realized I could put in the ID there to share a location by URL.

> But I will first experiment with the implementation, see if it at all accomplishes what I intended :)

When you are done, please open a PR, I'll gladly merge. Same for the kletterspots- and vegan-themes too BTW, let me know when they are good enough. We should then put it onto the WeeklyOSM, the ghost-bikes were sent in (not by me!) and featured two weeks ago, [that caused quite an uptick](https://osmcha.org/?filters=%7B%22comment%22%3A%5B%7B%22label%22%3A%22%23ghostbikes%22%2C%22value%22%3A%22%23ghostbikes%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%222020-07-05%22%2C%22value%22%3A%222020-07-05%22%7D%5D%2C%22editor%22%3A%5B%7B%22label%22%3A%22MapComplete%22%2C%22value%22%3A%22MapComplete%22%7D%5D%7D) in contributions, around 10 new ghost bikes added and a few new images.

**Comment by pietervdvn** [comment]
Closing this issue because it would need a server running - which is out of scope for this project. It would be cool to see it in a fork one day.

**Comment by chrneumann** [comment]
It's already experimentally running, e.g. https://frankfurt-vegan.de/kuli-alma/?lat=50.14951&background=osm# (Currently only works for the all vegan restaurants in Frankfurt).

Problem is, that it's not that useful yet (for SEO), as the markup is not that semantic and (maybe because of this), e.g. Google thinks that the sites (with different URLs) are duplicates. Didn't have the time to work on that yet.

But yes, this needs a rewrite rule on the server ;)
