### ISSUE TITLE
Image upload broken

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1685]
Currently on stable it seems like if you try to upload an image, it shows a succesful message in the UI but you don't get to see the image. 
Console reports:
![Screenshot_20231022_201421](https://github.com/pietervdvn/MapComplete/assets/1010226/43920a31-d8df-40ad-9c43-347dff759d6a)

unterwegs on Matrix is also experiencing this problem.

No changes on osm when you upload an image.

**DEV works fine though, it's something on stable that is making it not work**

**Comment by pietervdvn** [comment]
Good catch!

I made [some fixes to the etymology theme](480956d45dc767c77848ba32b176af373e73060a) which changed how the arguments of the 'image upload button' where handled, introducing a regression.
