### ISSUE TITLE
Bicycle infrastructure theme should not ask for cycleway or maxspeed on pedestrian roads

### ISSUE THREAD

**Issue by bxl-forever** [pietervdvn/MapComplete#1686]
Theme: https://mapcomplete.org/cycle_infra.html
OSM object to reproduce issue: https://www.openstreetmap.org/way/8174673

This street has "highway=pedestrian".

The theme asks whether the road has a cycleway.  It also asks about the maxspeed if this tag is missing.
![scrot_202310241115 18](https://github.com/pietervdvn/MapComplete/assets/23359667/5f7ca9bd-ada8-4d99-a069-8d8e1c59d2ae)

Expected behaviour: do not ask for cycleways and do not ask for maxspeed in such roads because those tags are not relevant with "highway=pedestrian".

**Comment by pietervdvn** [comment]
Fixed in e580f553197165d611258b8c68ed9f9a66ca42c4
