### ISSUE TITLE
Have 'wikimedia_commons' tag be used for image filtering in Artwork theme

### ISSUE THREAD

**Issue by fredao** [pietervdvn/MapComplete#1690]
it looks like the filter "has at least one image" doesn't work

**Comment by pietervdvn** [comment]
Hi,

I tested the filter and it seems to work as expected. Can you share the location, what you tried and what you expected to happen?

**Comment by thibaultmol** [comment]
I think I get what's going on:.
https://mapcomplete.org/artwork.html?z=17.2&lat=51.04129306911952&lon=3.399319529283048#node/9960209841
`wikimedia_commons` isn't being counted as 'an image' I think. Hence why a node like this will disappear if you change the setting even though it does have an image

**Comment by pietervdvn** [comment]
Which is why the text reads: _probably_ does not have a picture.

**Comment by thibaultmol** [comment]
Ok, that does explain that. I'll just modify this issue to atleast cover Wikimedia Commons which is a pretty common image style tag to be used on artwork things.

**Comment by fredao** [comment]
I checked it here: https://mapcomplete.org/artwork.html?z=14.8&lat=38.798200027890346&lon=-9.179276010901503&filter-artwork-has_image=1

whatever has happened since I opened the issue ... it works now ;-)
cheers - in OSM derFred ;-)
