### ISSUE TITLE
Wrong question showing for possible answers in sidebar

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#1706]
https://mapcomplete.org/cafes_and_pubs.html?z=14.7&lat=52.37087414883459&lon=4.842468436723948#node/5801833182

It is asking me for the opening hours but then showing the email input field. If I hit skip it still shows the same question but options for a different question.

<img width="942" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/921217/32c25491-3ae4-4e2a-9a41-00d104db4384">

<img width="489" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/921217/f3f9eb01-6266-46c1-95d9-3dd8251adcd0">

**Comment by pietervdvn** [comment]
I noticed as well, this is fixed in 7de0af15f100815288fea4fdb13f3e845bc79088
