### ISSUE TITLE
Allow to split/cut streets at a certain point

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#171]
This would be a similar feature as 'cutting a street' in mapcomplete.

There are few dependencies for this though:

- [x] Being able to show which street is selected with a different color (we should also be able to see this on mobile, where there is a popup over the full screen) (See #174)
- [x] Being able to 'project' a point onto the road and/or pick a point if it is close enough to an already existing point (also useful for a theme such as adding bollards)
- [x] Being able to modify the way geometry on OSM
- [x] Keep track of relations, so we don't break those

**Comment by tordans** [comment]
In https://zlant.github.io/parking-lanes/#17/52.47906/13.42876, the user can split streets but only on existing intersections. This might make it a bit easier to build and thus be a good first step for this feature.

(Hint: to see this edit feature one needs to click the well hidden edit checkbox in the bottom right corner)
