### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by pkp24** [pietervdvn/MapComplete#1715]
I'm unsure why I can;t log in. osm says the site is authorized, each time I click log in it brings up the page requesting authorization. I've tried it in edge and firefox.

**Comment by thibaultmol** [comment]
There was a problem in the code recently but that's fixed, maybe you're still on an old version or something, I had the same problem.

Try clearing the data and cache for mapcomplete and refresh the page.

**Comment by pkp24** [comment]
I tried this just before making the issue, was it fixed within that time
frame? I tried about 10 minutes prior

**Comment by thibaultmol** [comment]
It was 24-48 hours ago. I tried it 5 minutes ago and I'm not having this issue. So I'm not sure what's going on. 

Are you by any chance of working with the installed version of map complete? (On smartphones. If you install it as a PWA webapp)

**Comment by pkp24** [comment]
No, I'm using the website. It was my first time trying it after someone
shared a link a while ago.

**Comment by pietervdvn** [comment]
Hi,

I cannot reproduce this; please provide more details.

**Comment by pietervdvn** [comment]
Not enough information to reproduce
