### ISSUE TITLE
Favicon getting blocked by JS?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1721]
![Screenshot_20231129_111155](https://github.com/pietervdvn/MapComplete/assets/1010226/f28bdaf1-a1e4-4604-8224-889cf9190f58)
Firefox desktop, stable version of mapcomplete

**Comment by pietervdvn** [comment]
There _is_ no favicon.ico. However, the favicon is set in a different way.

`BINDING_ABORTED` means that the request in cancelled. The browser starts to ask a favicon.ico, realizes in the mean time that another icon is available and cancels the request.
