### ISSUE TITLE
Answers overflow above question header

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1723]
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/21a237ce-5951-4b70-84f5-fd17e28a1e32)

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/d0be9f2a-4232-45ae-aa82-8ac3ca69aa81)

When scrolling down, answers are visible above the question header. This overflow should be hidden.

Browser: Chrome, Edge

**Comment by thibaultmol** [comment]
Can reproduce in Firefox, but only if I enable the mobile layout in dev tools and set the height of the 'phone' to 400px.

Not sure what screen resolution you're using that's so small it triggers the scrollbar though

**Comment by danieldegroot2** [comment]
Looks like it is an issue with the high dpp screen, as usual.
