### ISSUE TITLE
Remake the custom theme generator

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#173]
The current custom Theme generator is buggy, ugly and not user friendly.

It should be redone once again

**Comment by pelderson** [comment]
The idea is not bad, though. For the user it's just not clear enough, it's a bit too ... uhm, code oriented, and it assumes too much prior knowledge. Yes, there are bugs, and I can't really tell how serious they are and how many more there are, but much can be improved with textual changes.  
Headings like "Mappings" doesn't really indicate what it does for the user, should be something like "Conditional <item>" , e.g. Conditional title.   
I could help from the user end? I have some smart people here who I can ask if they understand what they see. I've done that for Marc's Knooppuntnet Planner too.

**Comment by pietervdvn** [comment]
Also see #258 for inspiration

**Comment by pietervdvn** [comment]
Superseded by #1184
