### ISSUE TITLE
MapComplete Studio resets minzoom when editing layer

### ISSUE THREAD

**Issue by lliehu** [pietervdvn/MapComplete#1740]
While editing a layer with MapComplete Studio, I have experienced multiple times that its minimum zoom level was somehow automatically reset to 0.

I'm sorry that I don't have exact steps to reproduce because I haven't been able to pinpoint the condition. It might be related to editing the section "Which tags must be present on the feature to show it in this layer?" in "Data source" or it might not. I can try to investigate further if necessary.

**Comment by pietervdvn** [comment]
The issue was simple to reproduce: loading a layer would already trigger the bug.
