### ISSUE TITLE
Studio UI doesn't preselect currently configured option when editing shownByDefault

### ISSUE THREAD

**Issue by riQQ** [pietervdvn/MapComplete#1750]
1. Create a new theme in Studio and fill required fields with dummy values
2. Go to Tab *Advanced functionality* > Should this layer be enabled when opening the map for the first time? 
3. Select `the layer is hidden until the contributor enables it. (If the filter-popup is disabled, this might never get enabled nor loaded)`.
4. Press save
5. Switch to tab *Configuration file*. The configuration file contains `"shownByDefault": false`
6. switch back to the tab *Advanced functionality* and see that the question `Should this layer be enabled when opening the map for the first time?` is in edit mode and has no value selected
7. After pressing cancel for this question, the status `the layer is hidden until the contributor enables it. (If the filter-popup is disabled, this might never get enabled nor loaded)` is shown correctly

**After step 4**
![after saving shownByDefault](https://github.com/pietervdvn/MapComplete/assets/3404787/4713917b-6036-43c3-ab9e-f5249be52aa4)

**After step 5**
![configuration file](https://github.com/pietervdvn/MapComplete/assets/3404787/88d55135-7c9e-4b86-987c-5fd52561b3d4)

**After step 6**
![after switching back to advanced functionality](https://github.com/pietervdvn/MapComplete/assets/3404787/61e2bcff-1d09-436b-9303-2aa7b34ba6e4)

**Comment by pietervdvn** [comment]
Can reproduce. This is the UI which mistakes 'false' for 'undefined'
