### ISSUE TITLE
Multiple values for "changing_table:location" obfuscated for inexperienced mappers

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#1756]
The current version of the [toilets] view allows edits to specify a `changing_table:location` if the user has first confirmed that the toilet has one. This currently shows as a list of options with radio buttons. According to the [wiki page][1] for `changing_table=*`, multiple values can be semicolon separated for this key so facilities with multiple tables have to be input manually in the freeform "This changing table is located at: [user input]" option, which is not very user friendly and requires advanced OSM knowledge. (Can "new" mappers even see the `key=value` pair under the natural language 'rendering'?)

I think this should be changed to checkboxes so multiple options can be selected simultaneously as for the "What can be recycled here?" question on the [waste] view. I think it is very common for toilets that have an changing table in the `male_toilet` to also have one in the `female_toilet` (although not necessarily the reverse) so a multivalue list is the expected input much of the time. 

As an aside, I'm not thrilled with this tagging scheme as I think most mappers will only have access to a subset of the available toilets so it would be quite difficult for e.g. a typical male mapper to categorically declare that there is no changing facility in the female toilet, but it's the best we have. 

Prompted by [this thread][2] over on Mastodon.

[toilets]: https://mapcomplete.org/toilets
[1]: https://wiki.openstreetmap.org/wiki/Key:changing_table
[waste]: https://mapcomplete.org/waste.html
[2]: https://en.osm.town/deck/@thibaultmol/111764958447346290

**Comment by pietervdvn** [comment]
This has been enabled; I also rephrased the translations slightly to make more sense in the case that there are multiple changing tables. (Translations are not yet deployed)
