### ISSUE TITLE
fediverse handle containing dash not accepted on Hackerspaces map

### ISSUE THREAD

**Issue by lebeno** [pietervdvn/MapComplete#1762]
Answering `@MakerspaceBaasrode@mastodon-belgium.be` to the question _What is the Mastodon-handle of Makerspace-Baasrode?_ for node 9973410963 on the _Hackerspaces_ map gives this error: `A fediverse handle consists of @username@server.tld or is a link to a profile`

There seems to be some kind of input validation on the answer. When typing, the error is displayed the moment you type the `-` character in the handle. So probably this character has to be added as a valid character.

**Comment by pietervdvn** [comment]
Indeed, thanks for reporting!

If you set a mastodon handle in your profile description on OpenStreetMap.org, MapComplete will detect this handle.

I have added a button to see the linked fediverse account _directly_ on your home server, if set: 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/8652f170-9518-4f78-a51d-c5c77697f159)
