### ISSUE TITLE
Adding a shop doesn't ask for type anymore

### ISSUE THREAD

**Issue by barthanssens** [pietervdvn/MapComplete#1769]
Adding a new shop via mapcomplete.org v0.37.1 (using Chrome 120 on Windows 10) does not show the question with the selection list anymore to select the type of the shop. 

Only after skipping questions (like opening hours) and clicking on "reactivate skipped questions", the question is asked what type of shop it is

(not sure, but this _may_  trigger some OSM warning on freeform text being used instead when saving empty shop type)

**Comment by joostschouppe** [comment]
Example changeset that may be affected by this issue: https://overpass-api.de/achavi/?changeset=146528345
Some of the shops have the fixme with no good reason

**Comment by pietervdvn** [comment]
Seems to be fixed
