### ISSUE TITLE
Uploading a picture on desktop chromium opens the popup dialog twice

### ISSUE THREAD

**Issue by filipca** [pietervdvn/MapComplete#1771]
This is a minor problem.
I download the mapillary image and save it.
When I add the picture to serve as an imgur, I have to open the file twice.

**Comment by filipca** [comment]
Chrome, I have not tested on other browers.

**Comment by thibaultmol** [comment]
(also, Mapcomplete already has a 'see nearby images' feature, to link mapillary images to objects)

**Comment by filipca** [comment]
I cannot go under 10 MB.
So I give a link to youtube.  The problem is shown from second 33.
https://youtu.be/-GmQYFxu2eI

**Comment by filipca** [comment]
The reason why I do this =
"
Tien jaar mapillary.
Het is een wonder dat het nog bestaat.
We weten allemaal hoe wispelturig de informaticareuzen kunnen zijn.
Het wordt dus tijd voor een backup naar Imgur bijvoorbeeld.

Niet alleen als een backup, maar Imgur lijkt mij sneller dan Mapillary. En Mapillary ligt er soms ook eens uit. Het lijkt erop dat OSM wel eens belangrijk zou kunnen worden voor AEDs. Gisteren is er eentje gewist. Ik weet niet welk. 
Mijn werkwijze is als volgt =
Een overpass query die nu 1720 nodes teruggeeft van AEDs met mapillary maar zonder image.
Ik kies een AED en klik op de mapillary tag.
Ik neem een download van de beste mapillary foto.
Ik save lokaal, zonder de lange systeemnaam van het bestand te veranderen.
Ik laad de foto op met Mapcomplete.
Als iemand een kortere werkwijze weet, laat het weten. Met een keyboard accelerator ?
"

**Comment by pietervdvn** [comment]
It is not the goal of MapComplete to be an easy way to create a backup of Mapillary. As such, no specific features will be implemented to make this flow easier.

Note that IMGUR as image host is on shaky ground as well. Last year, they announced that they "would remove pictures that haven't been seen for a long time", so they _can_ remove all pictures when they feel like it. If we were to dump all mapillary-pictures on it, they'd might forbid this as well.

Note that I share your concerns about Mapillary suddenly ceasing to exist. However, the preferred approach to this would be to setup Geovisio/Panormax-servers and to create a tool which allows to copy all contributions of a person into this geovisio-server. If appropriate metadata is saved at the geovisio-side (esp. the original ID), then converting all the links is technically possible.

However, all these ideas are _far_ out of scope for MapComplete.

**Comment by thibaultmol** [comment]
> And your Mapcomplete becomes also more interesting with pictures on it.

(Mapillary images should also be displayed on Mapcomplete btw)

**Comment by filipca** [comment]
Maybe with
iif, isnumeric, string functions, regex

**Comment by thibaultmol** [comment]
?

**Comment by filipca** [comment]
I still have the problem with drinking water.
I do not have the problem with AEDs.

**Comment by pietervdvn** [comment]
Chrome only, dialog is triggered twice? Inspect FileSelector.svelte

**Comment by pietervdvn** [comment]
Indeed a browser specific bug. The 'click'-event of the label triggers (by code) the click-event of the input element. Firefox only opens a dialog once, but this bubbles up in chrome and lets it open the dialog twice. A `preventDefault` fixed this
