### ISSUE TITLE
Some icons aren't loading in Onwheels theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1772]
i'm guessing they weren't added for CORS maybe?
Entrance, indoor door and elevator

(car parking for some reason is smaller than normal. not sure why)
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/bbcb2ae1-542c-4047-9d9d-4c1d62920a73)

**Comment by pietervdvn** [comment]
Fixed in ef3eb4fcd0b0e3b0ebc005dee16eb899b73af2f7 (which mentions a wrong issue number)
