### ISSUE TITLE
Check mangrove private key export

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#1775]
See https://mas.to/@mangroveReviews/111878427559842532

**Comment by thibaultmol** [comment]
Also in general it actually didn't seem to work for me to push a review through Mapcomplete

**Comment by pietervdvn** [comment]
> Also in general it actually didn't seem to work for me to push a review through Mapcomplete

Are you saying that you _cannot make_ reviews using MapComplete?

**Comment by thibaultmol** [comment]
correct, I was trying to but it got stuck. 
Checking now, it does seem like my review got published... wonder why the ui got stuck then (don't have a screenshot, sorry)

Trying again now, I'm adding a review to the Meiniger hotel in Brussel midi:
https://mapcomplete.org/hotels.html?z=15.6&lat=50.83663280839215&lon=4.337097366660032#node/2669933071
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/c5fb7f7d-d111-4de2-b116-584ce4a59736)

Not sure if related:
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/d064e8e4-5fb3-404f-a63a-e0b72e0999be)

**Comment by pietervdvn** [comment]
I did export my private key: `{"crv":"P-256","d":" ... redacted ... ","ext":true,"key_ops":["sign"],"kty":"EC","x":"... redacted ...","y":"... redacted ... ","metadata":"Mangrove private key"}`

According to the mastodon post, this should be correct?

**Comment by pietervdvn** [comment]
> correct, I was trying to but it got stuck. ~Checking now, it does seem like my review got published... wonder why the ui got stuck then (don't have a screenshot, sorry)~ (sorry, was different location that got published. The review I was trying to publish here, hadn't worked)
> 
> Trying again now, I'm adding a review to the Meiniger hotel in Brussel midi and indeed gets stuck on 'saving...' https://mapcomplete.org/hotels.html?z=15.6&lat=50.83663280839215&lon=4.337097366660032#node/2669933071 ![image](https://private-user-images.githubusercontent.com/1010226/304110262-c5fb7f7d-d111-4de2-b116-584ce4a59736.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDY1MjUsIm5iZiI6MTcwNzc0NjIyNSwicGF0aCI6Ii8xMDEwMjI2LzMwNDExMDI2Mi1jNWZiN2Y3ZC1kMTExLTRkZTItYjExNi01ODRjZTRhNTk3MzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTM1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGUyNDU4YjJjMWVhYTUxNDNmOWZhOTJhZTlkZDc3MWY3YTI3ZWZlYjE3YWE5MTg2NWMyMjU1ZDE2YWM3ZmRjNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wHJZd0XS-ImHEB_JR1UZefqQuJ7SOCqiseOFKFDP8rY)
> 
> Not sure if related: ![image](https://private-user-images.githubusercontent.com/1010226/304110472-d064e8e4-5fb3-404f-a63a-e0b72e0999be.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDY1MjUsIm5iZiI6MTcwNzc0NjIyNSwicGF0aCI6Ii8xMDEwMjI2LzMwNDExMDQ3Mi1kMDY0ZThlNC01ZmIzLTQwNGYtYTYzYS1lMGI3MmUwOTk5YmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTJUMTM1NzA1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWVmYjk0ZGYwMWNlYTFiYWY4NTYwYzMzOGVjYWVjMzU5MzBkNGJlYjk1ZmIwZmI0MjU3ZGQzZmQ4ZGRmMjUyZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.VWI9R5uza-_v84GsW6aue0FIHuX2gBWPWQWTpmNqTpY)

Your screenshot states: "Opinion too long". Did you perhaps post a lengthy review?

**Comment by thibaultmol** [comment]
I did yeah... didn't know what the char limit is (not visualized in mapcomplete it seems)

**Comment by thibaultmol** [comment]
> I did export my private key: `{"crv":"P-256","d":" ... redacted ... ","ext":true,"key_ops":["sign"],"kty":"EC","x":"... redacted ...","y":"... redacted ... ","metadata":"Mangrove private key"}`
> 
> According to the mastodon post, this should be correct?

now try importing/using that on the mangrove website

**Comment by pietervdvn** [comment]
> now try importing/using that on the mangrove website

It seemed to work for me

> I did yeah... didn't know what the char limit is (not visualized in mapcomplete it seems) 

Me neither, I didn't even know there _is_ a char limit.

**Comment by thibaultmol** [comment]
Am I just using mangrove wrong? 
I took the .json private key I downloaded from mapcomplete. Then copy pasted the contents into either the login field or the  "Switch private key" field on the website. But that doesn't seem to do anything? console log says
```
Saving reviews for:  -----BEGIN PUBLIC KEY----- [keyhere] -----END PUBLIC KEY----- [9dc2f3f.js:1:85570](https://mangrove.reviews/_nuxt/9dc2f3f.js)
Fetched reviews:  undefined
```

**Comment by pietervdvn** [comment]
The char limit is 1000 characters apparently: https://gitlab.com/open-reviews/mangrove/-/blob/master/servers/reviewer/src/review.rs?ref_type=heads#L269

**Comment by pietervdvn** [comment]
I have implemented a opinion length check in fa9aca0685de5ea1ec16216836eac203d3188d96, so that is already fixed.

**Comment by keorn** [comment]
> I did export my private key: `{"crv":"P-256","d":" ... redacted ... ","ext":true,"key_ops":["sign"],"kty":"EC","x":"... redacted ...","y":"... redacted ... ","metadata":"Mangrove private key"}`
> 
> According to the mastodon post, this should be correct?

Yes, that looks correct. When I tried it in Chromium I did not see the spaces and got an error when importing. I will try again later and see what might be the cause of that.

@thibaultmol says that he does not see the submitted review in Mangrove, but maybe the issue was just that the review was not submitted due to the size limit mentioned above?

**Comment by pietervdvn** [comment]
> Yes, that looks correct. When I tried it in Chromium I did not see the spaces and got an error when importing.

Then, this might be a browser specific bug

**Comment by pietervdvn** [comment]
> Yes, that looks correct. When I tried it in Chromium I did not see the spaces and got an error when importing. I will try again later and see what might be the cause of that.

@keorn The export works correctly on Firefox, but chromium eats the spaces. I've escaped them now, and the export is correct now.

**Comment by pietervdvn** [comment]
> I don't think the user warning about max char limit reviews works yet? (I have cleared cache and the usual and I'm on dev.)

Correct. The deploy failed: https://github.com/MapComplete/mapcomplete-dev/actions/runs/7873801692

> If you click on my username in the review section, that works. but if you click on the actual review text, you get to a page with 0 reviews

Both links work for me, on FF and chromium.

**Comment by pietervdvn** [comment]
> ok, seems like the review I had made last month somewhere was not made using the same key. that's why I didn't show up on my account and why my account was empty. 

@thibaultmol See #1782

**Comment by thibaultmol** [comment]
> Both links work for me, on FF and chromium.

I swear It wasn't working last night.. i swear.. XD
It works now yeah, all good
