### ISSUE TITLE
OSM wiki images in notes don't render

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1776]
I'm assuming it's because the .jpeg link isn't actually a .jpeg, it's just the wiki image info page and not the raw image.
I guess you could hardcode something in MC to get the full image link if an image info page link gets posted... ?

**Comment by pietervdvn** [comment]
Can you please link an example.

**Comment by thibaultmol** [comment]
Oh whoops. Could have sworn I added the link

https://mapcomplete.org/notes.html?z=19&lat=28.71294619677424&lon=77.13803216063639#4099484

**Comment by pietervdvn** [comment]
I'm not gonna bother to write a ton of code to extract the correct image, so it now won't attempt to load the image anymore.
