### ISSUE TITLE
Entrances: switches from meter to centimeter

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1778]
If you're using the entrances layer in Onwheels for example. And the node already had a width set in meters.
If you then click edit, it will show the correct number but the wrong unit. The dropdown menu will show centimer by default instead of the correct unit
![Screenshot 2024-02-07 at 15-21-37 OnWheels](https://github.com/pietervdvn/MapComplete/assets/1010226/12957a37-7f1a-49a2-a528-08854ff1a715)
![Screenshot 2024-02-07 at 15-21-41 OnWheels](https://github.com/pietervdvn/MapComplete/assets/1010226/4956992c-83f3-4e3e-aa97-34686b2eff33)

example: https://mapcomplete.org/onwheels.html?z=20.7&lat=51.03709719270714&lon=3.7119458113110113#node/11577197608

**Comment by pietervdvn** [comment]
In this case, the value in OSM is effectively `37 cm` which would be incorrectly displayed as `37 meter`
