### ISSUE TITLE
Cyclofix: Bicycle rental zoom level is out of sync

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1779]
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/85a904e0-e069-4272-b90d-275ae46b2765)

Shows zoom in notice in layer menu at z<18, but it displays already at z>13.

**Comment by pietervdvn** [comment]
The bicycle rental is a 'schizophrenic' layer. It shows _all_ bicycle rental stations when zoom is >18 and but hides [docking bicycle rental](https://wiki.openstreetmap.org/wiki/File:London_cycle_hire_docking_station,_Denyer_Street,_Chelsea_-_geograph.org.uk_-_2020872.jpg) between z=12 and z=18, 'cause that would flood the map in some cities with the many docking stations they have available.

The app (or rather: the programmer) confuses the zoomlevels.
