### ISSUE TITLE
add new tagging to toilet theme toilets:menstrual_products=yes/now/limited

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1784]
See https://gay-pirate-assassins.de/@moanos/statuses/01HPH08CZQ30D1M831MK4FZKCQ

https://wiki.openstreetmap.org/wiki/Key:toilets:menstrual_products

**Comment by danieldegroot2** [comment]
Ref https://github.com/openstreetmap/id-tagging-schema/pull/1116

**Comment by pietervdvn** [comment]
I've made a few assumptions when adding this:

- I assume that there are no menstrual products by default. Someone might thus see (wrongly) that no menstrual products are in a toilet, even though there are some
- If `limited`, I assume that they are located in the women's toilet and show that.
