### ISSUE TITLE
Icons are not grouped properly

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1788]
Example: https://mapcomplete.org/playgrounds.html?z=16.9&lat=52.65017749696921&lon=-7.245905136127476#way/49341670

**Expected behaviour**
Restrictions icons and generic meta buttons (editor/share/favourite/...) are grouped together.

**Current behaviour**
Restriction icons are being shuffled with the generic meta buttons. They are not (properly) grouped/wrapped.

This happens regardless of browser zoom level.

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/93cf63db-1ae6-4284-9875-7a94e20585a6)

(Also, a scroll bar is shown in the heading element because the size of some element inside it is slightly exceeding its default height. There is no other content displayed when scrolling down in the heading.)

---

(_Disclaimer: I personally have a high dpi screen._)

**Comment by pietervdvn** [comment]
I guess you want the 'no dogs'-icon next to the 'no smoking icon', left of the 'share'-button?

**Comment by danieldegroot2** [comment]
Yes, assuming this is not an intentional special grouping. Otherwise, I would still want such groups to appear next to each other, the meta buttons always being last, or shown below them, or alternatively as 'more options' button next to the name (but this adds extra action needed by user).

**Comment by pietervdvn** [comment]
Those buttons simply appear in the order that they are defined in `icons.json` there is no inherit logic in them for now. I've changed the order for you.
