### ISSUE TITLE
Ways don't change color after answering question

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1803]
For example on the Street Lamps theme, if you set a street to be lit, then it doesn't change on the map until you refresh (or seem to wait a minute or so).
It used to instantly switch to yellow (as it should).
Tested on both stable and dev, fennec mobile, firefox desktop

https://github.com/pietervdvn/MapComplete/assets/1010226/e72a4630-01d4-4c0d-9978-7d2838d2285f

**Comment by pietervdvn** [comment]
This is because there are actually two layers at play here: one for lit streets, one for all streets. The 'all streets' doesn't have rendering for 'lit=yes' enabled (I've added that just now).

'Layer-jumping' is not supported at the moment, hence it would not rerender.
