### ISSUE TITLE
Loading screen no longer uses (browser) language setting

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1817]
Bug introduced very recently (maybe when/after trying to fix build).

### Current behaviour
Loading screen displays text for all languages

### Expected behaviour
Loading screen displays only text for language used by (browser*) language setting
(*if local setting fails, fallback to browser setting.)

Example: [`https://mapcomplete.org/aed.html?`]()

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/85b8225a-5f65-436f-b691-52197b27cbaf)

**Comment by pietervdvn** [comment]
Fallout of #1813 : the script removing the other languages loads slowly, as it used to get inlined automatically.
