### ISSUE TITLE
Custom Theme Generator shows error message

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#182]
When I try using https://pietervdvn.github.io/MapComplete/customGenerator.html with Google Chrome Canary I only see error messages in the right box.

Example:
![image](https://user-images.githubusercontent.com/111561/104822045-4d1f9a00-5840-11eb-98f7-e37784557db2.png)

PS: How do I select the error message?

**Comment by pietervdvn** [comment]
The custom theme generator is very buggy abd unpolished. The error message is because the theme isn't created yet, just start making your theme and the error will dissappear.

**Comment by pietervdvn** [comment]
When i have more time, I will remake it all. See #173 . I'm closing this issue for now as it is known behaviour. Thx for reaching out anyway!
