### ISSUE TITLE
Memorial layer asks for type when type is already present, but urecognised by Mapcomplete

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#1824]
The new Memorial layer only supports statues, plaques, memorial benches and ghost bikes. When a memorial is already tagged with one of the other memorial tags documented for [`memorial=*`][1] it sometimes ignores the tag and encourages the user to enter incorrect data by presenting the "what type of memorial is this" question anyway. I think the correct behaviour would be to display fallback text with the raw value of the memorial key as a placeholder for better wording. 

In testing to write this issue, I have found that it will usually incorrectly ask the questions the first time I select the feature after a page refresh, but if I dismiss the edit panel and click on the item again it will then display a very basic panel with no information and only the prompt to add a photo, if I then select a feature that genuinely lacks a memorial type it will not ask the question for that either. 

I also think it is misleading for the title of the whole panel to describe an item as a memorial plaque when the memorial type is either unset, or is set to an unknown value. 

Examples where this happens;
- [node 7869921183 (a cross)](https://mapcomplete.org/memorials.html?test=true&z=13.4&lat=26.579266760404437&lon=-78.60067815803887&layer-range=true#node/7869921183)
- [node 1295065994 (sculpture)](https://mapcomplete.org/memorials.html?test=true&z=16.7&lat=53.477041813771194&lon=-2.236141549108652&layer-range=true#node/1295065994)

[1]: https://wiki.openstreetmap.org/wiki/Key:memorial

**Comment by pietervdvn** [comment]
I might have launched this theme a bit to soon... I've first focused on the types that were already present in mapcomplete (benches and artwork), and was a bit to lazy to add the other types.

I've added them now.
