### ISSUE TITLE
Studio: Changing multilingual labels

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1829]
For labels such as layer name with multiple languages;
- Switching to other language and saving returns empty `""` or `"name"` (when switching language, keeping input without changes)
- Deleting a label seems impossible, returns empty as above.
- There is only one input for all languages, therefore the saved state (when to save / what is saved) may be ambiguous to the user.

**Comment by danieldegroot2** [comment]
The third is being caused by caching old data.

**Comment by danieldegroot2** [comment]
@pietervdvn Also, such layers also have non-functional link to wiki (which is used only for Tags)
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/6ea5ecdd-aa8b-48a1-90cc-0df281af6ed5)

**Comment by pietervdvn** [comment]
@danieldegroot2 Can you please provide some context for your last comment? The link is indeed invalid, but it unclear to me which element you're hovering here

**Comment by danieldegroot2** [comment]
@pietervdvn Example: Layer name
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/edf2ce36-57ba-4070-9ac8-d050b79e70c6)

**Comment by pietervdvn** [comment]
The highlighted info is debug information.

I think that with this UI, this is pretty usable: 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/ea050d71-779b-4e7a-a063-2b05e0980582)
