### ISSUE TITLE
Studio: Keeping studio unfocused for too long returns empty notice

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1830]
Coming back after a little bit, Studio returns an empty notice ( ` 🚫 ` )
There should be some text explaining why this notice appears.
Also, there should be a button to Go back (to ...) if possible

Instance: 0.41.1, 0.41.2-dev
Browser(s): Chrome 123.0.6312.86
OS: Windows 10

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/da233609-8720-4302-a6f9-9ff12fb500fd)

**Comment by pietervdvn** [comment]
The login code checks for new messages every 5 minutes. If you happen to not have internet or OSM goes down in the meantime, this is the result.

This error message should be improved though... And it now also attempts to reconnect automatically if you was offline for a while.
