### ISSUE TITLE
Studio: Selected elements are white (again)

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1831]
On "Rendering on the map" tab: "When should this item be shown (including special conditions)?"

**Observed**
Some elements' text becomes white when selected.
(May happen elsewhere too.)

**Expected**
Black text so it can be read.

Instance: 0.41.1, 0.41.2-dev
Browser(s): Chrome 123.0.6312.86
OS: Windows 10

_Note, high-dpp / large display_

(Not selected, with selection unfocused so you can still read the choice menu)
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/f6f1862c-46f0-470a-9684-a7e06ff2ded8)

(Selected, a choice becomes white so can not be read)
![image](https://github.com/pietervdvn/MapComplete/assets/67521919/6da134d7-f22d-4666-9f84-a1223a1ffe46)

---

Related:
- #1648 (for external link text -now instead icons- in a layer's about menu)
- #1615 (for -unselected- icons inside layers)

**Comment by thibaultmol** [comment]
(best to mention on each issue what browser/version/platform you're running and what MC version you had it in: stable/dev)

**Comment by danieldegroot2** [comment]
Done for this issue.
