### ISSUE TITLE
Settings: Translation string count in contributor statistics is missing (question)

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1834]
https://docs.weblate.org/en/latest/devel/reporting.html

Reporting is there `"Count" (Amount of strings)` but may not be exposed via their API. I assume this is why it is currently not displayed?

From https://github.com/WeblateOrg/weblate/issues/5459#issuecomment-792829978

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/2f7ca2a7-a1dd-41e0-b093-24c829913d11)

Instance: 0.41.1

**Comment by pietervdvn** [comment]
The number of commits is available from the commit history, but just as with the changesets: one commit might contain 1000 translated strings, and another contributor might have made 1000 commits with one change each.

But, as you care for it (and the other contribution counts use changesets/commits as well), I'll just add it.

**Comment by danieldegroot2** [comment]
Resolved in https://github.com/pietervdvn/MapComplete/commit/e62b7a26e0d416b080908969e313624aba940a1c for 0.41.1
(and pushed straight past 0.41.2-dev which seems to have not received this change yet.)
