### ISSUE TITLE
Education: Special education schools

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1839]
Suggestion: Adding some indication (question choice, icon) for special education schools
(special education needs, disabled, blind, deaf, etc.)

There is no tagging consensus (see [`school`](https://taginfo.openstreetmap.org/keys/school#values) and [`pedagogy`](https://taginfo.openstreetmap.org/keys/pedagogy#values)), there is overlap with existing values.

Related: #875

**Comment by pietervdvn** [comment]
School:for got rejected: https://wiki.openstreetmap.org/wiki/Proposal:Key:school:for, hence why it doesn't ask for it

Seems like 'pedagogy' is widely accepted now though
