### ISSUE TITLE
Cafes/Food: Show outdoor seating, food court areas

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1845]
Suggestion: Add [outdoor seating](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Doutdoor_seating), [food court](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dfood_court) areas with questions for i.e. heating(, light), wheelchair accessibility
(maybe could allow kerbs in OnWheels to be snapped to these on high zoom but idk about the combination's frequency)

**Comment by RobinLinde** [comment]
Basic version added in 6abe3c7
