### ISSUE TITLE
Blind/Maps: Show tactile map, tactile model

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1853]
Suggestion: Add [tactile maps](https://wiki.openstreetmap.org/wiki/Tag:information%3Dtactile_map), [tactile models](https://wiki.openstreetmap.org/wiki/Tag:information%3Dtactile_model). (with question for material)

Sidenote: There is also [`tactile_writing`](https://wiki.openstreetmap.org/wiki/Key:tactile_writing).

**Comment by RobinLinde** [comment]
Added in #2229
