### ISSUE TITLE
Hackerspaces: Add electronics charging, internet connection question

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1856]
Suggestion: Add [electronics charging](https://wiki.openstreetmap.org/wiki/Key:service:electricity), [internet connection](https://wiki.openstreetmap.org/wiki/Key:internet_access) questions to improve range of facilities for hackerspaces.
(These will usually be available, but this allows to specify the exact type, or explicitly state it where it is not the case)

Similar to [existing electronics charging questions](https://github.com/search?q=repo%3Apietervdvn%2FMapComplete+path%3A**%2Flayers%2F**+service%3Aelectricity%3D&type=code), [existing internet connection questions](https://github.com/search?q=repo%3Apietervdvn%2FMapComplete+path%3A**%2Flayers%2F**+internet_access%3D&type=code)

(There may be other tools/services which could be added)

**Comment by pietervdvn** [comment]
I've added the 'internet'-questions.

I'm not gonna ask about electricity. I assume that any hackerspace does provide electricity to their members. One could also wonder if there are e.g. USB-chargers, but that often depends if there is one in the space an no one lent it, misplaced it or accidentally broke it...

**Comment by danieldegroot2** [comment]
@pietervdvn Would it be useful to have a [locker](https://wiki.openstreetmap.org/wiki/Key:locker) question?
(to store -and maybe charge- personal items/resources/products/tools/devices/equipment/...)

Also, I'm assuming drinks/food are (not) provided / are not important (layer would be cluttered with vending machines..)
