### ISSUE TITLE
[Tailwind regression] Image carousel is ugly

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#186]

**Comment by tordans** [comment]
Here are two locations to see the bug:

- 1 image https://pietervdvn.github.io/MapComplete/index.html?layout=artworks&test=true&z=17&lat=50.85501&lon=4.36849#node_8191852126

- 10+ images https://www.openstreetmap.org/way/9386474 at https://buurtnatuur.be/?z=17&lat=50.845&lon=4.3707 (no deeplink on this instance of MapComplete, yet)

**Comment by pietervdvn** [comment]
The tailwind version isn't deployed yet on any of the linked versions... Sorry about that! I should have been clearer.

This is what I'm talking about:

![image](https://user-images.githubusercontent.com/1466478/105638454-fc78f400-5e72-11eb-836a-3944e41704b5.png)

This being said, the image carousel was already that ugly from the start, but now it is worse ;)

**Comment by pietervdvn** [comment]
Fixed in 79fc3f5 (and some other commits)
