### ISSUE TITLE
Add layer description to filter, add documentation link to theme

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1860]
Suggestion: Add layer description to filter with `i` info icon and/or add documentation link to theme menu.

Maybe you want to start by looking for the right object type, so you open the filter menu and find there are no descriptions.
It may not always be clear what a layer is until you find an object mapped nearby, or 'Add object', which you can look at.
Obvious cases could probably be given better name/icon (i.e. waste disposal bin is maybe rectangular box on wheels, whereas recycling is often large container - but recycling already has clear icon); fyi difference between waste basket and waste disposal bin is unclear here.

Though, most layers are rather generic and understandably don't have subfilters for all the values (i.e. recycling types)
Another option would be to add a direct link to the documentation on taginfo/GitHub in the theme menu (which I could not find).
(most users will not be aware of this, but it can introduce/tell potential contributors what layers do (not) contain.)

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/c8784c42-0ad7-458e-8e2b-501a064c7898)

**Comment by pietervdvn** [comment]
No. A MapComplete theme should act as a standalone, closed app. Linking (by default) to external documentation will confuse the non-technical users.

**Comment by danieldegroot2** [comment]
I will assume there is no obvious enhancement similar to suggested options (multiple), closing as not planned.
Better to continue on adding/improving descriptions for 'add object' where needed instead.
