### ISSUE TITLE
Adding entrance or object 'on wall' as standalone should have fixme

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1861]
Adding already specified outdoor entrance or 'on wall' object as standalone object should have a fixme like
`fixme=attach to wall/building`

Every Door already does this.
Example https://www.openstreetmap.org/node/11708094281/history/1
(sidenote: I am linking to initial version using versioning feature on osm.org recently improved by Anton Khorev)

**Comment by pietervdvn** [comment]
MapComplete already snaps to nearby walls and buildings. It has thus no use setting a fixme.

**Comment by danieldegroot2** [comment]
When the editor _does_ snap it to a wall, it is okay.
However, you can add an object, choosing 'on a wall', but decide to _not_ snap it to an existing wall. See for example
- https://www.openstreetmap.org/changeset/149279836
- https://www.openstreetmap.org/changeset/149279728

There may be no wall mapped nearby, or the user was not aware of / did not properly snap the object to the nearby wall, but knows the object is on a wall, adding it as a standalone object means the same as adding it without the 'on a wall' choice, losing detail and uploading inaccurate data.
The editor in this case is aware the object should be snapped to a wall, but allows the user to keep it seperate.

I would suggest either the user is restricted from adding it as a standalone object when choice is 'on a wall', or there is some feedback to mappers to indicate missing/inaccurate data (fixme); 'the user knows it is on a wall, there should be one nearby'.
Otherwise, mappers have to rely on validator applications to resolve inaccuracies introduced by this editor.
