### ISSUE TITLE
Missing space between license and date

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1863]
There's no space between cc0 and the date

https://dev.mapcomplete.org/bicycle_parkings.html?z=17&lat=50.78672324000104&lon=4.4242272999983925#node/9720010589
![ResizedImage_2024-03-31_15-55-41_1000](https://github.com/pietervdvn/MapComplete/assets/1010226/4696db4a-d6a5-4da1-b080-149daf352812)

**Comment by danieldegroot2** [comment]
I would suggest replacing the view count by the license text or date, if possible.
Only Imgur seems to return this data and [it is planned to move away from it](https://github.com/pietervdvn/MapComplete/issues/1451).

Also, it could be useful to expand the date of upload to Wikimedia and Mapillary images and add the author to Mapillary images too, if possible.

**Comment by pietervdvn** [comment]
> Also, it could be useful to expand the date of upload to Wikimedia and Mapillary

Added for Mapillary

>  images and add the author to Mapillary images too, if possible.

When they "updated" their API a while back, this was not possible - but it is possible now! Added

**Comment by pietervdvn** [comment]
> There's no space between cc0 and the date

Fun fact: the license + date line will expand with the total width and place the space in between. If the name of the creator is short, there won't be any space. As my name is quite long, I've never noticed this!
