### ISSUE TITLE
Advertising : New icon and question for poster box on a transport shelter.

### ISSUE THREAD

**Issue by valerie-garoux** [pietervdvn/MapComplete#1866]
Hello ! It could be great to use the poster box in shelter icon for better viewing what kind of poster box is in place. It should, I think, be accompanied with a question to ask if this is a poster box in a transport shelter or just on the ground.

Thanks for your work !

![image](https://github.com/pietervdvn/MapComplete/assets/159698633/a7cd193d-a2f6-4e66-92ff-0ba134365341)

**Comment by valerie-garoux** [comment]
Hello ! Thanks a lot for your speed (unbelievable really, I thought it would take months). In my city (and as I’ve seen, all around France), the norm is to have "_advertising=poster_box_" coupled with "_support=street_furniture:transit_shelter_". Is it possible for you to add this possibility in your code ? Thanks a lot again for your work ! It’s really an easy for us (my friends and myself) to add data in a fast and enjoyable manner.

**Comment by pietervdvn** [comment]
Hey,

Glad that you enjoy MapComplete!

Would you mind linking to an example and/or wiki page describing this?

Furthermore, are you asking to add this as option to choose? Or rather as extra condition to show the 'transit shelter' icon?

I need some guidance on how to proceed, as I want to avoid people adding a poster box which should actually select the transit shelter and indicate that it has an advertisement. The solution to this is to show the transit stops (if zoomed in a lot, e.g. >= 17), ask if they have a shelter and, if they do, ask if the shelter has an advertisement feature in it. (Note that having advertisement screens are becoming a thing in transit shelters!)

Would this be the correct tagging approach?



I'd also like to point you towards the [configuration file for the advertising layer](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/advertising/advertising.json). If you see missing tagging, feel free to make changes there and PR them.



PS: changes are first pushed to https://dev.mapcomplete.org before going to the "production"-version on https://mapcomplete.org (notice the `dev` in front of the former link). I upstream changes every once in a while.

**Comment by valerie-garoux** [comment]
![IMG_0701](https://github.com/pietervdvn/MapComplete/assets/159698633/aa2aa6aa-56b3-43f8-b071-58f4520e3a17)
![IMG_0702](https://github.com/pietervdvn/MapComplete/assets/159698633/5db4e682-526c-47dc-a67f-2fba69d5648e)
![IMG_0703](https://github.com/pietervdvn/MapComplete/assets/159698633/ae2ee223-46b0-40c7-9ff4-083a562df9ba)

Hello !

I share you an example here. Here, you have 2 poster_boxes on one shelter. The norm in french cities (I don’t know how it works further) is to have a transport shelter (a node or a way), and another node, close to the shelter, to show that there is advertising. The shelter can have a tag "advertising=yes", but the main part of the advertising information is with the advertising node, next to it.
On my example, you have one poster_box on the left of the shelter (whose reference is 223), and another one on the right-back (who’s referenced 222). If I choose to put all those datas in the shelter way, I will not be able to have the two references and the display showing 2 poster boxes.
The main part is that, with this manner of doing things, we can easily see that there is 2 poster boxes (and we have some places where there are 3 on one shelter).



I guess the best way to implement this would be to add an other option in the selection menu (next to the freestanding poster box and the wall-mounted one). This option will put "advertising=poster_box" and "support=street_furniture:transit_shelter" on the node directly, and will have the other options after that.
I don’t know of ways to put all of that information directly to the shelter way, but it can also be a good thing to do (I don’t know how to put that thing for people to understand the two ways of doing it).
And yes you are true with the screens appearing on shelters. I don’t know either on how to do that (maybe with another option). Or maybe with an other question "Is this feature mounted on a wall, on a transit shelter, or standing by itself?".


I can consult the configuration file, and (I don’t know how), understand approximately what is written, but my knowledge is really limited, so I don’t see any mistakes, but don’t take my word for a good answer…


Thanks a lot for your time ;)

PS : Ok thanks, that explains why I didn’t see changes on the website. That’s safer yes !

**Comment by pietervdvn** [comment]
I had a look to those examples. IMHO, if the poster box is physically part of the transit shelter, it should be snapped to the transit shelter.
This implies `advertising=yes` (for the transit shelter) and for the poster box it makes the 'support'-tag unnecessary.

It loses the information if the poster box has the advertising on the inside, the outside or both though - and it makes it technically more challenging...

**Comment by pietervdvn** [comment]
Another option is showing the shelters as well when zoomed in quite a bit: 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/da8a15ce-8aa9-4910-9045-e0f0c238e6c6)

**Comment by valerie-garoux** [comment]
You say « snap » like a relation between the shelter and the poster box (i’m a newbie with that type of linkage) ?
For the shelter with `advertising=yes`, I don’t know it it’s shown afterwards in MapComplete (like it was with a "no" value), but maybe, paying attention to that will be necessary.
It’s really cool yes with the changed icon (without the pole under the poster box). Visually, it is more efficient, and yes, with the shelter icon, it’s a bit like if there was several shelters, so it’s not the good icon for that.
I still don’t know how you can make everything to question people to add those informations, because, in many cases, we still don’t have the shelter created (it was created really recently in the place you’ve tested), so maybe by creating the shelter with the poster box, but it’s more complicated, or maybe just showing it and putting a `fixme` for every instance in a shelter, to add the shelter after, with another OSM editor.

I don’t really know because I don’t know how complicated is a feature to implement in your code.

Thanks a lot, really, to be this cool by listening to put things the better way possible.

**Comment by pietervdvn** [comment]
In MapComplete, I've added the option to create a new point 'snapped' into the transit shelter. (For now, only on https://dev.mapcomplete.org). It'll be snapped _and_ have `support=street_furniture:transit_shelter`.

When a standalone point, it'll render as transit shelter. If snapped, it'll render as a normal poster box.

If you want to snap existing standalone points, the easiest is to use the online iD-editor (openstreetmap.org -> edit) and to drag the little pin into the transit shelter.

L&R

**Comment by valerie-garoux** [comment]
OMG thanks a lot. It’s perfect ! Thanks again !
