### ISSUE TITLE
Login in desktop Chromium-based browsers on macOS opens OSM in new tab and fails

### ISSUE THREAD

**Issue by stefanb** [pietervdvn/MapComplete#1867]
Possibly related to the osm.org login / authorization page being opened in a new tab, which isn't closed and just keeps reloading authorization page when clicking the authorize button. It behaves the same in incognito mode.

In Firefox it works fine and there the osm.org login / authorize page is opened in the same browser tab.

**Comment by pietervdvn** [comment]
Cannot reproduce on Chromium on Ubuntu
Cannot reproduce on Chrome 121.0.06167.185 and 123.0.63112.86 on Windows 10 (in a VM)

Is this still an issue for you? Do you have any output from the console?

**Comment by stefanb** [comment]
I noticed the problem a few weeks ago when trying the app again after a long time (a year?) and has been occurring since.
Chrome on macOS.

Errors in console:
* GET https://gc.zgo.at/count.js net::ERR_BLOCKED_BY_CLIENT
* Got an error while running a callback: Error: metatagging-object for this theme does not have an entry at
  metaTaggging_for_last_click (or it is not a function)
  ping @ UIEventSource.ts:400
  setData @ UIEventSource.ts:765
  openNewDialog @ ThemeViewGUI-cef66702.js:24
  oA @ ThemeViewGUI-cef66702.js:243
* Not intercepting  https://www.openstreetmap.org/api/0.6/capabilities mapcomplete.org www.openstreetmap.org service-worker.js:109

**Comment by stefanb** [comment]
Question: is it intended for OSM login to be opened in a new browser tab? Imo that is causing the problem closing the login tab and getting back to mapcomplete app.

**Comment by pietervdvn** [comment]
No, the login page is supposed to load in the same tab. Can you try hitting Ctrl+F5 before logging in to force a full reload?

**Comment by stefanb** [comment]
Reloaded the page without cache (shift+cmd+R on macOS) produced the same result - opening the login page in new tab.

In console i could see the "Trying to log in..." and a few requests to https://mapcomplete.org/assets/...

Even manually clearing site data in developer console made no changes - the OSM login page still opened in new tab.

Observed this on Chromes on two different Macs.

**Comment by stefanb** [comment]
I should also add, that I am not seeing other websites opening new tabs on a whim.

**Comment by stefanb** [comment]
No such problem on Windows 10 when using same account (providing same set of browser extensions to rule those out).

**Comment by stefanb** [comment]
Tried also with a guest profile in Chrome on macOS and experienced the same problem.
No problem on mobile Chrome on Android.

To summarize:

|OS | Browser | Login works?|note|
|----|---------|---------|---|
| macOS| Chrome | **_No_** |2 separate macbooks, profile with extensions, incognito, guest profile with no extensions, **opens new tab** |
| macOS| Firefox | Yes | |
| macOS| Safari | Yes | |
| Windows| Chrome | Yes | tried with same set of plugins as on macOS |
| Android| Chrome | Yes |  |

**Comment by pietervdvn** [comment]
I'm gonna update the VM tonight, when I have decent internet.

**Comment by stefanb** [comment]
With the help of local OSM community I have added a few more tested browser / OS combinations to the matrix aboce, all without problems.

I suspect that it wrongly sets the `singlepage` parameter when setting up the authentication

https://github.com/pietervdvn/MapComplete/blob/073cd692e456ae63999bfc2770d0c204dc8a1793/src/Logic/Osm/OsmConnection.ts#L549

Spec at https://github.com/osmlab/osm-auth says:
> `singlepage` - If `true`, use page redirection instead of a popup (default: `false`)

**Comment by stefanb** [comment]
Interestingly, test on https://osmlab.github.io/osm-auth/ opens new tab in my chrome and then closes it, but in Firefox it opens a popup window and then closes it. In both cases the login succeeds.

**Comment by pietervdvn** [comment]
I've enabled 'single page' mode in all cases on `dev.mapcomplete.org`. Would you mind testing there? Should be live from about 14:00 Brussels time.

To test:

- [ ] Login flow on firefox
- [ ] Login flow on firefox in a PWA
- [ ] Login flow on firefox in an iframe
- [ ] Login flow on Chromium
- [ ] Login flow on Chromium in a PWA
- [ ] Login flow on Chromium in an iframe

**Comment by stefanb** [comment]
Yay, it works in both Chrome and Edge on macOS where it previously failed 🎉 🥳 
But of course other browsers should be tested too.
Thanks for setting up the test!

**Comment by stefanb** [comment]
Works also in Firefox, but haven't tested in iframe (is this legit use case r should it escape iframes?) nor PWA.
