### ISSUE TITLE
Mangrove review not working when not logged in

### ISSUE THREAD

**Issue by TimestaticYT** [pietervdvn/MapComplete#1868]
![Restaurants and fast food _ Fastfood Stern D_nerhaus](https://github.com/pietervdvn/MapComplete/assets/58912623/d75b1198-901d-48a2-bc64-ddb64dbcebd1)

I wanted to Add a review to Mangrove but it gave me an error message: `Something went wrongTypeError: Cannot read properties of undefined (reading 'publicKey')`

This is not the first time this has happened before and it deleted the entire review

**Comment by pietervdvn** [comment]
Did you ever make a review before?

> Could it be related to me choosing 4.5 stars when their website allows for only 4 or 5?

No, half-star reviews are supported and working.

**Comment by TimestaticYT** [comment]
> Oh, you are _not_ logged in. That's probably why.
> 
> > Could it be related to me choosing 4.5 stars when their website allows for only 4 or 5?
> 
> No, half-star reviews are supported and working.

Wait but isn't your OSM account seperate from the cryptographic key used mangrove?

**Comment by pietervdvn** [comment]
> Wait but isn't your OSM account seperate from the cryptographic key used mangrove?

Yes, but it is stored in the ISM-preferences. So, that is where it went wrong.
