### ISSUE TITLE
Satellite image from Google uploaded

### ISSUE THREAD

**Issue by Thierry1030** [pietervdvn/MapComplete#1872]
![Screenshot from 2024-04-04 07-18-24](https://github.com/pietervdvn/MapComplete/assets/64559939/da53b7d0-062f-4a7e-a4a2-d00b18ba518f)

Some of the users hereunder uploaded an image from Google on 3 April 2024

- - -
- 
Images in this thread are randomly selected from them and were made by: 
Awo
[@Thierry1030](https://en.osm.town/@Thierry1030)
Ninopiña10
warddr
5R-MFT
GEO ECLA
APneunzehn74
belvegore
Anfrageancg

**Comment by thibaultmol** [comment]
Seems like someone else caught it and removed the tag (best to remove it from the imgur dataset as well @pietervdvn ) https://www.openstreetmap.org/changeset/149510275#map=7/51.132/3.113

**Comment by pietervdvn** [comment]
Not much to do here, I don't see other technical things I can do to prevent this (and the rate of this has been extremely low), so I'm closing this issue.
