### ISSUE TITLE
{Today} function for use in text renderings and tag renderings

### ISSUE THREAD

**Issue by pelderson** [pietervdvn/MapComplete#188]
Is it possible to add a function to make the current date available in de renderings?

E.g. now you can use {<key>} or {all_tags} in a popup title, I would like a {today} function returning the current date as a string in the usual OSM date format. 

The use case is: setting survey:date on network nodes and connection routes with minimal fuss for the user i.e. without the free form field and without the date selector. I use this for the walking node networks theme; it ties in with vmarc's Knooppuntnet  support system for node network quality/maintenance. 

It allows systematic checking/maintenance projects focussing on oldest survey:date. The surveyors need to be able to use the tool with the absolute minimum of taps (i.e. no free form fields).

**Comment by pietervdvn** [comment]
This can now be done with the (automatically) [calculated tag](https://github.com/pietervdvn/MapComplete/blob/master/Docs/CalculatedTags.md) and the new substituting assignment tag `:=`, by having a mapping 

```
{
"if":"survey:date:={_now:date}", 
"then": "Surveyed today"
}
```

An example is [here](https://github.com/pietervdvn/MapComplete/blob/8c0cae7a8c26ea3bf76dac7d675868569d19506a/assets/layers/benches/benches.json#L244)

(Note: at this moment, this is only available on the [staging deployment](pietervdvn.github.io/MapComplete) - it will be on [mapcomplete.osm.be](mapcomplete.osm.be) soon)
