### ISSUE TITLE
Nodes: Change icon size, text alignment

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1885]
**Observed**
Text aligns to the left instead of the center and does not fit inside the current small icon.

Ex.
https://mapcomplete.org/cyclenodes?z=13.3&lat=51.97117110672119&lon=5.668852980513066
https://mapcomplete.org/walkingnodes?z=13.3&lat=51.97117110672119&lon=5.668852980513066

**Expected**
Text fits icon nicely, or is clearly visible otherwise.

Ex.
https://knooppuntnet.nl/nl/map/cycling
https://knooppuntnet.nl/nl/map/hiking

**Comment by RobinLinde** [comment]
Fixed in 6abe3c7
