### ISSUE TITLE
Black icons on map don't have white border/circle

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1887]
Black icons don't have white borders around them so they're hard to see on dark aerial footage.
![Screenshot_20240411-152409](https://github.com/pietervdvn/MapComplete/assets/1010226/b58baecb-0703-4314-8382-47475ad3ccf5)
https://dev.mapcomplete.org/waste.html?z=18&lat=55.6441481932691&lon=-3.138277951959708

**Comment by pietervdvn** [comment]
I guess you're specifically talking about the GPS-marker?
