### ISSUE TITLE
Etymology: Some objects display nearby images, others not

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1888]
**Observed**
At least on Etymology, some objects display nearby images, with no 'upload images' button or nearby images selection choice. Other objects do not display any images at all.

**Expected**
Consider hiding nearby images for all objects, or showing image questions for all objects.

Nearby images shown, images questions replaced by streetsign question at bottom (understandable)
https://mapcomplete.org/etymology.html?z=17&lat=52.65109259529348&lon=-7.249292336187182#way/240030141

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/592d8f76-c5b2-45ff-a6af-ed7638a6853a)

No images shown
https://mapcomplete.org/etymology.html?z=17&lat=52.65182483285125&lon=-7.2516580445751515#way/1023719146

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/e4d249d6-b252-46d9-9cb4-7c6c9daa2549)

Instance(s): MapComplete v0.41.4, v0.41.5-dev
Browser(s): Chrome 123.0.6312.106
OS: Windows 10

**Comment by pietervdvn** [comment]
Works as intended. It shows images from Wikimedia about the entity the POI is named after.

If there is no etymology link yet, there are nog images.

**Comment by danieldegroot2** [comment]
Sorry, did not check properly what it was referencing.
