### ISSUE TITLE
Etymology: Typo 'toursistic' in touristic places layer

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1889]
**Observed**
'Toursistic' instead of 'touristic' is used.

Code: https://github.com/search?q=repo%3Apietervdvn%2FMapComplete%20toursistic&type=code

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/56a2424d-d37b-476e-817c-ed5f53cbe544)

Instance(s): MapComplete v0.41.4, v0.41.5-dev
Browser(s): Chrome 123.0.6312.106
OS: Windows 10

**Comment by pietervdvn** [comment]
Fixed in weblate
