### ISSUE TITLE
Colour selector for free form key value

### ISSUE THREAD

**Issue by pelderson** [pietervdvn/MapComplete#189]
A colour selector offering the standard html-colours for a tagrendering would be a nice feature.
Comparable to the date selector calendar and the direction selector ring / compass.  
I guess it would need a new data type: {html_colour} or something? 

Use case: Walking node network routes. Some regions use colour indication instead of number indication.  The routes need the colour, if it's not there the node planner output (node strip) is of no use. 

Note: in this case, the free text user input should remain available, a. because of the other colour systems allowed in the colour tag, and b. because there can be multiple colours on a single route (semicolon separated list: blue;purple means bothe the blue arrows and the purple arrows lead you to the same network node) and even combi-colours (white-red means follow the white-red markings to the next network node).

**Comment by pietervdvn** [comment]
Added in v 0.7.2 in 8774b887d8f9032056b5a9785326e0f6c7cf0678
