### ISSUE TITLE
Etymology: Generalize title

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1890]
**Observed**
Currently title focuses on streets while it includes many object types.

**Expected**
Suggestion: 'Etymology - what is a **place** named after?' (based on existing content of description)

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/df068032-3ca1-4be5-9050-8f5d6d19baf3)

Instance(s): MapComplete v0.41.4, v0.41.5-dev
Browser(s): Chrome 123.0.6312.106
OS: Windows 10

**Comment by pietervdvn** [comment]
Hey Daniel,


You can fix small typos easily yourself by enabling translation mode:

[Screencast from 13-04-24 02:25:34.webm](https://github.com/pietervdvn/MapComplete/assets/1466478/a58b5e3b-cbef-4f78-b077-56ddfb354b0a)

Make sure to hit the small 'translate'-icon which appears when you enable translation mode.

Changes to the translations are synced every few days (they regularly generate a pull request)

(Note: this was previously slightly broken and sometimes didn't link correctly). 

(I've fixed this specific one during the example)
