### ISSUE TITLE
Use Wikimedia Commons image instead of Wikipedia image

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1891]
**Observed**
Objects display Wikipedia 'commons' images instead of showing Commons images directly.

**Expected**
If possible, consider hiding Wikipedia images if there is a Commons equivalent. (which is also indicated on the Wikipedia file page)

Sidenote: If no author provided, displays `No machine-readable author provided. **[displays name of uploader]** assumed (based on copyright claims).` which is in the author field (understandable, though kind of long text)

Example: Shows Wikipedia file with small Commons icon, instead of Commons file with large Commons icon. Original is on Commons.
https://mapcomplete.org/etymology.html?z=17&lat=52.65109259529348&lon=-7.249292336187182#way/240030141

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/592d8f76-c5b2-45ff-a6af-ed7638a6853a)

Wikipedia file: https://en.wikipedia.org/wiki/File:Kilkenny-castle.jpg
Original file on Commons: https://commons.wikimedia.org/wiki/File:Kilkenny-castle.jpg

Instance(s): MapComplete v0.41.4, v0.41.5-dev
Browser(s): Chrome 123.0.6312.106
OS: Windows 10

**Comment by pietervdvn** [comment]
The policy is to show all images available. If the image would be hidden, someone else would come by and wonder why this image does not show.
