### ISSUE TITLE
Add search field when on the 'Choose a layer to edit' page

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1898]
there are a lot of layers there currently obv.

While most of the people reading this know CTRL + F, some might not. So maybe having a simple text filter option there could be nice

**Comment by RobinLinde** [comment]
Rough concept I have for now
[Schermopname van 2024-04-21 01-10-43.webm](https://github.com/pietervdvn/MapComplete/assets/1395345/784a31c4-5b15-4ba7-a701-1820936f6600)

**Comment by pietervdvn** [comment]
I've already pulled in your commits, good enough for me ;)
