### ISSUE TITLE
Option to show a label on the map, next to or over the icon 

### ISSUE THREAD

**Issue by pelderson** [pietervdvn/MapComplete#190]
For objects with a ref it would be ideal to see the ref on the screen rendered next to or even over the icon. 
My use case, of course, is node network numbers. To specify, one should be able to add {<key>} to the Icon definition, e.g. "https://i.imgur.com/gnlFWCV.png {rwn_ref}", or as a separate parameter.

For network node numbers, I would use {rwn_ref} and a simple circle icon, which would make the nodes  appear just as you see them on all the planners. 
For network routes, I could use {ref} and a bar icon.

**Comment by pietervdvn** [comment]
This is implemented as [label in the layerConfigJson](https://github.com/pietervdvn/MapComplete/blob/bc4a5a7fe2140058b34e7330ce208bfd5c141094/Customizations/JSON/LayerConfigJson.ts#L136)

The exact meaning and rendering is still subject to (small) changes
