### ISSUE TITLE
Render charging stations as areas

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1903]
Currently if a charging station is mapped as an area, it shows up in Mapcomplete as a point without the actual area highlighted

**Comment by thibaultmol** [comment]
![Screenshot 2024-04-14 at 10-12-40 Way 1272481484 OpenStreetMap](https://github.com/pietervdvn/MapComplete/assets/1010226/bd46874a-6c2f-4df8-93c8-29ba3c75ddb5)
![Screenshot 2024-04-14 at 10-12-31 Charging stations Charging station for cars](https://github.com/pietervdvn/MapComplete/assets/1010226/f0d6ba90-afc0-4c7b-8b41-835c61bb910f)

**Comment by thibaultmol** [comment]
@RobinLinde could you check if this actually was fixed, because on my end i don't see the are rendering?
![image](https://github.com/user-attachments/assets/5084cd38-cf74-42cf-bb33-69956dbb6d49)

**Comment by RobinLinde** [comment]
@thibaultmol No idea why, but seems to look fine for me:
![Screenshot showing charging station in MapComplete](https://github.com/user-attachments/assets/e3c2822e-bf1d-4dc4-a2d7-eedd8e0f2896)

**Comment by pietervdvn** [comment]
The testcase: https://www.openstreetmap.org/way/1337331184#map=19/51.192104/4.419989
https://mapcomplete.org/charging_stations?z=19.6&lat=51.19209306285103&lon=4.419983516659045
Is rendering fine for me on librewolf (Firefox fork) on linux:

![image](https://github.com/user-attachments/assets/20c2fed3-9d4d-4ba6-a8b3-c0dd704e1cff)

(Note that 'uitbreidinsstraat' is missing. It was "highway=construction" a while back and is thus missing in protomaps)

**Comment by pietervdvn** [comment]
Renders fine in Chromium as well: 
![image](https://github.com/user-attachments/assets/f1bda6cf-c6b8-4740-b05b-36e8117bc708)

**Comment by thibaultmol** [comment]
hmmmm...  it still doesn't work for me
https://mapcomplete.org/charging_stations.html?z=19.5&lat=51.19212663325817&lon=4.420067958786262
![image](https://github.com/user-attachments/assets/630a7ddf-0ea0-4917-9b00-35a880e8436e)

chromium:
![image](https://github.com/user-attachments/assets/edb0efa1-7a8e-4981-9756-3edc982301ab)

**Comment by thibaultmol** [comment]
nvm, jakka changed my tagging (i think incorrectly, but need to check) so there is indeed no way there aynymore
