### ISSUE TITLE
Share infowindow via URL / Zoom to node/way if no lat/lng given

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#191]
It would be great to be able to share a specific info window via URL. 
This is usefull for debugging but also to share with other mappers in situations where I have a question about an object or want them to fill in answers for a specific object.

The way iD handles this: Whenever you have a node / way details open on osm.org and click edit, it will add `?node=ID`, ?`way=ID` to the URL. Re-using this pattern might be a good idea.
- https://www.openstreetmap.org/edit?way=41418905#map=19/52.47198/13.44725 (when "edit" on https://www.openstreetmap.org/way/41418905)
- https://www.openstreetmap.org/edit?node=8308189217#map=19/52.47612/13.45750

The deephistory on the other hand uses "`node/ID`"
https://osmlab.github.io/osm-deep-history/#/node/8308189217
https://osmlab.github.io/osm-deep-history/#/way/41418905

**Comment by tordans** [comment]
I just realised this is already there in the latest version, right?

eg. https://pietervdvn.github.io/MapComplete/index.html?layout=artworks&test=true&z=17&lat=50.85501&lon=4.36849#node_8191852126

Thanks!

**Comment by tordans** [comment]
# Reopened: Zoom missing

Right now, http://localhost:1234/index.html?layout=artworks&test=true#node_7830431446 would open the map at lat/lng 0,0 or something. Ideally, the map would use the coordinates of the given node/way.

**Comment by pietervdvn** [comment]
Yes, it is indeed more or less there - but it should still load the data directly from OSM and zoom to it.

This one is pretty high on my list, but first I want to finish the tailwind-refactoring.

**Comment by tordans** [comment]
Sounds good! 

If it's not finished yet, would you consider changing the param? I find the way/123 pattern very handy since it allows to just copy part of the OSM URL without changing it to _.

**Comment by pietervdvn** [comment]
Hmmm, IIRC having a `/` in the hash broke stuff, but I can't remember what exactly.

I might have a look at it later; I'm first refactoring a few more things.
