### ISSUE TITLE
Unclear “external data” message

### ISSUE THREAD

**Issue by fizwidget** [pietervdvn/MapComplete#1911]
Hello, 

It’s a small thing, but I find this message to be unclear/confusing:

![IMG_4308](https://github.com/pietervdvn/MapComplete/assets/1172012/04fead17-e1f1-498b-a4ab-49b473a92a8e)

What “external data” is it referring to? I’d assume Wikipedia/Wikidata, but [this node](https://www.openstreetmap.org/node/4055969197/history) doesn’t have IDs for them set.

Thanks!

**Comment by pietervdvn** [comment]
If a website is linked, ot moght contain some LOD-jolson containing e.g. opening hours and phone number. This is what ot is referring too, but the message should be improved.
