### ISSUE TITLE
Edgecase on Rainbow crossings theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1915]
The theme doesn't actually look for crossings but just for rainbow surface.
So this footway bridge is also shown. I think it's fine but just letting you know

https://www.openstreetmap.org/way/34835922

**Comment by thibaultmol** [comment]
Again, it's an edgecase but yeah https://overpass-turbo.eu/s/1KnN

**Comment by pietervdvn** [comment]
I've added displaying footways specifically for that bridge you linked - mostly to prevent users to add a crossing just to be able to add a picture.

IMHO this edgecase does not hamper data quality nor useability, so it's fine for me.
