### ISSUE TITLE
All questions should have a possible answer (or be optional)

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#192]
AFAIK, in StreetComplete there is a “rule” that every question needs to have tags that allow to answer the question. Even if the answer is “there is no such thing”.

I think, this should be “rule” for MapComplete Themes as well.

Having this pattern in place, allows to introduce feature that are based on the completeness of an object. This is, was StreetComplete does as well, it only shows objects and questions that are still to be answered.

Part of this is, whoever, that StreetComplete also has very fine grained rules on which objects are shown to the mapper in the first place. This is, to prevent a ton of “this does not apply” answers on objects that should not really have this tag. I don’t have an example for this out of the box but can research one if interest is there.

---

I could see this requirement be a problem for MapComplete Themes, so a workaround could be to allow questions to be required or optional in regards to a completeness-evaluation.

**Comment by pietervdvn** [comment]
This can be implemented by the theme itself, as is the case with buurtnatuur.be

This also highlights a core difference between SC and MC. MapComplete is a map _viewer_ which also acts as data gathering tool. However, it can be easily configured to be a map viewer on a specific map theme.

StreetComplete is a _surveying_ tool, which aims to asks as much useful questions at once. [I had a lengthy conversation on it here](https://github.com/streetcomplete/StreetComplete/issues/2461#issuecomment-756456786).

I could introduce a metatag based on the number of questions that can still be asked, which is feasible - and then leave it up to the theme to use the conditions to interpret them...

**Comment by pietervdvn** [comment]
I'm gonna close this issue, as it is non-actionable and a responsibility of the themes themselves, not of MC. Furthermore, it is impossible to validate this automatically too.
