### ISSUE TITLE
Studio: Duplicate question

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1921]
> <img width="1114" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/da5b6bbf-0ef4-437f-b513-307271f5c3e7">

Same for 

> <img width="1114" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/8ef058c8-0304-4fb6-be68-48a5770085bc">

I assume one of those answer is "do not" and one is "do"

**Comment by pietervdvn** [comment]
Indeed
