### ISSUE TITLE
Studio: Have the previously chosen option selected when editing

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1922]
I picked "allow search" which the UI knows and shows me as title: 

<img width="797" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/233fa583-e1b0-4e7e-9ea9-28d7ccd5e095">

However when click edit, my previous choice is not selected: 

<img width="797" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/62961c86-819b-4ce8-9d2d-74d5915a6fa4">

It should be selected to clarify what is the currently active option.

**Comment by tordans** [comment]
It looks like the same issue is present in the main app, where the selected answer is not active/selected when I click on edit

> <img width="431" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/a6b970ee-e9fe-4ac2-8683-4b66ce599e3e">

**Comment by pietervdvn** [comment]
Studio reuses the 'question'-component from the rest of the codebase, so will indeed behave the same.

**Comment by thibaultmol** [comment]
> Studio reuses the 'question'-component from the rest of the codebase, so will indeed behave the same.

Which tbf... is fine.. and honestly what Tobias is pointing out is something that I mentioned to you at some as well. How in mapcomplete it's annoying when editing an existing answer, that the answer is not actually selected if you open it. 

I think reusing this ui component is fine, you just need to have (both in studio and MC itself) actually show the filled in question based on the previously given answer
![Screenshot 2024-04-27 at 08-37-38 Restaurants and fast food Restaurant De Nieuwe Lekkerbek](https://github.com/pietervdvn/MapComplete/assets/1010226/41881ef3-e87f-4121-a043-2e873a1591e3)
![Screenshot 2024-04-27 at 08-37-41 Restaurants and fast food Restaurant De Nieuwe Lekkerbek](https://github.com/pietervdvn/MapComplete/assets/1010226/d14c0179-aa0e-43fc-9540-ebfdb482577d)
