### ISSUE TITLE
Studio: how to disable Adding Data?

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1924]
I have  `"enableAddNewPoints": false` in my Studio theme but I still see the "Add object" button and "Zoom in to add object" notice.

Example: https://mapcomplete.org/theme.html?z=17.6&lat=52.47748441461101&lon=13.440496252114144&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json#

<details><summary>Theme 11881 JSON</summary>
<p>

```
{
  "id": "berlin_emergency_water_pumps",
  "startLat": 50.8465573,
  "startLon": 4.351697,
  "startZoom": 16,
  "title": {
    "en": "Berlin Water Wells",
    "de": "Berliner Pumpen"
  },
  "description": {
    "en": "This map shows the location and operational state of berlin water wells (pumps).<br /> Please sende feedback to <a href='mailto:alex@osm-berlin.org'>alex@osm-berlin.org</a>. You can use this map to update the operational state of each pump and add/update a check date.",
    "de": "Die Karte zeigt die Funktionsfähigkeit und Position der Berliner Straßenbrunnen.<br />Feedback gerne an <a href='mailto:alex@osm-berlin.org'>alex@osm-berlin.org</a>.<br /><ul><li>Die Icons zeigen den Typ des Brunnen im Scherenschnitt.<li>Das Zusatz-Icon zeigt den Funktionsstatus (Funktionstüchtig, Defekt, Abgeschlossen, Unbekannt)<li>Der Text zeigt das Datum der letzten Funktionsprüfung bzw. den Hinweis, wenn diese durchgeführt werden sollte.</ul>"
  },
  "icon": "./assets/themes/drinking_water/logo.svg",
  "layers": [
    "https://studio.mapcomplete.org/11881/layers/berlin_emergency_water_pump_layer_v2/berlin_emergency_water_pump_layer_v2.json"
  ],
  "enableUserBadge": true,
  "enableShareScreen": true,
  "enableMoreQuests": false,
  "enableLayers": false,
  "enableSearch": true,
  "enableAddNewPoints": false,
  "enableGeolocation": true,
  "enableBackgroundLayerSelection": true,
  "enableShowAllQuestions": true,
  "enableDownload": true,
  "enablePdfDownload": true,
  "enableNoteImports": false,
  "enableTerrain": false
}
```

</p>
</details>

**Comment by tordans** [comment]
Maybe the way to do is different and I have to remove the Preset to remove the button?

However, what is `enableAddNewPoints": false` used for in this case?

<img width="1203" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/193fe0e0-139e-4601-a3fd-2ed83567f0fd">

**Comment by pietervdvn** [comment]
This feature switch is mostly meant to be used either as query parameter (e.g. in an iframe where adding new points must be disabled) or to be used when a theme uses several layers which have a preset. In either case, it is seldomly used.

**Comment by pietervdvn** [comment]
I've re-enabled it.
