### ISSUE TITLE
Studio: Update help text on presets

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1927]
The info text on the presets sound like it still described the previous UI and not the one where there is an explicit button to add presets

> Presets for this layer. A preset shows up when clicking the map on a without data (or when right-clicking/long-pressing); it will prompt the user to add a new point. The most important aspect are the tags, which define which tags the new point will have; The title is shown in the dialog, along with the first sentence of the description. Upon confirmation, the full description is shown beneath the buttons - perfect to add pictures and examples. Note: the icon of the preset is determined automatically based on the tags and the icon above. Don't worry about that! NB: if no presets are defined, the popup to add new points doesn't show up at all

- [x] "clicking the map"
- [x] "title" is gone?
- [x] The text tries to draw the UI so users know which shows up where. But that is super complex to read. It would be a lot easier to have a link to a screenshot that highlights the areas in question with the property name.
- [x] In https://mapcomplete.org/theme.html?z=17.6&lat=52.47748441461101&lon=13.440496252114144&userlayout=https%3A%2F%2Fstudio.mapcomplete.org%2F11881%2Fthemes%2Fberlin_emergency_water_pumps%2Fberlin_emergency_water_pumps.json# I have a broken image when adding a feature and I think that might be because there is no image defined in my theme? In this case the "Note: the icon of the preset is determined automatically based on the tags and the icon above. Don't worry about that! " is not true anymore… I would have to worry about it.

<img width="1205" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/8f0c5f36-d908-45f5-8619-52a2c1c3d8d3">

**Comment by pietervdvn** [comment]
> I have a broken image when adding a feature

This broken image is an iconBadge. You specified for the icon badges that `... {if: "status=", then: "https://tordans.github.io/.../questionMark.svg}, ...` but a bug prevented this from loading correctly. As, in a preset, `status` _will_ be unknown, it _did_ attempt to load this image and this bug acted up. 9827f07433787370c9238e324bff3c5381af8fba should have fixed _that_ issue.

**Comment by pietervdvn** [comment]
> The text tries to draw the UI so users know which shows up where. But that is super complex to read. It would be a lot easier to have a link to a screenshot that highlights the areas in question with the property name.

I have added a screen recording video instead.

**Comment by tordans** [comment]
> > I have a broken image when adding a feature
> 
> This broken image is an iconBadge. You specified for the icon badges that `... {if: "status=", then: "https://tordans.github.io/.../questionMark.svg}, ...` but a bug prevented this from loading correctly. As, in a preset, `status` _will_ be unknown, it _did_ attempt to load this image and this bug acted up. [9827f07](https://github.com/pietervdvn/MapComplete/commit/9827f07433787370c9238e324bff3c5381af8fba) should have fixed _that_ issue.

@pietervdvn I don't quite get where to put this…
The version below in "Editing layer `berlin_emergency_water_pump_layer_v2`" shows errors for the "if" in the "Configuration file" UI.

```
      "marker": [
        {
          "icon": "circle",
          "color": "#6BC4F7"
        },
        {
          "icon": {"if": "status=", "then": "https://tordans.github.io/MapComplete-ThemeHelper/OSM-Berlin-Themes/man_made-walter_well-status-checker/icons/pumpe_{pump:style}.png#.svg"},
          "color": "#6BC4F7"
        }
      ],
```
