### ISSUE TITLE
Property `enableImproveAccuraccy` is not allowed

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1928]
I created new theme but the UI warns me about this property `enableImproveAccuraccy`. I don't know what to do with this and it feels bad to have errors like that in the Configuration file UI.

```
  "allowMove": {
    "enableRelocation": false,
    "enableImproveAccuraccy": true
  },
```

<img width="472" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/2c00a693-3abe-4c3f-a924-a1ecb83a6e22">

**Comment by pietervdvn** [comment]
You made a typo. `accuracy` is written with a single `c` (for the last one)

**Comment by tordans** [comment]
@pietervdvn I cannot remember writing this myself. Is it possible that I copied it from a theme. But given there are a few occurrences of the typo in this codebase https://github.com/search?q=repo%3Apietervdvn%2FMapComplete%20enableImproveAccuraccy&type=code maybe something else is going on? (Or maybe I copied it from there…)

I wil reopen to at least remove the typo from the repo.

**Comment by pietervdvn** [comment]
Seems like I'm the one who often made this typo ;)

I have a theme linting script lying around; I've used that to correct this typo and I've added an error message for it so that this cannot happen in the future anymore.
