### ISSUE TITLE
Different styling on the map depending on completeness of the object

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#193]
I am looking at the tree layer. There are a lot of trees in OSM in Berlin.
Right now, I need to click every one of them to see the completeness. Same for the amenity=bicycle_parking data.

Ideally, the app would style the map icons differently, depending on the completeness of the object. IMO two styles are sufficient “not complete”, “complete”.

To make this work, however, wee need https://github.com/pietervdvn/MapComplete/issues/192

**Comment by pietervdvn** [comment]
First of all, this ties in with the question what MapComplete is in the first place: a map viewer or map editor.
Second, I do think that this should be dependent on the theme if this is wanted/needed.

However, this might be useful to add as metatagging. Even then, there are some issues: we can count the number of unanswered questions, but these might drop irregularly (e.g. if one answer enables more questions. - e.g. if there is a diaper changing table in a toilet, this enables questions where the diaper changing table is enabled). In any case, it depends on #287

**Comment by pietervdvn** [comment]
As this issue:

- has many technical difficulties
- only fits the vision of MapComplete half-heartedly
- won't add much value
- is stale for two years

I'm gonna close it
