### ISSUE TITLE
Studio: "Bug: Region received empty list as configuration" – What should I do?

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1932]
I see this message
> Bug: Region received empty list as configuration
> <img width="1363" alt="image" src="https://github.com/pietervdvn/MapComplete/assets/111561/8e789b9b-d461-42a6-8a2b-641ea3ef1231">

Code: https://github.com/search?q=repo%3Apietervdvn%2FMapComplete%20Region%20received%20empty%20list%20as%20configuration&type=code

The question is: What does it mean? What should I do?

**Comment by pietervdvn** [comment]
The popup you screenshotted, is a *read-only* title view. However, this reuses the code for the read- and writable tagrenderings. The popup tries to render the freeform-section, but it is not set and gives this error.
