### ISSUE TITLE
Studio: Some questions are not persisted

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#1933]
I have the advanced options active.

I edit the question metacondition and cssclasses because they are open when I open the Tab and I want them solved/gone.
Then I change the tab and back and those questions are there again.
Other questions create a network event, those questions don't.

**Comment by pietervdvn** [comment]
Hi,

Your transfer expired. Normally, screencasts can be uploaded directly to an issue.

**Comment by thibaultmol** [comment]
(if the video file doesn't fit. if you have ffmpeg installed you can auto size your video so it fits the max file size using
`ffmpeg -i input.mp4 -fs 10M -codec:v libx264 -preset fast output.mp4`)

**Comment by pietervdvn** [comment]
The JSON-format is defined in `src/Models/ThemeConfig/Json/*Json.ts` as various `interface`-entities.

The **docstrings** on every field are structured, with e.g. `question: `, `inline: `,  `group: `, ... These are converted into TagRenderings which are rendered in the studio to build the JSON.

In the mentioned cases, `ifunset` is missing in those docstrings. Hence, not setting a value will always popup the question.
