### ISSUE TITLE
When osm object gets created: answers get cleared

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1936]
Steps to repro:
- Create an object in mapcomplete, doesn't matter what.
- Quickly click on any answer to a question but don't submit yet.
When Mapcomplete then gets the info back from osm that the object has been created; it will clear all answers given.

Also has been a thing for a while, easy repro. Just never made an issue about it it seems

https://github.com/pietervdvn/MapComplete/assets/1010226/c7485c5d-eae8-44b6-ac82-aca632ef9d49

**Comment by pietervdvn** [comment]
Yes, I know...

There is also another situation where this happens:

- when you open an object, the object data is downloaded from the API to check for updates. If you were filling out an answer, the answer might get flushef
- when you add pictures, those changes are uploaded immedietaly as well, so filling out an answer while uploading often eats the changes too

Apr 29, 2024 11:00:37 Thibault Molleman ***@***.***>:

**Comment by pietervdvn** [comment]
Same root cause as #1935

**Comment by pietervdvn** [comment]
Just tested, fixed together with #1935

**Comment by thibaultmol** [comment]
Awesome, thx!
