### ISSUE TITLE
Tailwind: Use the same button style 

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#194]
I propose we create a css-styles-set using @apply and Tailwind to create a .btn class that we use for all button like buttons in the app.

First thoughts are: The btn-class handles the default color and hover styles. And additional utility classes handle the padding. We will probably need additional btn-large-Styles for the bigger buttons but maybe we can utility classes here as well.

Does this sound like something you would consider as a PR?

**Comment by pietervdvn** [comment]
YES! I was thinking about the same.

We can even use some var(--magic) in it, to allow the buttons to be coloured depending on the theme.

**Comment by tordans** [comment]
About the var(--magic): I opted to use the tailwind color classes for now. I still hope we find a way to reconfigure those for each theme, which would make it a lot easier to design based on the existing Tailwind color utils.

**Comment by pietervdvn** [comment]
Yeah, I agree - for now we should get it working first

**Comment by pietervdvn** [comment]
It seems like the current style has evolved and superseded this issue.
