### ISSUE TITLE
Certain questions by default answer 0

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1943]
I think this might be related to (it started happening after this change)
https://github.com/pietervdvn/MapComplete/commit/d488f8c9b2e295b7879d5dcee03f242139caed4e

I noticed all technical questions like voltage and amperage being set to 0 without me having touched them so far.
![Screenshot 2024-05-05 at 21-08-18 Charging stations Charging station](https://github.com/pietervdvn/MapComplete/assets/1010226/a26d1abe-dd68-4466-80f5-0e6b44a94fed)

https://mapcomplete.org/charging_stations.html?z=16.4&lat=52.087417500000555&lon=5.669479900000397#node/11159305073

**Comment by pietervdvn** [comment]
The parsing behaviour of text fields with a 'unit' has indeed changed

**Comment by pietervdvn** [comment]
Fixed in 12fc6d7d9d25cab41bfbdf23aa2e1818421908d8 (which mentions a wrong issue number)
