### ISSUE TITLE
Add PMD as option for the waste theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1944]
Currently it's not actually possible to map PMD (as we have in NL and BE) properly in mapcomplete.
https://wiki.openstreetmap.org/wiki/Key:recycling:pmd

consider rendering it in such a way so that it makes sense for people that don't know what PMD is

**Comment by thibaultmol** [comment]
Something seems wrong with your commit about this @RobinLinde 
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/7aaf2fb3-9309-4d97-b42f-9ed13b995dc3)

**Comment by pietervdvn** [comment]
Oh, right, all the translations moved around again

**Comment by RobinLinde** [comment]
Whoops, forgot to actually add the updated translations to that commit...

**Comment by pietervdvn** [comment]
a68b79fe7cadcccce7f9fc032dd729e5e023fd6e
I've moved the mapping to the bottom for now, will update translations and move up then
