### ISSUE TITLE
truncated city name depending on zoom level on map

### ISSUE THREAD

**Issue by laloutre87** [pietervdvn/MapComplete#1946]
I was on the page https://mapcomplete.org/cafes_and_pubs.html?z=8.7&lat=46.50507186825013&lon=0.41305714811585403 and i noticed that the city name wasn't the same depending on the zoom level. "Poitier" without an "s" before zooming, then the correct name when zooming ( attached screenshots) .  I'm not sure if this bug is linked to your project. 

![Screenshot_2024-05-10-09-43-22-950_org mozilla firefox](https://github.com/pietervdvn/MapComplete/assets/2885740/2a86805d-8639-4fdc-ac3f-fedb0081be23)
![Screenshot_2024-05-10-09-43-31-528_org mozilla firefox](https://github.com/pietervdvn/MapComplete/assets/2885740/ebcbdc06-7be4-45f4-a20f-0bd13988828f)

**Comment by pietervdvn** [comment]
Reproducible on the protomaps homepage: 
![image](https://github.com/pietervdvn/MapComplete/assets/1466478/169fc058-135d-4926-b3ba-3ec31665c132)
https://protomaps.com/

**Comment by pietervdvn** [comment]
This is an issue with protomaps, I've forwarded it to them; there is nothing I can do about this for now - so I'm gonna close the issue here.
