### ISSUE TITLE
Add dogs=outside to Pub & Cafes theme

### ISSUE THREAD

**Issue by Mannivu** [pietervdvn/MapComplete#1947]
The answer for dogs allowance is missing a [dog=outside](https://wiki.openstreetmap.org/wiki/Tag:dog=outside) answer.

**Comment by pietervdvn** [comment]
Hi, would you perhaps be willing to add this yourself here? https://github.com/pietervdvn/MapComplete/blob/80d4bf0ccfbdf060f014a05c402f99bec7ff3624/assets/layers/questions/questions.json#L622

**Comment by Mannivu** [comment]
I've added a PR #1948 (I've also uploaded a possible icon, feel free to discard if it's too ugly or not useful).

**Comment by pietervdvn** [comment]
Fixed in #1948
