### ISSUE TITLE
Style: Railway building shown with railway as outline

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1953]
https://mapcomplete.org/atm.html?z=18.3&lat=51.98453968171219&lon=5.904149992165571

OSM: https://www.openstreetmap.org/way/267216510

![image](https://github.com/pietervdvn/MapComplete/assets/67521919/c3b6704a-4d76-4ccd-bbcb-d03985f03003)

Instance(s): MapComplete 0.42.4, 0.42.5-dev
Browser(s): Chrome 124.0.6367.202, 124.0.6367.208
OS: Windows 10
Background: Protomaps Sunny

**Comment by pietervdvn** [comment]
Fixed in upstream
