### ISSUE TITLE
Tailwind: Change language-switcher-label to use translation system

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#196]
The label is hard coded ATM.

![image](https://user-images.githubusercontent.com/111561/105640414-34d1ff80-5e7e-11eb-8196-172f4a382d0f.png)

See also https://github.com/pietervdvn/MapComplete/pull/183/commits/d9040db12ae8cea7e6174e768c96a9710e3ca1ae

**Comment by pietervdvn** [comment]
I do think that this is either fixed or not relevant anymore - in either case, the label (in the welcome message) gets translated now.
