### ISSUE TITLE
Clocks: Add direct wall support option

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#1962]
Suggestion: Allow users to specify whether clock is located on wall or on a horizontal mount extending from the wall.

[`Key:support`](https://wiki.openstreetmap.org/wiki/Key:support)
- `support=wall_mounted` => mounted on wall usually with horizontal bar, at 90 degree angle with road, so clock face is visible along the road. (shops, train stations); could optionally be snapped to building (part) wall.
- `support=wall` => mounted directly on wall, so clock face is visible across the road. (clock tower, shopping mall, train stations); should be snapped to building (part) wall if possible.

This distinction is also useful for surveillance cameras, though there it can usually be derived from the camera type.
(unlike -public- street lighting where wall mount is way more common than lamp inside wall)

**Comment by RobinLinde** [comment]
Added in #2229
