### ISSUE TITLE
Not showing "what notes can you use to pay here?" on dev

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1969]
Currently dev (43.0) seems to have a problem on the vending machine theme where it doesn't show the "what notes can you use to pay here?" question. while on the exact same vending machine node it show it on regular stable (42.7)

https://mapcomplete.org/vending_machine.html?z=17&lat=50.824928700002914&lon=4.512982899999656#node/11935098172
![image](https://github.com/pietervdvn/MapComplete/assets/1010226/6b6cc38d-6afd-4179-a9a1-673241b5620e)

https://dev.mapcomplete.org/vending_machine.html?z=17&lat=50.824928700002914&lon=4.512982899999656#node/11935098172

![image](https://github.com/pietervdvn/MapComplete/assets/1010226/93119af6-7809-4552-a945-31de7320eb9f)

**Comment by pietervdvn** [comment]
I did some code simplifications, but reversed a `lon` and `lat` when calculating the country, resulting in no country found. And if no country is found, the currency cannot be determined, which hides the denomation question...

Anyway, fixed now.
