### ISSUE TITLE
Tailwind: Consider using form styles plugin

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#197]
Based on what I read about tailwind, this plugin is needed to style forms with tailwind utility classes. 

https://github.com/pietervdvn/MapComplete/pull/183#issuecomment-764671930
>  …We might want to add the tailwind-forms-plugin for the search input – see last section at https://blog.tailwindcss.com/tailwindcss-v2

**Comment by pietervdvn** [comment]
For now, the basic tailwind seems to be enough to handle the forms.
