### ISSUE TITLE
Add 'outdoor_seating' tag to restaurants

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#1976]
both as a question and as a filtering option.
To indicate if a restaurant has outdoor seating available

https://wiki.openstreetmap.org/wiki/Key:outdoor_seating

https://en.osm.town/@watmildon/112538992859485957

**Comment by RobinLinde** [comment]
Should now be fixed in #2300, just in time for summer (on the southern hemisphere)
