### ISSUE TITLE
Tailwind: Fix click action on answer-label

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#198]
I broke the answer click action in https://github.com/pietervdvn/MapComplete/commit/15a9441b1dfb2be298ab9d002f0c503adae7ce06.

One can click on the whole are (especially right circle), but only the actual text (left circle) will also trigger the JS. At least that is what it looks like looking at the tag-info-area below the answer.

<img width="548" alt="Bildschirmfoto 2021-01-24 um 19 54 21" src="https://user-images.githubusercontent.com/111561/105640526-dce7c880-5e7e-11eb-92f3-a12ae3eebace.png">

See also https://github.com/pietervdvn/MapComplete/pull/183#issuecomment-764334594

**Comment by pietervdvn** [comment]
Excellent find! It is fixed now, this was because the change handler didn't get registered.
