### ISSUE TITLE
[BUG] Uncaught (in promise) TypeError: y.featureSwitches is undefined

### ISSUE THREAD

**Issue by Binnette** [pietervdvn/MapComplete#1985]
I encounter this JS error when I try to edit, via the studio, my own theme "fruit-tree".
Then the screen is completely stuck are the only "exit" is to fully reload the studio web page.

So I am stuck with this bugged "fruit-tree" theme that I created.

- How can I delete this buggy theme ?

Edit : even when I try to edit a predefined theme (not made by me), I get the same error. Maybe the bug does not come from my theme.

- Any of you, can try to create or edit a theme, to see if the bug is reproduced ?

For info, I tried on Firefox. On edge, I have a similur issue : 

TagRenderingEditable.svelte:77  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'featureSwitchIsDebugging')

**Comment by Binnette** [comment]
Wow that was fast 🚀🚀🚀 Thanks a lot @pietervdvn

PS : for people still encountering this bug, make sure to clean browser cache 👍

**Comment by pietervdvn** [comment]
I was about to ask if you still had this issue, but apparently not :)

It is the console log wgich pointed towards the error which made it easy to fix, even though I couldn't reproduce
