### ISSUE TITLE
Tailwind: Fix or remove landscape version

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#199]
I wrote down details as code review comments at https://github.com/pietervdvn/MapComplete/pull/183/commits/6c4b15e33d307e63b4d843a1fd978d5d22df687f#

**Comment by tordans** [comment]
See also: https://github.com/pietervdvn/MapComplete/issues/200#issuecomment-766433516

>For some reason I cannot move the custom media query to the config. Or at least it does not show up in the generated css file.
>
>https://tailwindcss.com/docs/breakpoints#custom-media-queries
>
```
module.exports = {
  purge: [
…
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
…
      screens: {
        'landscape': { 'raw': '(max-height: 600px) and (min-width: 600px)' },
      },
    },
  },
  variants: {
…
  },
  plugins: [],
}
```

**Comment by pietervdvn** [comment]
Tweaked in 1b73f0a43a2e9ce2a5367f0833b811240de9c858, it is acceptable now

**Comment by pietervdvn** [comment]
I removed the landscape view, but made the 'fullscreen'-mode trigger at earlier width (md-breakpoints instead of sm-breakpoint).

I didn't use any of those fancy extensions, as I couldn't get them working...
