### ISSUE TITLE
Deleting features: should this be possible and what is the desired user flow?

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#20]
This should be difficult to do
This should be enabled by the layer

**Comment by pietervdvn** [comment]
This can be done with lifecycle prefixes and is layer-implementable

**Comment by pietervdvn** [comment]
De feature om een POI of een feature te verwijderen - daar twijfel ik zelf ook wat aan. Een tussenoplossing kan zijn om enkel POI te verwijderen als je die eerst zelf hebt gemaakt én niemand anders een aanpassing heeft gemaakt. Wanneer de contributor dan wat vertrouwder is met OSM (aka een aantal changesets heeft, bv. 50 of zo), kunnen we de restrictie erafhalen dat de contributor alle POI kan verwijderen.

Daarnaast zou ik het ook laten afhangen van het thema en soort object of een POI verwijderd kan worden. We kunnen zo bv. zeggen dat fietspompen verwijderd mogen worden, maar fietswinkels niet.

Daarnaast ben ik er een beetje van overtuigd dat zij die technisch vaardig genoeg zijn, genoeg pointers naar OSM hebben om het daar aan te passen.

**Comment by joostschouppe** [comment]
Copied from #221 :
Mapcomplete should probably NOT actually delete objects. But it would be best if in all themes you can mark an object as "this thing really does not belong here".
Suggested solution:

    add a generic "Validate/invalidate " to any popup
    answer options
        This place does not exist anymore > add a tag fixme='A MapComplete user says this place should be deleted'
        This is really something else > prompt "Please describe what's wrong here" and add the text to fixme tag
        I can confirm this place still exists > prompt "When did you verify this place?" to fill in survey:date

It would be best if these changes can be found easily. Suggestions:

    flag them for review (changeset metadata)
    add something to the changeset comment like, "fixme added"

**Comment by pietervdvn** [comment]
Requirements to delete objects:

### Soft deletion

Mark as "disused:feature" and retag them and not show them anymore (this can be done by the theme)

### Hard deletion

Hard deletion must be enabled with a special rendering by the theme, so that themes don't enable them by default.

Before deleting, the following requirements must be met:

1. [ ] The feature must not be part of way (if the feature is a node)
2. [ ] The feature must not be part of a relation
3. [ ] The contributor must have enough experience to remove something, e.g. 50 or 100 changesets - or the contributor must have been the only contributor up till now (to allow them to remove testing points again).
4. Maybe a small changeset message must be asked as well, aka the reason for deletion
5. [ ] Style this and make this user friendly

### Detecting deleted features

At last, features are cached in local storage. If the data is reloaded, we must be able to detect those features that are not returned anymore.

**Comment by pietervdvn** [comment]
This is implemented in a way that should prevent user errors as much as possible
