### ISSUE TITLE
NSI images broken

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2006]
![Screenshot_20240628_130313](https://github.com/pietervdvn/MapComplete/assets/1010226/8a2776c5-be50-4e5e-b6de-1e5c50ac225b)
both dev and stable. was on charging stations theme but prob reprod on any other theme where nsi are loaded

**Comment by pietervdvn** [comment]
This is specific for the charging stations. Seems like I didn't download all of them...
