### ISSUE TITLE
attribution gone on map

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2013]
Both on stable and dev is the map attribution just a (c)
![ResizedImage_2024-07-02_16-33-54_2007](https://github.com/pietervdvn/MapComplete/assets/1010226/8b059d84-0968-4060-a7af-525de8fd39e6)

**Comment by pietervdvn** [comment]
I've hidden them on small screens as they take a lot of space. Clicking/tapping the icon will reveal the 'attribution'-pane.
