### ISSUE TITLE
Error when tapping on bike shop

### ISSUE THREAD

**Issue by Coehill** [pietervdvn/MapComplete#2015]
I opened CycloFix from an Android device and tapped on a bike shop. This error was displayed:

"Something went wrong other error: , Could not fetch this website, probably blocked by them"

![screenshot of error](https://github.com/pietervdvn/MapComplete/assets/13023025/df6106da-bdd1-435c-9fe6-726b81b66e92)

**Comment by thibaultmol** [comment]
What you're seeing is the website scraper trying to extract data from the website of that bike shop. 

Sometimes the scraping server is offline. 

But it should probably be made more clear that's what this is about. (Or maybe just show if the server is offline or something) 

So yeah, UI needs to make it more clear

**Comment by pietervdvn** [comment]
I did update this UI a while back. Hit CTRL+F5 or long-press the refresh button to use the new UI for this:

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/1ad559be-db67-4730-98ca-ce57947acb96)
