### ISSUE TITLE
Carplay iOS

### ISSUE THREAD

**Issue by hschiavo** [pietervdvn/MapComplete#2021]
I would like to use Carplay, via iOS, to map locations with street lamp problems.

The idea is to send an alert with just a gesture, tap (https://photos.app.goo.gl/Avq4tfw6Egd4Ff6U6).

Then, obtain this alert data via the Nominatim API.

**Comment by pietervdvn** [comment]
Hi,

MapComplete is a webapp, not a native app. Afaik, integrating with carplay requires a native iOS app - which is not planned ATM.

Second, I don't think OSM is suited for this kind of data, unless you can provide a tagging scheme.

You're also talking about an 'alert'. Would this be an alert to nearby contributors? There is no infrastructure to do so, and the MapComolete user pool is not big enough to make this useful.

At last, Nominatim is a location search engine - not some alert API. You are not making sense.

So, I'm closing this issue but feel free to elaborate on your idea if you think you can change my mind.
