### ISSUE TITLE
OSM api is getting cors blocked ?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2023]
I'm not sure what's going on, because on one hand it clearly is uploading but on the other hand it's staying stuck on 'uploading changes.
https://www.openstreetmap.org/changeset/153957837

![image](https://github.com/user-attachments/assets/cf8eefb8-acbb-4763-ae84-151d6377b536)
This is happening on the GRB theme on dev in firefox

**Comment by thibaultmol** [comment]
![image](https://github.com/user-attachments/assets/892e2af3-b87e-4c6f-a74d-84541accfb33)

**Comment by danieldegroot2** [comment]
Clearly something is wrong, it is creating unconnected empty nodes (top right)
https://overpass-api.de/achavi/?changeset=153957837

**Comment by danieldegroot2** [comment]
In the problematic way it first deleted, then added some nodes. It may have been trying to fetch the deleted nodes, but I can't say.
https://www.openstreetmap.org/way/1006810927/history

**Comment by thibaultmol** [comment]
Yeah, i noticed it was creating duplicate ways as well, had to delete those manually
https://www.openstreetmap.org/changeset/153958987#map=16/51.0339/3.3920

**Comment by pietervdvn** [comment]
This should have improved by now, but might still appear in other forms.

**Comment by pietervdvn** [comment]
Seems to be fixed/stale, so I'm closing this issue
