### ISSUE TITLE
Mapillary doesn't work atm

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2026]
![image](https://github.com/user-attachments/assets/9acea7f5-c68c-4a56-8ec1-ac68116e8982)

it seems like (maybe if there's a lot of images nearby, the amount of images it's requesting fails out?)

both on dev and stable: https://dev.mapcomplete.org/cyclofix.html?z=20.2&lat=51.09101209999872&lon=4.493265699997892#node/12056129954

**Comment by danieldegroot2** [comment]
Related https://forum.mapillary.com/t/website-keeps-logging-me-out/5451/5
Or, try switching to another browser like Chrome.

**Comment by thibaultmol** [comment]
is it related though? i'm not a vpn and i'm just on the normal isp that most people in Belgium are on. Plus i've never had this issue before... 

![image](https://github.com/user-attachments/assets/39cc9e41-1031-4f73-8ef0-335f3273052b)
same thing happens in firefox incog and chrome (no extensions)

**Comment by thibaultmol** [comment]
my phone (with wifi off) also results in no images found

**Comment by pietervdvn** [comment]
This looks like a timeout to me. There indeed are many pictures - opening the URL directly results in 2000 (!) items, which takes a while to load hitting the timeout.

**Comment by pietervdvn** [comment]
I've reworked this in c20013c5f54c8c74df6a518097210ffee828ec9d, should work now
