### ISSUE TITLE
Show proper error message if a nearby image lookup failed?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2027]
Currently it just doesn't show any error for the end user and just says there are no images nearby

![image](https://github.com/user-attachments/assets/bff50292-72e2-43c8-a6b0-b5eb3d760dd0)

**Comment by pietervdvn** [comment]
I've reworked this in c20013c5f54c8c74df6a518097210ffee828ec9d, should work now
