### ISSUE TITLE
Defibrillators: Explanation in French seems location-specific

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2037]
Defibrillators theme asks for additional explanation in local language, English and **French**. French seems logical for Belgium, but outside Belgium, French is usually not an international language, except in few parts of the world. (let alone as fallback in browsers)

It may be better to base the question on the user's preffered languages, though usually there may only be one -local- preffered language, or the area's languages based on an (external) dependency/list.

In this case I was looking at one in Ireland. Irish Gaelic may be spoken still in some parts, but French is somewhat unlikely, ignoring education being available.

**Comment by pietervdvn** [comment]
True, I've put a condition on this.
