### ISSUE TITLE
Resize mapillary icon

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2043]
Mapillary 360 seems to return large Mapillary icon now.

![image](https://github.com/user-attachments/assets/d3b0b197-e588-4d53-b94d-03cb2b0dee7c)

![image](https://github.com/user-attachments/assets/03337022-0884-41aa-a668-320d29429248)

![image](https://github.com/user-attachments/assets/05da13be-b079-4819-bccc-6235742eb990)

Ex.
Object https://mapcomplete.org/postboxes.html?z=15.3&lat=52.65595465380551&lon=-7.243202150813772#node/11926885617
Image https://www.mapillary.com/app/?focus=photo&pKey=765450735722259

**Comment by danieldegroot2** [comment]
Already fixed in dev.

**Comment by pietervdvn** [comment]
Indeed, I noticed as well and fixed it.
