### ISSUE TITLE
Mobile: Links are unclear

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2049]
For me personally, on mobile (iOS Safari), links in i.e. 'attribution' menu are unclear. They are formatted as regular plaintext (without any formatting -e.g. underline- like on desktop), so the user is unaware they may be clicking on a link, or which parts of the text are links.

I would like to suggest specifying these as links for mobile if not yet.

**Comment by pietervdvn** [comment]
Can you add a screenshot?

**Comment by danieldegroot2** [comment]
Sorry, I can only illustrate it instead of adding a screenshot.
(white fill line used to hide underline, while in reality full letters are still there of course)

mobile (no underline)
![image](https://github.com/user-attachments/assets/4ec82bc1-91ff-4592-90e5-777823cec013)

desktop (has underline); they already don't have the link 'blue' colour or visited 'purple' colour on desktop
![image](https://github.com/user-attachments/assets/e7f5b0a5-b150-4378-8212-703f7c8219a5)

**Comment by danieldegroot2** [comment]
Unrelated, but similar issues
- https://github.com/SAP/ui5-webcomponents/issues/3837#issuecomment-914338841
- https://github.com/postcss/autoprefixer/issues/1473#issuecomment-1243370592

**Comment by pietervdvn** [comment]
Indeed a Webkit-based browser specific issue. Thanks for the linked issues, they contained the answers I needed and it is now fixed. (I didn't test on safari, but on Gnome-web which uses the same underlying web-rendering engine)
