### ISSUE TITLE
Not able to log in at the playgrounds theme

### ISSUE THREAD

**Issue by Thierry1030** [pietervdvn/MapComplete#2052]
Unlike other themes, I cannot log into the playgrounds theme ... I have this issue since at least 1 week ...
Look at the attachment

![playground](https://github.com/user-attachments/assets/142fca19-aa33-4253-9cb8-e0b5dbd64420)

**Comment by pietervdvn** [comment]
Your screenshot shows `mapcomplete.OSM.BE`. I registered `.org` about a year ago; it should automatically redirect. Try `Ctrl+F5`

In any case, this looks like a really old version.
