### ISSUE TITLE
Studio: Layers sometimes parsing incorrectly when editing a previously saved layer for certain icons

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#2055]
I've been compiling a few personal and a couple of built in layers into an overall theme. I have had a few different errors relating the the layer selection.

I am seeing that when I "edit an existing theme" for the main menu and select the existing theme I get a layer prompt to select what layers I want to include. When I look at the configuration file 6 files are already listed. This includes three pre-existing layers and three custom ones. The Configuration file tab for this error displays "No errors, warnings or messages". The icon path is listed as the last line before the final `}`.

In attempting to recreate this error with a new theme I instead got a different error that I had managed to undo by manually deleting most of the config file, deleting the theme and trying again:

Steps to cause the second problem:
1. create new theme, giving it a name and [this icon](https://upload.wikimedia.org/wikipedia/commons/6/6d/France_road_sign_ID29.svg)
2. add default address layer
3. receive errors (detailed below)

>> Can not iterate over layers in theme, it is a "address"
> 
>> The layer with name a was not found as a builtin layer. Perhaps you meant atm, map or bank? For an overview of all available layers, refer to https://github.com/pietervdvn/MapComplete/blob/develop/Docs/BuiltinLayers.md
> 
>> The layer with name d was not found as a builtin layer. Perhaps you meant atm, bbq or food? For an overview of all available layers, refer to https://github.com/pietervdvn/MapComplete/blob/develop/Docs/BuiltinLayers.md
> 
>> The layer with name d was not found as a builtin layer. Perhaps you meant atm, bbq or food? For an overview of all available layers, refer to https://github.com/pietervdvn/MapComplete/blob/develop/Docs/BuiltinLayers.md
> 
>> The layer with name r was not found as a builtin layer. Perhaps you meant atm, bbq or map? For an overview of all available layers, refer to https://github.com/pietervdvn/MapComplete/blob/develop/Docs/BuiltinLayers.md
> [more errors slowly spelling "address" truncated]

A previous time that I had the second error I received more errors because it was spelling out the full web address of the custom layer instead before it was truncated. The version of these errors that display under the Configuration file tab look a bit different, the first two are:

> - error `layers` Can not iterate over layers in theme, it is a "address" `prepare.Fuse(AddContextToTranlationsInLayout, PreparePersonalTheme, WarnForUnsubstitutedLayersInTheme, On(layers, Concat(SubstituteLayer)), SetDefault of socialImage, On(layers, OnEach(Fuse(On(tagRenderings, OnEach(RewriteSpecial)), On(tagRenderings, Pipe(Concat(ExpandRewrite), Pure)), On(tagRenderings, ), On(tagRenderings, OnEach(DetectInline)), AddQuestionBox, AddEditingElements, SetFullNodeDatabase, On(lineRendering, Pipe(OnEach(ExpandRewrite), Pure)), On(pointRendering, ), On(pointRendering, ), SetDefault of titleIcons, AddRatingBadge, AddFavouriteBadges, AutoTitleIcon, On(titleIcons, ), ExpandFilter))), ApplyOverrideAll, On(layers, OnEach(Fuse(On(tagRenderings, OnEach(RewriteSpecial)), On(tagRenderings, Pipe(Concat(ExpandRewrite), Pure)), On(tagRenderings, ), On(tagRenderings, OnEach(DetectInline)), AddQuestionBox, AddEditingElements, SetFullNodeDatabase, On(lineRendering, Pipe(OnEach(ExpandRewrite), Pure)), On(pointRendering, ), On(pointRendering, ), SetDefault of titleIcons, AddRatingBadge, AddFavouriteBadges, AutoTitleIcon, On(titleIcons, ), ExpandFilter))), AddDefaultLayers, AddDependencyLayersToTheme, AddImportLayers, PostvalidateTheme).WarnForUnsubstitutedLayersInTheme`
> error `layers.0` The layer with name a was not found as a builtin layer. Perhaps you meant atm, map or bank? For an overview of all available layers, refer to https://github.com/pietervdvn/MapComplete/blob/develop/Docs/BuiltinLayers.md `prepare.Fuse(AddContextToTranlationsInLayout, PreparePersonalTheme, WarnForUnsubstitutedLayersInTheme, On(layers, Concat(SubstituteLayer)), SetDefault of socialImage, On(layers, OnEach(Fuse(On(tagRenderings, OnEach(RewriteSpecial)), On(tagRenderings, Pipe(Concat(ExpandRewrite), Pure)), On(tagRenderings, ), On(tagRenderings, OnEach(DetectInline)), AddQuestionBox, AddEditingElements, SetFullNodeDatabase, On(lineRendering, Pipe(OnEach(ExpandRewrite), Pure)), On(pointRendering, ), On(pointRendering, ), SetDefault of titleIcons, AddRatingBadge, AddFavouriteBadges, AutoTitleIcon, On(titleIcons, ), ExpandFilter))), ApplyOverrideAll, On(layers, OnEach(Fuse(On(tagRenderings, OnEach(RewriteSpecial)), On(tagRenderings, Pipe(Concat(ExpandRewrite), Pure)), On(tagRenderings, ), On(tagRenderings, OnEach(DetectInline)), AddQuestionBox, AddEditingElements, SetFullNodeDatabase, On(lineRendering, Pipe(OnEach(ExpandRewrite), Pure)), On(pointRendering, ), On(pointRendering, ), SetDefault of titleIcons, AddRatingBadge, AddFavouriteBadges, AutoTitleIcon, On(titleIcons, ), ExpandFilter))), AddDefaultLayers, AddDependencyLayersToTheme, AddImportLayers, PostvalidateTheme).On(layers, Concat(SubstituteLayer)).on[layers].concat.each`

The bug did not appear when I used one of the built in MapComplete icons (bug.svg).

This was tested in Microsoft Edge, switching from Firefox when I experienced the second problem for the first time.

**Comment by pietervdvn** [comment]
2055 Answer

Hi InsertUser,

There seems to be two issues going on here.

The first one, the one you've encountered by trying to recreate the first issue is simply because you've incorrectly added the layers.
In your test, you probably have `"layers": "address"` instead of `"layers": ["address"]` - note the brackets. When I add a layer like this, I get the same symptoms you describe.
As this confused you a lot and did cost you (but also me) a lot of time, I've added an error message for this.

The first issue can be reproduced way easier:

1. Load an existing theme
2. Go to the layer menu and make a change (e.g. change a builtin layer to a different layer)
3. Go to a different tab, e.g. "feature Switches"
4. Go back to the `layers` tab
5. Discover the layers gone :(

However, I've finally figured out what was wrong and fixed it :)
