### ISSUE TITLE
Bookcases: User test violette34

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2059]
Ref (Jul 6, 2024) https://community.openstreetmap.org/t/how-to-create-a-map/115646/6

- User is required to create an account to add a public bookshelf. Alternative websites (mostly non-OSM) do not require this.
-- Anonymous 'mapcomplete-user' profile, note, or contact option could be provided, but it might be worse than current behaviour.

**Comment by pietervdvn** [comment]
See #821
