### ISSUE TITLE
Can't add artwork

### ISSUE THREAD

**Issue by krijnsent** [pietervdvn/MapComplete#206]
First of all: great work! Can i somehow help this project?

I'm trying to add an artwork through the site (personal, switched 3 items on: water points, art work & book_shelves) and click add item and see my browser blinking on this URL:
`https://mapcomplete.osm.be/personal?z=19&lat=52.08085&lon=5.123837#node_-1`
I do see the number next to the star in my profile going up (tried it a couple of times from different browsers on my phone & pc), but everytime it stops here.

**Comment by tordans** [comment]
The way data is saved via MapComplete is, that the app opens a changeset and leaves it open. It then relies on the default-API behaviour to close changesets automatically after an hour. I assume, they are counted only after they are closed(?)

See also https://github.com/pietervdvn/MapComplete#uploading-changes

**Comment by pietervdvn** [comment]
If the id stays -1, somehing goes wrong. Is your internet stable? Is there an error in the console visible?

**Comment by krijnsent** [comment]
![image](https://user-images.githubusercontent.com/21982451/106623645-20c08900-6575-11eb-8f6f-12bcaba40e29.png)

Which leads to:

![image](https://user-images.githubusercontent.com/21982451/106623798-4483cf00-6575-11eb-94e9-be0bd8590960.png)

**Comment by pietervdvn** [comment]
Hey,

I'm back at my computer, so I could do some decent testing now.

Adding a point is indeed flaky; furthermore it seems like the link doesn't update but the addition does actually go through. Closing and reopening the popup might fix the link though.

I'll investigate later when I have some more time.

**Comment by krijnsent** [comment]
Just did a check: I can add e.g. add a bookcase through the https://mapcomplete.osm.be/bookcases page, that seems to work fine, so it looks like the issue is only in the personal part.

**Comment by pietervdvn** [comment]
Hey @krijnsent : I did publish a new version - would you mind testing if the bug still exists?

**Comment by krijnsent** [comment]
Just did a small test, that seemed to okay. Will test a bit more in 2 days and close the issue when they are okay too. ( added https://www.openstreetmap.org/node/8524726674 )

**Comment by pietervdvn** [comment]
Yeah, the code base saw quite some changes in the past month - especially in changeset handling, so it is very well possible the bug has gone away. Or it might still be there...

I'm gonna close the issue for now, if it reappears, please do reopen this issue.
