### ISSUE TITLE
UI: Close button overlaps disable all button in Chromium-based browsers

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2067]
Ref https://github.com/pietervdvn/MapComplete/commit/09f531d30885105ab45505c119d10b4be913302e

The close button partially overlaps the 'Disable all filters' button in this position.
Happens regardless of zoom or browser.

These buttons should be moved in front of the Close button and some space added in between.

Ex. https://dev.mapcomplete.org/waste.html?z=16.7&lat=52.65095007066202&lon=-7.251758841745186#filters

![image](https://github.com/user-attachments/assets/06133bac-8f1f-42cf-b8b0-cff926d3a776)
Chrome, Edge

![image](https://github.com/user-attachments/assets/0fc918a0-024d-4223-acd1-6ca494f02e2b)
Firefox

Instance: v0.44.13, 0.44.14-dev
Browser: Chrome 127.0.6533.89, Edge 127.0.2651.86, but not on Firefox 128.0.2 (see above)
OS: Windows 10
Note, high-dpp screen.

Also, not iOS Safari on mobile (buttons seem properly wrapped into a second row inside the header)

**Comment by pietervdvn** [comment]
This got fixed on dev in the meantime, but might still be visible on master
