### ISSUE TITLE
[Feature request] Studio: allow icons to align to draw direction of way

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#2072]
Certain features that might be rendered have an implicit direction to them recorded as part of the way they belong to. e.g. oneway streets where arrows may point in the direction of travel or [locks on canals][1] where the gates "point" upstream. 

It would be good if it were possible for an icon that shows on the centroid of a way to orient itself to the direction of the way it is generated for. At present it appears that the rotation field under "rendering on the map" only allows fixed values or calculation based on existing tags. 

Would be possible to allow some sort of standard text string that can be used to inherit the draw direction of the way as an input to the rotation options for the displayed icon?

An additional thing that might be useful is for tags on nodes to be able to rotate according to [forward backward left and right][2] tags that refer to the direction of their parent way. This could be used for example to show the direction of a `traffic_sign` or the correct orientation for a [`bus_bay`][3] on a [`public_transport=stop_position`][4].

[1]: https://wiki.openstreetmap.org/wiki/Key:lock
[2]: https://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right
[3]: https://wiki.openstreetmap.org/wiki/Key:bus_bay
[4]: https://wiki.openstreetmap.org/wiki/Tag:public_transport%3Dstop_position

**Comment by pietervdvn** [comment]
Hi,

You can use [_direction:centerpoint](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/CalculatedTags.md#_directioncenterpoint) for this, it is meant to be used in the rotation field.

The rotation field is a CSS-property, so one can use e.g. `calc( {_direction:centerpoint} - 90 )`

**Comment by pietervdvn** [comment]
Example use:

![image](https://github.com/user-attachments/assets/fca04d70-c916-464f-b952-2674eb684f9f)
![image](https://github.com/user-attachments/assets/6b9a0937-c0c7-42b4-928d-a61f8cb69e5e)

**Comment by InsertUser** [comment]
Oh, neat.

In that case I guess my feature request is: please add a mention that metatags are supported in the help text for rotation.

**Comment by pietervdvn** [comment]
I have added common rotations as options for 'rotation' and opened  and

![image](https://github.com/user-attachments/assets/89273757-6397-416a-bb2c-aad24952ea8d)

Furthermore, the introduction for 'pointrendering' now also mentions that the calculated tags can be used as well.

**Comment by pietervdvn** [comment]
> An additional thing that might be useful is for tags on nodes to be able to rotate according to [forward backward left and right](https://wiki.openstreetmap.org/wiki/Forward_%26_backward,_left_%26_right) tags

While this is pretty useful, it is also pretty hard. For starters, MapComplete might not have downloaded the parent way (esp when downloaded from the cache server or from overpass). Second, a node might have multiple parent ways. If you have a compelling use case, feel free to bother me again for this, but there are currently some other features I'd like to create which will increase useability more.
