### ISSUE TITLE
Vending machine documentation has overpass query which excludes many

### ISSUE THREAD

**Issue by J-Arx** [pietervdvn/MapComplete#2075]
In [the documentation for thematic map vending machines](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Themes/vending_machine.md) under "b[asic tags for this layer](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Layers/vending_machine.md#basic-tags-for-this-layer)" there is an esclamtion mark which seems confusing and contradictory for me as this excludes many vending machines. The esclamation mark got there probably due to autogeneration of that documentation from [assets/layers/vending_machine/vending_machine.json](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/vending_machine/vending_machine.json).

**Comment by pietervdvn** [comment]
The documentation is auto-generated based on the definition files, so those cannot be human errors.

And yes, some vending machines are excluded (such as parking ticket vending machines) because they clutter the map and are not what most people search for in such a theme.
