### ISSUE TITLE
Broken link to theme documentation for custom themes

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#2076]
When using a custom theme a broken link to the theme documentation is generated and presented to users seeking more information. 

To access the link:
1. Open a custom theme generated via the studio and dismiss the initial introductory overlay
2. Click on the hamburger menu. 
3. Under the "About MapComplete" tab a link will be displayed: "Open the documentation for thematic map {theme name}"
4. Clicking the link will attempt to take the user to: `https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Themes/{full URL of loaded JSON}.md` which does not exist and results in a github 404 error.

I think this link should be suppressed for custom themes. Alternately an option could be provided in the studio editor to link to e.g. an OpenStreetMap wiki page used to document the custom theme.

**Comment by pietervdvn** [comment]
Thanks for pointing this out!

> Alternately an option could be provided in the studio editor to link to e.g. an OpenStreetMap wiki page used to document the custom theme.

This is quite hard. Sometimes, the info is on `wiki.osm.org/wiki/Key:<key>`, othertimes on `Tag:key=value`. And often, the theme is broader then a single tag.

**Comment by InsertUser** [comment]
When I mentioned a wiki page I was thinking about the way that JOSM has [many](https://wiki.openstreetmap.org/wiki/JOSM/Plugins) pages under `https://wiki.openstreetmap.org/wiki/JOSM/Plugins/{plugin name}` or how some people add little bits of personal mapping information under their user space. 

So if there was something that could benefit from documentation e.g. if brought in external data it would then be able to have a place to document it either on the wiki under `wiki.osm.org/wiki/MapComplete/custom/{theme}` or the Github project where the json was hosted.
