### ISSUE TITLE
permanent link to draft themes

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#208]
You can create a permalink to a personal theme with the current theme generator
But that link will always refer to that specific version - once the link is out there, you can't fix anything anymore
This was solved by hosting the json on the OSM wiki, which is a crazy solution. And it broke :)
A simple solution could be to allow the user to refer MapComplete to a random URL with a pure JSON file, for example https://raw.githubusercontent.com/osmbe/play/master/mapcomplete/vaccination.json
That way, people can host the theme on their own github page / basement fileserver / whatever

**Comment by pietervdvn** [comment]
Please test: https://pietervdvn.github.io/Staging/?userlayout=https%3A%2F%2Fraw.githubusercontent.com%2Fosmbe%2Fplay%2Fmaster%2Fmapcomplete%2Fvaccination.json
