### ISSUE TITLE
low contrast on cycle paths on protomaps style

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2085]
![image](https://github.com/user-attachments/assets/846a9741-c9f3-44b0-9108-42ec4d1e6236)

regular osm carto:
![image](https://github.com/user-attachments/assets/0939c412-4c6d-4726-a3b3-45f847108f48)

https://mapcomplete.org/kerbs_and_crossings.html?z=18.5&lat=50.996941657021864&lon=3.3080771509539773#node/11400056919

(ignore how the cycleways and such aren't connected xd)

**Comment by pietervdvn** [comment]
![image](https://github.com/user-attachments/assets/d6a92e9b-0037-4fcb-b6fc-e8addb3d07e6)
