### ISSUE TITLE
Search: searching for postcode should show nearby postcodes first

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2090]
If i search for '8755' (Ruiselede) when the map has Ruiselede in view or nearby, it should show that first in the search.

https://pietervdvn.github.io/mc/feature/search/cyclofix.html?z=10.7&lat=50.99638986657038&lon=3.362367373869347

but currently it shows global results and doesn't take location in mind
![image](https://github.com/user-attachments/assets/27a8f588-2dfb-49f2-9dc0-7f4dab5850d9)

**Comment by thibaultmol** [comment]
also about search, don't know if it's worth making an issue about, cause i don't know how realistic it is:
but while: 'gent-sint-pieters' and 'gent sint pieters' works. 'gentsintpieters' doesn't... I think that's fine. but just letting you know

**Comment by pietervdvn** [comment]
The actual search content is provided by Komoot. If it doesn't support postal codes, then bother them to include it into search.

**Comment by thibaultmol** [comment]
it does actually support postcodes cause if i do "markt 8755" does work. just only postcode isn't enough.
What is being sent to the komoot api (is there an option to include the current viewport coordinates)? (might be worth mentioning that the search feature is done using Komoot in the readme of the project?)

**Comment by pietervdvn** [comment]
THe viewport coordinates are included already.
It seems that komoot does not support searching for postal codes alone, so this will not be supported.
