### ISSUE TITLE
Search: not showing enough detail in results

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2091]
If you search for 'markt', obv you get a lot of results. but the first result should clarify that it's the Markt in Tielt but it just Markt in West-flanders which could be any of the potential 50+ options xd

![image](https://github.com/user-attachments/assets/5dc190a6-7925-432c-a816-40e6e4fd1227)
(on this screenshot it's not the first result because i forgot where exactly my viewport was when it showed up first, but you still see two results that don't specify enough)

**Comment by pietervdvn** [comment]
Included in #2156
