### ISSUE TITLE
Toilets: Don't display access=private

### ISSUE THREAD

**Issue by leonhandreke** [pietervdvn/MapComplete#2094]
Yesterday I found https://www.openstreetmap.org/way/1215028723 using the public toilets map. Turns out it's a toilet that's locked and exclusively for use by bus drivers. It's tagged using access=private. The map on openstreetmap.org displays a slightly transparent toilet sign for this toilet.

**Comment by thibaultmol** [comment]
Hmm, seems like the wiki says that everything tagged as amenity=toilets should be public or customers.
![image](https://github.com/user-attachments/assets/406d00e1-af39-48d5-9e48-a021c6e138bf)


I don't know https://wiki.openstreetmap.org/wiki/Tag:amenity=toilets?uselang=en

**Comment by leonhandreke** [comment]
Ah, so maybe this should be a [building=toilets](https://wiki.openstreetmap.org/wiki/Tag:building%3Dtoilets) then? I'll ask in an appropriate place and then follow up here.

**Comment by leonhandreke** [comment]
I browsed the OSM forums a bit and decided to retag as `building=toilets` https://www.openstreetmap.org/way/1215028723/history/2. Thank you for the quick turnaround and thank you for making this map!
