### ISSUE TITLE
Add bicycle traffic counter to Cyclofix & Bicycle Infrastructure maps

### ISSUE THREAD

**Issue by Coehill** [pietervdvn/MapComplete#2101]
Many cities implement bicycle traffic counters on bike paths and trails.  It is useful to know for bicycle advocacy work.  Please include this in the Cyclofix and Bicycle Infrastructure maps.  The documentation is here:

Tags:
|         Key         |             Value             |
|:-------------------:|:-----------------------------:|
| man_made            | monitoring_station            | 
| monitoring:bicycle  | yes                           |
| name                | name of counted street        |
| start_date          | year since starting counting  |
| support             | pole                          |
| visibility          | street                        |
| website             | URL of online data state      |

Documentation: https://wiki.openstreetmap.org/wiki/Bicycle

**Comment by pietervdvn** [comment]
Hi!

If you want, you can test https://mapcomplete.org/studio and create this layer yourself. Thus makes it easier to pull it in.
