### ISSUE TITLE
how might mapcomplete work with a tool like task manager?

### ISSUE THREAD

**Issue by alibama** [pietervdvn/MapComplete#211]
curious whether there might be a way to connect this tool to something like https://tasks.openstreetmap.us/ so that we could have a management layer alongside this improved user interface?

**Comment by pietervdvn** [comment]
Hey,

One can use the URL-parameters to set a starting location, which could get close. It is also possible to embed MC in an iframe or something similar.
 However, there is no support at the moment for locking, communication nor showing a GPX.

I'm not planning on implementing such a feature; unless there is a good reason to do so (e.g. a bigger project with some funding)
