### ISSUE TITLE
Theme idea: all about dogs

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#212]
- [x] dog parks
- [ ] fence height
- [x] opening hours
- [ ] any object where dogs are NOT allowed (often on paths, parks)
- [ ] dog toilets
- [x] dog excrement waste baskets
- [x] poo bag machines
- [x] vets
- [x] animal shops
- [ ] dog hairdressers

**Comment by Tauvic** [comment]
Great idea, really like it

**Comment by pietervdvn** [comment]
The waste basket themes recently got a question asking if the waste basket dispenses excrement bags.

The easiest would be to simply reuse the layer 'as is' (simply put "waste_baskets" into the `layers`-list).

Next steps could be to add a little icon if a dispenser is available, or to add a filter for them.

**Comment by joostschouppe** [comment]
Well actually... the "dog excrement waste baskets" are purpose-built to collect poo bags -  bot none of them in my area have poo bags! So you need both the waste=dog_excrement as well as the poo-bag-dispensing tag

**Comment by pietervdvn** [comment]
For the vets: I've made an ad-hoc theme for them, it is on the wiki. That could be a separate theme with layer reuse as well.

**Comment by joostschouppe** [comment]
I got a reply! I'll join them for a chat soon. Any interested in joining? 
Perhaps @elgaard, [who is working on a theme](
https://github.com/pietervdvn/MapComplete/pull/764)

**Comment by pietervdvn** [comment]
Theowner of dogvalley also mentions benches to sit on his website somewhere, so these could be mixed in too.

Drinking water and water wells (with water not suited for human consumption) might be useful too

**Comment by pietervdvn** [comment]
Also: dog- a'd cat cafés are not shown right now, we should think about tagging for them and add them.

Cafes are omitted in the current theme too, that should be fixed

**Comment by pietervdvn** [comment]
The new theme has already attracted a few edits by random contributors within the first day :)

**Comment by pietervdvn** [comment]
> I got a reply! I'll join them for a chat soon. Any interested in joining?

I'm gonna pass the first meetings, got a bit too much to do right now

**Comment by fxedel** [comment]
As of the excrement bags: In Germany, we have lots of waste buckets where you can also pull out a new, empty bag. These are mapped as `amenity:vending_machine` with [`vending=excrement_bags`](https://wiki.openstreetmap.org/wiki/Tag:vending%3Dexcrement_bags). It would be really good to include them in the map (I also thought about adding a whole new map for this), since it could be likely that also local authorities would use and maintain that map.

Furthermore, for shops, there is the generic option "add new shop" and the option "dog-friendly shop". Is it possible to drop the first one? Similarly, there should only be pet-specific options for the restaurants.

**Comment by kjonosm** [comment]
Is it worth adding dog-related kennel or breed clubs to the theme? Presumably tagged as [`club=dog`](https://taginfo.openstreetmap.org/search?q=club%3Ddog#tags) in OSM.

https://en.wikipedia.org/wiki/Category:Kennel_clubs
https://en.wikipedia.org/wiki/Breed_club

**Comment by pietervdvn** [comment]
Hi all,

I'm currently issue-pruning and would like to close this - unless there is still some interest and usage. 

Perhaps there is someone who wants to add some layers for this?

**Comment by pietervdvn** [comment]
I'm bundling everything in #1967
