### ISSUE TITLE
Indoor: Add Copy Room

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#2131]
I would like to suggest adding 'Copy Room' as room type to the Indoor theme.
| name | ref | notes |
| - | - | - |
| Copy Room | [`room=printer`](https://taginfo.openstreetmap.org/tags/room=printer#overview) | [in use] A [(photo)copy(ing) room](https://en.wiktionary.org/wiki/copy_room) or 'printer room' is a room with a [(photo)copy machine and/or printer and/or scanner and/or similar device](https://wiki.openstreetmap.org/wiki/Tag:amenity=printer), sometimes with computer(s) intended mainly for this purpose. It may also provide various (white) paper, cutting and perforation machine, scissors, stamps, stickers, envelopes. could host 'file room' (on its own I suppose it is tagged as `room=storage`).

Found mainly in educational buildings, sometimes in library buildings but there printers are more often part of the library room.

Some do not have a door, so it is understandable if it is considered indoor area / corridor part, though `door=no` exists.

---

(sidenote: pieter can click the edit button on this post to see some other examples of room types. however, most are minor/ambiguous so I won't propose them in this issue.)

**Comment by pietervdvn** [comment]
Hey Daniel,

If you feel adventurous, you can add this into the JSON file directly here: https://github.com/pietervdvn/MapComplete/blob/5c641f071a3a0bdd294dc77570bb9069181ace06/assets/layers/indoors/indoors.json#L318

Adding only 'en' as language is enough
