### ISSUE TITLE
Problem with background selector on chrome

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2176]
It seems like if you try to load the background selector on chrome it doesn't render properly. tested on dev:
url: https://dev.mapcomplete.org/waste.html?z=16.9&lat=51.070610033811676&lon=4.539489187900813&background=DV_OrthoPhoto#background

![image](https://github.com/user-attachments/assets/f38d415e-1d59-407d-9146-58b74f04a714)

**Comment by pietervdvn** [comment]
Your CSS didn't properly load. Hit Ctrl+F5 and the problems'll disappear.

(Weirdly, I did get the same symptoms on my computer)
