### ISSUE TITLE
Background selector doesn't change when you choose dropdown item

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2177]
On dev both on firefox desktop and fennec I noticed that you can't switched background layer. nothing happens when you click anther dropdown menu item

https://github.com/user-attachments/assets/86ce0f2f-0f45-468d-99d0-cd4bbb061c53

**Comment by pietervdvn** [comment]
This was fixed a while back, but it seems like I didn't properly mention the issue number in the commit.
