### ISSUE TITLE
IMGUR api token expired

### ISSUE THREAD

**Issue by davidpnewton** [pietervdvn/MapComplete#2178]
Upon trying to upload an image using Mapcomplete the following is seen:

![image](https://github.com/user-attachments/assets/b931dc6b-8075-4413-a7b4-6039d6d4f5ec)

This occurs in both Android and Windows versions of Chrome and occurs both on the live and dev Mapcomplete instances. The development tools of Chrome in Windows shows the following:

![image](https://github.com/user-attachments/assets/53c0d227-1083-4641-ab05-4e17f96016f5)

This behaviour started showing up yesterday.

**Comment by pietervdvn** [comment]
Seems like imgur finally blocked us - after four years of using it without any issue.

For now, I've simply disabled the image upload capabilities.

**Comment by pietervdvn** [comment]
Time to implement #1451

**Comment by thibaultmol** [comment]
The move to Panoramax has pretty much happened (although there clearly are some bugs). But considering imgur support isn't coming back normally, I guess we can close this issue
![image](https://github.com/user-attachments/assets/0283be3a-632e-4b28-8968-40e30c8535ad)

**Comment by pietervdvn** [comment]
Correct. This issue acted more as to inform people coming here
