### ISSUE TITLE
Test replacing TailwindCss with WindiCss

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#218]
https://windicss.netlify.app/guide/migration.html#tailwind-config-js

￼ it looks like this is a smart replacement for tailwindCss. It has the same feature but uses a different process to generate the CSS file. It sounds like this would work around the issue of postCSS￼ by not using it.

**Comment by pietervdvn** [comment]
Right now, it seems like pruning works and a switch to WindiCSS is not needed (and quite a bit of work)

I'm gonna close this issue as stale/unneeded.
