### ISSUE TITLE
diet:vegan=only and diet:vegetarian=only not rendered on friet shops

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2191]
Credit to luna for finding this one:

If you are using the fries shop theme and look at a cuisine=friture that has either of these tags, mapcomplete won't render them in the ui:

https://mapcomplete.org/fritures.html?z=16.9&lat=50.877139695550966&lon=4.700422947292395#node/4349764322

fyi: maybe put cuisine question more at the top? if you see non-friet places on the map, they'll have their actual cuisine tag barely visible

**Comment by thibaultmol** [comment]
From Luna:

This is how it looks now

![image](https://github.com/user-attachments/assets/f46125b0-9e1f-410e-ab5a-26825846a81c)

It shows that veggie and vegan options are available, but this is tagged with `only` for both!

It should differentiate between `yes` and `only` and it doesn't render on the map

**Comment by pietervdvn** [comment]
I've added the badges in f8ef32f123340cb9db0060cdca7f4622cd55c228 and had another look, it should work now
