### ISSUE TITLE
Error in hydrant theme

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2198]
![image](https://github.com/user-attachments/assets/11324349-ca3b-4873-9046-8c5a89727462)

when i went on this page, this error showed up in the console

https://dev.mapcomplete.org/hailhydrant.html?z=16.8&lat=50.89155389376086&lon=4.556349331135266&background=osm#

**Comment by pietervdvn** [comment]
This is a bug in writing settings, should be fixed in 7060f7cf6cac807877efb8babc8586eabfc79351
