### ISSUE TITLE
Fries theme: double answers

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2199]
it seems like some questions have duplicate answers somehow

![image](https://github.com/user-attachments/assets/239d7636-9431-4344-ac08-7b805ac20d28)

Also, there should be separate answer for `=only` but currently saying they're available sets the value to =only which isn't correct. it should be =yes if there there are available. 
![image](https://github.com/user-attachments/assets/3860d0a7-e6a8-4708-893a-61ea048bf3e7)

**Comment by pietervdvn** [comment]
Ah, I forgot te reset the translations

**Comment by pietervdvn** [comment]
Fixed in 6a4166febb5ce386beac8bbb06cd7527b90c6a12
