### ISSUE TITLE
small layout issue

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#220]
POI details ([example](https://mapcomplete.osm.be/campersite?z=17&lat=51.52267&lon=-2.1007#node/4934147421)) have a lot of blank space when the resolution is very high:

![afbeelding](https://user-images.githubusercontent.com/10122639/111283080-04693f00-863f-11eb-8fc5-b2cdfcfc01b8.png)

(I can only make this happen if I zoom out on the page as I am on a low resolution screen)

**Comment by pietervdvn** [comment]
Not relevant anymore wuth the sidetab-layout
