### ISSUE TITLE
Add self service to bike wash

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2203]
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_wash

https://www.vrt.be/vrtnws/nl/2024/10/09/leuven-opent-eerste-bikewash-aan-sporthal-heverlee/

[self_service](https://wiki.openstreetmap.org/wiki/Key:self_service) and maybe some other things as well

**Comment by pietervdvn** [comment]
The difference between "self-service" and "automated" is quite unclear to me

**Comment by thibaultmol** [comment]
automated would be a machine where you just put your bike in and it does the work for you, like this:
![image](https://github.com/user-attachments/assets/b0444c0c-20ee-44d8-8eb2-a17bf65fd4fd)

**Comment by pietervdvn** [comment]
Ah, allright. Is that image under a reusable license?

**Comment by thibaultmol** [comment]
Oh yeah no, just the first one I found on image search.

I did find this one of a manual wash: https://commons.wikimedia.org/wiki/File:Sankt_Gallenkirch-Valiserabahn_lower_station-Bicycle_wash_system-02ASD.jpg
