### ISSUE TITLE
Themes with a non-default background cause a performance issue

### ISSUE THREAD

**Issue by Mannivu** [pietervdvn/MapComplete#2207]
When opening the Hydrant map, there's something wrong: the left panel is open and uses the whole screen, while the map keeps updating in background causing heavy load. This happens both on Desktop and Mobile.
![image](https://github.com/user-attachments/assets/a236f038-75b2-4e1e-8f08-b44f16061fae)

**Comment by thibaultmol** [comment]
I can confirm I have the same problem but I keep forgetting to report it. 

Usually does go away by itself iirc, but it's a bit confusing in the first couple seconds that you open a theme

**Comment by pietervdvn** [comment]
This is specific to themes which have a custom background set and is fallout of #

Because of the performance issue, the menu drawer isn't immediately hidden, causing the symptoms that OP witnessed.
