### ISSUE TITLE
"deleting" objects

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#221]
Mapcomplete should probably NOT actually delete objects. But it would be best if in all themes you can mark an object as "this thing really does not belong here".
Suggested solution:
- add a generic "Validate/invalidate <layer name object>" to any popup
- answer options
    - This place does not exist anymore > add a tag `fixme='A MapComplete user says this place should be deleted'`
    - This is really something else > prompt "Please describe what's wrong here" and add the text to `fixme `tag
    - I can confirm this place still exists > prompt "When did you verify this place?" to fill in `survey:date` 

It would be best if these changes can be found easily. Suggestions:
- flag them for review (changeset metadata)
- add something to the changeset comment like, "fixme added"

**Comment by pietervdvn** [comment]
Also see #20

**Comment by pietervdvn** [comment]
Closing as duplicate
