### ISSUE TITLE
dev is doing weird things with preferences

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2212]
I noticed preferences not working this morning (I had the 'one question at a time' again set. didn't check debug text yet before changing it back)

noticed console on my pc also showing weird things
![image](https://github.com/user-attachments/assets/967d9619-aa0d-42fd-b7fa-6284dbefe080)

0.47.5, those errors don't show up on regular, only on dev

i have the json of my settings, but it's already set correctly there because i changed it maybe?

**Comment by pietervdvn** [comment]
In either case, I recently made some changes to how long (>255 characters) get handled. As such, some cleanup is needed and this might have some bugs. You might have witnessed this cleanup (which might indeed forget some settings).

**Comment by thibaultmol** [comment]
Custom themes are also gone
![Screenshot_20241015-195602](https://github.com/user-attachments/assets/67072eb0-014f-4945-92fc-2a5c1f015925)

**Comment by thibaultmol** [comment]
hmmm, did a hard refresh but still seems like it's struggling in the console

![Screenshot_20241017_080520](https://github.com/user-attachments/assets/c7245404-d961-4d27-8d62-b57416879821)
![Screenshot_20241017_080509](https://github.com/user-attachments/assets/02b4d5c4-2d6a-41a5-bfe2-f32b6fa53938)


even though the hidden themes and such have come back
