### ISSUE TITLE
Wrong license on images uploaded to Panoramax

### ISSUE THREAD

**Issue by RobinLinde** [pietervdvn/MapComplete#2213]
Possibly related to #2212

Seems like the license is defaulting to CC-BY-SA 4.0 despite having it set to CC0

Example image: https://panoramax.mapcomplete.org/#focus=meta&map=17/53.123331/6.603539&pic=015e1e8e-cfdd-4df0-99c4-988a830fe92d&speed=250&xyz=27.00/0.00/30

**Comment by pietervdvn** [comment]
I thought that I dropped the setting for the image license, but apparently not. Most people don't care about the license anyway.

**Comment by thibaultmol** [comment]
* to clarify: Panoramax currently doesn't allow multiple licenses on one instance (atleast not when uploading) so it's not really possible atm
