### ISSUE TITLE
Add info about Matrix chat to contributing doc

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#2239]
On Reddit you recently recommended hoping on Matrix to chat.
I had read the contributing guidelines recently and didn't remember a link to Matrix so double checked and it's not there.
Might be nice to add a line saying if you'd like to talk about something you can join the matrix chat here.
I know there's a link at the top of the readme but if someone isn't looking for matrix specifically they might miss it.

Cheers

**Comment by pietervdvn** [comment]
Indeed, fixed!
