### ISSUE TITLE
Bug: All shops are bicycle shops

### ISSUE THREAD

**Issue by bryceco** [pietervdvn/MapComplete#224]
Many (all?) shops in my neighborhood are presented as bicycle shops. For example a shop=beauty,name=* presents:

This shop is specialized in selling beauty and does bicycle related activities

This bicycle shop is called Enchante Day Spa & Salon

**Comment by pietervdvn** [comment]
This is a nice bug you discovered there! This is an artefact due to mixing the layers from the various themes. I'll look into it later.

**Comment by pietervdvn** [comment]
I've made the selections for 'bicycle shop' quite a bit narrower, so this should not happen anymore.
