### ISSUE TITLE
Strange confirmation dialog in Drinking water dialog (adding new)

### ISSUE THREAD

**Issue by mnalis** [pietervdvn/MapComplete#2249]
On both desktop (firefox) and mobile:

- open `Artwork` theme
- click `Add a new feature`
- choose `Add an artwork`
- confirm `The new POI will have tourism=artwork` / `Add an artwork` (BTW that page has a typo in its title _"Add a an artwork?"_, so you may want to fix that too; but not worth opening the new issue...)
- strange new blank window (with only two icons) appears:
![small_Screenshot 2024-11-12 at 19-52-02 Artwork](https://github.com/user-attachments/assets/6b7238c2-4f0a-40f7-a3ad-fdccf77dc40f)

On mobile I assumed page has failed to load and so I gave up (after few attempted page refreshes), but now on Desktop I tried clicking the checkbox and it seems to allow me to proceed to choosing a position on a map. I canceled the process here, as I don't have real data right now, and don't want to add fake artworks).

I think it used to work normally (i.e. without that strange almost-blank page) few weeks ago, but I cannot 100% guarantee that.

**Comment by mnalis** [comment]
Clicking on existing artwork works without that blank bage, and directly opens questions about artwork just fine. Also,  quick check on other theme like `Drinking water` seems to have same issue too. `ctrl-f5` does not seem to help.

**Comment by pietervdvn** [comment]
Is your 'favourites'-layer enabled?

**Comment by pietervdvn** [comment]
I've changed a few things in the approach there which might result in this behaviour

**Comment by mnalis** [comment]
> Is your 'favourites'-layer enabled?

You mean in `filter data`? Yes, `Favourites` have that box checked there (not that I have any idea what that does yet :smile: - it probably was enabled by default, I don't seem to recall  touching or even seeing that before). Should I try disabling that?

> I've changed a few things in the approach there which might result in this behaviour
> [08e3c63](https://github.com/pietervdvn/MapComplete/commit/08e3c6368aa25adc9e12401c44371f114180be25)

Is that supposed to be pushed to production yet? If so, it didn't work, even after `ctrl-f5`, I could still reproduce the bug on artwork layer.  Then after a few more tries it seemed like it was fixed, but then switched to other layer and reloaded that, and then switched back to artwork the bug was there again. :man_shrugging:

**Comment by pietervdvn** [comment]
Yeah, the caching is quite aggressive. In "settings", there is, under 'debug' a little button to force reload.

**Comment by mnalis** [comment]
> Yeah, the caching is quite aggressive. In "settings", there is, under 'debug' a little button to force reload.

Ok. I've tried that too: opened "artwork" theme, go into settings, clicked on `Clear caches` under `Debugging options`, clicked `ctrl-f5` for good measure. And artwork seems to work fine. But then I switched to "Drinking water" theme, and the bug _still_ pops up there.

Or must I go to `Clear caches` for _**each and every theme**_? Because:
- If not, it seems the bug is still there, but only happens intermittently depending on who-knows-what conditions
- But if so, that would seem awfully inconvenient;  would it be possible to make that debugging button clear *all cached data for all themes*?  Or even better (for the users) would there a possibility that the server force-pushes those fixes when theme is updated automatically (e.g. versioned URLs)?

**Comment by mnalis** [comment]
Unfortunately, I'm still seeing that bug (desktop Debian GNU/Linux Firefox 128.4.0esr) :cry: 

- opened drinking water theme, tried adding new water source, bug is THERE
- did settings / debugging options / clear cache
- did ctrl-F5
- tried adding new water source, NO bug
- opened artwork theme,  tried adding new artwork, NO bug
- opened restaurants, tried adding new restaurant, NO bug
- opened drinking water theme, tried adding new water source, bug is THERE AGAIN

![small_Screenshot 2024-11-28 at 00-07-13 Drinking Water](https://github.com/user-attachments/assets/d3dbe1d1-1abc-4875-9c14-3e0480c64c8f)
