### ISSUE TITLE
Show themes hierarchically

### ISSUE THREAD

**Issue by bryceco** [pietervdvn/MapComplete#225]
![image](https://user-images.githubusercontent.com/279734/111371699-fe7f5800-8656-11eb-95f8-7c71a0e405c6.png)
This page was pretty confusing to me initially. I didn't understand why things were repeated and only some items were selectable. I think you need to use indentation to make the theme/layer relationship more obvious. 

I also think checkboxes/switches would make it more obvious from first glance that these are items that can be enabled/disabled. 

It might also be good for themes to be collapsible so I can easily ignore things of no interest in this very long (and sure to get longer) list. 

Lastly, the mishmash of theme names is confusing: Cyclofix, Open Foo Map, Trees. Are some Open and others not? And they aren't really maps even when they have map in the name. As a newbie do I need to know the difference?

**Comment by pietervdvn** [comment]
Yeah, that is true.

The 'personal theme' was addes somewhat as an afterthought for the hardcorde OSM-contributors who wanted to mix and match layers from themes, but as a result, it is somewhat of a mess sometimes.

The individual themes should stand on their own and are free to use their own styling (also resulting in an inconsistent set of themes).

As a newbie, the personal theme is hidden for this exact reason; it only unlocks after 15 changesets when they know OSM somewhat.

I'll keep this issue open and might implement your suggestions someday, but right now I lack the time to do so.

**Comment by bryceco** [comment]
Okay, I'll refrain from using the "personal" theme (probably should be renamed to something more meaningful) as the basis for my comments for the time being.

**Comment by pietervdvn** [comment]
Yeah, there are still quite some bugs there!

Maybe renaming it would already help. Something like 'mix and match your theme'? If you come up with something, feel free to make changes to [this file](https://github.com/pietervdvn/MapComplete/blob/master/assets/themes/personalLayout/personalLayout.json) and to open a PR.

Also: good thing that you haven't tried out the custom theme generator yet - that thing is filled with bugs...

**Comment by pietervdvn** [comment]
The current panel only shows every available layer and only shows it once - so this should be clearer now.

**Comment by bryceco** [comment]
Looks much better now.
