### ISSUE TITLE
config file editor gives wrong hint for missing tag

### ISSUE THREAD

**Issue by tiptoptom** [pietervdvn/MapComplete#2251]
The hint should be 'test='
![Screenshot from 2024-11-13 11-02-14](https://github.com/user-attachments/assets/32831be9-b7b2-411d-a83d-45fc67c52bff)

https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Tags_format.md#if-key-is-not-present

**Comment by pietervdvn** [comment]
Oopsie...
