### ISSUE TITLE
Split road at an intersection

### ISSUE THREAD

**Issue by Zverik** [pietervdvn/MapComplete#2257]
I'm adding speed limits with MC, and found one thing to improve. Usually limits work from intersection to intersection, regardless of sign placement. If we were to allow splitting there, it would introduce less random nodes near intersections, and make mapping differing limits for different sides of intersections more precise.

UI-wise maybe it should be a checkbox "split at an intersection" that pops up when you in the splitting mode tap close to one. Selected by default.

**Comment by pietervdvn** [comment]
Normally, if a split is within 5 meters of an already existing point, that point will be reused.

I've however improved the UI to make this clearer: 
![image](https://github.com/user-attachments/assets/17287436-ae97-4366-8f4f-7d57d9afaff7)

**Comment by pietervdvn** [comment]
This will live on dev for a while. This is a somewhat bigger change that I'd like to give some time to become mature.
