### ISSUE TITLE
Increase tap area for lines

### ISSUE THREAD

**Issue by Zverik** [pietervdvn/MapComplete#2261]
Having used MapComplete for a day on a bike ride, [fixing speed limits](https://mapcomplete.org/maxspeed.html?z=16.5&lat=59.399616288681614&lon=24.716642702352488) around my area, I had one major issue: selecting a street took me 5-10 taps, sometimes an extra tap adding the street into my favorites (why make this feature even), initiating splitting, or marking the task skipped (would make sense in MapRoulette, but why here?).

The reason is, you can only tap on 2-3 pixels of a line's width. Naturally you can use a speed limit shield as well, but for long streets, it's pretty hard to find. And there are no shields on red streets with no `maxspeed` tags. With a mouse it's better (but not much, since the cursor doesn't change when hovering over lines, unlike shields), but with fingers, you're doomed.

So please, increase the tap area for lines. It could be done by overlaying a wider transparent line over a displayed one, for example. Idk, you're the developer :)

Additionally it might make sense to change a mouse cursor when hovering over tappable lines, but I hate when people add multiple tasks into a single issue, so let's pretend I didn't write this.

**Comment by pietervdvn** [comment]
Hi Ilya,

You're totally right. And it was something I was aware of for a long time but never bothered to fix; but your issue had me think again about it.

As "I'm the developer", I've opted to not draw an invisible buffer (as that would be a big penalty hit when rendering a map), but I've instead opted to query all features within 20px and then search the closest way.

I'm deploying this on https://dev.mapcomplete.org for now; it'll go to master when I feel like it. Would you mind giving it a test there?

**Comment by Zverik** [comment]
Wow Pieter, you're fast! I've tested this, and feels so much better now! Haven't had to tap twice on anything. Thank you :)
