### ISSUE TITLE
Openstreetmap link doesn't show if not logged in

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2274]
I assume this is maybe intentional but i have no idea why:
https://mapcomplete.org/charging_stations.html?z=19&lat=51.20780090375928&lon=4.419039168023346&background=DV_GRB#node/12367684499

if i go there, i don't see the openstreetmap icon/link to the object. only when i login do i see it.
![image](https://github.com/user-attachments/assets/c3e9d5ce-492a-4069-9fc0-01aa40fa88bc)

**Comment by pietervdvn** [comment]
This is indeed intentional.

I assume that someone who is not logged in, is a complete newbie and not aware of the underlying OSM-infra. For them, it is just a confusing, extra link.

**Comment by thibaultmol** [comment]
I suppose that makes sense. It's nice as a visual reminder that it's osm; is how i was looking at it

**Comment by pietervdvn** [comment]
A newbie won't recognize the logo anyway, an explicit mention of OSM at the bottom of the popup would be better for this
