### ISSUE TITLE
Add ability to draw area's/lines

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2276]
it's something that's been missing from mapcomplete since the start, which is fair because adding it won't be trivial.

But for certain things it will be really ideal or even needed that the functionality is there.

An example: charging stations can get mapped as nodes but ideally get mapped as ways so that you can then add each individual charge_point in the area of the charging station.

**Comment by pietervdvn** [comment]
See the readme:

> An explicit non-goal of MapComplete is to modify geometries of ways, especially generic geometry editing. (Splitting roads is possible; in some restricted themes, geometry conflation is also possible). If adding geometry would be supported, we'd also have to show all geometries (to avoid accidental intersections). This would invite showing and editing other geometries as well, resulting in a general-purpose editor. However, we already [have an excellent, web-based general purpose editor](https://wiki.openstreetmap.org/wiki/ID).
