### ISSUE TITLE
Deleting objects broken on stable and dev

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2278]
There seems to be something that's causing as error, regardless of the option I choose. both on stable and dev.
Firefox mobile and firefox desktop.

![image](https://github.com/user-attachments/assets/423515a5-cc59-44bc-89ef-8736a99ce096)

Example of something i was trying to delete as a duplicate: https://dev.mapcomplete.org/waste?z=22.3&lat=50.81326087085489&lon=4.378561523982285#node/4558218899

**Comment by pietervdvn** [comment]
I've made some changes to how deletions are handled, this is a bit of fallout for this. Thanks for reporting!

This should however only have been the case on dev
