### ISSUE TITLE
amenity=waste_disposal gone on waste theme?

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2279]
Somehow around noon it was still fine, but this evening I noticed that  somehow `amenity=waste_disposal` is gone from the mpa
both on stable and dev. firefox and chrome.

![image](https://github.com/user-attachments/assets/4ba86910-8962-4ba5-9c7e-1d7c9e487615)

![image](https://github.com/user-attachments/assets/2cfdd7bc-fc44-4877-8fed-d8ed1488f7a9)

https://mapcomplete.org/waste?z=19.1&lat=50.815282637817546&lon=4.382392065174486#node/12376455569

and I have the layer turned on (as per default). I even added that point this afternoon using mapcomplete...

**Comment by RobinLinde** [comment]
Same here, also added [one](https://www.openstreetmap.org/node/12376016064) earlier today...
![MC screenshot showing 2 recycling containers and no waste disposal](https://github.com/user-attachments/assets/000e7e23-63e5-423b-b3af-8fbd64c29adb)
Also, it seems I can only see the filter menu (or any other menu) when the drawer menu is also opened.

**Comment by thibaultmol** [comment]
Luna also stumbled on this issue, they're indeed just not being displayed anymore. She said they are being displayed between zoom level 16 and 17 but not beyond 17
https://dev.mapcomplete.org/waste.html?z=16&lat=50.81228147197996&lon=4.382613393670226&background=DV_OrthoPhoto

**Comment by thibaultmol** [comment]
@RobinLinde could you look into this, it's ok if you don't want to. (would like to have it fixed for fosdem. is a nice map for internal use)

**Comment by RobinLinde** [comment]
Not sure how far I'm getting with this, but found out that a direct URL does work: https://dev.mapcomplete.org/waste.html?z=21.5&lat=50.8153069&lon=4.3821834#node/12376469465
It will disappear on closing still

**Comment by RobinLinde** [comment]
@thibaultmol think I found out the problem, seems to be because of the `minzoomVisible` being there. Weirdly enough, doesn't seem to cause any problems in the postboxes theme.
