### ISSUE TITLE
recycling:waste=yes can be rendered but not selected

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2280]
In the waste theme, I noticed today the tag `recycling:waste=yes` on a recycling container is actually shown in the ui if it's mapped. but it's not something you can ADD because it's not shown in the list of options for a recycling container in the 'What can be recycled here?' question

**Comment by RobinLinde** [comment]
If I recall correctly this was because there were some notes on the wiki about only using this for places where residual waste is actually recycled, and not in other cases. To make the theme simpler I only added it as a rendering. With the current wiki definition it seems kinda fine to include it.

**Comment by RobinLinde** [comment]
Looked up the original wiki text:
General waste container (black bags) (don't use this if the waste is not recycled, use a tag like [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[waste_disposal](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_disposal) or [amenity](https://wiki.openstreetmap.org/wiki/Key:amenity)=[waste_basket](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_basket) instead)
