### ISSUE TITLE
Can't open filter or background menu

### ISSUE THREAD

**Issue by RobinLinde** [pietervdvn/MapComplete#2281]
Noticed this after merging develop into my overlay test, but it seems I can only open the filter/background menu, when I also open the drawer menu. Otherwise it will open, but it stays invisible.
[Screen recording](https://github.com/user-attachments/assets/9bfd3929-2a73-4510-ba68-8a00c356f6b8)

**Comment by pietervdvn** [comment]
Regression of an earlier UI-improvement. I should test better
