### ISSUE TITLE
authorization is overly broad

### ISSUE THREAD

**Issue by gdt** [pietervdvn/MapComplete#2283]
I clicked the login button, and was presented with the osm oath screen, with the following permissions:
    - Read user preferences
    - Modify user preferences
    - Modify the map
    - Upload GPS traces
    - Modify notes
    - Sign-in using OpenStreetMap

I understand read preferences (sort of, but it's ok), modify the map (that's the point), and modify notes, and sign-in (sort of, but also ok).

I don't understand modify user preferences.

"Upload GPS traces" is a big problem.  If  I were running this with location someplace, I get it that if I click 'change this object'  there will be a changeset with my osm userid.    But I basically don't ever want to upload a trace, and certainly not without reviewing it to make sure it only has public data.    This makes me wonder "when does the web page direct the browser do upload traces"?

I have been seeing this is other contexts (e.g. StreetComplete), and I wonder if this is partially because of the new auth scheme.  I remember being able to uncheck the permissions individually.

Overall, I would suggest to remove the concept of uploading traces.   If not, the privacy policy should explain if they are gathered by default when using browser geolocation, and under what circumstances they are uploaded.

**Comment by pietervdvn** [comment]
>  But I basically don't ever want to upload a trace, and certainly not without reviewing it to make sure it only has public data. This makes me wonder "when does the web page direct the browser do upload traces"?

Your location trace is kept locally on your device for about three days. You can see this by enabling the layer "my travelled track" (where you can also disable this).

There is a button there to upload this trace if you'd want this, where the privacy implications of doing this are clearly explained. It is a bit stupid to ask to login _again_ if people want to do this; which is why this permission is asked up front.

Also keep in mind that you can always _uncheck_ the permissions you don't want to give!

**Comment by gdt** [comment]
In the OSM page I see, there are permissions listed as bullets.  The html looks like

```
<p>Authorize MapComplete to access your account with the following permissions?</p>

<ul>
    <li>Read user preferences</li>
    <li>Modify user preferences</li>
    <li>Modify the map</li>
    <li>Upload GPS traces</li>
    <li>Modify notes</li>
    <li>Sign-in using OpenStreetMap</li>
</ul>
```

And I can't figure out how to uncheck any of that, either from looking at the rendered page and clicking around, or reading the page source.

I then edited the URL for the oauth2 page to drop the pemissions I didn't want, and then got a prompt without write prefs and upload gpx.  I was able to authorize and return.

**Comment by pietervdvn** [comment]
Oh, I'm mistaken about the possibility to disable a certain permission.

**Comment by gdt** [comment]
I suspect you remember correctly that you could, and something about the osm.org oath transition to something newer (sorry, that's the extend of my memory!) broke this.  I remember that in the past one could uncheck things; I (perhaps wrongly attributed) remember doing this with StreetComplete.  I am seeing this problem in a number of programs.

**Comment by pietervdvn** [comment]
The used permissions:

- Read user preferences
- Modify user preferences

Those are used for to read and save various settings, favourites, history...
So yes, both 'read' and 'modify' are important. 

- Modify the map

Well, duh ;)

- Upload GPS traces

Only used if you effectively upload a trace

- Modify notes

Used mostly in the "notes"-theme

- Sign-in using OpenStreetMap

This is actually the only one which is unneeded and unused. I've originally added this as preparation for the panoramax instance, but we've solved this in a different way.

**Comment by riQQ** [comment]
See b23b216564fa73f6feed88dee417ec20b8f4e8c7
