### ISSUE TITLE
surveillance: disabling police stations does not work

### ISSUE THREAD

**Issue by gdt** [pietervdvn/MapComplete#2285]
In the surveillance theme, the filter popup shows two kinds of cameras and police stations.  I opened the left panel and then the filter popup, and deselected police stations, and then hit the X.  Reopening filter shows police stations deselected.   But, I keep seeing police stations.  And, if I open the right panel, I see an active filter of not showing police stations.

(As an aside, I don't think police stations belong in the surveillance theme.  But that's a style preference, not a bug.)

**Comment by pietervdvn** [comment]
This is a known issue which was fixed on dev. I'm rolling those out soon (tomorrow or the day after)
