### ISSUE TITLE
Campersite theme doesn't show tourism=camp_site

### ISSUE THREAD

**Issue by zorglubu** [pietervdvn/MapComplete#229]
In France at least, most tourism=camp_site allow caravans and campers, except if motor_vehicle=no or equivalent. And they represent most of the places for caravans and vans.

If I am not wrong, these camp_site are ignored and they shoudn't, even if you focus on vehicles.

**Comment by pietervdvn** [comment]
Paging @joostschouppe

**Comment by joostschouppe** [comment]
It's a theme about campersites and sanitary dump stations. Campersites are spaces dedicated to campers, they are quite different form campings. Of course, we can expand the theme to also include campings. I'm personally just not that interested in them, so I'm not panning on making it myself. But I'd be willing to help someone code such a layer.

**Comment by joostschouppe** [comment]
The goal is to create a mapping tool as well as a usable map. I'm assuming you meant caravan_site in your previous comment. Excluding camp_site already helped me notice that a lot of campings seem to be tagged erroneously with caravan_site or the other way around. For sanitary_dump_station, they are often mapped as a node within a camp_site, so they would show up.II had previously used sanitary_dump_station=yes to also show places like a camping that have this as an extra tag. But that would make weird places like harbors show up :) - I already had to add vehicle=no to exclude the hundreds of boat-only stations in Sweden.
And that's for a topic I know. I don't think MapComplete should have a theme layer without a proper data model, and I don't feel like I can write that myself. Maybe if I analyse Open Camping Map...

**Comment by pietervdvn** [comment]
It seems like this discussion has gone stale, so I'm closing it.
