### ISSUE TITLE
Open note without location

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#2311]
I feel like it should be possible to go to a url with only the note id and no gps location (and have mapcomplete look up in the api where the note is and pan to it)

so this should work:
https://mapcomplete.org/notes?#4551671
but currently it doesn't

**Comment by pietervdvn** [comment]
Due to technical limitations, this will only work for people who are logged in.

**Comment by thibaultmol** [comment]
No external notes api you can use?

**Comment by pietervdvn** [comment]
If you are not logged in, the CORS-headers of OSM.org block this request. It might be possible somehow, but will take quite some effort (which IMHO isn't worth it).
