### ISSUE TITLE
Using `width` instead of `width:carriageway`

### ISSUE THREAD

**Issue by SupaplexOSM** [pietervdvn/MapComplete#2318]
MapComplete is using the key `width:carriageway` for some themes to specify the width of roads and streets. However, the meaning of `width:carriageway` has become obsolete since the understanding of the meaning of `width` on a road or path has narrowed down to the same meaning as `width:carriageway`. In earlier years, there was a lack of clarity here, so some mappers (like me) used/invented `width:carriageway` as an interim solution. Later, however, the meaning of `width` was clarified and, at the latest since StreetComplete supports `width` on roads and streets, this meaning has in fact become established.

It would therefore be helpful if MapComplete also uses `width` instead of `width:carriageway`, as MapComplete currently seems to be the only application that still actively encourages `width:carriageway`.

**Comment by pietervdvn** [comment]
Ah, good to see that consensus has been reached about this tag.

I've updated the layer using this property. It'll still show `width:carriageway` is `width` is not available, but will add new values under `width`.
