### ISSUE TITLE
Minor changes to themes

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#234]
I'll update the ticket as I see more issues I can address myself:
- the benches theme should probably contain picknick sites as well. Many of them aren't actually sites, but just a single table. So there should be a question like "is this place really a picnic site, or just a table?"
- add operator / operator:type to the camera theme
- ~~drinking water is very often broken. We probably need a question like the one for bicycle pumps to mark them as broken. Though perhaps many are simply deactivated for winter? That's of course hard to know, and I have no idea how to tag it.~~ EDIT: I must have overlooked this!

**Comment by pietervdvn** [comment]
>     * drinking water is very often broken. We probably need a question like the one for bicycle pumps to mark them as broken. Though perhaps many are simply deactivated for winter? That's of course hard to know, and I have no idea how to tag it.

This one already implemented, for quite a while - but it is "hidden" under the default assumption that the drinking water still works: 
![image](https://user-images.githubusercontent.com/1466478/113459735-abf3b900-9416-11eb-8b1b-9aa15899a5a5.png)

**Comment by pietervdvn** [comment]
Fritures: add a small icon for vegetarian fritures, add opening hours indicator

**Comment by pietervdvn** [comment]
Also see #229

**Comment by pietervdvn** [comment]
Most of them seem to be implemented, so I'm closing this issue
