### ISSUE TITLE
Licenses of images used in the campersite theme

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#237]
@joostschouppe Which icons did you in the campersite theme? What are the licenses? Should we give attribution?

I'm making a small system where the attribution is added as a .json and can be displayed in-app.

**Comment by joostschouppe** [comment]
They were taken from Osmand-resources. The license info is here: https://github.com/osmandapp/Osmand/blob/master/LICENSE
Except for a specific subset (which I did NOT use), they are all CC0, so no need to attribute. It is not clear to me where exactly the icons I used are from, so it would be hard to give exact attribution.

**Comment by pietervdvn** [comment]
Allright, that is noted. The social image was found by google reverse image search, so that is found too.
