### ISSUE TITLE
Attribution of climbing theme icon

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#239]
@chrneumann : I'm currently trying to figure out the licenses and attributions of all the used artwork. Would you be so kind to tell me where you found [the icons in the climbing theme](https://github.com/pietervdvn/MapComplete/tree/master/assets/themes/climbing)

I know that you changed many of those, but I suspect that you started with an already existing icon that should be attributed as well.

**Comment by chrneumann** [comment]
The icons are based on the icons of the OSM climbing wiki site: https://wiki.openstreetmap.org/wiki/Climbing
It's stated there that they are public domain.

**Comment by pietervdvn** [comment]
Excellent! Thanks for getting back, I've updated the licensing information.
