### ISSUE TITLE
Add project to taginfo

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#247]
https://wiki.openstreetmap.org/wiki/Taginfo/Projects
https://github.com/taginfo/taginfo-projects/blob/master/CONTRIBUTING.md

**Comment by Ltrlg** [comment]
The generated files look incomplete? The [AED one](https://raw.githubusercontent.com/pietervdvn/MapComplete/master/Docs/TagInfo/mapcomplete_aed.json) for example lists only emergency=defibrillator, but the popups use both specific ([`defibrillator:location`](https://github.com/pietervdvn/MapComplete/blob/a189fa4ba00d1f177242075b103bf297b72acd6e/assets/themes/aed/aed.json#L219)) and non-specific ([`mapillary`](https://github.com/pietervdvn/MapComplete/blob/a189fa4ba00d1f177242075b103bf297b72acd6e/Logic/Actors/ImageSearcher.ts#L80)) other tags.

**Comment by pietervdvn** [comment]
Yeah, that is correct. For now, only the tags selecting a layer are included. I will check how that goes and add more tags tomorrow.

**Comment by pietervdvn** [comment]
These are working now except for image as that is a special case.
