### ISSUE TITLE
Direction tool

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#248]
* On a phone you don't see the map, so you have to remember the "map context" to be able to add the direction. Perhaps we could show the direction interface transparent so you can see the background map through it
* In Chrome on Android the interaction (show the value as a piece of pie) does not work (tested on three devices). EDIT: this is also the case on Chrome on PC

**Comment by pietervdvn** [comment]
Fixed: 
![image](https://user-images.githubusercontent.com/1466478/123017586-29ebae80-d3cd-11eb-9152-777ea9da10c1.png)
