### ISSUE TITLE
Question can be hidden from user and require scrolling

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#255]
Move question to top?

Make OH widget slimmer, with less wide lines?

Make popups larger on large screens at least?

![screen10](https://user-images.githubusercontent.com/899988/115843723-6cb9f600-a41f-11eb-98d5-fa02b76f2340.png)
https://pietervdvn.github.io/MapComplete/cyclofix?z=15&lat=50.08907&lon=19.94842#way/180878005

**Comment by pietervdvn** [comment]
The placement of the questions-box is configurable per theme. If it is not configured, they go at the bottom at this moment. It also depends on how you see MapComplete:

- If you consider it a map viewer which nudges one to add extra information, the questions go at the bottom.
- If you consider it a map editor which also shows already known information, the questions go at the top.

We could make this default placement user-configurable, but user settings are another level of complication (both in code and in presentation to the user). I'm gonna think about, if it is worth it.

**Comment by matkoniecz** [comment]
> If you consider it a map viewer which nudges one to add extra information, the questions go at the bottom.

Oh, I missed this viewpoint (I approached it as part of documenting how StreetComplete differs from similar tools).

If that view can be assumed to be default, then current default (overridable by projects) makes sense. And Cyclofix self-describes itself as a map for cyclists, not easy to use editor

**Comment by pietervdvn** [comment]
Indeed!
