### ISSUE TITLE
Consider documenting how it differs from StreetComplete

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#257]
or maybe no, but I would thankful for confirming my summary or pointing out what is missing:

MapComplete is also an OpenStreetMap-viewer, while it is not focus of SC.

MapComplete is available as a website - so available on PC, iPhone etc

MapComplete will not work offline.

In MapComplete it is easier to add more experimental, extremely detailed and more personal styles, as each topic is separated with its own part.

MapComplete is a bit more complex to use - both because one needs to go hunting for a specific map style rather than getting bunch of quests by default and is likely to ask far more detailed question (email address and phone number of bicycle shop etc). After all if it would duplicate StreetComplete it would be a bit pointless and it is pretty hard to compete with SC by being easier to use and more newbie friendly, while there is space for "more complicated/detailed/involved editor working like SC".

Also, MapComplete has no requirement to make question easy to answer, making both possible to ask more questions than StreetComplete but making it more complicated to use.

No support for splitting ways in MapComplete.

Have I missed something important?

**Comment by pietervdvn** [comment]
You missed: MapComplete allows the addition of new points.

But for the rest, your difference is spot on. Part of the differences and differences in vision are outlined in one of [StreetComplete's issues](https://github.com/streetcomplete/StreetComplete/issues/2461#issuecomment-756456786), but it wouldn't hurt to summarize it, for example [here](https://github.com/pietervdvn/MapComplete/blob/master/Docs/What_is_MapComplete.md).

I'm also planning on making a SOTM-video about MC, where one section will be a comparison with MapContrib and StreetComplete

**Comment by pelderson** [comment]
This would be my list:
====
MC works in the browser on any device. SC is a mobile app. 
MC requires a connection, SC can work offlne. 
MC acts as a theme POI map (openstreetmap viewer), with on-demand user edit facility. SC is a general map app automatically asking predefined questions based on location. 
MC therefore requires more user taps/clicks than SC.
MC has user-defined themes, based on a user-defined selection of objects, and displayed in a user-defined way. This user is a savvy theme-developer. 
MC can retrieve and display nodes, ways and relations, and add/edit any tags, as defined by the theme developer.
MC can add stand-alone nodes (!? not sure if SC can)
MC and SC can not change geometry (!? not sure if that’s completely true for SC).
MC and SC are aimed at the non-savvy user. An OSM account is needed for editing.
MC does not “follow” the user’s location, and requires user action for focus. SC automatically asks questions about objects at your location. 
SC limits the user to easy predefined questions and answers about well-known features. MC can range extremely simple (just add a node, no questions asked) to pretty specialized and very detailed for a dedicated theme. That is up to the theme developer. 
MC themes can be created and adapted very quickly, depending on theme developers (savvy users). SC has a release schedule for new functionality and questions, dependant on app developers. 

The primary use case of SC is: completing OSM feature attributes where you are.
The primary use case of MC is: viewing, adding and editing OSM-features and attributes from a particular viewpoint, e.g. things relevant for Cycling, or Stolpersteine, or Public Transport. 
========
