### ISSUE TITLE
Vastlopers na toenemende vertraging

### ISSUE THREAD

**Issue by pelderson** [pietervdvn/MapComplete#259]
MapComplete werkt steeds trager en op een gegeven moment breekt hij af. Na herladen gaat het weer snel.

Ik heb een themaatje waarmee ik alleen maar punten toevoeg, kliklklikklikklikklikklaar (ja, 5 klikken per toevoeging).
De afhandeling gaat in het begin heel snel, maar hoe meer ik er doe hoe langzamer het wordt, en op een gevement krijg ik van de browser eerst "De pagina reageert niet wilt u wachten?"  en als ik Wachten kies, komt "Oeps er is iets foutgegaan". Na F5 gaat het dan weer snel, etc.
De oplopende vertraging en uiteindelijk de crash zit na het schermpje met "Je toevoeging is voor iedereen zichtbaar". De wijzigingen, op de laatste na, zijn wel in OSM opgeslagen.
Dit gedrag van een toepassing had ik in mijn DOS-dagen meteen voorzien van de diagnose "geheugenlek", later ook "cache moet groter".

**Comment by pietervdvn** [comment]
Jup, the thing leaks memory. Will fix it one day, when I have some more time

**Comment by pietervdvn** [comment]
This should have improved a lot with the 0.8.0-version
