### ISSUE TITLE
Feature pop-up only opens once when on z13 or below

### ISSUE THREAD

**Issue by ubipo** [pietervdvn/MapComplete#26]
The detailed feature pop-up only opens once when clicked on at z13 or below. Clicking again doesn't do anything.
To reproduce:
1. Zoom out until "Zoom in om de data te zien" appears
2. Click a feature, the pop-up will open
3. Close the pop-up
4. Click the same feature, pop-up doesn't open

**Comment by pietervdvn** [comment]
I can not reproduce this behaviour (although there are some hacks in the live version).

Could you please state the browser and OS?

**Comment by pietervdvn** [comment]
Hang on, I can reproduce it. It is only the case for points, not for areas.
