### ISSUE TITLE
Problem with production build 

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#262]
I would like to host an instance of MapComplete. I can successfully run the debug build using:

    npm run start

I can open the page at `http://localhost:1234/index.html` and also open the individual themes.

The production build also builds now:

    npm run build

and I can open the `index.html` and the front page looks good. However the links to the individual themes are not working. For example the first link, cyclofix links to "cyclofix?z=1&lat=0&lon=0", but there doesn't seem to be a file called `cyclofix` in the `dist` folder and so it doesn't open.

I also ran `npm run generate` and `npm run generate:editor-layer-index` before, so that doesn't seem to be the problem.

Any idea?

**Comment by pietervdvn** [comment]
At debug time, the theme is loaded by using the URL-parameter "layout=<themename>". The 'MoreScreen' links to `index.html?layout=<theme>` iff the host is `127.0.0.1`.

For a production build, there is a script which generates a html for every theme (cyclofix.html, aed.html, ...). These are generated with `npm run prepare-deploy`

**Comment by pietervdvn** [comment]
I've written better and [more detailed instructions](https://github.com/pietervdvn/MapComplete/blob/master/Docs/Development_deployment.md) and did a few fixes in the setup scripts, which should improve things for new contributors.

**Comment by sebkur** [comment]
Thanks for improving the guide!

**Comment by sebkur** [comment]
OK, that helped!

I'm still getting errors, though.

When I run `npm run prepare-deploy`, the last step of that is `npm run generate:docs`. That seems to expect the `taginfo-projects` repository to be checked out to the parent directory:

    const tagInfoList = "../taginfo-projects/project_list.txt"                                                                                                             
    let projectList = readFileSync(tagInfoList, "UTF8")                                                                                                                    
        .split("\n")                                                                                                                                                       
        .filter(entry => entry.indexOf("mapcomplete_") < 0)                                                                                                                
        .concat(files.map(f => `${f} https://raw.githubusercontent.com/pietervdvn/MapComplete/master/Docs/TagInfo/${f}.json`))                                             
        .sort()                                                                                                                                                            
        .filter(entry => entry != "")

Maybe we should add to the instructions that we need to do that. Or, alternatively, we could also include the `taginfo-projects` repo as a submodule of this git. Then we'd need to update instructions to checkout this repo using `git clone --recurse-submodules [repo url]`. Another option: I'm not sure yet generating the docs is strictly required for a production build (do the generated docs appear somewhere within the website?) otherwise we could also just remove it from the `prepare-deploy` task?

**Comment by sebkur** [comment]
that being said, when I clone the `taginfo-projects` git, everything builds

**Comment by sebkur** [comment]
> I've changed the behaviour in that script; it'll give an error message now instead of crashing the build.

excellent, makes sense
