### ISSUE TITLE
Web manifest paths

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#263]
Now that I can successfully build the application, it almost works.

In the `dist` directory, I have all the generated html files for the individual themes, i.e. `cyclofix.html`, `shops.html`, etc. I can also successfully open them in the browser after deploying to the webserver (example: https://waldbrand-app.de/mapcomplete/cyclofix.html). However, the links from the front page in `index.html` don't point to `cyclofix.html` etc, but just `cyclofix` which do not yet work in my setup (example: https://waldbrand-app.de/mapcomplete/cyclofix).

Those paths do work on your deployment on Github pages. I'm not an expert on progressive web apps, but I assume after some googling that this has something to do with the web manifest files, i.e. `cyclofix.webmanifest` etc. What I do not get yet is, how would my browser know when I enter the url with just cyclofix at the end, without the `.html` extension, that it should look for `cyclofix.webmanifest`, parse that and conclude that the real content should come from `cyclofix.html` as stated in the `start_url` attribute within the manifest? The manifest files are also online (example: https://waldbrand-app.de/mapcomplete/cyclofix.webmanifest) and after some tinkering with the nginx config, they're also served with mime type `application/manifest+json`

**Comment by sebkur** [comment]
Update: it works when deployed to Github pages:
https://waldbrand.github.io/MapComplete/index ← note you can leave out the `.html` suffix here as well
also:
https://waldbrand.github.io/MapComplete/cyclofix

**Comment by sebkur** [comment]
So I guess the assumption that deploying to any file server works out of the box is not entirely correct. I think probably some configuration is required for the web server to process the web manifests to map the paths specified in there to actual html files. And GitHub pages seems to do that automatically, not sure yet what I need to do for a plain old nginx server to make this work. I guess it would also be interesting to find out how it works on Apache.

**Comment by sebkur** [comment]
For now I'm working around this by using links from the front page to the individual themes that do have the `.html` suffix: https://github.com/waldbrand/MapComplete/commit/ea69142b8beeba607a4b022aa90189d84522e4b9

**Comment by pietervdvn** [comment]
I have added the explicit .html-suffixes as you did by now.

The webmanifests should work with relative paths too now - that was previously broken.
