### ISSUE TITLE
Only English and Dutch enabled, how to enable the others?

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#264]
On my local fork and also on the main instance at https://pietervdvn.github.io/MapComplete/index.html the language picker in the top right corner only shos "en" and "nl" to pick from while the language assets already define a bunch of other languages like Spanish and French. Is there something I need to do to enable one of those languages in a deployment? Does it have to do with the translation coverage? I haven't found the place in the code where the languages displayed as choice is determined from the set of available languages.

**Comment by pietervdvn** [comment]
The languages available on the welcome page, are the languages in which the index-title has been translated as per [this code](https://github.com/pietervdvn/MapComplete/blob/2b49a84a5b74cbde86f310563cace898c55557d6/UI/BigComponents/MoreScreen.ts#L128).

You can thus enable a new language on the index page by adding a translation [here](https://github.com/pietervdvn/MapComplete/blob/2b49a84a5b74cbde86f310563cace898c55557d6/assets/translations.json#L166)

**Comment by pietervdvn** [comment]
(Note that the languages available in a theme are set by the individual theme)
