### ISSUE TITLE
Problem with calculated tag

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#275]
I'm trying to use the `calculatedTags` feature to calculate the flow rate for hydrants from the diameter which is usually tagged.

I've looked at the docs and also at the layers from the other themes that do use calculated tags, but I cannot seem to get it to work.
Here's what I'm doing: https://github.com/waldbrand/MapComplete/commit/5b4460e410cf2bd8464aebe3964dba5e46950d97

So for the sake of just testing it, I'm just trying to assign a literal string value to a calculated tag and use that during tag rendering.
I am able to render the builtin calculated tags such as `_country` without any problem.

Thank you!

**Comment by sebkur** [comment]
It's probably something simple I'm missing. Any idea what's going on?

**Comment by pietervdvn** [comment]
Hi,

Nothing wrong with your code, I accidentally broke the calculated tagging (which is fixed [here](https://github.com/pietervdvn/MapComplete/commit/0ad16cfe3f5cd2d0b5fe578d4ce3b8868f23e396))

I'd also recommend to add an extra (read-only) tagrendering for the flowrate and not lump it together with the options of the width (as then you're gonna have to replicate that and because it is not gonna work and show ugly empty options).

**Comment by pietervdvn** [comment]
At last: keep in mind that those tags are only calculated when the data is _loaded_ - not when the data is changed! This means that the flowrate will not be shown when the user just answered a question.

**Comment by sebkur** [comment]
Thanks for the quick fix!

**Comment by sebkur** [comment]
> I'd also recommend to add an extra (read-only) tagrendering for the flowrate and not lump it together with the options of the width (as then you're gonna have to replicate that and because it is not gonna work and show ugly empty options).

That sounds like a good idea, I'll try to do that

**Comment by sebkur** [comment]
> At last: keep in mind that those tags are only calculated when the data is loaded - not when the data is changed! This means that the flowrate will not be shown when the user just answered a question.

Hmm, would it be much trouble just re-calculating all calculated tags of the object at hand after changing a value of one of its tags? I imagine this makes sense in most cases, if some calculated tag is derived from a regular tag... when the regular tag gets updated it would usually imply the calculated tag needs to be updated, too. As only one object is updated at a time, I would think the computational overhead is nothing to worry about here.

**Comment by pietervdvn** [comment]
I'll have a look when I have some more time for it - tracked in #287
