### ISSUE TITLE
allow "hints" when defining questions

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#277]
I find myself often adding hints to questions, for example "What is the official identification number of the device? (if visible on device)". It would make more sense to have something like:

> What is the official identification number of the device?
> [answer field]
> _Only add a number if it is visible on the device_

**Comment by pietervdvn** [comment]
Good first issue to have the OSOC-team get some feeling with the codebase

**Comment by pietervdvn** [comment]
This has been implemented a while ago: `questionHint` is a piece of information that is shown together with the question.

[Example usage](https://github.com/pietervdvn/MapComplete/blob/b92e9b815da3e1b15c9859f6d4726bac09307b7b/assets/layers/nature_reserve/nature_reserve.json#L333)
