### ISSUE TITLE
improvements in charging_stations

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#279]
I don't understand why, because this line https://github.com/pietervdvn/MapComplete/blob/a8463ac0ceb175d1a1b1cbc53bfdebe3758f856a/assets/themes/charging_stations/charging_stations.json#L103 isn't conditional.

See also:

(also `capacity` is useful for bike charging stations)

_Originally posted by @thibaultmol in https://github.com/pietervdvn/MapComplete/issues/250#issuecomment-824274515_

**Comment by joostschouppe** [comment]
I created a version where @thibaultmol 's other point is addressed: if the object has no network, then we ask for the operator
I also addressed an issue that often comes up: who can use this charging station. Some belong to for example a B&B or restaurant, and then only clients can use them.

Unfortunately, three issues remain:
- the one posted above
- my version doesn't actually work :( , [see error here](https://mapcomplete.osm.be/?userlayout=https://raw.githubusercontent.com/osmbe/play/master/mapcomplete/charging_stations.json)
- operator is very widely used when the theme would suggest network instead. In Belgium for example, over 180 stations are `operated` by Allego, while only 7 belong to the `network` Allego. Should we adapt to the mess or try and clean it up somehow?

**Comment by pietervdvn** [comment]
@joostschouppe Your version doesn't work, because you used an array as condition for the if. But then, MC doesn't know wether this is a 'or' or a 'and'. So, change `"if": ["access=permissive","access=public"]` into `"if": {"or": ["access=permissive","access=public"]}` and it'll work. I'm also doing my best to show in the error message exactly where it goes wrong (the [0] indicates the index), so you can follow it quickly.

**Comment by pietervdvn** [comment]
The core issue: there is no question defined, so it won't ask for this attribute if it isn't already present.

**Comment by pietervdvn** [comment]
> operator is very widely used when the theme would suggest network instead. In Belgium for example, over 180 stations are operated by Allego, while only 7 belong to the network Allego. Should we adapt to the mess or try and clean it up somehow?

The tagging itself should not be discussed in this repo; but MC can be adapted to show both entries and/or to erase one if the other is set.

**Comment by joostschouppe** [comment]
Thanks a lot for the help, got it sorted now.
I'll think about it a little more, but I'm thinking the most user friendly would be "Who operates this?". 
Then: "Does this operator have a network of charging stations?"
Answer options:
"Yes" > fills in network with the value for operator
"No" > fills in no:network=yes

**Comment by MikiDi** [comment]
> When adding the operator, best to add the wikidata as well

The example wikidata values listed would be for network, not (necessarily) operator, right?

**Comment by pietervdvn** [comment]
I've summarized everything in #387 (and for #389 for the network/operator/brand discussion)
