### ISSUE TITLE
Mapping cycle infrastructure (oSoC-project for Provincie Oost-Vlaanderen) 

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#298]
Contact: Claudia De Pus (Mobiliteitsdienst Oost-Vlaanderen; hiervoor ondersteuning van de gemeentes)

# Data collection

1. Add cycle lane/track left/right/both
2. Road segments should be splitable within the tool
3. Show cycleways and add a detailed datamodel, including:
   - Explain track vs path
   - Lit, surface (see StreetComplete approach and categories for Erpe-Mere), legal status, (find inspriation in the project template, see streetcomplete and routeplanner parameters), smoothness (see iD editor for implementation)

# Data visualiseren

1. Scores voor comfort, veiligheid, commute getoond moeten worden; wellicht gebaseerd op zaken als Liggen er grote wegen in de buurt van een vrijliggend fietspad? Kunnen we de afstand ertoe bepalen? Liggen er nog andere obstakels tussen (haag, geluidsmuur, betonblok, boordsteen). Perhaps also parking lanes
2. Badge/icoontje voor segment met wijziging laatse X dagen (en niet gemaakt ingelogde gebruiker) [optioneel-]
3. Some statistics about completeness (e.g. surface of cycleways) [optional+]

# Aangeleverde data

Wat met data van Erpe-Mere en Dendermonde?
- Sowieso als inspiratie
- Eventueel kijken om te integreren? Wat als aan de community wordt gegeven?
- Kunnen we de verzamelflow verbeteren?

Note: the MapComplete website should be in Dutch; English is optional

# Communication
- prepare communication material
- use the OSM & fietsersbond network te encourage uptake

# Optioneel

Cycle crossings: type of crossing, who has priority, is there traffic signs
Cycle markings: type of marking (dashed line, full line, suggestion)

- RSS-feed of changes (low priority)
- traffic sign data

**Comment by pietervdvn** [comment]
Ter info:

https://www.youtube.com/watch?v=b5jcxMamr3g&list=PLqjPa29lMiE0NZ-ouVFWgwz8vftq7dAd1&index=27

https://github.com/BikeOttawa/OSM-Bike-Ottawa-Tagging-Guide

**Comment by pietervdvn** [comment]
Ter info:

Fietsbarometer@ugent.be is geemaild met de vraag voor meer info; "ze zullen het doorgeven"

**Comment by pietervdvn** [comment]
Ter info:

StreetComplete

**Comment by pietervdvn** [comment]
https://zlant.github.io/parking-lanes/#15/51.2103/3.2248

Visualisatie voor links/rechtse cyclelanes

**Comment by pietervdvn** [comment]
Ter info: https://link.springer.com/article/10.1007/s11116-021-10198-0

**Comment by pietervdvn** [comment]
https://cargorocket.de/2021/05/31/routing.html

**Comment by joostschouppe** [comment]
Draft OSLO standard for cycle path data should be considered

**Comment by pietervdvn** [comment]
https://www.mobielvlaanderen.be/vademecums/vademecumfiets01.php

**Comment by RobinLinde** [comment]
From template: http://mijndev.openstreetmap.nl/~ligfietser/fiets/index.html
Also might look at http://mijndev.openstreetmap.nl/~peewee32/traffic_sign/traffic_sign.htm for alternatives

**Comment by pietervdvn** [comment]
https://wiki.openstreetmap.org/wiki/JOSM/Plugins/RoadSigns

**Comment by RobinLinde** [comment]
```xml
<sign ref="NL:C06" name="Closed for motor vehicles with more than 2 wheels">
    <tag key="motor_vehicle" value="no"/>
    <tag key="motorcycle" value="yes"/>
    <tag key="moped" value="yes"/>
    <tag key="mofa" value="yes"/>
</sign>
```
