### ISSUE TITLE
Heighten the bus factor

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#304]
Hey guys!

As some of you might already know, I broke my hip and might not be available all the time. In other words, I do think it is important to get some more community members as collaborators in here - even if it is just to merge a translation pull request.

So, if you are interested in joining, let me know.

Depends on #303 
Get Joost confident merging PR's
Give @sebkur keys to deployment

**Comment by pietervdvn** [comment]
I'd also like to get some others involved who are interested, maybe @matkoniecz @chrneumann @tordans ?

**Comment by matkoniecz** [comment]
Sorry, right now I am quite busy (and I sadly mostly abandoned OSM Carto :( ), so I am not planning to be more involved here.

**Comment by pietervdvn** [comment]
> Sorry, right now I am quite busy (and I sadly mostly abandoned OSM Carto :( ), so I am not planning to be more involved here - StreetComplete is more than enough for now.

No problem, everyone their own engagements. Thanks for letting me know.

**Comment by chrneumann** [comment]
Oh, sorry to hear that, how did that happen? As everyone I'm quite busy, but I can have a look at PRs or Issues from time to time. Might need some notification from GitHub and I'm not sure if I'm confident enough to merge more than simple changes.

**Comment by pietervdvn** [comment]
> Oh, sorry to hear that, how did that happen?

I made an ugly fall while rollerskating... Really stupid...

> Might need some notification from GitHub and I'm not sure if I'm confident enough to merge more than simple changes.

Joost is also doing this kind of work. I'll add you as collaborator; you can choose how engaged you want to be. For now, I'm already better and more active but it's good to have a bit of spread in case of emergencies.

**Comment by sebkur** [comment]
thanks for your trust @pietervdvn and happy to be onboard here

**Comment by pietervdvn** [comment]
Thanks for helping out! Learning about such a project is always a bit of a task, so it's in our best interest to get all the experienced contributors onboard.

**Comment by tordans** [comment]
> I'd also like to get some others involved who are interested, maybe … @tordans ?

Thanks for reaching out. Right now I don't have the time to contribute, unfortunately. But continuing the CSS refactoring from the beginning of the year is still on my list.

**Comment by pietervdvn** [comment]
Great! I have added you as collaborator, whenever you feel like picking this up again, you're welcome to join (but don't feel pressured to).
Thanks for your contributions btw!

**Comment by pietervdvn** [comment]
I feel like the community and knowledge has been spread out (which is great).

I'm gonna close this issue now, as keeping it open has no added value anymore.
