### ISSUE TITLE
"Syntax of the command is incorrect" in "run init"

### ISSUE THREAD

**Issue by limex** [pietervdvn/MapComplete#307]
Hi,
I followed https://github.com/pietervdvn/MapComplete/blob/master/Docs/Development_deployment.md till step "npm run init"
and got a "Syntax of the command is incorrect".
Any idea what went wrong?
I attached the log files.
Thanks in advance.
[2021-05-28T05_56_32_579Z-debug.log](https://github.com/pietervdvn/MapComplete/files/6558622/2021-05-28T05_56_32_579Z-debug.log)
[2021-05-28T05_56_32_552Z-debug.log](https://github.com/pietervdvn/MapComplete/files/6558623/2021-05-28T05_56_32_552Z-debug.log)

**Comment by limex** [comment]
Ok. I found the reason and the fix.
Reason for issue: 
https://stackoverflow.com/questions/65627536/the-token-is-not-a-valid-statement-separator-in-this-version

Fix: 
Install Powershell Core
Update to the latest npm and nodejs
Delete the MapComplete Folder and start all over again with the Install Steps.

**Comment by pietervdvn** [comment]
Hi Limex,

I never tested those scripts on linux. It would be an added value if you were to update the README with the lessons you learned, so others don't have to make the same mistakes. Would you mind making a PR?

**Comment by limex** [comment]
Hi, I run into additional issues because of using Windows to build the code. I finally gave up and settled for Ubuntu Terminal in Windows. Therefor my findings above where probably going in the wrong direction.
I suggest that you change the Wiki and mention building in Windows as "experimental". People with average coding skills (like me ;) ) would then not waste time with it.

**Comment by pietervdvn** [comment]
Allright, I'll mention it
