### ISSUE TITLE
Too many roads excluded in slow_roads?

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#309]
Here, it seems all roads that are access=private are excluded as slow roads: https://github.com/pietervdvn/MapComplete/blob/e38b4fae64a0d73f3b78a88036dabb2c16ced2a6/assets/layers/slow_roads/slow_roads.json#L21
However, this can be overruled by foot|bicycle=yes|permissive|designated. So it seems some roads could be excluded without good reason.

**Comment by pietervdvn** [comment]
Indeed, but I kinda consider 'highway=footway;  access=no;foot=yes' as very wrong and very car-centric.

Feel free to improve though!

**Comment by pietervdvn** [comment]
I'm gonna close this issue now, as the project has been launched and is considered finished.

Note that the slow-road theme is not publicly visible in the first place.
