### ISSUE TITLE
Open Climbing Map

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#33]

**Comment by chrneumann** [comment]
Working on this :+1:

**Comment by pietervdvn** [comment]
Nice.

[I already started making one once, but it is very unfinished.](https://pietervdvn.github.io/Staging/index.html?userlayout=climbing#eyJpZCI6ImNsaW1iaW5nIiwidGl0bGUiOnsibmwiOiJPcGVuIEtsaW1rYWFydCJ9LCJkZXNjcmlwdGlvbiI6eyJubCI6Ik9wIGRlemUga2FhcnQgdmluZCBqZSB2ZXJzY2hpbGxlbmRlIGtsaW1nZWxlZ2VuaGVkZW4sIHpvYWxzIGtsaW16YWxlbiwgYm9sZGVyemFsZW4gZW4ga2xpbW1lbiBpbiBkZSBuYXR1dXIifSwibGFuZ3VhZ2UiOlsibmwiXSwibWFpbnRhaW5lciI6IiIsImljb24iOiJodHRwczovL2QzMHk5Y2RzdTd4bGcwLmNsb3VkZnJvbnQubmV0L3BuZy80NTI0Ni0yMDAucG5nIiwidmVyc2lvbiI6IjAiLCJzdGFydExhdCI6MCwic3RhcnRMb24iOjAsInN0YXJ0Wm9vbSI6MSwid2lkZW5GYWN0b3IiOjAuMDUsInNvY2lhbEltYWdlIjoiIiwibGF5ZXJzIjpbeyJpZCI6ImNsaW1iaW5nIiwibmFtZSI6IkxheWVyIiwibWluem9vbSI6MTAsIm92ZXJwYXNzVGFncyI6eyJhbmQiOlsic3BvcnQ9Y2xpbWJpbmciLCJjbGltYmluZyF+cm91dGUiXX0sInRpdGxlIjp7InJlbmRlciI6eyJubCI6IktsaW1nZWxlZ2VuaGVpZCJ9LCJtYXBwaW5ncyI6W3siaWYiOnsiYW5kIjpbImxlaXN1cmU9c3BvcnRzX2NlbnRyZSJdfSwidGhlbiI6eyJubCI6IktsaW16YWFsIn19XX0sImRlc2NyaXB0aW9uIjp7Im5sIjoiRWVuIGtsaW1nZWxlZ2VuaGVpZCJ9LCJ0YWdSZW5kZXJpbmdzIjpbeyJtYXBwaW5ncyI6W3siaWYiOnsiYW5kIjpbImNsaW1iaW5nOmJvdWxkZXI9eWVzIl19LCJ0aGVuIjp7Im5sIjoiQm9sZGVyZW4ga2FuIGhpZXIifX1dfSx7Im1hcHBpbmdzIjpbeyJpZiI6eyJhbmQiOlsiY2xpbWJpbmc6dG9wcm9wZT15ZXMiXX0sInRoZW4iOnsibmwiOiJUb3Byb3BlIGtsaW1tZW4ga2FuIGhpZXIifX1dfV0sImhpZGVVbmRlcmxheWluZ0ZlYXR1cmVzTWluUGVyY2VudGFnZSI6MCwiaWNvbiI6eyJyZW5kZXIiOiJodHRwczovL2QzMHk5Y2RzdTd4bGcwLmNsb3VkZnJvbnQubmV0L3BuZy80NTI0Ni0yMDAucG5nIn0sIndpZHRoIjp7InJlbmRlciI6IjgifSwiaWNvblNpemUiOnsicmVuZGVyIjoiNDAsNDAsY2VudGVyIn0sImNvbG9yIjp7InJlbmRlciI6IiMwMGYifSwicHJlc2V0cyI6W10sIndheUhhbmRsaW5nIjoyfSx7ImlkIjoicm91dGVzIiwibmFtZSI6IkxheWVyIiwibWluem9vbSI6MTgsIm92ZXJwYXNzVGFncyI6eyJhbmQiOlsic3BvcnQ9Y2xpbWJpbmciLCJjbGltYmluZz1yb3V0ZSJdfSwidGl0bGUiOnsicmVuZGVyIjp7Im5sIjoiS2xpbXJvdXRlIn0sIm1hcHBpbmdzIjpbeyJpZiI6eyJhbmQiOlsibmFtZX4qIl19LCJ0aGVuIjp7Im5sIjoiS2xpbXJvdXRlIDxpPntuYW1lfTwvaT4ifX1dfSwiZGVzY3JpcHRpb24iOnsibmwiOiJJbmRpdmlkdWVsZSBrbGltcm91dGVzIn0sInRhZ1JlbmRlcmluZ3MiOlt7InJlbmRlciI6eyJubCI6Ik1vZWlsaWpraGVpZHNncmFhZCA8Yj57Y2xpbWJpbmc6Z3JhZGU6ZnJlbmNofTwvYj4ifSwicXVlc3Rpb24iOnsibmwiOiJXYXQgaXMgZGUgbW9lbGlqa2hlaWRzZ3JhYWQgdmFuIGRpdCBwYXJjb3VyPyJ9LCJmcmVlZm9ybSI6eyJrZXkiOiJjbGltYmluZzpncmFkZTpmcmVuY2gifX0seyJyZW5kZXIiOnsibmwiOiJMZW5ndGUgPGI+e2NsaW1iaW5nOmxlbmd0aH08L2I+In0sInF1ZXN0aW9uIjp7Im5sIjoiV2F0IGlzIGRlIGxlbmd0ZSBpbiBtZXRlciAodmFuIGRlIGdyb25kIHRvdCBoZXQga2F0cm9sPykifSwiZnJlZWZvcm0iOnsia2V5IjoiY2xpbWJpbmc6bGVuZ3RoIiwidHlwZSI6Im5hdCJ9fSx7ImZyZWVmb3JtIjp7ImtleSI6ImNsaW1iaW5nOmJvbHRlZCIsInR5cGUiOiJuYXQifSwicmVuZGVyIjp7Im5sIjoiQWFudGFsIHR1c3Nlbmhha2VuIDxiPntjbGltYmluZzpib2x0ZWR9PC9iPiJ9LCJxdWVzdGlvbiI6eyJubCI6IkhvZXZlZWwgdHVzc2VuaGFrZW4gemlqbiBlciBoaWVyPyJ9fSx7InJlbmRlciI6eyJubCI6IkRlemUgcm91dGUgaGVldCA8Yj57bmFtZX08L2I+In0sInF1ZXN0aW9uIjp7Im5sIjoiV2F0IGlzIGRlIG5hYW0gdmFuIGRlemUgcm91dGU/In0sImZyZWVmb3JtIjp7ImtleSI6Im5hbWUiLCJhZGRFeHRyYVRhZ3MiOlsibm9uYW1lPSJdfSwibWFwcGluZ3MiOlt7ImlmIjp7ImFuZCI6WyJub25hbWU9eWVzIiwibmFtZT0iXX0sInRoZW4iOnsibmwiOiJEZXplIHJvdXRlIGhlZWZ0IGdlZW4gbmFhbSJ9fV19XSwiaGlkZVVuZGVybGF5aW5nRmVhdHVyZXNNaW5QZXJjZW50YWdlIjoxLCJpY29uIjp7InJlbmRlciI6Imh0dHBzOi8vdXBsb2FkLndpa2ltZWRpYS5vcmcvd2lraXBlZGlhL2NvbW1vbnMvNS81MC9HcmVlbl9BcnJvd19VcC5zdmcifSwid2lkdGgiOnsicmVuZGVyIjoiNCJ9LCJpY29uU2l6ZSI6eyJyZW5kZXIiOiIyMCwyMCxjZW50ZXIifSwiY29sb3IiOnsicmVuZGVyIjoiIzBmMCJ9LCJwcmVzZXRzIjpbeyJ0YWdzIjpbInNwb3J0PWNsaW1iaW5nIiwiY2xpbWJpbmc9cm91dGUiXSwidGl0bGUiOnsibmwiOiJLbGltcm91dGUifSwiZGVzY3JpcHRpb24iOnsibmwiOiJFZW4ga2xpbXJvdXRlIG9wIHJvdHMifX1dfV0sInJvYW1pbmdSZW5kZXJpbmdzIjpbXX0=). I'm posting it here as it can serve as some inspiration. Note: under the 'share'-tab, you can find a link to the custom generator to edit the theme.

**Comment by chrneumann** [comment]
Thanks, I'll have a look!

**Comment by chrneumann** [comment]
Ok, some thoughts:

You have two layers, climbing opportunity and route. I thought about having more layers, for example do differentiate climbing gyms, boulders and cliffs. That would lead the problem that the tag configuration / questions will have to be repeated for all of them. Which is already the case for your implementation: You support climbing:grade for routes, but not for the climbing opportunities.

How would you do that? Is there a way to define the tags/questions in one place and refer to it in another? Or would you copy the definition? Or just use one big layer? Are there similar use cases in other layers/themes?

Thanks :)

**Comment by pietervdvn** [comment]
Hey,

Yes, this is possible - these are the 'RoamingRenderings' - tagrenderings added to every layer. With the 'condition' certain layers can be excluded. An example usage can be found [here](https://github.com/pietervdvn/MapComplete/blob/master/assets/themes/buurtnatuur/buurtnatuur.json#L338), they can also be added in the custom Generator, under the 'layer' section, then 'Add layers'-section - as can be seen on the bottom of the following screenshot:

![image](https://user-images.githubusercontent.com/1466478/99248562-f4fcf500-2808-11eb-8991-bf88d6ba4250.png)

Another hint: read through the JSON-interface-definition for [TagRenderings](https://github.com/pietervdvn/MapComplete/blob/master/Customizations/JSON/TagRenderingConfigJson.ts), [Layers](https://github.com/pietervdvn/MapComplete/blob/master/Customizations/JSON/LayerConfigJson.ts) and [Layouts](https://github.com/pietervdvn/MapComplete/blob/master/Customizations/JSON/LayoutConfigJson.ts). That should help. Also: please let me know if something is unclear, AFAIK are you the first to read them so things might still be unclear.


(BTW: I saw your twitter and your CCC-affection - [your probably gonna like this theme too](https://pietervdvn.github.io/Staging/surveillance.html?z=14&lat=50.92143&lon=4.38363); if CCC would be happening this year, we would could had a chat IRL...)

**Comment by pietervdvn** [comment]
PS: my previous theme was very unfinished and was just to get you on track - if you end up not using anything from it, that is fine by me.

**Comment by chrneumann** [comment]
Thanks! Just tried the RoamingRenderings feature but can't get it to work: https://gist.github.com/chrneumann/7d3270854c76ce931a920b4466e1bba5

The length tag won't show up. I looked at the sources, but there is no reference to "roamingRenderings" of the LayoutConfig class beside of the generator. Is it even in use in the master branch?

(Yeah, let's try to meet at the next CCC, whenever that happens :) )

**Comment by pietervdvn** [comment]
> Is it even in use in the master branch?

Oops, no, seems like I broke that in a refactoring... 
Will fix tonight.

**Comment by chrneumann** [comment]
Ok, nice, works :) Still, I'm unsure what to do with general tags like website, opening_hours, ... Is there a way to reuse them (does this have anything to do with SharedLayers?).

**Comment by pietervdvn** [comment]
Hey Christophe,

General tagRenderings can be found in [questions.json](https://github.com/pietervdvn/MapComplete/blob/master/assets/questions/questions.json) - or at least, the `website` tag and icons for wikipedia and wikimedia.

They can be summoned by placing their name instead of the tagrendering in the `tagrenderings`-array in the json-file. It is not (yet) possible to add those in the customGeneratorUI.

Feel free to add some general tagrenderings there, I'll gladly join more PR's ;)

I'll also update the docs a little bit on that.

**Comment by pietervdvn** [comment]
I have pulled the climbing theme back into the main MapComplete instance and made various improvements on the go (such as reviews and opening hour indications).

@chrneumann Feel free to update kletterspots.de with it and to add more if you want to; for now, I'm happy with the result so I'm closing the issue.

**Comment by chrneumann** [comment]
Thanks! I'll created a PR with the missing translations.

You added questions for the route grading. In the OSM wiki it's recommended to use the UIAA grading system. I would suggest to use this for the question and only display french and other ratings. Or have both? Note sure. In Germany, the FB scale is used in boulder gyms, and the UIAA in rope climbing gyms.

**Comment by pietervdvn** [comment]
Well, it depends. In Belgium I've only seen the french system used, whereas Germany uses the UIAA-system mostly: https://www.guidedolomiti.com/en/rock-climbing-grades/

Good question on how to proceed; we can do both and e.g. only show one as long as the other isn't filled in or something.

**Comment by chrneumann** [comment]
Ah, didn't know that the UIAA is not that common. In fact, the Wiki also recommends to "Map the usual one(s) for the climbing spot". Which makes sense. But that would mean having questions for all the systems. Or being able to have a question "Which grading system?" without a tag but which can be used to choose the next questions. Or having a table. Kinda difficult.
