### ISSUE TITLE
Cyclofix redirect does not work

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#330]
When I open https://cyclofix.osm.be/map/, i see

> This instance of mapcomplete has moved. To use the production version, go to mapcomplete.osm.be Redirecting you to the development version

But the redirect does not happen.

Only once I open the URL of the given iframe directly (https://pietervdvn.github.io/MapComplete/cyclofix.html?z=14&lat=50.843&lon=4.3535), I am redirected to https://pietervdvn.github.io/mc/develop/cyclofix.html?#welcome

# Quickfix suggestion

Change the wording:

> This instance of MapComplete has moved. 
> Please use the production version at https://mapcomplete.osm.be/cyclofix.html?#welcome
> or the development version at https://pietervdvn.github.io/mc/develop/cyclofix.html?#welcome

with Links being clickable with `target=_parent`.

**Comment by pietervdvn** [comment]
Even better: I fixed the upstream cyclofix.osm.be website. Thanks for pointing out the breakage!
