### ISSUE TITLE
Charging theme: "you can charge your bike without risk of theft of the adaptor"

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#358]
At some cycle charging stations, you're supposed to just leave your charger out in the open. These things cost good money, so they are prone to theft. Apparently, some bicycle charging stations have a system where you can "lock your charger in", so this risk isn't there. Here's an example: https://mapcomplete.osm.be/charging_stations?z=18&lat=50.73627&lon=4.235851#node/8821265447

To do:
- [ ] find or make a data model
- [ ] add a question to the charging theme

**Comment by pietervdvn** [comment]
Moved into #387
