### ISSUE TITLE
Add required rope length as a property for climbing sites

### ISSUE THREAD

**Issue by ladc** [pietervdvn/MapComplete#361]
Many climbers have a 60m rope but some sites require longer ropes. To avoid injury or death it is useful to list the required rope length (twice the height of the highest route or pitch).

**Comment by chrneumann** [comment]
There is the length property of the route (climbing:length) that should suffice. Is there a problem with this?

**Comment by joostschouppe** [comment]
When trying to add the info [here](https://mapcomplete.osm.be/climbing?z=15&lat=50.36223&lon=5.461192&tab=2#node/8781421258), the length question doesn't appear. Maybe it's conditional to other questions?

**Comment by chrneumann** [comment]
It has to be climbing=route|sport|traditional. The latter two will be set by other questions ("is sport/traditional climbing possible here").

**Comment by pietervdvn** [comment]
I took this issue as an opportunity to update the climbing theme on mapcomple.osm.be and to take advantage of some new features.

Small overview of the most prominent changes:

- The rope length is now also asked on climbing gyms
- On a route, the length is asked by default
- Ask for the number of bolts
- Ask rock type on climbing=crag
- An encompassing feature (climbing=crag or climbing=area) now detects which climbing=route's are embedded and will compile a small histogram (soon on production):

![image](https://user-images.githubusercontent.com/1466478/122748832-eee26180-d28c-11eb-8b49-46ca009cc761.png)

**Comment by ladc** [comment]
Very useful, thanks!
