### ISSUE TITLE
Prevent loading all images associated with a feature

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#365]
When a lot of images are associated with e.g. a Wikidata item that is tagged on a feature, MapComplete seems to load all of these images. This is a challenge for browsers. Perhaps the amount of pictures that MapComplete tries to load should be limited.

example (be aware that this will stress test your browser):
https://mapcomplete.osm.be/artworks.html?z=19&lat=51.20921&lon=3.224723#way/354948557

**Comment by pietervdvn** [comment]
The images are currently limited to about 10 items.
