### ISSUE TITLE
Is hideUnderlayingFeaturesMinPercentage still doing something?

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#368]
I have `"hideUnderlayingFeaturesMinPercentage": 0` in my theme (it ended up being there as it was also used in the theme I started to work with initially). It seems to be in use in quite many of the existing themes and layers, but I don't find any reference to that property in the codebase, so I'm wondering if that thing is actually doing anything (any longer)?

**Comment by pietervdvn** [comment]
This is indeed an old feature, used by the first theme (http://buurtnatuur.be) and it was used to hide e.g. pieces of forests in a park (as in that case only the park was relevant).

It is now possible to do this with a caulcated tag (using 'overlapWith') and [showIf](https://github.com/pietervdvn/MapComplete/blob/master/Customizations/JSON/LayerConfigJson.ts#L89)

It is still generated by the custom theme generator though, but they are indeed ignored. I should clean them up one day though
