### ISSUE TITLE
Testing server

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#369]
I'm wondering if it would be possible to have an instance of MapComplete that is connected to testing APIs of OSM only, so that one can try out themes without modifying the real OSM database.

If I remember correctly, there is a development API that could be used for uploading changesets, although I'm not sure which one of those this would be:
https://apis.dev.openstreetmap.org/

Probably it would also be required to have an Overpass instance that provides data from the OSM testing instance; I'm not sure that exists. (We could ask the people running Overpass instances)

**Comment by sebkur** [comment]
sorry, I forgot for a moment that in development mode changes just won't be saved, so this is probably not required at all

**Comment by sebkur** [comment]
Is there a way to enable the testing mode on a normal MapComplete instance (some magic parameter or something?)

**Comment by joostschouppe** [comment]
Yep, just add test=true behind the ? and before the first #
All URL parameters are documented here: https://github.com/pietervdvn/MapComplete/blob/master/Docs/URL_Parameters.md
Still might be fun to be able to actually write to the dev server, but probably not needed right now

**Comment by sebkur** [comment]
thanks

**Comment by pietervdvn** [comment]
Already possible - see the backend url parameter: https://github.com/pietervdvn/MapComplete/blob/master/Docs/URL_Parameters.md#backend

**Comment by sebkur** [comment]
ah, awesome
