### ISSUE TITLE
Buurtnatuur: scrub (struikgewas) wordt als bos gelabeld

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#37]
In Buurtnatuur wordt natural=scrub (struikgewas) als "bos" gelabeld. Dat zorgt soms voor vreemde resultaten.

**Comment by pietervdvn** [comment]
Hey Seppe,

Ik weet het, en ik ben er nooit toe gekomen om dit deftig te fixen. Aangezien buurtnatuur.be zelf pretty much dood is (21 oktober de laatste significante edit, de voorbije twee maand slechts twee andere edits) ga ik deze issue sluiten.

Mocht er volgend jaar een reincarnatie komen van het thema, kom ik er op terug.
