### ISSUE TITLE
Tailwind: Test JIT Compiler

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#371]
The new JIT Mode in TailwindCSS could solve https://github.com/pietervdvn/MapComplete/issues/201.

Video / Intro into JIT: https://youtu.be/DxcJbrs6rKk
Also https://www.youtube.com/watch?v=3O_3X7InOw8 for a more extensive intro.

https://github.com/tailwindlabs/tailwindcss/releases talks about Parcel not being compatible, yet, but it also gives a alternative solution:

>If you discover your build tool isn't yet compatible with the new dependency tracking system, you have two options:
>
>Compile your CSS separately using the new Tailwind CLI. You can use packages like npm-run-all or concurrently to compile your CSS alongside your usual development command by adding some scripts to your project like this:
>
>// package.json
{
  // ...
  "scripts": {
    "dev": "npm-run-all --parallel dev:*",
    "dev:server": "vite",
    "dev:css": "tailwindcss -o src/tailwind.css -w",
    "build": "tailwindcss -o src/tailwind.css && vite build",
    "serve": "vite preview"
  },
}

I think this is worth testing out since it would reduce the css filesize by a lot and make development more flexible. I will try to look into it if I find the time; but that a big _if_, unfortunatell.

**Comment by tordans** [comment]
# Update

I confirmed, that the css file that is generated by Tailwind currently is 3.3 MB (non compressed). So this issue is still a worthy effort. 

It tried getting the app running on my new M1, which does not work, yet. https://github.com/pietervdvn/MapComplete/issues/475 is the current blocker.

Notes about what I would like to try:

- remove the old TW stuff `npm uninstall tailwindcss postcss autoprefixer` (https://tailwindcss.com/docs/installation#post-css-7-compatibility-build)
- setup latest tailwind without postcss and with JIT mode (https://tailwindcss.com/docs/just-in-time-mode)

Something like…
```
    "start": "start:prepare && npm-run-all start:parcel",
    "start:prepare": "ts-node scripts/generateLayerOverview.ts --no-fail && npm run increase-memory",
    "start:parcel": "parcel *.html UI/** Logic/** assets/*.json assets/svg/* assets/generated/* assets/layers/*/*.svg assets/tagRendering/*.json assets/themes/*/*.svg assets/themes/*/*.png vendor/* vendor/*/*",
```

The goal is, to have parcel and tailwind live next to each other (with no special glue like postcss) and hand over the css file whenever needed. This works with live reloading as well.

**Comment by pietervdvn** [comment]
This is pretty cool! I'm not very good with configuring tailwind, but if you can get these improvements working, that'll be great and I'll gladly merge the PR

**Comment by tordans** [comment]
I think I got it working 🥳  :-D.
