### ISSUE TITLE
Include query parameters in redirect

### ISSUE THREAD

**Issue by FloEdelmann** [pietervdvn/MapComplete#381]
I've shared a shortlink to the benches map, centered and zoomed to my home town:
https://t1p.de/sitzbank links to https://pietervdvn.github.io/MapComplete/benches.html?z=15&lat=48.10276&lon=11.77953
(Fun fact: that shortlink was also published in the local newspaper twice: [LeVa 01/2021, page 6](http://lebendiges-vaterstetten.info/pdf/LeVa_01_2021.pdf) and [LeVa 05/2021, page 4](http://lebendiges-vaterstetten.info/pdf/LeVa_05_2021.pdf))

Now, the MapComplete URL changed to https://pietervdvn.github.io/mc/develop/benches.html, and the old link redirects the user to that new URL automatically. Unfortunately, all query parameters (zoom, latitude, longitude) are lost during the redirect. So now when entering the shortlink, the map is not centered and zoomed in anymore, but showing the whole world.

Is it possible to include the query parameters (all or only those three) when the redirect happens?

**Comment by FloEdelmann** [comment]
Including the hash would also be nice, as there is another shortlink https://t1p.de/gogabank that links to a specific bench: https://pietervdvn.github.io/MapComplete/benches.html?z=17&lat=48.11207&lon=11.77752&fbclid=IwAR0aAEjSMtIEWJJBdY3SW2oILHqw6Bbqra319MvtBZT4qSwv6DPZOKJSRRc#node/8678747533

That link is even more broken, as it is also redirected to just https://pietervdvn.github.io/mc/develop/benches.html?#welcome

**Comment by pietervdvn** [comment]
Fixed

**Comment by pietervdvn** [comment]
PS: in the future, refer to 'mapcomplete.osm.be' as that is a more permanent link.

**Comment by FloEdelmann** [comment]
Nice, thank you. I'll use the official URL from now on.
