### ISSUE TITLE
new units feature: leave a space between the value and the units

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#383]
If you enter a value using the new units feature, it will be registered without a space between the value and the units. This is seen as a "common mistake", according to https://wiki.openstreetmap.org/wiki/Map_features/Units

**Comment by seppesantens** [comment]
Some issues left:

![image](https://user-images.githubusercontent.com/17066627/124375412-58f20200-dca2-11eb-9ffb-d228c82c7ff2.png)

![image](https://user-images.githubusercontent.com/17066627/124375434-76bf6700-dca2-11eb-98d5-5a101d6fb550.png)

**Comment by pietervdvn** [comment]
Oh, these are fixed on develop already, but not on the feature branch as the feature branch was merged in develop and is abandoned now.

**Comment by seppesantens** [comment]
Ok, my bad.
Then I think it just comes down to adding a space here: 
![image](https://user-images.githubusercontent.com/17066627/124394131-4c02fc00-dcfe-11eb-8674-fffd9f582015.png)

**Comment by seppesantens** [comment]
Sorry, a bit confused here. How should I test the develop version?

**Comment by seppesantens** [comment]
That still gives issues when I try to enter a new value. not sure what is going wrong

**Comment by pietervdvn** [comment]
[Now it works!](https://pietervdvn.github.io/mc/develop/?z=13&lat=51.23306&lon=3.529443&userlayout=https%3A%2F%2Fraw.githubusercontent.com%2Fseppesantens%2FMapComplete-Themes%2Funits%2FOpenWindPowerMap%2FOpenWindPowerMap.json#node/5359022299)

You'll also want to set [eraseInvalidValues](https://github.com/pietervdvn/MapComplete/blob/19d34454af90631334a38500227153dc37e09ed4/Customizations/JSON/LayoutConfigJson.ts#L260) as to make sure that 'generator:output:electricity=yes' gets ignored and triggers the question.

**Comment by seppesantens** [comment]
Great! I've added the eraseInvalidValues.
