### ISSUE TITLE
make charging stations useful

### ISSUE THREAD

**Issue by cauerego** [pietervdvn/MapComplete#386]
look at plugshare. and miio. and this: https://mapcomplete.osm.be/index.html?userlayout=https://raw.githubusercontent.com/avataranedotas/mapcomplete/main/postos_B009.json#welcome

there are many things still missing. here are a few key ones from the top of my mind:

- charging speed. this is crucial! it should be simple to filter and see in the map the differences, above all.
- what kind of plug is available. also need a filter.
- access: not all are public. not all public is free. not all stays open 24/7. filter and visibility would be nice.
- emergencies offer many more options, including home owners, small business and temporary luck.

as it is, the map is basically useless for real use case.

in my case, i also need a fine filter for speed. normal stations (that can go from 3 to 20kwh), if it's 3 or 6 makes the whole difference!

ps: i never ever seen a charging station for bikes, nor do i own any bike.

**Comment by seppesantens** [comment]
Starting your own theme is of course a great way to get to know MapComplete, but you could also get a headstart by adding to an existing theme like https://mapcomplete.osm.be/charging_stations.html?#welcome It's not really clear from your post whether you want features added to the existing theme in the MapComplete repository or to your own theme.

For some of the features you mention, like the charging speed, the data model described on the wiki does not provide a solution. In those cases, it would be good to first have a consensus on how we should map/tag these features.

**Comment by pietervdvn** [comment]
> https://mapcomplete.osm.be/index.html?userlayout=https://raw.githubusercontent.com/avataranedotas/mapcomplete/main/postos_B009.json#welcome

Well, this is a pleasant surprise! Didn't know this one ;)

**Comment by pietervdvn** [comment]
I'm closing this because:

- I'm gathering everything in #387 
- The issue itself is more a collection of "I want this" then a really actionable issue

**Comment by cauerego** [comment]
thanks for all feedback.

can't wait to see a useful theme, regardless of which one! 😘

ps: i didn't create any themes.

**Comment by seppesantens** [comment]
@cauerego Ah yes, now I see. I thought you were linking to a theme you created yourself, but that's obviously not the case.
