### ISSUE TITLE
Charging stations theme

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#387]
One issue to bundle all improvements and documentation links for the charging stations

## Target audience

The theme should cater to:

- The user of an electric vehicle searching for a charging spot (will need filtering functionality)
- Agencies who wish to complete charging station data in their territory

## Documentation and resources

- [The OSM wiki page on charging stations](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station)
- [Overview of plugs on wosm](https://wiki.openstreetmap.org/w/index.php?title=Key:socket&uselang=en)
- [Plug icons (wcommons)](https://commons.wikimedia.org/wiki/EV_Charger_Gallery)
- [Another, unofficial MC-theme](https://github.com/avataranedotas/mapcomplete)
- ~[Improvements made by Joost](https://github.com/osmbe/play/blob/master/mapcomplete/charging_stations.json)~  (all changes pulled in)
- [https://www.plugshare.com/](https://www.plugshare.com/) has a lot of plug types listed - icons are not CC probably though!

## States of charging stations

We should visually reflect the state of a charging station:

A charging station can be:

- [x] Operational
- [x] Under construction, planned
- [x] Disused
- [x] Only suited for bicycles/cars or both (we might mention other vehicles in the popup, but these are not the core audience)
- [x] Private access only
- [x] Access during certain hours only

## Tags to ask questions for

- [x] Network
- [x] Operator (if not part of a network - see #250)
- [x] Capacity  (as in number of cars)
- [x] fee + charge
- [x] socket:<type>:amperage
- [x] parking:fee
- [x] payment=*
- [x] maxstay
- [x] Contact info
- [x] ref

**Comment by pietervdvn** [comment]
## Stretch goals

### You can charge your bike without risk of theft of the adaptor

Proposed by Joost in #358

At some cycle charging stations, you're supposed to just leave your charger out in the open. These things cost good money, so they are prone to theft. Apparently, some bicycle charging stations have a system where you can "lock your charger in", so this risk isn't there. Here's an example: https://mapcomplete.osm.be/charging_stations?z=18&lat=50.73627&lon=4.235851#node/8821265447

To do:
- [ ] find or make a data model
- [ ] add a question to the charging theme

**Comment by pietervdvn** [comment]
### Asking for amenities (e.g. bicycle cafés) if they offer a charging station

I'd rather not do this, but let them map a charging station seperately. The calculated tags can still link to it though!

**Comment by joostschouppe** [comment]
RE amenities with charging stations: I agree it is better to map seperately whenever possible. I wonder how much of the cafés etc that offer this really do this in a formal way - for example, maybe they just offer this as a service "behind the bar": give them your battery and charger and they'll charge it for you. More research necessary :)

**Comment by joostschouppe** [comment]
The plug types for cars make little sense for bikes I think
Bicycle charging is often free, so you could first ask "Do you have to pay to use?" and only if yes, ask the payment options question

**Comment by Thierry1030** [comment]
Is it an option/desirable to integrate the charging stations (only the ones for bicycles) in Cyclofix?

**Comment by pietervdvn** [comment]
> The plug types for cars make little sense for bikes I think

There migth be some BOSCH-specific plugs IIRC, but charging stations for them are probably pretty rare. Needs more research

> RE amenities with charging stations

Might also be interpreted as 'there are wall plugs available if you sit in the restaurant, you can use it while you eat'. More research needed

> Is it an option/desirable to integrate the charging stations (only the ones for bicycles) in Cyclofix?

Technically definitively possible, however, this should be done with care. I can show only the ones explicitely marked for bicycles at high zoom levels, but will have to show _all_ charging stations at high zoom levels to prevent the addition of duplicate entries.

**Comment by avataranedotas** [comment]
Currently the theme:
- is only showing the number of ChaDeMo plugs
- is not showing the other plug types and numbers
- is not showing plug power
- ChaDeMo plugs are not type 4, they are just ChaDeMo
- is not showing whether parking is free or paid
- is not showing which payment methods are accepted by the station
- is not showing different icons for slow, fast, or super fast chargers
- is not showing operator contacts (phone, email)

You can check the latest version of my theme at: https://mapcomplete.osm.be/index.html?userlayout=https://raw.githubusercontent.com/avataranedotas/mapcomplete/main/postos_B009.json

**Comment by pietervdvn** [comment]
Hi @avataranedotas ,

Thanks for reaching out!

I did discover your theme previously and it served as a big inspiration though, even though the Portugese was a bit hard to get for me.

> is only showing the number of ChaDeMo plugs

Not all plugs were already added, I've added a few more in c9f20795 (and I removed the 'type 4' from chademo).

> is not showing plug power

I suppose that every plug has a fixed voltage, but the amperage (and thus the total power) can be different? Is a list available of which plug offers what voltage? I'm compiling all the information [in this csv file](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/charging_station/types.csv) which is then compiled into the theme. (Note: PR's are very welcome to improve this list - e.g. with an extra column of default voltages/power outputs !)

> is not showing different icons for slow, fast, or super fast chargers

What makes a charger a fast or slow charger?

**Comment by pietervdvn** [comment]
@joostschouppe @avataranedotas (and of course all the others): _What are typical costs_ for using a charging station?

Is the cost expressed per time? Or per kWh?

**Comment by avataranedotas** [comment]
> @joostschouppe @avataranedotas (and of course all the others): _What are typical costs_ for using a charging station?
> 
> Is the cost expressed per time? Or per kWh?

The cost can be expressed in time, per kWh, per session, or a combination of those 3.
In the case of my country (Portugal) it is worthless to put the price of charging on OSM because the price will vary according to the card you use to activate the station (different providers with different price schemes) and the price will also be different according to the time of day and day of the week.

Prices can vary wildly according to the type of charger and location.
Prices per kWh can vary from as low as 0.15€ to 1.00€ per kWh.
Prices per time can vary from 0.02€ to 0.20€ per minute.

**Comment by pietervdvn** [comment]
Hi everyone here,

A version with all these features is up and running on the main mapcomplete instance.

All of the aforementioned features are implemented there. Could you all please test them?

**Comment by avataranedotas** [comment]
On first glance I see that the plugs "type2_cable" are not being shown.
"type2" plugs are just a socket and you need to bring you own cable
"type2_cable" plugs have the cable attached to the charging station, they are usually found on faster chargers

Also there are other types of plugs missing:
tesla_supercharger_ccs (can use the same icon as CCS)
tesla_destination

tesla_destination is particularly tricky to show an icon, because the plug is different in North American than the rest of the world

Check also [Key:socket](https://wiki.openstreetmap.org/wiki/Key:socket

**Comment by avataranedotas** [comment]
I also noticed the map icon for "under construction" stations is the same as "working" stations.

**Comment by pietervdvn** [comment]
I'm closing this issue as most of it is implemented
