### ISSUE TITLE
Don't create funny values in existing keys

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#39]
Example: https://www.openstreetmap.org/way/151775447

key | value
-- | --
access | toegankelijk, maar het is eigendom van Ter Dreve.
fixme | Freeform access tag used: possibly a wrong value

Maybe it's better to add a access:description tag, rather than an access tag and a fixme tag

**Comment by pietervdvn** [comment]
This changed as you proposed, the freerorm is nu saved as 'access:description'
