### ISSUE TITLE
cycle_infra core data model

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#397]
1. Is there a cycleway? (see https://github.com/pietervdvn/MapComplete/issues/410)
- No cycleway (`cycleway:both=no`)
- There is a shared lane (`cycleway=shared_lane`)
- There is a lane next to the road (`cycleway=lane`)
- There is a track, but no cycleway drawn seperately from this road on the map. (`cycleway=track`)
- There is a seperately drawn cycleway (Try to give a warning if people pick "track"?)
      - `bicycle=use_sidepath` if obligatory (de facto default in Belgium, though there is traffic sign F99 for optional paths)
      - `bicycle=optional_sidepath` if optional (common in Germany and exists in the Netherlands)
      - `cycleway=seperate` is implied if either of these two is filled in, but could be used if people don't know if the cycleway is obligatory or not

Note: we will create a questionaire per side of the street, see https://github.com/pietervdvn/MapComplete/issues/401

2. Is this a `cyclestreet`? (re-use from existing theme)
3. Is the road/the path `lit`? 
4. `maxspeed`

[if "Mixed traffic", no cycleway]
- `width:carriageway`
- `parking:lanes`
- `surface `(see StreetComplete)
- `smoothness `(see iD editor)

[if shared lane, lane or track - ask based on streetside]
* `cycleway:surface`=* (see StreetComplete)
* `cycleway:traffic_sign` (legal status D7, D9, D10 ) > implies segregated=yes/no
* `cycleway:width`
* `cycleway:smoothness`

[if lane]
What cycle markings are there? 
* tag to be invented? Values: "red strip", "red strip and white lines", "white lines only"
* might fit with `cycleway:separation` as well

[ if lane or track]
* `cycleway:buffer` (distance from curb to start of cycle lane)
* is the lane or track shared with pedestrians? / is it segregated

[if track]
* `cycleway:separation`: what kind of buffer is there? (trees, wall, parking strip, plants , rumble strip, curb, grass, hedge, bollards, ditch)
* [if the buffer is just a curb] Is the path elevated vis-a-vis the carriageway? (tag to be invented?)

## Maybe: hazard of doors from cars that are parked

Possibly hazard:bicycle=door_zone or [cycleway:doorzone](https://wiki.openstreetmap.org/wiki/Proposed_features/Key:cycleway:doorzone)

**Comment by SupaplexOSM** [comment]
A few additional notes:

**`bicycle=use_sidepath`** on the highway line should only be used if the separately mapped bike lane is compulsory (then plus `bicycle=designated` on the cycleway line) – but depending on the country or legal situation, this is often not the case. Here, where I'm living e.g. (in Berlin), only a few street-accompanying cycle tracks are compulsory to use and `bicycle=use_sidepath` would then not be correct at the highway line (because I would prefer/I'm allowed to ride on the street – it's more `bicycle=yes` or – better, but undocumented and currently rarely used – `bicycle=optional_sidepath`).

Also, I would like to mention the **`cycleway:separation`** scheme, which is currently under development, to map the type of buffer/protection/separation (like trees, curbs, bollards, railings etc.): https://wiki.openstreetmap.org/wiki/Proposed_features/cycleway:separation

(In addition, I would prefer to always include a **directional suffix** on cycleway tags, e.g. "cycleway:right=separate", but that's probably a matter of taste...).

**Comment by seppesantens** [comment]
In the "OSLO Fietsinfrastructuur" project of "Digitaal Vlaanderen", similar questions arise. Inspiration can be found in the reports and presentations here: https://data.vlaanderen.be/standaarden/standaard-in-ontwikkeling/vocabularium-en-applicatieprofiel-fietsinfrastructuur.html

**Comment by joostschouppe** [comment]
From Tim Couwelier on Element:
 wegcode is fairly clear on this, it's either signposted with signs like D7/D9 in which case color or material choice does not matter at all, or it's the area between two parallel stripe lines that's too narrow for car traffic.
by default, that last option can only be one-way cyclelanes
none of the 'suggestiestroken' hold any juridical value, but best practice is to avoid red for them (attempted to reserve that for cycleways with priority for the cyclists), it's either color (ideally oker) or some type of ground marking (i've seen 'marker nails', spaced 15x15 cm blocks, repeated cyclist symbols with 'sergeantstreep', ...
fietsstraat holds - in juridical sense - zero guidelines as to 'how it should look', just the traffic signs for it are formal
and now exist is both a zonal and non-zonal version (despite the latter often being placed as it it were zonal though)

**Comment by RobinLinde** [comment]
>     * tag to be invented? Values: "red strip", "red strip and white lines", "white lines only"
> 
>     * might fit with `cycleway:separation` as well

Theme now uses `cycleway:seperation` for lines, might be worth using [`cycleway:colour`](https://taginfo.openstreetmap.org/keys/cycleway%3Acolour#overview), since it's already being used.

**Comment by SupaplexOSM** [comment]
> [...] might be worth using [`cycleway:colour`](https://taginfo.openstreetmap.org/keys/cycleway%3Acolour#overview), since it's already being used.

It would be better to use `cycleway:[<side>:]surface:colour`, because it's about the colour of the surface? These tags are also more widely used.

**Comment by RobinLinde** [comment]
Implemented almost completely, apart from `parking:lanes` and `cycleway:surface:colour`

**Comment by Thierry1030** [comment]
bollards and cycle_barriers are already visualised. I would also add block, sump_buster and bus_trap

**Comment by Thierry1030** [comment]
for a node with traffic lights I would consider to add the green and red time

**Comment by Thierry1030** [comment]
and for a node with traffic lights I would also consider crossing:island
