### ISSUE TITLE
Changesets with new tags are not uploaded

### ISSUE THREAD

**Issue by AgusQui** [pietervdvn/MapComplete#399]
The new tags that are added with the questions are not being uploaded to OSM. I've already tried various themes. If new nodes are uploaded, but the added tags are not uploaded.

For example, here I answer a question in Open Toilet Map, and OSM does not upload:
![Example](https://i.imgur.com/rezZsyS.png)
In OSM: [node](https://www.openstreetmap.org/node/1228825448)

**Comment by pietervdvn** [comment]
Oops, that should not have happened... Sorry about that! Thanks for reporting, I've fixed it this morning
