### ISSUE TITLE
Show left and right of the road seperately

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#401]
To show the cycleway left and right
To be able to edit street sides separately

**Comment by pietervdvn** [comment]
0) Start from branch develop
1) LayerConfigOverview: how and where to configure the split? Create a decent format, document and check it with pietervdvn. Also make sure to configure which tags are applicable for a left/right switch
2) Wire this into LayerConfig.ts
3) Create a featureEventSource parelllizing the two roads; find a way to to identify the left and right feature and to stream tag changes back to the original object.
4) Make sure it works well with the split road feature! (Aka: the split road feature should split the _original_ road id)

**Comment by joostschouppe** [comment]
Current thinking:
- with leaflet plugin the result will look messy on the main map
- cyclosm shows a lot of the data already, so maybe not do the same in an uglier way
- TBD: what DO we show on the main map?
- for data input, we NEED to show the road sides seperately, like so: 
![afbeelding](https://user-images.githubusercontent.com/10122639/126321261-4fcbd491-1dac-4648-971d-3ea1f2e8504e.png)
- all questions related to a side of the road (is there a cycleway, what is the surface of the cycleway etc.) will be asked based on the color of the street side. Use something like "on the green side of the road" where green is colored green
- for answer options, let's include icons like [these](https://github.com/streetcomplete/StreetComplete/blob/master/res/graphics/cycleway%20graphics/lane_belgium.svg), not just text

**Comment by tordans** [comment]
@pietervdvn @joostschouppe could you give a short update about this feature (and the [road splitting](https://github.com/pietervdvn/MapComplete/issues/171)). My assumption is, that you planned to work on this for this years round of improvements but did not get to it, yet. And therefore, for now, there is no work planned on it? Do you still consider it a thing to do later? — I ask to evaluate when it would be a good time to work on a parking:lane Quest for MC which IMO only makes sense with this feature in place, first.

**Comment by pietervdvn** [comment]
This was indeed planned but we didn't have enough time. There is a fork where this is half implemented, but I'd lile to refactor the LayerConfigJson for these features.

Road splitting works half but might break relations in some cases (but is not tested yet). This is on the dev branch.

**Comment by pietervdvn** [comment]
Implemented on develop, [example theme here](https://pietervdvn.github.io/mc/develop/sidewalks.html?z=18&lat=51.21189&lon=3.217454&language=en#welcome)
