### ISSUE TITLE
Add a scalebar to the map

### ISSUE THREAD

**Issue by karelleketers** [pietervdvn/MapComplete#403]

**Comment by pietervdvn** [comment]
1) Think about the location of the scalebar. Where should it go? At the bottom or upper corner? Left or right? Or maybe in the middle? What on mobile? Should it only be shown on desktop? Maybe ask Hannah?

This should be triggerable by a feature switch - perhaps even the location should be settable by it.

- Add a feature switch in 'State.ts'
- Have a look in InitUiElements how they are handled there
- Add the feature switch in 'LayoutConfigJson.ts' and document what it does. Wire it in 'LayoutConfig.ts' as well, and make sure it gets overridden by the URL-parameters too (again, see how it is done with the other feature switches)
