### ISSUE TITLE
Mapping of points: crossings, traffic lights, bollards, etc.

### ISSUE THREAD

**Issue by RobinLinde** [pietervdvn/MapComplete#404]
## Crossing

- [x] `highway=crossing`
- [x] `crossing=*`
- [x] `bicycle=*`
- [x] `tactile_paving=*`
- [x] `crossing:island=*`

See the [wiki](https://wiki.openstreetmap.org/wiki/Key:crossing)

## Traffic lights

- [x] `highway=traffic_signals`
- [ ] `traffic_signals:direction=forward/backward`
- [x] `button_operated=*`
- [x] `red_turn:right:bicycle=yes/no`

Also view the [wiki](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtraffic_signals)

## Barriers

- [x] `barrier=bollard/cycling_barrier`
- [x] `maxwidth:physical=*`
- [x] `bicycle=*`

### Bollard

- [x] `bollard=*` for [type](https://wiki.openstreetmap.org/wiki/Key:bollard)

### Cycle barrier

- [x] `cycle_barrier:type=*`
- [x] `width:separation=*`
- [x] `width:opening=*`
- [x] `overlap=*`

More details in [docs](https://github.com/osoc21/BikeInfrastructure/blob/master/bollards.md)

**Comment by pietervdvn** [comment]
Some objects should be snapped to a road when placed. Wild idea: when #408 is implemented, we might reuse the 'add point to road' functionality to do this.

**Comment by RobinLinde** [comment]
```
[bbox:{{bbox}}]; way[highway~"^(motorway|trunk|primary|secondary|tertiary|unclassified|residential|living_street|service(motorway|trunk|primary|secondary)_link)$"]->.car; way[highway="cycleway"]->.bike; node(w.car)(w.bike); out;
```

**Comment by RobinLinde** [comment]
```json
    {
      "question": {
        "en": "Can a cyclist turn right when the light is red?",
        "nl": "Mag een fietser rechtsaf slaan als het licht rood is?"
      },
      "condition": [
        "highway=traffic_signals"
      ],
      "mappings": [
        {
          "if": "red_turn:right:bicycle=yes",
          "then": {
            "en": "A cyclist can turn right if the light is red",
            "nl": "Een fietser mag niet rechtsaf slaan als het licht rood is"
          }
        },
        {
          "if": "red_turn:right:bicycle=no",
          "then": {
            "en": "A cyclist can not turn right if the light is red",
            "nl": "Een fietser mag rechtsaf slaan als het licht rood is"
          }
        }
      ]
    }
```
