### ISSUE TITLE
Load vector tiles into basemap

### ISSUE THREAD

**Issue by karelleketers** [pietervdvn/MapComplete#407]

**Comment by pietervdvn** [comment]
- Start from the master branch, create a new branch from there (feature/vector-tiles)
- Have a look at what vector tiles are
- Have a look leaflet.js docs (also see minimap.ts)
- Have a look at the leaflet vector tile plugin

**Comment by pietervdvn** [comment]
Also relevant: BaseLayers.ts

**Comment by pietervdvn** [comment]
Superseded by #1182
