### ISSUE TITLE
Quest: glass containers

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#41]
In municipalities where there is no garbage collection of glass, it's really useful to know where they are, and information tends to be scattered! 
Originally proposed by @joostschouppe

**Comment by Thierry1030** [comment]
can this item be integrated in the "waste basket theme"?

**Comment by joostschouppe** [comment]
There's a first draft of a "container theme" here: https://hackmd.io/KVTLvVvWRVK9LXsjRHuW9A?view#JSON
Made by a few people from Flemish municipalities.

**Comment by RobinLinde** [comment]
Preview version of waste theme(#668) also includes glass containers: https://pietervdvn.github.io/mc/waste-theme/waste.html

**Comment by pietervdvn** [comment]
As the waste theme is published, this is implemented.
