### ISSUE TITLE
Input: cycleway types

### ISSUE THREAD

**Issue by arnodeceuninck** [pietervdvn/MapComplete#410]
First version finished (simple questions)
There still needs to be an option to specify the type per side of the road

**Cycleway types:**
- [x] **Fietsweg**  (los ingetekend) (`highway=cycleway` of `highway=path` met `bicycle=designated`)
- [x] **Fietsweg** (deel van de weg) (`highway=*` met `cycleway=track`)
- [x] **Fietstrook** (`highway=*` met `cycleway=lane`)
- [x] **Fietsstraat** (`highway=*` met `cyclestreet=yes`)
- [x] **Fietssugestiestrook** (`highway=*` met `cycleway=lane`)

**Comment by RobinLinde** [comment]
Related to #401

**Comment by joostschouppe** [comment]
Oh, this is an interesting tidbit (a comment from @westnordost [somewhere on the wiki](https://wiki.openstreetmap.org/wiki/Talk:Proposed_features/cycleway:separation#cycleway:left:lane:separation:width)):    
- 150 lines of code JUST for finding out what kind of cycleways there are left and right: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/main/java/de/westnordost/streetcomplete/quests/bikeway/CyclewayParser.kt
- 3106 lines of code JUST to test the above: https://github.com/streetcomplete/StreetComplete/blob/master/app/src/test/java/de/westnordost/streetcomplete/quests/bikeway/CyclewayParserKtTest.kt

**Comment by pietervdvn** [comment]
https://www.openstreetmap.org/way/115446299/history

Roads with 'highway=path; bicycle=designated' are not picked up. I hate this kind of tagging, but it should work as well

**Comment by RobinLinde** [comment]
> 
> 
> https://www.openstreetmap.org/way/115446299/history
> 
> Roads with 'highway=path; bicycle=designated' are not picked up. I hate this kind of tagging, but it should work as well

Should haven been fixed in https://github.com/pietervdvn/MapComplete/commit/c1d94cfdeee046ebd6412843b07bf4731d6964ea

**Comment by joostschouppe** [comment]
Looking at the code, seems like cycleway:left, cycleway:right and cycleway:both won't show up either

**Comment by joostschouppe** [comment]
I'm thinking "fietsstraat" should perhaps be a separate question, as in reality, unfortunately there are some cyclestreets that also have cycleways.

**Comment by pietervdvn** [comment]
Fietsstraten should definitively be a seperate question, see for example [here](https://www.mapillary.com/app/?pKey=912125009565869&focus=photo&lat=50.83905&lng=4.3821083333333&z=17&x=0.3482885246527505&y=0.4803679104349583&zoom=1.8858093126385809) (cyclestreet + traffic in one direction, shared busway in another) or [here](https://www.mapillary.com/app/?pKey=814128082871260&focus=photo&lat=51.10567222222201&lng=4.328016666666713&z=17&x=0.2598100128249191&y=0.6761960272832449&zoom=1.043659440186551) (cyclestreet + traffic in one direction, suggestiestrook in the other direction)

**Comment by joostschouppe** [comment]
StreetComplete offers answer options with a neat little icon:
https://github.com/streetcomplete/StreetComplete/tree/master/res/graphics/cycleway%20graphics
These icons could also help to visualize the currently mapped situation

**Comment by joostschouppe** [comment]
Flow of the question:
- select a street side
- answer questions for that street side (say, cycleway:right)
- answer questions for the other street side (cycleway:left). Answering the same option as for cycleway:right:* creates a cycleway:* tag and removes the corresponding cycleway:right tag
- IF answer on left and right were the same, merge cycleway:left:* and cycleway:right=* tags
