### ISSUE TITLE
Translations of "Add a new {category} here" problematic

### ISSUE THREAD

**Issue by sebkur** [pietervdvn/MapComplete#419]
It's challenging to add proper translations for this string for languages that have different indefinite articles depending on the grammatical gender, as the article needs to be there but depending on what the category is, the article might not match...

I best understand it in German where it would need to be
* "Hier eine neue {category} hinzufügen" for female gender
* "Hier einen neue {category} hinzufügen" for male gender
* "Hier ein neue {category} hinzufügen" for neutral gender

I think in Dutch you don't have that problem similar to English, but other languages such as French will also have that issue.
I can see that in French it is solved like this: "Ajouter un/une {category} ici". I guess this is an OK workaround and in German we could hence have "Hier ein/e/n neue {category} hinzufügen" but is not optimal.

Are there any other options?

**Comment by pietervdvn** [comment]
That is a good point. BTW, in dutch we have a 'gender' too, with 'de' and 'het'.

I'm gonna think a bit about this one, as I don't see a solution right away

**Comment by sebkur** [comment]
yeah, I have a rusty memory about some memory I learned a few years ago... but for indefinite articles there's only "een" right?

**Comment by pietervdvn** [comment]
Yeah, we indeed have a catch-all with 'een' which is applicable for the 'Voeg hier een {category} toe'. Probably the reason this flew under my radar.

**Comment by pietervdvn** [comment]
By now, I've also dropped the 'new' part from the translations, as it is a bit more polished like that.

**Comment by pietervdvn** [comment]
I moved the article out of the general translation into every single preset for most languages, which should fix this issue: https://github.com/pietervdvn/MapComplete/commit/78b54d2fce99b10fa7521a7190ba49e2b48d6ee5

The default text is `Add {category} here`, the preset should now be `a hydrant`, instead of the older `Add a {category} here`.
