### ISSUE TITLE
Add a baselayer that would allow measuring objects

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#425]
These seem to be the the relevant GRB layers for road infrastructure:

![afbeelding](https://user-images.githubusercontent.com/10122639/125584802-00ddf401-a97b-401e-bdff-848d827a3fe2.png)

You can query them on https://geoservices.informatievlaanderen.be/raadpleegdiensten/GRB/wms with layer IDs like GRB_SNM

This is a stand-alone webmap [grb.zip](https://github.com/pietervdvn/MapComplete/files/6814423/grb.zip) where you can switch all these layers on and off.

Note: it seems roads on bridges aren't mapped in the same detail. You just have a KNW with the bridge itself.

**Comment by pietervdvn** [comment]
While definitively cool, it is quite a bit of work to setup for something that is too region-specific, so I'm not gonna implement this in the foreseeable future.
