### ISSUE TITLE
Analyze Erpe-Mere data, possibly use it as test data for the tool

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#427]
### FIETSWEG
Contains fietssnelwegen with attributes:
* width
* surface
* maxspeed
* lit

### FIETSPAD
Contains cycleways with attributes
* cycleway:width
* whether or not the cycleway is elevated re the roadway
* cycleway:separation (ribbelzone, parkeerstrook, ...)
* cycleway:buffer
* cycleway:surface
* road markings
* maxspeed
* lit (poor info)
* traffic_signals / roundabout (rare)

### ANDERE
Contains mixed traffic roads
* cyclestreet
* oneway
* carriageway:width
* surface
* maxspeed
* traffic_signals / roundabout (rare)

Surface types:
- asphalt
- paving stones
- concrete plates
- compacted
- unpaved
- other

## Geographical scope
* Erpe-Mere municipality
* Roads/paths that are part of the BFF (priority network for having good infrastructure, not visible in the field)

**Comment by RobinLinde** [comment]
https://qgiscloud.com/RobinVanDerLinde/Erpe-Mere/
