### ISSUE TITLE
Cycleway accessibility data

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#428]
Ticket for analyzing the data provided by Robin (inventory for Antwerp province)

## Cycleways
- classification somewhat similar to ours + some descriptions
- oneway
- surface
- "state of repair"
- width
- incline (which unit?)
- image

## Highway crossings
- unsafe (sometimes with reason in description)
- sometimes: "lowering for wheelchairs available", zebra, cycleway crossing, traffic signs, guidance for the blind, button to operate traffic sign
- image

## Obstacles
- damaged roadway
- bollard, lift beam (and free space next to it)
- level differences (think gutter, traffic calming, _borduur_, sump buster, incline), sometimes with height

## Waymarking signs
- just pictures of the cycle network waymarking

## Other POI
- picnic tables
- benches
- waste baskets

**Comment by pietervdvn** [comment]
For bollards: there is a new proposal: https://wiki.openstreetmap.org/wiki/Proposed_features/Advanced_cycle_barrier_tagging
