### ISSUE TITLE
better experience for new users who don't understand the tool yet

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#441]
- don't start the map at 0 0 0. If the map has no default starting place, it should probably start at the bbox of the country that people are accessing from. Or perhaps every default theme should have a starting point in an "interesting place" with a sufficient but non-crazy amount of data. 
- when people open a theme for the first time, they might not get the point. They just see an empty map and have to zoom or wait for data to load. Wait time can be a little long, and then people start to move around, which triggers a new data query and a new waiting time - and then they move again and they get an error. Maybe it would be better to extend the message "Data is being loaded - this can take a few seconds and starts again if you move the map a lot"

**Comment by pietervdvn** [comment]
1. The theme decides where the starting location is, so this can be set per theme. If the user has geolocation enabled (in a previous visit), the page will zoom to their location automatically. At this moment, it is a lot of work to figure out the broad location of the user _in a privacy respecting way_.

2. Wait times should indeed be improved, but that is a broader issue then usability.
