### ISSUE TITLE
Replace references to Maps.Me with Organic Maps

### ISSUE THREAD

**Issue by sfkeller** [pietervdvn/MapComplete#443]
There are quite some references to Maps.Me which turned has been bought by investors and became worse.

Proposal: Replace these references with Organic Maps https://organicmaps.app .

**Comment by pietervdvn** [comment]
Hi Stefan,

Yes, that would indeed be better. I'm currently swamped, but if you have some time, these references can be changed (by pretty much anyone) on the [weblate instance](https://hosted.weblate.org/projects/mapcomplete/core/)
