### ISSUE TITLE
Gps issues in Firefox 

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#444]
In the recent versions, location services seem messed up. The location and lock works perfect on chrome, but gives approximate fixes in Firefox.

**Comment by pietervdvn** [comment]
I did enable accurate position again, this should improve the situation; can you confirm?

**Comment by joostschouppe** [comment]
I just tried again. It starts off with the correct location (perhaps
because Osmand always has a recent fix in my device), and then quickly or
after a few soconds jumps to a wrong location a few hundred meters away.

**Comment by pietervdvn** [comment]
Try disabling 'network location services' on your phone - I had similar issues
