### ISSUE TITLE
Useful to ask for access restrictions for nodes that are not on a way?

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#450]
![image](https://user-images.githubusercontent.com/17066627/127571059-eb2eec32-2c25-49e2-84a3-0a07a6fb244a.png)

In this example, the bollards are in between the main road and the sidewalk, see https://www.mapillary.com/app/?pKey=299470418457285 I wonder whether it's useful to ask for access restrictions in these cases. It seems a bit weird to ask "Can a bicycle go past this barrier?" here.

**Comment by tordans** [comment]
FYI: The same topic was discussed in StreetComplete GitHub recently with the result to only ask if bollard is on a road. (Question about if it is removable/fixed though). https://github.com/streetcomplete/StreetComplete/issues/3017
