### ISSUE TITLE
Several typos throughout repo: "seperate" instead of "separate"

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#457]
See https://github.com/pietervdvn/MapComplete/search?q=seperate
These should be replaced by "separate".

(If no one beats me to it, I'll fix it myself, but I don't have the possibility to do it now)

**Comment by matkoniecz** [comment]
It would be also nice to cleanup added tags (I did it with `cycleway`) say in https://www.openstreetmap.org/changeset/109521274

**Comment by pietervdvn** [comment]
Also see https://www.openstreetmap.org/changeset/109190875
