### ISSUE TITLE
Bicycle rental brainstorm

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#466]
Things that users might want to map:

- The charge per day, per bicycle type
- payment, authorization, shop type, ...
- number of available bikes per type
- Which accessories might be rented (helmets, panniers, reparation kit, bicycle child seat)

**Comment by pietervdvn** [comment]
In the running, [proposal for tagging update](https://wiki.openstreetmap.org/wiki/Proposed_features/bicycle_rental:type) has been made

**Comment by Thierry1030** [comment]
the association where I am guiding already rents out bicycles ... for that I added the tag "service:bicycle:rental=yes" via Cyclofix ... soon we will also rent out ebikes, children bikes and a "follow me" ... do I continue to use service=ebike=rental=yes" or better rental=ebike" etc?
-> asnwer @pietervdvn : Eeuhm, it's always the edge cases that are the hard ones, where multiple services are combined 😉
In any case, i'd go for rental=bicycle;ebike;cargobike;.... As it isn't a shop, 'shop=(bicycle)_rental' is not applicable; neither is 'shop=bicycle'. amenity=bicycle_rental might be acceptable doubletagging though, but might also be not.

**Comment by pietervdvn** [comment]
Possible types of bicycles are `city_bike, trekking_bike, bmx, ebike, cargobike, tandem`. For disabled people: https://www.gsportvlaanderen.be/fiets-mee

**Comment by Thierry1030** [comment]
association that rents out touring and trekking bicycles and equipment to go "on cycle holidays" -> https://www.openstreetmap.org/node/9119366785
https://bike-packer.be/en/our-services/equipment-rental/

**Comment by Thierry1030** [comment]
> Possible types of bicycles are `city_bike, trekking_bike, bmx, ebike, cargobike, tandem`. For disabled people: https://www.gsportvlaanderen.be/fiets-mee

to consider to add: speed pedelec, children's bike, follow me, balance bike (loopfiets), penny-farthing (hoge bi, vélocipède)

and for cargobike perhaps also make a distinction between the "family bakfiets" to mainly transport children and the 'cargo bike" to mainly transport goods ...

**Comment by pietervdvn** [comment]
What is a 'follow me'? Or is this a copy-paste error?

**Comment by Thierry1030** [comment]
"follow me" -> not a copy-paste error.
It's a bicycle coupling to connect the children's bicycle to your own bicycle, creating a tandem.
https://followme-tandem.nl/#follow

**Comment by pietervdvn** [comment]
Oh, that's what they are called! There are also extensions like these: https://s3-eu-west-1.amazonaws.com/fietsersbond/app/uploads/2013/10/18104007/burleypiccolobest.jpg

**Comment by pietervdvn** [comment]
The bicycle rental page has been updated.

@Thierry1030 Would you feel up to the challenge of filling [the table over here?](https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dbicycle_rental#Types_of_bicycles)

The main challenge is to add a small description and to find an appropriate picture
