### ISSUE TITLE
NodeJS 16

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#475]
I am trying to get the app running on a M1 with a current NodeJS version (16.9.1). Which all works out just fine
- `npm run init` works
- `npm run start` works, more or less

I get this weird error about a .css file that is missing but not part of the repo. And it is not included anywhere that I can find (https://github.com/pietervdvn/MapComplete/search?q=imageUploadFlow)…

```console
> mapcomplete@0.0.5 increase-memory
> export NODE_OPTIONS=--max_old_space_size=4096

Server running at http://localhost:1234 
🚨  /Users/…/…/MapComplete/css/imageUploadFlow.css:undefined:undefined: ENOENT: no such file or directory, open '/Users/…/…/MapComplete/css/imageUploadFlow.css'
Error: ENOENT: no such file or directory, open '/Users/…/…/MapComplete/css/imageUploadFlow.css'
```

The browser shows 

```
🚨 Build Error
/Users/…/…/MapComplete/css/imageUploadFlow.css:undefined:undefined: ENOENT: no such file or directory, open '/Users/…/…/MapComplete/css/imageUploadFlow.css'

Error: ENOENT: no such file or directory, open '/Users/…/…/MapComplete/css/imageUploadFlow.css'
```

Any idea what that is about?

**Comment by pietervdvn** [comment]
Nope, no clue. Is this an old git repo that was recently updated? Try `npm run clean` to remove the cache (or remove the .cache directory and node_modules directory yourself)

**Comment by tordans** [comment]
I thought I tried all those debugging steps but now that I removed all files and did a clean checkout, this error is gone. Thanks for the help!
