### ISSUE TITLE
Remove slick-carousel

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#476]
Related to https://github.com/pietervdvn/MapComplete/issues/475

When running the app with node 16, I got this error.
I could not finde `slick-carousel` used in the app (did I miss it?) and `npm uninstall slick-carousel` resolved the issue.

It looks to me like an unused dependency.

Browser output:
```
🚨 Build Error
/Users/…/MapComplete/node_modules/slick-carousel/slick/slick-theme.css:undefined:undefined: ENOENT: no such file or directory, open '/Users/…/MapComplete/node_modules/slick-carousel/slick/slick-theme.css'

Error: ENOENT: no such file or directory, open '/Users/…/MapComplete/node_modules/slick-carousel/slick/slick-theme.css'
```

**Comment by pietervdvn** [comment]
slick-carousel is not used anymore. 

However, I can't seem to find any mention of slick-carousel in package.json or package-lock.json anywhere. Could this be an old leftover of your install?

**Comment by tordans** [comment]
I thought I tried all those debugging steps but now that I removed all files and did a clean checkout, this error is gone. Thanks for the help!
