### ISSUE TITLE
`InnerRenderAsString` does not exist

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#477]
While debugging https://github.com/pietervdvn/MapComplete/issues/475, I ran a `yarn tsc` to see if that shows any errors, which it did:

```console
$ yarn tsc           
yarn run v1.22.10
warning package.json: License should be a valid SPDX license expression
$ /Users/tobiasjordans/Development/OSM/MapComplete/node_modules/.bin/tsc
scripts/generateWikiPage.ts:24:10 - error TS2339: Property 'InnerRenderAsString' does not exist on type 'BaseUIElement'.

24         .InnerRenderAsString()
            ~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

It looks to me that this method does not exist in the code https://github.com/pietervdvn/MapComplete/search?q=InnerRenderAsString. I replaced it with `.toString()` which resolved the error.

If this is a relevant issue … and a OK solution, I can submit a PR.

**Comment by pietervdvn** [comment]
Yeah, this is a small script that I use seldomly to update [the wiki page](https://duckduckgo.com/l/?uddg=https%3A%2F%2Fwiki.openstreetmap.org%2Fw%2Findex.php%3Fsearch%3Dmapcomplete&rut=67ac60f200f96b152c1148f9b102113532ccd4dad77b94db26663b40525aa94c)

Please, send over the PR if this script works!
