### ISSUE TITLE
Questions with boolean answers

### ISSUE THREAD

**Issue by Cj-Malone** [pietervdvn/MapComplete#488]
Hey, I'm trying to working on a theme for OSM UKs upcoming quarterly project, Waste and Recycling. I'd like to collect data like owner and operator, but also types of recycling accepted such as `recycling:car_batteries=yes/no`. I think that means we need a "Freeform type" for bools. Or is there another way to ask yes/no questions?

**Comment by pietervdvn** [comment]
Hi,

This is done using the 'mappings'. If you set 'multiAnswer: true' in the question, the checkboxes show up. Note: this is not available in the custom theme generator, you have to write your JSON manually for this.

**Comment by pietervdvn** [comment]
An example can be seen here: https://github.com/pietervdvn/MapComplete/blob/2b78c4b53fce756e4d8076ad712444b60bafdc39/assets/layers/waste_basket/waste_basket.json#L31

**Comment by pietervdvn** [comment]
Also read through the docs: https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md#making-your-own-theme

**Comment by Cj-Malone** [comment]
Nice one, since we want 2 exclusive options I'd need `multiAnswer: false`, and it does indeed change it to radio boxes :)

So I'm currently looking like this:
```
{
          "question": {
            "en": "Accepts car batteries?"
          },
          "multiAnswer": false,
          "mappings": [
            {
              "if": "recycling:car_batteries=yes",
              "then": {
                "en": "This centre <b>accepts</b> car batteries"
              }
            },
            {
              "if": "recycling:car_batteries=no",
              "then": {
                "en": "This centre does <b>not</b> accept car batteries"
              }
            }
          ]
        }
```
Is there a way I can get this to be pre populated, when you go back to customise (pressing the pencil to the right) an already tagged answer?

Also is this a theme you would be interested in accepting upstream?

**Comment by pietervdvn** [comment]
You'd put in a value matching empty, and hide it from the answers:

``
{
              "if": "recycling:car_batteries=",
              "then": {
                "en": "This centre does not <b>accept</b> car batteries"
              },
              "hideInAnswer": true
            }
``

**Comment by pietervdvn** [comment]
Hi @Cj-Malone 

How is it going with the theme? Can you share a preview?

Also, there is a telegram/matrix channel where you can ask for help if you need some.

**Comment by Cj-Malone** [comment]
Honestly I've not done anything in the last 4 days, [this](https://github.com/osm-uk/TODO/issues/1#issuecomment-927183397) is what I got to.

**Comment by pietervdvn** [comment]
Hi @Cj-Malone ,

I'm gonna close this issue as stale. If you have more questions, make sure to reach out via [telegram](https://t.me/MapComplete) or [Matrix](https://app.element.io/#/room/#MapComplete:matrix.org)
