### ISSUE TITLE
Getting pictures from Wikimedia Commons seems to be broken

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#498]
![image](https://user-images.githubusercontent.com/17066627/135744182-43748f3f-123d-4302-a065-f416ad08b9aa.png)

**Comment by pietervdvn** [comment]
Works/fixed on develop: https://pietervdvn.github.io/mc/develop/artwork.html?z=19&lat=51.24091&lon=2.916062&language=en#node/5529739722

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/136199054-1f9422a0-8477-467f-8eaf-185bef3c4809.png)
It looks great now ;)
