### ISSUE TITLE
Cyclestreets - is "overtaking:motor_vehicle=no" necessary?

### ISSUE THREAD

**Issue by bxl-forever** [pietervdvn/MapComplete#519]
Those are the tags MapComplete adds to a way when the user declares it as a cycle street: "cyclestreet=yes" and "overtaking:motor_vehicle=no".
The latter seems to go against the "Don't map your local legislation"-principle.  For instance, in Belgium every cycle street has that rule.  I would tend to believe this implicit tag is not useful and should not be added at all.

If adding this tag is necessary, maybe we should update the wiki and recommend it explicitely.

**Comment by pietervdvn** [comment]
I've had some complaints that it _wasn't_ scoped to belgium: https://www.openstreetmap.org/changeset/116789721
