### ISSUE TITLE
Tree-Theme: Add new key:foraging

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#528]
There is a new key that might be interesting for the tree-theme:

Proposal https://wiki.openstreetmap.org/wiki/Proposed_features/key:foraging
> Whether or not foraging plants / fruit / fungi etc. is permissible for a given location or plant.

I interpret the proposal in a way, that especially fruit trees would benefit from both an `access` and `foraging` tagging.
For example an apple tree alongside a field might be access=yes, but foraging=no.

AFAIK the proposal was done by @jdcarls2, so he might know more :).

[Convenient link to a mapcomplete tree edit panel](https://pietervdvn.github.io/mc/develop/trees.html?z=19&lat=52.47423&lon=13.44707&language=en#node/3411198588).

**Comment by pietervdvn** [comment]
This is interesting, but:

- The key has very little use
- This is only useful to ask on trees which have edible fruits (or other edible parts). For this, the species of a tree should be known and it should be derived if the tree has edible fruits - this could possible be fetched from wikidata.

**Comment by jdcarls2** [comment]
Yeah, I really thought more folks would be in on it, given the initial response I got on the various OSM communications channels about `foraging`. I've been meaning to add more known locations to OSM that could use the tag, but, well, life gets in the way.

Regarding @pietervdvn 's 2nd point, though, foraging is for more than food! Many plants which produce nothing worth eating are still of interest to foragers for their flowers, bark, roots, or leaves. Tea, medicine, dye, etc.

Perhaps a more *useful* way of increasing the use of this tag and recording valuable information would be to ask the question on the **Into Nature** theme, to ask it of entire park areas.

In practice, `foraging=yes` and `foraging=permissive` are usually some private person's thing, and you only know about it from a conversation, hard to do with MapComplete. But `foraging=no` is usually signed, and foraging differs from general access, fishing, and hunting. In my area, many state and county properties will permit hunting and fishing during the appropriate season, but strictly prohibit harvesting plants at all times. In other areas, however, certain foraging activities are allowed, but with permits. I think it's worth noting these kinds of restrictions when they can apply to an entire area.

Maybe this theme idea could be transferred over to Into Nature?

**Comment by pietervdvn** [comment]
@jdcarls2 Certainly an interesting topic. I've commented on the wiki page, and I kindly invite you to create a PR to add the foraging-key on e.g. the forests layer.

**Comment by pietervdvn** [comment]
I'm gonna close this issue, as it has gone stale and there seems to be little interest in it.

I'll still gladly accept a PR adding this key though.
