### ISSUE TITLE
Bike theme shows two 'underground' and two 'surface level parkings'

### ISSUE THREAD

**Issue by habi** [pietervdvn/MapComplete#541]
I'm currently mapping bicycle parkings for the [PotM in Switzerland](https://wiki.openstreetmap.org/wiki/EN:Project_of_the_month_Switzerland).
The bike theme of MapComplete is great for this.
Today I saw that adding the relative location of the bike parking suggests 'Underground parking' and 'Surface level parking' both twice, as seen in the screenshot below.

![IMG_6396 (1)](https://user-images.githubusercontent.com/1651235/140192492-8d74b725-b8f8-4fa2-a8c6-cf502ea969d9.jpeg)

I *think* the problem lies in the lines 223ff in bike_parking.json, where - as far as I understand it - both are showing up twice in the code...
https://github.com/pietervdvn/MapComplete/blob/5fbc778624a419a565ecfc6bdfe5ecc05a11e053/assets/layers/bike_parking/bike_parking.json#L223

Is this deliberate, or could this be corrected by 'simply' removing the double-mention in the JSON file?

**Comment by pietervdvn** [comment]
Hi Habi,

Good find! Indeed, this got into the question twice and should not be there. Removing one of them should indeed suffice (but the translations might get confused though if you do this though).

**Comment by habi** [comment]
So, if I removed the 'offending' duplicates in the JSON in a PR here that wouldn't help?
I'm happy to try to contribute, but don't want to trip up other contributors/dependencies :)

**Comment by pietervdvn** [comment]
Yes, it would help, but you'll have to run `npm run reset:translations` after you made your change to update the translation files.
