### ISSUE TITLE
Etymology: many requests to Wikidata

### ISSUE THREAD

**Issue by NonnEmilia** [pietervdvn/MapComplete#551]
After using Open Etymology Map for a while (~5 minutes, both on Firefox and Chrome) I've seen many requests (in the order of hundreds) to Wikidata's servers, even when simply panning or zooming the map.

Should it be related to #530?

**Comment by pietervdvn** [comment]
Jup, definitively related.

The core issue here is that the wikidata-search box is reloaded to much for every previously opened feature and does a search (and rerender) every time again, even if it is hidden.

I've added in some caching, which alleviates this but not yet fixes this.

**Comment by pietervdvn** [comment]
This cannot be replicated in the latest versions, so is probably fixed.
