### ISSUE TITLE
Switch to a panel based UI (remove editing inside a box in the map)

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#552]
I notice that the editing UI inside a box on the map does not work very well for me. Especially with more complex editing experiences – Like anything that is more than a simple question-answer click. For example splitting lane, measuring distance and such.

An alternative – an IMO better – UI would be to have two panels.

Example UI: https://radparken.info/mitmachen/bahnhof/1

| Mobile | Desktop |
|---|---|
| <img width="512" alt="Bildschirmfoto 2021-11-07 um 06 43 40" src="https://user-images.githubusercontent.com/111561/140634214-f7c15a27-b647-440f-9882-efb385a57b51.png"> | <img width="1122" alt="Bildschirmfoto 2021-11-07 um 06 43 17" src="https://user-images.githubusercontent.com/111561/140634216-e693e00c-7985-4f6d-8186-0ee46ae0f7ad.png"> |

This UI still holds the interactivity of of the existing interface in the sense that the answer-mode is still allows to switch objects on the map. One might argue this is even easier, since the map is easier to navigate now.

This UI gives a clearer focus on the answer mode.

It prevents existing UI elements from overlapping with the answer UI. Which is something that happends right now, very easily and makes the Interface pretty hard to navigate. [Screenshot Source](https://pietervdvn.github.io/mc/develop/cycle_infra.html?z=20&lat=52.47294&lon=13.4363&language=en#node/31032851).
![image](https://user-images.githubusercontent.com/111561/140634260-bdbd46aa-c801-4ce1-95f5-e23af463e0ca.png)

**Comment by pietervdvn** [comment]
This topic is a bit of contentious one. Some people prefer the sidebar approach, others find the popup more intuitive. Both have their advantages and their drawbacks.

The popup is more integrated and less confusing for non-technical users, whereas the sidebar approach gives more room to the users to answer questions (and is technically easier).

I'm gonna leave this issue open and see if other people have opinions on this too.

**Comment by tordans** [comment]
@pietervdvn I wonder: What is blocking the sidebar path? It sounds like we both agree it's a lot cleaner and improves UX. Are there counter arguments that are strong enough to stop those improvements?

**Comment by pietervdvn** [comment]
Well, I'm not entirely sure that abolishing the popup _is_ more user friendly, as it increases the distance from the selected node to the questions.

This also implies that the selected node should be highlighted in some way

**Comment by tordans** [comment]
Let me try to explain why I think it is (more user friendly).

A map pin based UX is great for certain situations
- Small pieces of information are great, like a street name, maybe name+image
- Situations with large screens are great; meaning situations where the screen size is known, like business apps or display apps (museum, …). In those cases, even with big info panels work well.
- They are great, when the interaction is smooth: Clicking an element has a transition to the popover view and the transition does not trigger things that disturb my flow
- They are less great, when there is a lot of information
- They are less great, when the context becomes less important than the content of the panel. In other words: I use the map to select something (a task), but then I am focussed on this task. The map now is secondary; the UI should be optimized to solve the selected task

For MapComplete they are not great (anymore)
- It is _a lot_ of information in the panels
- It is _a lot_ of interaction in the panels
- There is even inception-kind-of-interaction happening, that is confusing in this UI (components to change the pin position or to calculating distance for example)
- MP is supposed to run on very different screen sizes and has a App-like-UI with floating UI elements. The current layout causes super complex "UI moments" like in [the screenshot above](https://user-images.githubusercontent.com/111561/140634260-bdbd46aa-c801-4ce1-95f5-e23af463e0ca.png) where the UI and the panel are in conflict
- MP is an app, where the map is used to select a task, but then the content of the task becomes the most important UI element. In the current UX the map does not help me anymore to understand "where am I" (see screenshot above), but instead is UI noise around my main task area that I need to filter out to work.
- The sub-tasks like "move pin" and "calculate width" are – from a usability point of view – much better suited for a split off view. For example, suggesting a position change to a POI in Google maps does not happen in the main app, but in an overlay which provides clear guidance and a clean context.
- Switching the UI would also solve the issue, that you click an element and the map needs to pan in order to show the super big info panel. Which in turn triggers a reload of data. Which is shown with a big notice _overlaying_ the info panel. — This can be optimized with preloading and improvements to the UI; it can also be solved by avoiding the issue :).

Is the user used to this kind of panel UI?
I think yes, given that all major map UIs work this way. On mobile and on desktop.
- Bing maps shows a left side panel for a POI https://www.bing.com/maps
- Google maps the same https://www.google.de/maps/place/PENNY/@52.4718628,13.4456237,18.3z/data=!3m1!5s0x47a84f755b35e30d:0x82223b0c1a01a2c9!4m5!3m4!1s0x47a84f7544d8ae19:0x9d99f11f6f13e277!8m2!3d52.4723311!4d13.4454548
- Apple maps the same https://duckduckgo.com/?q=penny%2C+Rixdorf%2C+berlin&t=h_&ia=web&iaxm=maps&strict_bbox=0&bbox=52.47393389830928%2C13.443892410064791%2C52.47133282249593%2C13.449192455078219&iai=15426261491445982513


I hope that helps to give some insights into my thoughts.

**Comment by joostschouppe** [comment]
A sidebar is only an option on large screens, right? That is also how MapContrib works, and I seem to remember I found that a little confusing at the start. But I do think it looks a little more stylish with a sidebar. I don't have a strong opinion either way, BUT I would really enjoy a feature where the loaded POI are summarized in the sidebar by default (ordered by their distance from the center of the screen). Clicking on the map POI would highlight/exactly and the content in the sidebar. Clicking on the sidebar POI would highlight the map POI. Especially if details of the poi are shown in the sidebar or in combination with the existing filter feature, that would be really fun

**Comment by tordans** [comment]
> A sidebar is only an option on large screens, right? 

No, it works great on mobile. I added example images in my initial message. It's not a "side"bar anymore, though. The idea is more about "a separate area that takes over the main focus from the map". I also have an example Link in my first message 
 https://radparken.info/mitmachen/bahnhof/1 that shows a version of this pattern. This can be optimized further, but it allows to see it in action – that is, if Google Maps is not enough to show the UI pattern in action.

----

About the list feature: IMO that is something an unrelated feature. It's also quite hard to get right from a UX point of view (syncing hover/select states between map and sidebar, especially when one of both has some kind of pagination (page based on the sidebar and most likely clustering based in the map).

**Comment by tordans** [comment]
@pietervdvn this sounds great. Is this on a staging env somewhere to test out? I was looking at https://github.com/pietervdvn/MapComplete#examples and the docs folder but could not find the staging/dev URL.
