### ISSUE TITLE
Regularly validate theme images

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#553]
I suggest to add a validation process that makes sure all images of all official themes are present.

Example: 
* Image https://pietervdvn.github.io/mc/develop/assets/themes/cycle_infra/Cycle_barrier_double.png shows a 404
* Its part of the second question in https://pietervdvn.github.io/mc/develop/cycle_infra.html?z=20&lat=52.47315&lon=13.4363&language=en#node/31032851
* <img width="400" alt="Bildschirmfoto 2021-11-07 um 06 59 56" src="https://user-images.githubusercontent.com/111561/140634352-01eb6a33-631c-4cc9-9586-d59c9f5ea10e.png">

A few ideas how this could happen:
* Use github actions to curl the images one a day and create issues for broken images.
* Extend the release script to check all curl the image on release an create a markdown table in this repo with a list of all checked images - with a focus on broken images
* Add error reporting JS (something like Airbrake or [of this sort](https://github.com/cheeaun/javascript-error-logging)) inside the app that sends an error report for broken images
* …

**Comment by pietervdvn** [comment]
This is peculiar, because they _are_ checked before upload.

Normally, all image links are extracted from the theme/layer files, checked that they exist and checked that they do have a license.

**Comment by pietervdvn** [comment]
Removed images did linger around in the license files, giving the impression that they still existed. These are now removed, so this shouldn't happen anymore.
