### ISSUE TITLE
Width measurement tool very hard to see

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#554]
The width measurement tool is nearly invisible when measuring smaller things.

Small thing – I cannot see it:
<img width="536" alt="Bildschirmfoto 2021-11-07 um 06 37 20" src="https://user-images.githubusercontent.com/111561/140634381-b172a079-a737-4d9f-895c-9379073a5ab8.png">

Larger circle – It is still hard to see but visible:
<img width="546" alt="Bildschirmfoto 2021-11-07 um 06 37 33" src="https://user-images.githubusercontent.com/111561/140634386-a5c1ec91-d9da-422a-9c8c-69eb149622ae.png">

**Comment by pietervdvn** [comment]
And it is pretty hard to use on mobile too, as a thumb will obstruct the view of this measurement.

Any ideas on how to improve this?

**Comment by pietervdvn** [comment]
As the 'width'-tool currently does not exist anymore, I'm closing this issue.

Feel free to create a new issue if you want the width measurement resurrected.
