### ISSUE TITLE
Add feature to edit tags correctly

### ISSUE THREAD

**Issue by TheAdventurer64** [pietervdvn/MapComplete#558]
When it comes to editing tags, many editors have a way to directly edit 
basic tags such as website and opening hours without the need to answer "survey" questions. To standardize Map Complete with other editors, I propose that basic tags like `website=*` should have their own editor, with the questions being removed.

**Comment by pietervdvn** [comment]
Hi,

Welcome to the repository.

Unfortunately, I'm not entirely getting what you are trying to say. Maybe a small image would help?

**Comment by TheAdventurer64** [comment]
Thanks for the welcome! I was thinking of something like this: ![image](https://user-images.githubusercontent.com/50059322/140845154-1a5fd51b-2074-4da5-9828-a0775efcde57.jpeg)

**Comment by pietervdvn** [comment]
Hi,

All this functionality is already implemented in e.g. the [shops theme](https://mapcomplete.osm.be/shops?z=19&lat=51.19698&lon=3.21691&language=en#node/2929614451). The only differerence is that one has to click the 'pencil' to change an attribute or click the 'move' button to move it around.
 Unknown attributes are asked one-by-one as not to overwhelm the contributor - but this can be changed [by setting a URL-parameter](https://mapcomplete.osm.be/shops?z=19&lat=51.19684&lon=3.216944&language=en&fs-all-questions=true#node/2929614451). 


And yes, there is input validation and normalization as welll.

Keep in mind that MapComplete does not aim to edit everything, but focusses on just a single topic at once. If you feel that a theme on pharmacies would be a good addition, [please go on and create on.](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md). When it is finished, I'll be very happy to include it!

**Comment by TheAdventurer64** [comment]
> Hi,
> 
> 
> 
> All this functionality is already implemented in e.g. the [shops theme](https://mapcomplete.osm.be/shops?z=19&lat=51.19698&lon=3.21691&language=en#node/2929614451). The only differerence is that one has to click the 'pencil' to change an attribute or click the 'move' button to move it around.
> 
>  Unknown attributes are asked one-by-one as not to overwhelm the contributor - but this can be changed [by setting a URL-parameter](https://mapcomplete.osm.be/shops?z=19&lat=51.19684&lon=3.216944&language=en&fs-all-questions=true#node/2929614451). 
> 
> 
> 
> 
> 
> And yes, there is input validation and normalization as welll.
> 
> 
> 
> Keep in mind that MapComplete does not aim to edit everything, but focusses on just a single topic at once. If you feel that a theme on pharmacies would be a good addition, [please go on and create on.](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md). When it is finished, I'll be very happy to include it!

The one issue I have is that the themes have questions like "What are the opening hours?" and "What is the website?", which I feel are not necessary.

**Comment by pietervdvn** [comment]
For a website, this might be clear without question. For some more specific stuff, a question really helps to indicate what is needed. For non-technical users, a question and the  'step-by-step' flow really helps too.
