### ISSUE TITLE
network / operator in charging stations

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#559]
In charging_stations, when you have a network but not an operator, this is what you see;

![afbeelding](https://user-images.githubusercontent.com/10122639/141476904-d99a31f4-77d9-4300-9163-9b7b4d5dd8a9.png)

That looks a little weird. It does make sense when you open up the question:

![afbeelding](https://user-images.githubusercontent.com/10122639/141477053-4f63c1f2-a74c-41c7-85b2-b1da8c5df7a4.png)

I'd suggest:
if network=* & !operator then ask "Does a local business (not *network*) take care of this station?"
With answers: 
*operator* takes care of this station
*network* also takes care of this station

if !network & operator=*, then ask the current operator question first.

**Comment by pietervdvn** [comment]
This is only triggered of the `operator`-tag is identical to the `network`-tag.

I'm gonna hide the 'operator'-question if a network is defined which should solve most of the issues here.
