### ISSUE TITLE
GRB import tool: megathread

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#564]
Please, leave all feedback, remarks and discussion on the GRB theme here.

TODO:

- [x] The conflation tool might leave leftover points if conflating to less points
- [x] The conflation tool moves points to aggressively
- [x] Importing a building, then editing it while not yet uploading breaks the uploader - especially if editing happens while the upload is happenen as id rewrite doesn't happen.
- [x] The conflation tool snaps to aggressively in some cases (e.g. imported building which is closeby)
- [x] Address logic: deal with units
- [x] Address logic: don't show crab if it is included in the GRB-building
- [x] Address logic: actually copy the address data of the GRB-building into OSM when 'import building' is clicked
- [x] Address logic: a hnrlabel which has a dash is an interpolation, often in steps of two
- [x] Fix CORS issues
- [x] Detect intersections with other objects 
- [x] Allow to add multipolygons (e.g. [here](http://127.0.0.1:1234/index.html?layout=grb&test=false&z=21&lat=51.15775&lon=3.611188&language=en&layer-address=false&filter-crab_address=show_matched_addresses.1&layer-All%20OSM%20objects=false&background=AGIV#https://betadata.grbosm.site/grb?bbox=401905.89472345676,6649104.216470912,402058.7687800271,6649257.090527481/2))
- [x] Block import if the OSM-layer hasn't loaded yet
- [x] Recalculate metatagging after an import to fix various detections (addresses, ...)
- [x] Import ref:urbis and ref:picc
- [x] The importer sometimes generates duplicate points in a way
- [x] Duplicate buildings are introduced on tile bounds

Feedback log:

- [x] By hgcvm: addresses as node or on the building: this has been improved
- [x] By joost: address logic has improved
- [x] Stijn Claes: wonky rendering and/or with delay: won't fix for now
- [x] Stijn Claes: not adding a tag/deleting a tag gets a strikethrough now (if the property is present on the original object)
- [x] Stijn Claes: 'The overlapping openstreetmap-building has no address information at all' even when there is no building in OSM at all: should be fixed, to validate when GRB is online
- [x] Stijn Claes: Clicking on a CRAB-address-label after an import indicates 'Dit CRAB-adres ligt in een OSM-gebouw. Het OSM-gebouw heeft geen volledig adres' even when the correct address was imported together with the building outline. --> IN the todolist above
- [x] Pietervdvn, hgcvm: failed detections: should be fixed with intersection detection and import block if OSM hasn't loaded
- [x] Tim Couwelier: background is fixed, man_made=mast is filtered away now

**Comment by hgcvm** [comment]
Are address being added as node inside building? Why not on the outline of the building itself? Or am I doing something wrong?
https://www.openstreetmap.org/node/9255807782
https://www.openstreetmap.org/way/1002945461

**Comment by joostschouppe** [comment]
Building on @hgcvm 's remark, this is the address logic I'd propose:
- never upload addr:flats by default
- do not show ALL crab addresses by default
- if a building has a single address, upload address-on-building to OSM by default
    - edge case: building has address from two different streets, but somehow GRB didn't realize > if a CRAB address is on top of a GRB building that does NOT include that address, do show that CRAB address
- if a building has more than one address:
    - and all the CRAB address nodes are on the same XY, DO upload address to OSM by default
    - and there are CRAB address nodes on more than one
- if a building has NO address, always show CRAB addresses if they are on top
- if a CRAB address exists, and there is no building nearby that contains that same address, DO show the address

**Comment by pietervdvn** [comment]
Yeah, the address logic is still very wonky and unimplemented.

**Comment by pietervdvn** [comment]
The import button of this building fails (the conflation map does not show up: https://pietervdvn.github.io/mc/develop/grb?z=21&lat=50.83754&lon=3.242833&language=nl&background=AGIV&layer-type_node=false&layer-OSM-buildings=false&layer-address=false&layer-All%20OSM%20objects=false)

**Comment by pietervdvn** [comment]
https://www.openstreetmap.org/way/1009407631

The GRB overlap detection doesn't work for this building

**Comment by StijnClaes** [comment]
Quick comments on version of the tool Pieter indicated on 12:50 on 6/12/2021:
- There seems to be some delay in the visualization after importing a building with the tool. Some buildings change color, some not.
- Current tool gives the impression that the tag 'building:min_level' is added, but that's not the case.
- Current tool indicates 'The overlapping openstreetmap-building has no address information at all' even when there is no building in OSM at all
- A quick look in iD shows good results of the import.
- Clicking on a CRAB-address-label after an import indicates 'Dit CRAB-adres ligt in een OSM-gebouw. Het OSM-gebouw heeft geen volledig adres' even when the correct address was imported together with the building outline.

**Comment by pietervdvn** [comment]
Detection of already imported buildings failed here: https://www.openstreetmap.org/way/551248816/history

Still offered to import anyway...

**Comment by hgcvm** [comment]
Hier is ook iets foutgelopen:
https://www.openstreetmap.org/way/551248811 staat bovenop https://www.openstreetmap.org/way/491720506

**Comment by timcouwelier** [comment]
Gebruik makend van mapcomplete.osm.be 
- Kan er een andere default achtergrond? GRB of OSM, of recente ortho vlaanderen, ipv de gedateerde luchtfoto?
- in Roeselare zijn Weidestraat 108 en Jacobus Vermanderstraat 19 voorbeeld van waar het bestaande OSM-gebouw eronder blijkbaar niet gedetecteerd wordt, onduidelijk waarom.
- man_made = mast toont als building = yes, terwijl die er uit gefilterd mogen worden. Die worden normaal als punt gemapt.

**Comment by timcouwelier** [comment]
(dev versie heeft blijkbaar al OSM als default achtergrond)

**Comment by pietervdvn** [comment]
@timcouwelier About the background: you can quickly switch those with the three buttons on the bottom-left. Defaults are the best layers according to the editor-layer-index and are currently GRB and AIV-latest.

Default layer is GRB according to the theme, but opening the theme on a global zoom level or outside belgium will default to OSM as GRB is not available there.

The failed detections are hard to reproduce, will have a look when the tool is up and running again.

I've filtered out the `man_made=mast` (see 4131e9b9)

**Comment by gplv2** [comment]
Hi, 
FYI:

`man_made=mast` has been fixed in the postgis API.  It's transformed to a point instead of a polygon.  It's included in grbosm.site again.   Maybe the filter can be switched off/ made optional again.

**Comment by pietervdvn** [comment]
@gplv2 I'm gonna leave them out for now - the theme is already complicated enough. Ideally, the 'masts' theme should also pickup the antenna import that has been done.

**Comment by pietervdvn** [comment]
https://www.openstreetmap.org/changeset/99373302#map=17/50.84905/5.48344

> Ik vind alsmaar meer fouten: 1) dat script gebruikt een lijn i.p.v. een vlak om een gebouw aan te duiden. 2) hoeken van gebouwen die dicht tegen elkaar staan voegt ie samen bij die hoeken terwijl dat in werkelijkheid zo niet is: Stippelstraat 23, Sint-Truiden. Stippelstraat 24 en 26. 3) Als er een binnenplaats is in een gebouw dan maakt ie alleen de "outer" lijn maar niet de "inner" of hij maakt ze verkeerd: Startelstraat 53.

**Comment by pietervdvn** [comment]
De CS-comment is wat uit context getrokken, het gaat specifiek om de GRB-importer van mapcomplete waar er wat issues mee waren, zijn ondertussen rechtgezet.

**Comment by pietervdvn** [comment]
Ja, dit zijn 100% MC-issues. Het samenvoegen van punten stond te ruim, uploaden van polygons met holes was gebroken, een issue waar de UI naar lon/lat ipv lat/lon sprong,... Niets aan jouw kant dus.

**Comment by pietervdvn** [comment]
> Maakt mij niet uit welke kant, fix the problem, not the blame :)

Probeer ik ook wat te doen, ik wou je gewoon geruststellen dat jij niets hoeft te doen.

**Comment by joostschouppe** [comment]
Some feedback from user Jozin:

* Soms gebeurt het dat Mapcomplete een “Upload this building to OpenStreetMap” wil uitvoeren terwijl Mapcomplete in feite een “Replace the geometry in OpenStreetMap” moet doen.

* Ik merk dat wanneer dat 20.000 MiB van het geheugen van mijn (splinternieuwe) PC bereikt, Mapcomplete crasht. Ik zie dan geen andere mogelijkheid dan Mozilla Firefox af te sluiten en opnieuw op te starten. Wanneer ik Firefox opnieuw opgestart heb dan moet ik op “Reload page” drukken om de juiste situatie van GRB te krijgen.

* Zelfs wanneer een gebouw reeds door Mapcomplete geüpload is naar OpenStreetMap duidt Mapcomplete dat gebouw aan als zijnde niet geüpload. Dit gebeurt soms.

* Mapcomplete verbindt gebouwen met elkaar die niet aan elkaar gemaakt mogen worden, meestal aan één hoek

**Comment by pietervdvn** [comment]
Most of the issues have been fixed by now, and this issue is stale - so I'm closing it now.
