### ISSUE TITLE
Datacaching: brainstorm

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#581]
Setup a server where the data for the layers is available in a cached format.

To build the cache:

- Setup a hetzner(?) server
- [Fetch the torrent link](https://planet.osm.org/planet/planet-latest.osm.bz2.torrent) and download the planet file
- Convert it to geojson tiles with ```osmium extract --bbox lon,lat,lon,lat --overwrite --output=planet-<tileindex>.osm.pbf planet.osm.pbf
osmium export planet-<tileindex>.osm.pbf --output=planet-<tileindex>.geojson````
- Run the cache script to extract the needed features as `layerid-tile.geojson`
- Put it online!

Note: this might still need to use overpass to query for _new_ features

**Comment by pietervdvn** [comment]
Also see https://github.com/mapcontrib/mapcontrib/issues/385#issuecomment-1073350929

**Comment by Lee-Carre** [comment]
> Setup a hetzner(?) server

Unless you (understandably) want to keep it specifically in Germany, I can recommend [ByteMark](//www.bytemark.co.uk/).

**Comment by pietervdvn** [comment]
This is implemented; the issue can thus be closed
