### ISSUE TITLE
Support Icon overlays in Custom Theme Generator (feature request)

### ISSUE THREAD

**Issue by InsertUser** [pietervdvn/MapComplete#593]
As someone who is a little iffy on the second point of the [Making Your Own Theme page][1] (JSON comfort) I have gone some way to creating a theme for personal use with the Custom Theme Generator, but would like to add some icon overlays like in the sport and cycleshop themes. I could add them manually to the 'basic' JSON created by the generator, but existing examples like the contents of the bike_shop.json file cause the generator to fail to load and I'd quite like to test the code in the sandbox area of the generator so that I don't introduce spurious data to OSM.  

Would it be possible to add 'badge' support to a future version of the theme creator?

As this is probably a tonne of work, is there a separate sandbox to use instead which supports all aspects of the themes?

[1]: https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md

**Comment by pietervdvn** [comment]
To set mapcomplete in 'sandbox mode', add the URL-paramer `test=true`. An orange 'testin will appear next to your userbadge.

The custom theme generator is currently unmaintained as it took too much work.

Feel free to reach out via the matrix/telegram-group for help and feedback on your theme! I'm curious what you are working on.
