### ISSUE TITLE
Preload map data for view around current one

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#599]
Right now moving/zooming out requires noticeable waiting, every single time, as data loads.

Maybe it would be possible to preload data a bit more so small move is not requiring waiting (like StreetComplete does).

Triggered by https://github.com/streetcomplete/StreetComplete/pull/3616#issuecomment-1003994872

**Comment by matkoniecz** [comment]
#579 is related

**Comment by pietervdvn** [comment]
That _should_ be the behaviour, but it is broken :'(
