### ISSUE TITLE
Things misplaced in the copyright tab

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#600]
https://mapcomplete.osm.be/hailhydrant.html?z=17&lat=53.56607&lon=10.00143&language=en&tab=3&welcome-control-toggle=true#welcome

Especially the two first ones feel like should be in new 🧡 tab or go to existing "about MapComplete"
![screen02](https://user-images.githubusercontent.com/899988/147922494-3fed4668-08b7-439c-ba00-ee976ccfdb01.png)

**Comment by pietervdvn** [comment]
You're right - they ended up there accidentally/historically.

I also got in touch with some contributor who proposed to move some of these to different places of the website, so I'll probably handle this one if such a big rework happens.

In any case, this is pretty low priority right now so I'm not gonna fix this right away but when the time is right for it.

**Comment by pietervdvn** [comment]
Those extra actions have been moved to tge 'start'-page, the copyright-button got itns own button.

This resolves this issue.
