### ISSUE TITLE
Bicycle infrastructure asks for traffic lights on an unmarked crossing

### ISSUE THREAD

**Issue by riQQ** [pietervdvn/MapComplete#609]
Happens on nodes with
```
highway=crossing
crossing=unmarked
```

In the wiki [crossing=unmarked](https://wiki.openstreetmap.org/wiki/Tag:crossing%3Dunmarked) is defined as
> pedestrian crossings without zebra crossing or traffic signals

Example: https://mapcomplete.osm.be/cycle_infra.html?z=19&lat=49.79345&lon=9.942455&language=en#node/395422425

<img src="https://user-images.githubusercontent.com/3404787/148842751-05ec6e0a-6b9c-4c98-9f6f-046717eee54d.png" width="40%" height="40%">

![image](https://user-images.githubusercontent.com/3404787/148842848-6d783442-c3f8-4e2b-9bb2-ac2f28755ed0.png)

**Comment by RobinLinde** [comment]
Probably because `crossing=unmarked` is not one of the mappings of the layer. Had already fixed this in a local branch, but will push a fix and open a PR
