### ISSUE TITLE
Move away from wget

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#621]
Would you be open to moving away from wget?

In the spirit of making it easy as possible to setup for new users it would be good to remove extra dependencies.

One option is to have a small download script in JS like

```
const http = require('http');
const fs = require('fs');

const file = fs.createWriteStream("assets/editor-layer-index.json");
http.get("https://osmlab.github.io/editor-layer-index/imagery.geojson", function(response) {
  response.pipe(file);
});
const file2 = fs.createWriteStream("assets/polygon-features.json");
http.get("https://raw.githubusercontent.com/tyrasd/osm-polygon-features/master/polygon-features.json", function(response) {
  response.pipe(file2);
});
```

curl would be another option since it's installed by default on most operating systems

**Comment by pietervdvn** [comment]
Fine for me. Scripts go into the 'scripts' directory, you can put it ther.

Thx for smoothening the setup process
