### ISSUE TITLE
Support Gitpod

### ISSUE THREAD

**Issue by RayBB** [pietervdvn/MapComplete#623]
Would you be open to supporting Gitpod?

It's a free and open source tool that lets you spin up temporary dev environment in the cloud.
It's a very nice way to let someone get up and running to make small changes without having to do any setup work.

I set it up for Open Library and it's worked pretty well there https://github.com/internetarchive/openlibrary

 The only thing this requires is adding a `.gitpod.yml` to indicate which commands to run.

**Comment by pietervdvn** [comment]
I'm a bit resistant to add this.

- I don't want to officially endorse some editor - especially not a (commercial) cloud editor
- It' not something I'm using
- Github has their own live editing tools for this

I get that it is 'only a single file', but there are already enough such files - of which too much are unused...

**Comment by RayBB** [comment]
That's why I asked. I know that not everyone want to get people used to free things like this that can then easily be taken away but some are more of the mindset of if it helps reduce contributor friction for a few years lets enjoy it while it lasts.

I'll add that:
* It is an very active and popular open source project https://github.com/gitpod-io/gitpod
* As far as I know, GitHub codespaces isn't generally available (I'm in beta though and it's fine) and I don't think they've announced any free plans
* I think the folks in open library who were most excited for gitpod were folks with lower end hardware, restricted computers, or slow internet connections

Personally, I think it's a nice touch to make contributing fast but if you don't think others would likely use it then we can close this. Maybe they'll find this ticket and reopen to request it one day

**Comment by pietervdvn** [comment]
Hi,

Even though gitpod looks like an amazing product, I'm not gonna add the configuration file for the simple reason that no active contributors (aka me) use it right now. This means that the gitpod configuration file won't be maintained and might break without anyone noticing.

By extension, I'm not fond of adding _any_ editor specific files in the repo. I've cleaned a few such files just now by the way.
