### ISSUE TITLE
notes theme: filtering by date works in Chrome but not in Firefox

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#637]
At least for me, filtering by date gives me results in Chrome, but an empty map in Firefox, no matter which date I pick and both for before and after

[example link](https://mapcomplete.osm.be/notes.html?z=11&lat=51.10219&lon=4.274093&language=en&filter-opened_after=%7B%22search%22%3A%222022-01-20%22%7D&filter-opened_after-search=2022-01-20&filter-is_open=true)

Chrome:
![image](https://user-images.githubusercontent.com/17066627/151617485-3a6407d5-5c2b-4a24-9b7f-731fa37a4dbe.png)

Firefox:
![image](https://user-images.githubusercontent.com/17066627/151617629-9b946494-cb9d-44a5-902a-2eee10cbc4b2.png)

**Comment by pietervdvn** [comment]
This works fine for me both on firefox 96.0 and chromium. I suspect a difference in date parsing is the culprit. Which version are you using?

**Comment by joostschouppe** [comment]
I have the same exact situation as Seppe. My Firefox version is 87.0 (yeah... on a work PC)

**Comment by gplv2** [comment]
For those who haven't hacked their CORS :), neither works :

FF:  Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.openstreetmap.org/api/0.6/notes.json?limit=10000&closed=7&bbox=4.74609375,50.903032831112576,4.833984375,50.95842672335991. (Reason: CORS request did not succeed). Status code: (null)

Chrome

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.openstreetmap.org/api/0.6/notes.json?limit=10000&closed=7&bbox=4.74609375,50.903032831112576,4.833984375,50.95842672335991. (Reason: CORS request did not succeed). Status code: (null)

![Screenshot from 2022-02-02 03-09-59](https://user-images.githubusercontent.com/907459/152082532-1b3c8e37-41e1-4e49-8dad-1567c4ad4a67.png)
![Screenshot from 2022-02-02 03-08-49](https://user-images.githubusercontent.com/907459/152082537-0bae27af-b0c3-4416-a91a-36bee7bd91e2.png)

**Comment by pietervdvn** [comment]
@gplv2 This is bizarre, as it works fine for me on both firefox and chrome - with the normal CORS-rules enabled.

If there really is a problem, this is an unrelated issue as date-filtering happens on the local data and does not create a new network-request.

**Comment by gplv2** [comment]
ok, I'll test again later.  I'm on ubuntu 20.04 so chances are always it reacts a bit different than the windows family, But the request probably failed because there was no local data (yet) here with me.    I'll do a deeper test later, I just opened and looked at the errors , thought it would help.   The filter in the interface did nothing visibly on both browsers. 

FYI:


Google Chrome | 97.0.4692.99 (Official Build) (64-bit)
-- | --
Revision | d740da257583289dbebd2eb37e8668928fac5ead-refs/branch-heads/4692@{#1461}
OS | Linux
JavaScript | V8 9.7.106.19

**Comment by pietervdvn** [comment]
Hey @seppesantens,

Is this still an issue for you? I cannot reproduce the issue on firefox, the example link works just fine for me.

**Comment by seppesantens** [comment]
I lost track of this issue. I just tested it again and the issue is no longer there.
