### ISSUE TITLE
Transparency of iOS Home Screen icons is not transparent

### ISSUE THREAD

**Issue by habi** [pietervdvn/MapComplete#640]
I can nicely add Home Screen icons for themes, but their transparent background is shown black.
The 'playground' theme is thus completely black, making it quite ugly on my home screen.
Weirdly, the transparency of the icon is quickly as I'd expect it to be when 'quitting' from the theme, but at rest it is b0rked.

Here's a short screen recording of how this looks on my iPhone 12 mini with iOS 15.2, when the bookmarks are in a folder on the Home Screen.

https://user-images.githubusercontent.com/1651235/152240493-3ec5c2b2-4aff-45fa-97e1-b79009e7236c.mp4

**Comment by pietervdvn** [comment]
From [Apples guidelines:](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/app-icon/)

> Keep the background simple and avoid transparency. Make sure your icon is opaque, and don’t clutter the background. Give it a simple background so it doesn’t overpower other app icons nearby. You don’t need to fill the entire icon with content.

**Comment by habi** [comment]
It seems that this is an iOS issue:

> For example, favicon are often transparent. But iOS does not support transparency

as found in https://stackoverflow.com/a/23824196

I can confirm that even the [base icon](https://github.com/pietervdvn/MapComplete/blob/develop/apple_touch_icon.png) *with* transparency is shown with a black border on the Home Screen.

BTW: The StackExchange icon is also shown with a black border at rest, and a transparent border when 'quitting' the bookmark.
I guess this is a bug with iOS.

**Comment by pietervdvn** [comment]
This is a limitation of iOs. However, as all the theme icons are .svg's in the first place, the pre-deploy processor can automatically add a white background to them and then generate an extra .png-version of this image. I've added this.

Would you mind testing with a theme from https://pietervdvn.github.io/mc/develop?

**Comment by habi** [comment]
> Would you mind testing with a theme from https://pietervdvn.github.io/mc/develop?

The workaround of having a white fill works nicely in this case.

(Even though I would like to have pretty transparent icons on my Home Screen, but that's an issue with Apple ;) )

**Comment by pietervdvn** [comment]
@habi So I can assume it works? I'd love to see a screenshot!

**Comment by habi** [comment]
Sure!
The playground icon for example was only black and looks good now.

![image](https://user-images.githubusercontent.com/1651235/152748815-b8c3f97e-3906-4b11-b3dd-735d9b8b1980.jpeg)
