### ISSUE TITLE
UK addresses theme - master ticket

### ISSUE THREAD

**Issue by RobJN** [pietervdvn/MapComplete#647]
A master ticket to store a summary of the feedback received on the UK Addresses theme. Most of these I would need help with. I have grouped these according to their priority. 

High
------
- [x] On importing a point, you get the option to move the point. This is a bad idea for this dataset as we know the locational accuracy is correct (and moving it will make the accuracy worse). I cannot see how to stop the moving minimap from showing.
- [x] Find out why the "id": "uk_addresses_embedding_outline" block is not working.

Medium
-----------
- Bing is not appearing in the imagery list.
- The word “string” in the freeform text box is a technical term that would be better replaced by something else.
- Some of the points that come from Russ’s JSON service may not be addressable locations. For these the user could say something like “no address is here” and MC add a tag (noaddress=yes) to OSM. If we did this, then MC would need to match the JSON point to the OSM tag otherwise the next mapper coming along will be asked again for the address. This might require us to use a nearness match (that is, test if JSON point is in exact same location as OSM point). Could put a “this is not an addressable location” button below the “Add this address” button (first or second screen?).

Low
------
- Update MC so that it only adds source=survey (or similar) if GPS on AND user near to the object they are changing.
- It would be nice if the theme could limit what shows in the imagery list.

**Comment by RobJN** [comment]
The following are feedback we have received but are not yet convinced it is a good idea to change it. This is awaiting more feedback.

Awaiting more feedback
--------------------------------
- Make it possible to add a completely new point (Russ's server doesn't return all address points). An advanced user mode might be the best way to do this as we are not sure if is a good idea for beginners.

**Comment by pietervdvn** [comment]
> * Find out why the "id": "uk_addresses_embedding_outline" block is not working.

Because the layer with polygons is not loaded if it is not shown.
I've added in some checks that mark this layer as "always load"





> * Bing is not appearing in the imagery list.

See https://github.com/osmlab/editor-layer-index/issues/1441



> * The word “string” in the freeform text box is a technical term that would be better replaced by something else.

I've changed this to the key + type. I've made this configurable via the JSON as `freeform: {key: xyz, placeholder: some text}` or `freeform: {key: xyz, placeholder: {en: Some example, nl: voorbeeld}`



> * Some of the points that come from Russ’s JSON service may not be addressable locations. For these the user could say something like “no address is here” and MC add a tag (noaddress=yes) to OSM.

NO. THIS IS A BAD IDEA. Should we also place `not:tree`, `not:shop`, `not:whatever` on every other location where there is none of these features? Should we fill the ocean with no:address?

For a small dataset (a few thousands point at most), OSM-notes could be used for this; but not in this case.

This _must_ be kept in a separate database.



> * Update MC so that it only adds source=survey (or similar) if GPS on AND user near to the object they are changing.

For this, the distance to the modified objects is leaked - this can be determined afterwards.



> * It would be nice if the theme could limit what shows in the imagery list.

MC loads the entire ELI and picks whatever applicable layer, so filtering those might get hard as this is a highly dynamic list. This would indeed be nice, but it is very hard to do and isn't a priority for me right now.

**Comment by RobJN** [comment]
Thanks. 
On the noaddress=yes topic: this is already being used in OSM as it is useful to know when a building/other feature has no address. Was thinking that MC would add noaddress=yes plus the answer to a question such as "Please describe what is here instead". I'll ask for more feedback from the UK OpenStreetMap community.

**Comment by pietervdvn** [comment]
> On the noaddress=yes topic: this is already being used in OSM as it is useful to know when a building/other feature has no address. Was thinking that MC would add noaddress=yes plus the answer to a question such as "Please describe what is here instead". I'll ask for more feedback from the UK OpenStreetMap community.

noaddress=yes is an acceptable tag if used on other features, e.g. to indicate that a certain building doesn't have an address - contrary to what one could expect. This is perfectly acceptable: the building can be surveyed, and that it doesn't have an address can be surveyed too.

However, placing a single node which only carries "noaddress=yes" is not acceptable.

At last, in many cases, if UPRN has a plotline, there might be a garden, greenfield, ... instead.

**Comment by Cj-Malone** [comment]
> On importing a point, you get the option to move the point. This is a bad idea for this dataset as we know the locational accuracy is correct (and moving it will make the accuracy worse). I cannot see how to stop the moving minimap from showing.

+1

This is one that I think is important.

**Comment by pietervdvn** [comment]
> This is one that I think is important.

Yeah, it would help to 'clear' an area. However, this reporting of a negative has to happen via another database then OSM.

**Comment by RobJN** [comment]
Looking at what CJ quoted, he was referring to a different topic (the screen that allows you to move an import point)

**Comment by Cj-Malone** [comment]
Also I did a [test changeset](https://www.openstreetmap.org/changeset/117122175). Data wise this produced some good address points, there were some unexpected tags though. [ref:GB:uprn=null](https://www.openstreetmap.org/node/9486941676) and multiple `urpn_count`. I think the first is clearly wrong, and the second may get a heated conversation around.

**Comment by RobJN** [comment]
Adding ref:GB:uprn=null in to OpenStreetMap is not a good idea. I found [the source in the tiled geoJSON](https://osm-uk-addresses.russss.dev/addresses/18/130128/88109.json) and it appears in there as "ref:GB:uprn": null. The lack of quotation marks around "null" confirms that we didn't intend for this to go into OpenStreetMap. @pietervdvn do you have any suggestions on how to fix this please?

Will keep consulting the OSM community on the uprn_count tag. Personally I find it useful. As I understand it (correct me if wrong Pieter), MC needs to bring at least one tag through from the import as this tag is what triggers the questions pop-up. I guess we could delete it post a question being answered though if deemed not valuable in OSM.

**Comment by pietervdvn** [comment]
The import-button whitelists which tags do get imported. [I have removed the ref:GB:uprn from this whitelist, so at least it won't go through anymore](338e16bf8a08c6951ea7d1aaa8b74cdd55c96d94)

And yes, at least one tag should be added in order for the 'addresses'-layer to pick it up.

**Comment by pietervdvn** [comment]
Derp, of course. [I've patched the geojson loader to remove 'null-entries' instead](338e16bf8a08c6951ea7d1aaa8b74cdd55c96d94).

En passant, I've also enabled the filter to only show unmatched addresses

**Comment by arrival-spring** [comment]
Is there any info/source code on the API?

Even just the details of fetching files like [this one](https://osm-uk-addresses.russss.dev/addresses/18/128577/86944.json) (linked above)

i.e. what do the x and y in the url mean? As they don't appear to be lat/lon or easting/northing

**Comment by RobJN** [comment]
@arrival-spring : Feel free to message me if you want to know more about the tiled files it fetches. I can put you in contact with Russ who set this tiled layer up if needed.

**Comment by pietervdvn** [comment]
I'm closing this issue, as all high-priority items are handled; others have their own separate issue or won't be fixed.
