### ISSUE TITLE
Clicking on a Pin in macOS Safari does nothing

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#658]
On https://mapcomplete.osm.be/cyclofix.html?z=19&lat=52.52169&lon=13.41724&language=en#way/879144135 I see two Map Pins. Clicking on them does not doe anything on MacOS Safari. Only clicking the blue area works in this Browser.
I cannot see any console error about it.

**Comment by tordans** [comment]
There is not a lot to see – clicking does nothing, except for the area.
I am macOS 12.2 with the Safari that comes with this Version.

**Comment by pietervdvn** [comment]
Any console output indicating an error?

**Comment by pietervdvn** [comment]
Reproducible on Epiphany (aka Gnome Web)

**Comment by tordans** [comment]
FYI, there is a ticket at https://github.com/openstreetmap/openstreetmap-website/issues/2811 for quite a while which might be related.

**Comment by tordans** [comment]
I assume [this is for here](https://github.com/pietervdvn/MapComplete/issues/700#issuecomment-1066285475)

>Seems to be related. @tordans does the workaround (right clicking or long clicking) work for you too?

Yes, right click does work. The Video show the right clicks with a green, the left with a black circle: https://share.icloud.com/photos/06cxY1whcu0Rja9BtaLj2iGbQ

**Comment by pietervdvn** [comment]
@tordans Could you check again with the current develop version?

**Comment by pietervdvn** [comment]
I did test again today with the latest leaflet version; this seems to work correctly.

Feel free to reopen this issue if the problem pops up again.
