### ISSUE TITLE
Improve copywriting of themes

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#665]
Lots of the theme descriptions are pretty bad and bland, e.g.:

- `On this open map, one can find and mark information about charging stations`
- `On this open map, one can find and mark information about charging stations`

Improving these is important for new users and for search engine optimalisation.

**Comment by joostschouppe** [comment]
Sidenote when working on this: in the ? section, I'd suggest replacing:

> Use it to add OpenStreetMap info on a single theme. Answer questions, and within minutes your contributions are available everywhere. The theme maintainer defines elements, questions and languages for it.

With
> Use it to add OpenStreetMap info on a single theme. Answer questions, and within minutes your contributions are available everywhere. In most themes you can add pictures or even leave a review. The theme maintainer defines elements, questions and languages for it.

(I'd do it myself but couldn't find it in the code)

**Comment by joostschouppe** [comment]
I gave it a first look (finally, I know!). Looking at Campersites & Cyclofix first. 

**Campersites:**
Current:
> This site collects all official camper stopover places and places where you can dump grey and black water. You can add details about the services provided and the cost. Add pictures and reviews. This is a website and a webapp. The data is stored in OpenStreetMap, so it will be free forever and can be re-used by any app.

Suggested:
> _This map collects all official camper stopover places and places where you can dump grey and black water._

> Zoom in and this information will be shown on the map. Click on any point to see more details - or add them yourself! You can also use this map to add missing points. All it takes is making and connecting an OpenStreetMap account.

> This is a MapComplete theme. Click through the tabs of this section to learn more about the project and its themes. All edits go straight into OpenStreetMap: they are open data that anyone con re-use.

**Cyclofix:**
Current:
> The goal of this map is to present cyclists with an easy-to-use solution to find the appropriate infrastructure for their needs.<br><br>You can track your precise location (mobile only) and select layers that are relevant for you in the bottom left corner. You can also use this tool to add or edit pins (points of interest) to the map and provide more data by answering the questions.<br><br>All changes you make will automatically be saved in the global database of OpenStreetMap and can be freely re-used by others.<br><br>For more information about the cyclofix project, go to <a href='https://cyclofix.osm.be/'>cyclofix.osm.be</a>.

Suggested
> This map is for cyclists who want to find nearby bicycle pumps, repair stations and tube vending machines. It'll also help you find bicycle cafés, shops, parking and even drinking water. 

> Zoom in and this information will be shown on the map. Click on any point to see more details - or add them yourself! You can also use this map to add missing points. All it takes is making and connecting an OpenStreetMap account.

> This is a MapComplete theme. Click through the tabs of this section to learn more about the project and its themes. All edits go straight into OpenStreetMap: they are open data that anyone con re-use.

As you can see, the second and the third paragraph are identical. Some of the theme's have some description of the functionalitty, most don't. This discription is useful, but should be centralised. So I suggest we put the second and third paragraph in a central place (which makes it easier to maintain!), and make sure the theme-specific description only explains the topic, not the functionality.

If that's a go, then I still wonder if the first paragraph for both themes here is sufficient. I'm thinking less is more, but maybe from an SEO point of view it should be a little more wordy? (that should be possible without making it annoyingly wordy :))

**Comment by pietervdvn** [comment]
The '?' section is one big block currently. You can change it via the translation button.

**Comment by pietervdvn** [comment]
Regarding an explanation of MapComplete:

I'm a bit opposed on explaining what MC _is_ as this should be self-evident. A very small introduction indeed wouldn't hurt though.

Second, some themes (exclusively commissioned themes) _don't_ have the theme switcher, for them it doesn't make sense to mention other themes. This can however be solved by having a generic paragraph with `This map collects information which you can edit` and a second paragraph `you can also discover other themes here` which is only shown if the theme-tab is enabled. (I'll add a button to switch to the theme tab)

Thirdly, most (if not all) layers have the ability to add pictures.

At last, for SEO-purposes, we can stuff the wordy explanation below the real explanation and language picker. No-one will read it, but that is not the point of SEO-text anyway.

**Comment by pietervdvn** [comment]
I did a small mockup of what this could look like: 
![image](https://user-images.githubusercontent.com/1466478/175060352-705d108e-4745-44be-b2d6-c36329b31a9c.png)

'Tab the map to add a new POI' is a separate translation which is hidden if no new POI's can be added.

**Comment by pietervdvn** [comment]
Closing this issue as it is stale, very broad and a bit vague.

Furthermore, issues with copyrighting a specific theme can be done by quickly jumping into weblate.
