### ISSUE TITLE
Etymology - Add feature types for cultural/social/sports places

### ISSUE THREAD

**Issue by Codain** [pietervdvn/MapComplete#671]
The following features are missing from my point of view in the Etymology theme:

- amenity=arts_centre
- amenity=library
- amenity=theatre
- amenity=community_centre
- amenity=social_facility
- amenity=hospital
- leisure=sports_centre

I would be happy to have them available in the etymology theme.

**Comment by pietervdvn** [comment]
Hi,

Thanks for the suggestion. I'm currently a bit swamped with work, but if you make a pull request similar to https://github.com/pietervdvn/MapComplete/pull/661, I'll hapilly merge it.

**Comment by pietervdvn** [comment]
Fixed in #678
