### ISSUE TITLE
change unit typo use kW in place of kw

### ISSUE THREAD

**Issue by lepirlouit** [pietervdvn/MapComplete#683]
In verband met de charging_Station map
Ik denk dat de units "kW" zou moeten zijn in plaats van "kw"
W moet in hoofdletter omdat het naar "James Watt" verwijst
https://nl.wikipedia.org/wiki/Watt_(eenheid)

attention, megawatt will be MW

**Comment by riQQ** [comment]
In which place do you see this problem? Do you have a link?

The only place I can find is in the documentation here:
https://github.com/pietervdvn/MapComplete/blob/55dd4c58eed5305fd2eacc02d2cbf6d2af74673b/Docs/Layers/charging_station.md
