### ISSUE TITLE
UK address theme - skip move point

### ISSUE THREAD

**Issue by RobJN** [pietervdvn/MapComplete#684]
On importing a point, you get the option to move the point. This is a bad idea for this dataset as we know the locational accuracy is correct (and moving it will make the accuracy worse). I cannot see how to stop the moving minimap from showing -> is it possible?

**Comment by pietervdvn** [comment]
Hi,

I disabled the precise location input for the UK-addresses theme yesterday. This is only on the develop branch at the moment.
