### ISSUE TITLE
Bicycle charging free but need a key

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#694]
I think a charging station [like this one ](https://www.mapillary.com/app/?lat=51.1921636&lng=4.8131592999722&z=17&pKey=191762936499688&focus=photo&x=0.699570777235196&y=0.5617375369602186&zoom=2.2813688212927756) is free to use, but you need to go inside to get a key. So the answer options don't really fit: 

![afbeelding](https://user-images.githubusercontent.com/10122639/157616367-2cf0ea85-aaa0-4d5c-b255-b83af518a5e0.png)

I guess a rephrasing could work?

**Comment by pietervdvn** [comment]
This is actually part of the 'access' restriction: in this case, it is free to use for customers, so this can be 'access=customers' or even 'access=key' (which is used in the toilets-theme as well.

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/157770078-09297e18-99c5-4f22-9bc5-6f6b7f81384c.png)
This is how it looks like now
