### ISSUE TITLE
Update link in Github Sidebar

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#699]
The link at 
<img width="358" alt="image" src="https://user-images.githubusercontent.com/111561/158022133-2485cb44-084b-45de-b62e-971207f00580.png">

is https://pietervdvn.github.io/MapComplete/index.html which shows "This page is not found.".

It should probably be https://mapcomplete.osm.be/index.html?

**Comment by pietervdvn** [comment]
Wow, totally forgot to update that link - thanks for pointing out. Fixed it!
