### ISSUE TITLE
Integrate Notes functionality

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#70]
In some cases, people will want to add data that is not possible to add within the tool. In those cases, adding a Note might be an option. However, most of this info might be a good fit for the note=* tag.

(Migrated from https://github.com/osmbe/cyclofix-docs/issues/14)

**Comment by pietervdvn** [comment]
A note theme has been added.

Todo: add the option to create a new node

**Comment by pietervdvn** [comment]
Themes which include the 'note' layer now also will be able to add a new note when the map is clicked.
