### ISSUE TITLE
Size of the repo

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#701]
I noticed, that the repos got quite bit at 582 MB.
Is there a way to get rid of some of the larger files?
Or maybe some git-pro-commands to not load the history (I assume that is where the 400+MB are located?)

The biggest file to get rid of is this pack.
Some of the presentations could maybe be moved to a different repository.
And if we want to get into details, we could reduce the size of some of the images; which would likely be a good idea for page speed. But it's not the big fish here :-).

`find . -type f -exec ls -al {} \; | sort -nr -k5 | head -n 25` shows me …

```
437931629; ./.git/objects/pack/pack-9645f5bc7b827563e5c4d35d9ad1c539533a5ee2.pack # 453 MB
16610815; ./Docs/MapComplete_SOTM.odp
16147732; ./Docs/Presentations/MapComplete_SOTM.odp
11218180; ./Docs/Misc/GrbAutoTool.gif
10058621; ./Docs/ImportProcess.mp4
9928251; ./Docs/Presentations/Fossgiss.odp # 9,9 MB
9034824; ./Docs/Tools/centerpoints.geojson
8838938; ./assets/layers/bike_repair_station/repair_station_example_3.jpg # 8,8 MB
5457985; ./Docs/MapComplete-Auto_apply.gif
3287358; ./assets/SocialImageTemplate.svg
3268721; ./assets/SocialImageTemplateWide.svg
2317260; ./assets/generic_osm_background.png
1830678; ./Docs/Tools/stats/stats.2020-7.json
1801242; ./assets/MapComplete_Screenshot.png
1650429; ./assets/SocialImage.png
1374472; ./.git/objects/pack/pack-9645f5bc7b827563e5c4d35d9ad1c539533a5ee2.idx
//1134058; ./package-lock.json
1085086; ./assets/themes/buurtnatuur/ANB.jpg
1085086; ./assets/layers/nature_reserve/ANB.jpg
```

[For some pictures](https://apps.apple.com/de/app/grandperspective/id1111570163?mt=12):
<img width="854" alt="image" src="https://user-images.githubusercontent.com/111561/158068181-d90d15f4-103f-4951-be58-eca7105f1b6a.png">

**Comment by tordans** [comment]
Here is a way to improve this situation:

On the iD Repo, there is [a recommendation to not pull all the git history](https://github.com/openstreetmap/id#installation). Following that and alternative ways (see below), **I can reduce the filesize from 610 MB to 160 MB.**

However, I remember from a long while ago that I had issues when using this option and continuing working with git and the (more or less) recent article by github goes into details about those issues/why and alternative options https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/.

**Git full clone:**

```
git clone https://github.com/pietervdvn/MapComplete.git
…
Empfange Objekte: 100% (54469/54469), 610.07 MiB | 6.82 MiB/s, fertig.
```

**Git shallow clone:**

```
git clone --depth=1 https://github.com/pietervdvn/MapComplete.git
…
Empfange Objekte: 100% (1691/1691), 161.82 MiB | 6.82 MiB/s, fertig.
```

**Git treeless clone:**

```
git clone --filter=tree:0 https://github.com/pietervdvn/MapComplete.git
…
Empfange Objekte: 100% (1477/1477), 161.76 MiB | 6.82 MiB/s, fertig.
```

I will work with the treeless clone for now. Should I not report any issues here, I recommend updating the readme similar to iD's readme.

**Comment by pietervdvn** [comment]
According to this guide, a _blobless_ clone is best: https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/

I've added that into the 'develop_deploy'-guide
