### ISSUE TITLE
Ideas for a better theme creation experience

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#707]
We did a live demo on the FOSSGIS OSM Community Event this month. We had to solve a few hurdles along the way. This a list of ideas that came to mind after thinking about the process afterwards. 

**Edit-Preview-Page:**

- [x] Create a page with a text area on the left and the running website on the right. I use the textarea to edit my theme JSON, the website updates whenever I click an update button. The helper side handles the url encoding in the background.
- [x] Investigate if https://github.com/josdejong/jsoneditor can be used to create a page that allows to online edit a theme JSON. This should prevent all the "trailing comma" errors and similar. (This editor seems to be the only web editor for JSON with relevant traction out there.)

**JSON Errors:**

- [x] Investigate if errors shown by the App when a theme is can be improved. And maybe prevented (text line).
- [x] Investigate if errors can be avoided by validating the JSON first. 'jsoneditor' (above) does that on one level. But could there be a process step that first validates the json file? Is that something https://json-schema.org/ could help with? 

**Documentation/Guidance:**

- [x] Change [the starter file](https://raw.githubusercontent.com/pietervdvn/MapComplete/develop/Docs/theme-template.json) in a way that it would work right out of the box, so I can use it as a running starter
- [x] Create a list of special situations that link to other theme files where I can see special json config situations like snapping to a way. This could be a general feature list with links to the theme.
- [x] Remove the custom theme generator [from the docs](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md) (and YT? and code?) since it is not recommended to use it anymore.
- [x] Recommend a way to create a theme without the base64 approach. We used Github Gist but that had issues with caching, which are hard to understand and work around.
- [x] Explain the difference between the theme-template that has the layers inline and the official themes in the repo where the layers are extracted in external json files. That might already be explained, but I did not find it during our live session. Maybe a comment in the /layers folder in the repo and a comment in the theme-template could solve this.

**Comment by pietervdvn** [comment]
Related to #173

**Comment by pietervdvn** [comment]
>  Investigate if errors can be avoided by validating the JSON first. 'jsoneditor' (above) does that on one level. But could there be a process step that first validates the json file? Is that something https://json-schema.org/ could help with?

Yep, these would definitively help. [I already generate them](https://github.com/pietervdvn/MapComplete/tree/develop/Docs/Schemas) and do use them actively in my own editor, where they are a huge help.

Furthermore, there is documentation on the format in the `XXXConfigJSON.ts`-files, where all the special cases are described.


Anyway, this is all rather low on my priority list now.

**Comment by pietervdvn** [comment]
Superseded/done in #1184
