### ISSUE TITLE
Don't save straight to OSM?

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#71]
When you click on the button to add something, you get to this screen:

![afbeelding](https://user-images.githubusercontent.com/10122639/87943393-4507bd00-ca9e-11ea-8cc5-70b97c551b75.png)

At this point the POI is already being uploaded to OSM and there is no way to cancel the object creation. People tend to click around and will accidentally create points, and will then panic because they have no idea how to undo their "damage".

Note: during data validation we DID NOT have the impression this happened a lot - all the people who have mentioned this also said "so I went to OSM.org to delete the object" :)

(migrated from https://github.com/osmbe/cyclofix-docs/issues/19)

**Comment by pietervdvn** [comment]
A confirmation dialog has been added. So sexy :)
