### ISSUE TITLE
More aggressively go to user location

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#724]
I wouldn't mind MapComplete to remember my location a bit more aggressively. I think it would be a better UX if you start at a reasonable location, and the map remains frozen for panning (zooming allowed) until the data is loaded. Perhaps overwritable with using the search window.

If you have used a Theme before and used it to zoom to current location; it would make sense to zoom to current location without user input on next Theme visit.

New users often seem to miss the point that we actually overlay POI, because they start with a world map. Even a somewhat random location that actually shows data might be better then an overview map.

Perhaps the "go to map" button could have a "open the map at my current location" variant, where clicking it would open the "you want to share the location" browser interface thingy

**Comment by pietervdvn** [comment]
There is a bunch of issues to unpack here.

First of all, the current behaviour is:

- Is a location set in the URL parameters? If so, use those
- Is a startlocation set in the theme? If so, use those. These are often (0,0, zoom = 0)

When wanting to zoom to the current geolocation, there are a few issues:

- IF geolocation has been granted before, it will take at least a few seconds till the position is known
- If geolocation has not been granted before, a popup is shown. I consider it rude to immediately ask for the geolocation

At last:
- We can save the previously visited location on device or in the OSM-preferences (the latter will be available only after a few seconds too, but can be synced across devices).
In either case, zooming to the previously visited location is an reasonable option.

The question then is whether or not to zoom to the geolocation once it is available or not.
