### ISSUE TITLE
Is Mapcomplete theme creation being deprecated?

### ISSUE THREAD

**Issue by maphouse** [pietervdvn/MapComplete#725]
I just noticed this https://pietervdvn.github.io/mc/develop/index.html?language=en suggests that theme creation must be done by request (v0.18.0-alpha-2) while the original (https://mapcomplete.osm.be/?language=en, v0.17.2) suggests the feature is still active... What should users be expecting here?

**Comment by pietervdvn** [comment]
Hi,

This questions has a nuanced answer.

First of all, only a logged-in contributor with sufficient changesets will see the link to the custom theme generator. I suspect you haven't logged in in the dev version, resulting in the link to the issue tracker being visible.

Second, the custom theme generator itself is not maintained anymore - but will stay online as long as it still (kindof) works. (Note that the code of the custom theme generator is _not_ in the current branches anymore, I removed them during a refactoring)

At last, sideloading your own theme file is still supported and will remain supported for the foreseeable future, wether it was created by the custom theme generator or written in some other tool. As long as it is a valid theme file, MapComplete will pick it up.
