### ISSUE TITLE
minimap not loading

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#726]
In Chrome on Windows, I have this issue when working on a Note or adding a new pin:

![afbeelding](https://user-images.githubusercontent.com/10122639/162236065-715400d9-87e1-410d-b22f-686f94fbbe72.png)

In Firefox, the background map does load. The same behaviour happens in the develop version

**Comment by pietervdvn** [comment]
Reproducible in chromium on linux (dev version)

Note that this is only the case in desktop mode; in mobile mode (smaller screen), the minimap works.
