### ISSUE TITLE
Help mappers "empty the map"

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#74]
If the theme manager has a certain ambition for the data (e.g. "all things need picture"; "all things need tag x, y and z"), you could help mappers help to reach that goal by using icons that change if they are considered "done" or not.

This is a feature that can really help to improve data quality.

There are a few options to implement this, e.g. have a (red) glow for 'still needs fixing'.

However, we also need to make sure that it doesn't get in the way, e.g. by only showing the glow to logged in users or by being able to disable it (e.g. a URL parameter)

(migrated from https://github.com/osmbe/cyclofix-docs/issues/46)

**Comment by pietervdvn** [comment]
This can be done by the theme, which can show different icons depending on known information.
