### ISSUE TITLE
Theme description overflow is hidden

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#746]
For long descriptions on themes overview, the text overflow is hidden. There does not seem to be either a short description or enhancement to the long description, such as an ellipsis ("...").
The same description is displayed fully when featured.

In overview:
![image](https://user-images.githubusercontent.com/67521919/162789584-2a7f89b8-ca11-4b2f-a040-02c01f3762cf.png)

When featured:
![image](https://user-images.githubusercontent.com/67521919/162789670-ceb948c3-a4cb-4575-a174-8e215c132ce9.png)

Browser(s): at least Chrome

**Comment by pietervdvn** [comment]
This is very hard to fix, as this might differ between browsers, translation and theme.
