### ISSUE TITLE
Change icon link names and add external link icons

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#747]
The links should have the name of the websites they go to, i.e. "(on) Wikimedia Commons" "[(on)] GitHub" and should have an external link icon to indicate the user is going to a different website.

![image](https://user-images.githubusercontent.com/67521919/162790516-c4218e1e-2522-4f20-bbc5-7dd777d50e02.png)

**Comment by pietervdvn** [comment]
We expect users to realize they'll go to an external website if they have a link.

Furthermore, this is very low impact; so I'm not gonna implement this.

**Comment by danieldegroot2** [comment]
Ok. Thanks for the reply. Having full links makes it slightly harder to read, but that's ok I suppose.
