### ISSUE TITLE
Button text is not readable on iPhone 12 mini (and misaligned in Safari on OS X)

### ISSUE THREAD

**Issue by habi** [pietervdvn/MapComplete#751]
The button text on the 'copyright' tab is not readable on iOS 15.2 on an iPhone 12 mini, as seen in the screenshot below.
![IMG_8564](https://user-images.githubusercontent.com/1651235/163037649-1a353dfd-d805-402e-9ffa-e0f7df17c5af.PNG)

**Comment by habi** [comment]
Technically, I was looking for the [translation feature](https://www.openstreetmap.org/user/Pieter%20Vander%20Vennet/diary/398959)

**Comment by habi** [comment]
In Safari (Version 15.4 (17613.1.17.1.6)) on OS X Monterey (12.3 (21E230), the text of the buttons is weirdly aligned (in my opinion).
<img width="1436" alt="Screenshot 2022-04-12 at 21 16 03" src="https://user-images.githubusercontent.com/1651235/163038884-226ec1af-7d92-4711-b2b5-59404a002dce.png">

The JOSM button has no visible text.
<img width="868" alt="Screenshot 2022-04-12 at 21 18 11" src="https://user-images.githubusercontent.com/1651235/163038893-3345b038-a5ec-4ae2-a54a-be249e5e6c8f.png">

**Comment by pietervdvn** [comment]
This seems to be a browser-specific bug.

Btw: the translation feature is _not_ available on mobile as these screens are too small.
