### ISSUE TITLE
Coulour difference of POI layer switches not very clear

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#76]
Maybe it's just because I'm color blind, but seeing which layer is switched off here is a bit hard for me

![afbeelding](https://user-images.githubusercontent.com/10122639/88811887-6449cd00-d1b7-11ea-8fc9-5e608191f3ba.png)

**Comment by pietervdvn** [comment]
Hmm, this was a bug. Fixed now.
