### ISSUE TITLE
tag rendering URLs

### ISSUE THREAD

**Issue by govvin** [pietervdvn/MapComplete#763]
It appears that when  "URL" freeform type is selected, the string input is automatically set to lower-case.

However, there are URLs that are case sensitive, and will work unexpectedly if they don't match exactly.

For example, if I paste the string `https://aaliyahsambale.github.io/rosasmurals/images/IMG_2840.jpg` in a URL input box, MC will save it as `https://aaliyahsambale.github.io/rosasmurals/images/img_2840.jpg` instead , which will then fail with a 404 error (notice, "IMG" versus "img" in the transformed string.)

**Comment by pietervdvn** [comment]
Oh, indeed! I've disabled the lowercasing.

**Comment by govvin** [comment]
@pietervdvn 

This behavior is still observed with themes shared using `https://pietervdvn.github.io/mc/develop/theme.html?`, but not if the theme link is shared using the share tab from the custom theme generator.
