### ISSUE TITLE
Feature request: extracting coordinates from geotagged photos

### ISSUE THREAD

**Issue by govvin** [pietervdvn/MapComplete#767]
While I'm not sure how this can be made possible, I am wondering whether it would be possible for MapComplete to use the location of a geotagged photo shared by a user, which the map can then set as the initial location for a feature being modified, or added, apart from linking to the photo itself with the image=* tag.

What do you think?

**Comment by pietervdvn** [comment]
The GPS-sensor can be very noisy. As a result, the geotag can be off by 100m in some cases - so we always want the contributor to set the pin on the right location.

Second, I'm afraid that this workflow will be confusing for users.

So, nice idea in theory, but not in practice.
