### ISSUE TITLE
Semicolon

### ISSUE THREAD

**Issue by Hopperpop** [pietervdvn/MapComplete#776]
Is it possible to support tags with multiple values?
For example here is a friture with both burger and friture tag. 
![image](https://user-images.githubusercontent.com/11853634/164945133-c3d8f58c-fb7d-4b26-b5f7-c4a29dc8a572.png)

Because of this, it's not showing up on the "Friturenkaart". 
I have been playing with a regex like `cuisine~(^|;)chinese($|;)`, but that gets translated to a overpass query: `["cuisine"~"^(^|;)asian($|;)$"]`. Defeating its purpose. 

It's understandable to not have full support for multiple values in question and mappings. But to me it should be still be usable as an filter or condition.

**Comment by pietervdvn** [comment]
For the friturenkaart (and similar such as your 'asian'-map), you can use `cuisine~(.*;)?friture(;.*)?` which will behave like you want.

I chose to force matching the entire value, as that can have unexpected results. For example, if `amenity~bank` and would match a _substring_ containing this regex, one could end with `amenity=blood_bank` and similar.


(I'm a bit swamped right now, if you want to fix the friturenkaart, I'd happily accept a PR.)
