### ISSUE TITLE
Wikidata picker - Ability to select multiple items

### ISSUE THREAD

**Issue by Codain** [pietervdvn/MapComplete#797]
Way https://www.openstreetmap.org/way/68999049 is a museum dedicated to two painters: Maurice Utrillo and Suzanne Valadon. It would be nice to be able to select those two painters instead of only one or none.

Another example: https://www.openstreetmap.org/way/180537912

**Comment by JLZIMMERMANN** [comment]
I have the same case for one street in Avignon : one name but for the father and son.
Rue Mignard : Pierre Mignard + Nicolas Mignard.
![image](https://user-images.githubusercontent.com/4929752/194692124-10e6dd4c-bd0d-4b24-b797-258729ecb0a8.png)

https://imgur.com/C6WpLxh
https://mapcomplete.osm.be/etymology.html?z=19&lat=43.94756&lon=4.806003&language=fr#way/120750010

**Comment by tordans** [comment]
IMO the clean way to solve those cases is, to create a Wikidata entry for the road, then create the relation on to the two people on that wiki data entry and use the road-wikidata-id in OSM.

(I don't know / did not check, though, if road-level wikidata entries are supported by the theme; those would be plain `wikidata` tags on the way.)
