### ISSUE TITLE
Update dev to live URLs to prevent them from breaking

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#798]
Issue just fyi, since the first URL variant is no longer working already.

Update URLs in other repositories from [pietervdvn.github.io/MapComplete](https://github.com/search?q=pietervdvn.github.io%2FMapComplete&type=code) (includes OSMBE) and [https://pietervdvn.github.io/mc/develop/](https://github.com/search?q=https%3A%2F%2Fpietervdvn.github.io%2Fmc%2Fdevelop%2F&type=code) to `https://mapcomplete.osm.be/` or notify authors to do so.
(why would they use the dev environment anyways)

**Comment by pietervdvn** [comment]
> why would they use the dev environment anyways

Because `pietervdvn.github.io/MapComplete` used to be the location of MapComplete before `osm.be` setup the domain.

Which repositories are you talking about specifically?
