### ISSUE TITLE
Update from NSI

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#799]
Suggestions (multiple possible QoL enhancements which or may not be feasible);

- Suggest brands based on geoJSON in NSI if possible.
- Update brands, operators, etc. from NSI
- Make sure all themes which could have such a question have it configured.

Example: Public Bookcases. ([NSI](https://nsi.guide/index.html?t=brands&k=amenity&v=public_bookcase) \ [Code](https://github.com/osmlab/name-suggestion-index/blob/main/data/brands/amenity/public_bookcase.json))
_(Some public bookcase brands are from [this recently merged PR](https://github.com/osmlab/name-suggestion-index/pull/6532);
if you are willing to look into creating Wikidata pages for items such as these -or add more items-, feel free to do so.)_

See also Shops theme, currently does not seem to have a brand question/display.

**Comment by danieldegroot2** [comment]
@pietervdvn It seems based on https://github.com/pietervdvn/MapComplete/issues/1833#issuecomment-2024238528 using more APIs is not planned, meaning it should rely on adding `brand` options and/or `brand:wikidata` question/display manually to layers/themes. Could you let me know if this is assumption is correct, please? In that case you can close as not planned.

**Comment by pietervdvn** [comment]
Now implemented.
