### ISSUE TITLE
Theme creation: Template ideas

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#800]
If not already, allow to create themes from
- (a combination of) presets from some known list (ie. wiki approved tags (and keys)) (or some specific tag).
- objects added/changed by you (or someone else)
- [NSI](https://nsi.guide/) items
- (geotagged images with compatible license from eg. Wikimedia Commons)

And,
- Filter if you want nodes, ways or relations
- Specify an overlay if you want to work from existing (government) data -OT: ofc with a compatible license-
- Confine to some area (eg. based on Nominatim search or OSM id); although this wouldn't be nice for others (so maybe these would be completely private themes..or not).
- Specify start zoom
- Configure (additional) background options, and/or allow viewers of the theme to do so.
- Auto-suggest existing icons.

Unrelated: Review background layer options; make sure
- tile urls are up-to-date and 
- everything works properly in the backend (and caching, also in general, is optimized)

Unrelated: Create a mirror, at least for yourself, which could be helpful to facilitate import themes or similar.

(otherwise) for #173. Some things may not apply.

**Comment by pietervdvn** [comment]
This issue seems to be a collection of vague ideas rather then actionable items. Furthermore, it hasn't seen _any_ interaction in the past year, so I'm gonna close this issue.
