### ISSUE TITLE
Bookcases: Additional `books` values

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#804]
[`books`](https://wiki.openstreetmap.org/wiki/Key:books) has few uses (1.4k), but is also used to specify genre/topic/language.
If possible, allow adding/changing(individual) additional semi-colon seperated values for these.

**Comment by pietervdvn** [comment]
Feel free to add this yourself [here](https://github.com/pietervdvn/MapComplete/blob/174ced9967c95076d83682649b038b99d3b131d2/assets/layers/public_bookcase/public_bookcase.json#L154)

You'll probably want to add `"multiAnswer":true` and to remove the 'adults and children books' in that case. A `"freeformKey"` might be needed to

**Comment by danieldegroot2** [comment]
Would it be possible to do it like opening hours?
* Mostly books for {audience} (selection menu)
-- [Empty]
-- Children
-- Adults
-- Children and adults
* 'The audience, genre, topic, language for these books is (mostly)'
-- `freeform`: {audience} +- anything you like

I have discovered given values wouldn't be able to be changed, it should be possible to lock multiple values without issues.

(at least for now, multiple selection menus could be added later if wanted if/when they become more populair)

**Comment by pietervdvn** [comment]
Hi,

I don't really have time to implement every idea and theme improvement - please read the documentation, have a look at existing themes and feel free to send a PR.
