### ISSUE TITLE
Language picker: Add display text

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#805]
Add display text (language, language code and/or flag) to the language picker. I think it used to display the language, but for me it no longer does, now it is just a dropdown arrow (I assume because it wasn't compact enough). The one in the help menu still displays the language.

(See also [LanguagePicker.md](https://github.com/pietervdvn/MapComplete/blob/16a39b0ea8e5aebc398c7b9c018a51d49dd1a8e7/Docs/LanguagePicker.md))

![image](https://user-images.githubusercontent.com/67521919/166228936-f17e6185-661a-42b5-8729-3b6ed7a0d059.png)

**Comment by pietervdvn** [comment]
The userbadge does not exist anymore in the current version, so this issue has become irrelevant.

**Comment by danieldegroot2** [comment]
Thanks again for the reply. This works properly inside of the settings menu now.
