### ISSUE TITLE
Add spacing between language picker and logout button

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#806]
The language picker and logout button have no space between them, which does not look very appealing and may cause worries you will accidentally hit the logout button.

![image](https://user-images.githubusercontent.com/67521919/166229315-73503cb3-0d7b-47ce-b0a5-d42abadf2729.png)

Browser(s): Chrome

**Comment by pietervdvn** [comment]
As the userbadge is completely gone and replaced by a userinfo panel, this issue is not relevant anymore.
