### ISSUE TITLE
Theme ideas from OSMdata

### ISSUE THREAD

**Issue by danieldegroot2** [pietervdvn/MapComplete#808]
Theme ideas to explore (not all relevant ofc):
https://demo.openstreetmap.fr/map

**Comment by pietervdvn** [comment]
Hi Daniel,

Thanks for your pointer. However, just spawning ideas and linking to 'possible sources of ideas' is distracting, non-actionable and costs the maintainers time.

If you do a feature suggestion, this has to be more detailed and concrete then just a link to some nice webapp.

If you want a new theme, I recommend you to try to implement your own: https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md
