### ISSUE TITLE
External theme message hard to understand; shows unrelated(?) js code

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#812]
I wonder what this message is telling us.

- "loaded for the wide internet" probably means "loaded from an external source that is not controlled by the mapcomplete project"? I wonder if that is really helpful at this point. I think/hope the json files are excaped before using, so is there any relevant attack vector? And if so, the message should be a pre-loading message like "do you trust <url> and want to load the json, that could…".
- I don't understand the JS code. What code is that actually? It's not from the external source, is it?
- Issue tracker: Should this be a relevant info, a link would be good.

Suggestion:
I could image the message being simplified to …

> This theme is based on the external configuration `URL`.

And maybe an external theme should have a required contact option so that could be liked there.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/111561/166638480-b7dbc711-73c6-44bb-87e0-dabdf5d78cad.png">

**Comment by pietervdvn** [comment]
Hi,

The custom javascript is from the 'note import layer'. For every layer, a new companion layer is created automatically which parses OSM-notes and checks if they are an import candidate. [Examples of these notes can be found here](https://mapcomplete.osm.be/toerisme_vlaanderen?z=13&lat=51.11984&lon=4.456501&language=nl); a single one is [e.g. this one](https://www.openstreetmap.org/note/3023064)

And no, these files are _not_ escaped. If the `calculatedTags` do contain code to siphon of the access token or to install malware, it'll just do that.

The maintainer field could be used for contact information.

**Comment by pietervdvn** [comment]
The javascript warning won't show up anymore as the import layers have been disabled for unofficial themes.
