### ISSUE TITLE
OSM for the blind

### ISSUE THREAD

**Issue by Justine567** [pietervdvn/MapComplete#819]
Accurate environment data is one of the most important navigation aids for blind and visually impaired people and essential for independent navigation.
In order to lower the threshold on entering barriers (e.g. barriers, lowered curbs) or aids (signal lights, guidance systems for the blind) in OSM and to recruit new mappers  ( on mapping events)  we kindly ask to add the topic "OSM for the blind" as a new theme.
Find more information and Attributes on: https://wiki.openstreetmap.org/wiki/OSM_for_the_blind

Our next mapping event ( on this topic) is planned for the 21st and 23rd of June 2022. We would love to use MapComplete for these and future events.

**Comment by joostschouppe** [comment]
Hi Justine,
@pietervdvn builds this tool in his free time, except when someone is interested enough in a project to pay him to build a theme or a feature. While accessibility is on the roadmap, it might take a while for a theme to get built. Some basic stuff is already there, for example, this [theme about entrances](https://mapcomplete.osm.be/entrances.html?z=20&lat=50.7374&lon=4.239057&language=en#node/7581118567) already allows to add details about those. I think the theme you propose would absolutely be welcomed, if someone builds it or pays for someone to do so.
Building (parts of) a theme is not that  hard! There's a small community of people who are able and willing to help out, but aren't able to build everything that is requested by themselves.

**Comment by pietervdvn** [comment]
Hi,

Thanks for your suggestion. However, if I would build every request I got, I would need about 500hrs/week. There are simply to much types of objects to create themes for them all by myself.

This is why I ask your help: read through [the documentation](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Making_Your_Own_Theme.md) and maybe create a relevant layer? Once you have a first layer, you'll be able to expand on this.

**Comment by RobinLinde** [comment]
I do have a theme about kerbs and some more detailed mapping of crossings somewhere locally, those layers might be of use, I'll see if I can find them.

**Comment by Justine567** [comment]
> Hi Justine, @pietervdvn builds this tool in his free time, except when someone is interested enough in a project to pay him to build a theme or a feature. While accessibility is on the roadmap, it might take a while for a theme to get built. Some basic stuff is already there, for example, this [theme about entrances](https://mapcomplete.osm.be/entrances.html?z=20&lat=50.7374&lon=4.239057&language=en#node/7581118567) already allows to add details about those. I think the theme you propose would absolutely be welcomed, if someone builds it or pays for someone to do so. Building (parts of) a theme is not that hard! There's a small community of people who are able and willing to help out, but aren't able to build everything that is requested by themselves.

**Comment by Justine567** [comment]
Thank you @joostschouppe and @pietervdvn for your suggestion and documentation. We will have a look into it and evaluate how much can be done by us or commissioned.

@RobinLinde Thank you for offering and searching for your layers. That would be very helpful! Especially lowered kerbs are extremely critical for save navigation.

**Comment by RobinLinde** [comment]
Kerbs and their details are now also in the Kerbs and Crossings theme: https://mapcomplete.osm.be/kerbs_and_crossings.html

I've actually started combing and tweaking some layers in a test theme over here: https://mapcomplete-git-feature-osm-for-the-blind-robinlinde.vercel.app/blind_osm.html
Currently it shows the kerbs, some public transport stops and crossings, with an indicator for tactile paving, and some questions about various accessibility features.
