### ISSUE TITLE
make anonymous contributions possible via semi-structured notes

### ISSUE THREAD

**Issue by seppesantens** [pietervdvn/MapComplete#821]
For new users that are pointed to a MapComplete to make a quick edit 'in the field', it's often a big barrier to first create an OSM account. While [anonymous (non-tracable) map edits](https://wiki.openstreetmap.org/wiki/Anonymous_edits) are not a good idea, we could capture contributions from not (yet) logged-in users in anonymous, semi-structured notes. These notes have already been used by MapComplete to do [assisted imports](https://wiki.openstreetmap.org/wiki/MapComplete#Running_an_assisted_import_with_MapComplete). We could still nudge contributers to log in, but also allow creating notes without an account or a login.

**Comment by pietervdvn** [comment]
My two cents on this: we know the barrier for signing up is large. We should try to lower this barrier by making the sign-in process easier - which requires us nagging the OSMF and OWG.

There are lots of fronts on which this can be improved:

- Being able to run the login flow in an iframe
- When signed up, make sure that the confirm-email comes instantly instead - right now this takes a few minutes
- If signed up per email, prepare a link people can click to take them to their inbox. Many (big) email providers expose the search-state in their URL, which means we could send them over to the search only showing the signup email (e.g. [Gmail](https://mail.google.com/mail/u/0/#search/openstreetmap)). Using this trick, we'll lose less people which are distracted by their other emails. This could be a small stand-alone project to gather those, similar to the ELI.

I'm not very inclined on implementing this issue with anonymous notes, as:

- It's quite a bit of programming work
- This is gonna put extra burden on the community (which we burden already enough with the import notes)
- We'll have to provide a way to easily apply these notes (which is error prone)
- Some contributors will simply mass-apply them all, becoming anonymous edits by proxy
- By not having an account, we cannot get back to the anonymous contributor and cannot try to pull them back into OSM.
- Making the import process smoother will improve OSM as a whole.

So, I'm probably not gonna make this - but if someone implements this completely and makes a PR, I would still merge this in.
