### ISSUE TITLE
New theme 'highway=speed_camera'

### ISSUE THREAD

**Issue by Thierry1030** [pietervdvn/MapComplete#824]
Hello everybody,
I'm thinking of creating a new theme 'highway=speed_camera'.
If somebody is interested in this theme and/or it might be combined with other themes (maxspeed=* ?) please tell me.
Pieter showed me in the meantime how to add a feature to an existing theme.

**Comment by RobinLinde** [comment]
I've got a working example in the `feature/speed-camera` branch, where it's added as a new layer to the maxspeed theme. Demo available [here](https://mapcomplete.osm.be/theme.html?userlayout=https%3A%2F%2Fgist.githubusercontent.com%2FRobinLinde%2F7aac9aea7988577530c06787521d5c5b%2Fraw%2Fb60519666fbe3819112c9bfa78a6dad7bb728f75%2Fmaxspeed.json).
