### ISSUE TITLE
Adding pump seems to fail

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#83]
I added two pumps yesterday with the tool, and both times it failed to write the service:bicycle:tools=no tag. So this question still showed when I checked today "Which services are available at this bike station?"
https://www.openstreetmap.org/node/7780958104
https://www.openstreetmap.org/node/7781027538
In both cases the image also failed to be added (I seem to remember double-checking that it was associated to the object, but I can't be sure).
I also added this cycle rack: https://www.openstreetmap.org/node/7781000357
Here the image worked, but the capacity tag failed to be saved! (I distinctly remember filling that out)
I tried from home now, and after making edits on mobile, the "Saving" warning just kept being visible on the screen. (Firefox on Android)
Edits on the PC (Firefox on Windows) did work.
Edits on Chrome on Android did work as well. However, there the Locate me button didn't work!

**Comment by pietervdvn** [comment]
I had a look to all the flow of how saving works, things should have improved now (there was an interplay of various small bugs at work).
