### ISSUE TITLE
Genus vs species in new tree layer

### ISSUE THREAD

**Issue by matkoniecz** [pietervdvn/MapComplete#830]
Is it a good idea to tag genus of trees into `species:wikidata`?

Some people complained, so I started using `taxon:wikidata`

There is also `genus:wikidata`

**Comment by pietervdvn** [comment]
What does the wiki say about this? I chose species as that one has the most entries (25k) according to taginfo.

Feel free to send a PR, but we should make sure that the old data is still shown, either by retagging all or by rendering it.

**Comment by matkoniecz** [comment]
I am not considering either version as superior and I am not planning to make PR - I started using `taxon:` as taxonomy is a horrific quagmire.

I just wanted to let you know that I run into it before with some people complaining.
