### ISSUE TITLE
UK Address theme: House number and name questions not showing

### ISSUE THREAD

**Issue by RobJN** [pietervdvn/MapComplete#832]
On importing an address it used to pop up the housenumber question and if "This building has no house number" was selected it would pop up the housename question. This is no longer happening - the questions don't pop up at all and the user has to click the pencil icon to bring them up. This is confusing for new novice mappers.

I have tracked the error down to this change: 
https://github.com/pietervdvn/MapComplete/commit/fe8c63d7628019e798c65451df8e377618dc28b1#diff-1d7774058445100b25d3bd4cdf1d9abd355c58d5ae3326dd4d7555a1c8f59bd8

@pietervdvn : Just reverting the edit to the UK Addresses json seems to fix this (when I encode the previous theme JSON in Base64 and test that way). I don't think that reverting is the right solution as you obviously made a change for a reason :-). Can you help so that we can get these questions showing up again please?

P.S. I don't understand some of the tags you introduced (e.g. not:addr:unit) but I assume you had your reasons for adding them.

**Comment by pietervdvn** [comment]
This change was made due to an extra check I added as not to have dead mappings. In the previous case, some items would never show up (i.e. the 'No housenumber known') which was in spirit with the original setup.

The 'nohousenumber' tags are to indicate that a contributor marked these buildings explicitely as having no house number.

Dropping the mappings with `if: housenumber=, then: The housenumber` will revert the behaviour to asking questions if they aren't known.

**Comment by RobJN** [comment]
Hi @pietervdvn : There was a reason why e.g. "No housenumber known" didn't show up to the user; namely we didn't want it to. We preferred this user interface:

![image](https://user-images.githubusercontent.com/5060210/173391545-30290ef0-9fa5-4a77-bb7e-123c62aad31a.png)

Instead of what now shows:

![image](https://user-images.githubusercontent.com/5060210/173391676-5dbaad4c-d970-4aed-94c3-5dced080e13e.png)

That is to say, when no housenumber known, we wanted it to still show "House or building name" in light grey text.

Can you help me to understand what the issue with "dead mappings" is please? If it is cosmetic rather than a fundamental problem, then are you happy if I revert back to the previous behaviour as this is the user layout that our community thought worked best for this theme? Thanks

**Comment by pietervdvn** [comment]
If a user selects a value , it should always update the view too.

If a user would see `building or housename`, open it, confirm that there is no housename and see the same grey text again, this is confusing and a small percentage of user would think the update didn't go through and/or that the tool is broken.

(Note that it still shows the grayed-out "building or housename" if housename is not explicitly set to 'no housename)

I did build an automated check for this kind of things, which are 'dead mappings' and which did flag this issue.

We can still change the rendering (e.g. render 'this building has no housename' in grey too), but it should still make it clear that someone marked this building as not having a housename.

**Comment by RobJN** [comment]
We can understand that logic when you must answer all questions, but this
is not the case for UK addresses. Our own user feedback led us to the
solution that we had deployed until a few months ago. Is there anyway we
can get back to that please as it is our communities preferred user
interface? Thanks

**Comment by pietervdvn** [comment]
I suggest using "building or housename" for unanswered and "building or housename: this building was marked as not having a name" if 'no:housename=yes'.

**Comment by RobJN** [comment]
Ok. And just to check, I can do that by using all the "not:addr:*" tags you added (and the earlier no:housename=yes) without falling the "dead mapping" checks you have implemented? If so I will give that a go.

Would you accept something shorter like "building or housename: none"?

**Comment by RobJN** [comment]
Hi @pietervdvn : I went to make the changes today but ran in to another problem. If the user answers that there is no sub-unit (for the addr:unit tag) this adds a tag "not:addr:unit=yes" but this tag is not removed if the user then changes their mind adds a sub-unit. In this case MC ends up adding the addr:unit tag but does not remove the "not:addr:unit=yes" 

I'm getting a bit confused with the JSON format as it has been a few months since I looked at it last so cannot figure out how to fix this one on my own. What do I need to change to make it work (i.e. remove "not:addr:unit=yes" if addr:unit tag added)? Thanks

**Comment by pietervdvn** [comment]
Hi,

Indeed. I've fixed this in e45facf4

**Comment by pietervdvn** [comment]
> Would you accept something shorter like "building or housename: none"?

Yeah, as long as it is clear for the contributors that someone did mark it as not having a housename.

**Comment by pietervdvn** [comment]
With the pull request merged, I do think this issue is resolved; feel free to reopen it if there still is an issue.

**Comment by riQQ** [comment]
For reference, the mentioned PR is #901.
