### ISSUE TITLE
Wrong language label for traditional and simplified chinese

### ISSUE THREAD

**Issue by Supaplextw** [pietervdvn/MapComplete#841]
[zh_Hant](https://mapcomplete.osm.be/?language=zh_Hant) should be 正體中文 (Traditional Chinese), and [zh_hans](https://mapcomplete.osm.be/?language=zh_Hans) should be 简体中文(Simplified Chinese)

**Comment by pietervdvn** [comment]
I finally got around fixing this.

I'm using wikidata for these entries, is this correct as well? 

![image](https://github.com/pietervdvn/MapComplete/assets/1466478/bb77c8de-f1ea-4cc0-b751-9818d21212df)

**Comment by pietervdvn** [comment]
Confirmed fixed
