### ISSUE TITLE
Use Tailwind CSS `children:` variants

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#850]
The way this project is set up, Tailwind has a limitation to style nested elements.

With the new "arbitrary variants" feature (https://github.com/tailwindlabs/tailwindcss/pull/8299, https://twitter.com/adamwathan/status/1523345746421985281) we can add classes to a parent element and style the child span tag. To test this, we can use a config like  https://github.com/tailwindlabs/tailwindcss/blob/1402be2dd0cdc00745e24b45cea388bf7d37509f/tests/variants.test.js#L65.

In order to use this today, we need to use the dev preview of TailwindCSS.

A good candidate for testing is the login box; the text can now be centered.

---

I experimented with this locally but my changes are not ready for a PR. Wanted to create this Issue now, to let you know what can be done soon.

**Comment by pietervdvn** [comment]
@tordans Do you think this is still relevant? If not, this issue might be closed

**Comment by pietervdvn** [comment]
It seems like this is not relevant anymore, so I'm closing this issue.
