### ISSUE TITLE
Updates Tailwind to Version 3

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#851]
We should migrate to the newest version and update / cleanup the config while doing so.

The required changes are described by the update guide at https://tailwindcss.com/docs/upgrade-guide#configure-content-sources

If no one beats me to it, I will contribute a PR at some point; but don't know when, yet.

**Comment by pietervdvn** [comment]
Sounds good. At first glance, none of the functionality that needs updating is used; so I don't think updating will break anything.

Thanks again for keeping an eye on these updates!

**Comment by tordans** [comment]
FYI, the latest version is now released which includes the feature we are looking for 
- https://tailwindcss.com/blog/tailwindcss-v3-1 
- https://youtu.be/nOQyWbPO2Ds?t=1392

**Comment by pietervdvn** [comment]
Seems like the maplibre-port already uses tailwind >3.1, so this issue can be closed.
