### ISSUE TITLE
Introduce Prettier to the project

### ISSUE THREAD

**Issue by tordans** [pietervdvn/MapComplete#852]
I started to like using https://prettier.io/ (with the [Tailwind Prettier Plugin](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)) in all my projects. It takes a lot of mental load and save formatting time during development. And for a shared code base, it makes sure people format their contributions the same way.

In my opinion it would be a great addition to this project as well. What do others think?

---

Practically speaking, we would need to create one big "bring all files in line" commit. All future changes should then be formatted before commit, which could even be standardized [via Husky](https://prettier.io/docs/en/precommit.html#option-4-huskynethttpsgithubcomalirezanethuskynet) and CI checks.

**Comment by pietervdvn** [comment]
Hi,

Yes, that would be pretty great to do. I already experimented with similar setups, but never really finished those.

Ideally, this is done as a pre-commit hook.

Right now, I let my IDE do all the formatting and did a few such formatting commits.

At last, please be aware that some directories (especially `json`-files in the translation directory) _should not_ be formatted. This formatting is handled by the generateTranslation scripts, but I'm sure that can be configured.

**Comment by tordans** [comment]
_This is just for me for when I find the time to look into this:_ https://github.com/FixMyBerlin/fixmy.rsv/pull/50/files integrates Husky to run Prettier in a project I am working on. https://github.com/FixMyBerlin/fixmy.rsv/search?q=husky — It is likely we can use the same here.
