### ISSUE TITLE
Render a Mapillary layer

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#874]
This is based on a Twitter discussion, replicating here for documentation reasons and for future reference.

[Source on Twitter](https://twitter.com/asturksever/status/1535200605446234112)

> Please, can you point out how can I enable Mapillary imagery layer? When I click existing object, it pops up attribute table for the object.

Sorry, but a mapillary-layer is not available and not planned. The core of MapComplete is to keep it simple and to focus only on the objects fitting the theme. Adding a generic mapillary layer would detract from that goal.

Within the popup of a single object, it makes sense, but only to select images associated with the object. If you want to edit with the mapillary-layer, iD does a great job on that.

At last, there is a tiny 'open in mapillary'-button hidden in the attribution or - if you're on mobile - via the 'help'-menu under the copyright-tab.

**Comment by thibaultmol** [comment]
I guess for armchair mappers, being able to see what areas have mapillary imagery available, from within Mapcomplete (just an overlay with the green lines, no interactivity) could be interesting

**Comment by pietervdvn** [comment]
> I guess for armchair mappers

For armchair mappers, there is an excellent online editor available. It's called iD and its available right from the OSM.org homepage. And they do render the mapillary layer right if you enable it in settings. Furthermore, it offers way more presets.

Simply put: adding the mapillary layer will distract and confuse new/non-technical mappers and shifts the focus to much towards the editing part of OSM.
