### ISSUE TITLE
Popup close button not clickable when using small width screen

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#876]
When mapcomplete is used on a device/window with a small viewport (where the right-top ui element (profile) has to go underneath the the top-left (search bar)). It causes the Close button of the popup no be behind one of those ui elements
Current behavior:
![Screenshot_20220610_175511](https://user-images.githubusercontent.com/1010226/173105383-f97ff222-75db-4094-8e3a-fa8ae49afa01.png)

Expected behavior:
![Screenshot_20220610_175533](https://user-images.githubusercontent.com/1010226/173105390-69ca3347-8e6a-4798-a42e-1bb280c6aa47.png)

**Comment by pietervdvn** [comment]
This is a known issue which cannot be fixed at the moment.

**Comment by pietervdvn** [comment]
With the new sidebar-layout, this issue is resolved
