### ISSUE TITLE
"Add a new point?" dialog should have a bigger map on mobile

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#877]
Right now it looks like this:
![Screenshot_20220610_180019](https://user-images.githubusercontent.com/1010226/173105774-64317798-6cec-4718-9ea7-0933a485d5e8.png)
But it makes it difficult on mobile if you want to zoom in on the map. But the rest of the screen isn't in use.
So I figure it might be better if it was like this: 
![Screenshot_20220610_180653](https://user-images.githubusercontent.com/1010226/173106813-217d8cbf-f8df-4dd6-b4fd-b60740a69046.png)

**Comment by pietervdvn** [comment]
Some presets _do_ use the extra space to give a detailed explanation of the POI:

![image](https://user-images.githubusercontent.com/1466478/173188508-86ac13c9-e53c-4130-a16d-2323dcebc73a.png)

2. Extremely low-height-devices might not show the 'cancel'-button anymore or even the 'confirm-button' if the map gets an increased height. These low-height-devices are less common in the western world nowadays, but not necessarily in other regions.

That being said, a slight increase in size (coupled with a `max-height: 50vh`) doesn't hurt.

**Comment by thibaultmol** [comment]
I don't think it's changed?
![Screenshot_20220617_224440](https://user-images.githubusercontent.com/1010226/174398801-5b538f33-ac3e-434e-b4bd-9971f3ad3f00.png)
Image from firefox devtools mobile size.

**Comment by pietervdvn** [comment]
This flow has been revised with the MapLibre port, the map got it's own step and plenty of space.
