### ISSUE TITLE
Filter Wikimedia commons images (no photos of people for example)

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#878]
Encountered an interesting thing today
https://mapcomplete.osm.be/postboxes.html?z=18&lat=51.04698&lon=3.744782&language=en&tab=1#node/2225103159
![image](https://user-images.githubusercontent.com/1010226/173117509-12dd405c-f18e-42af-9268-af838fc5d49e.png)

The nearest image is a headshot of an actor. I looked on the commons page, I don't know fully how Commons works, it doesn't seem like the data can tell you that it's a person. but the common page itself is listed under actors. So maybe there is some possible filtering possible there?
![Screenshot_20220610_191200](https://user-images.githubusercontent.com/1010226/173117621-51d9f564-9409-493f-bfa1-ba1adc28902e.png)

**Comment by pietervdvn** [comment]
At this moment, there is very little possibility to filter these images as no structured data exists indicating it is a protrait.

Furthermore, I'm relying on the [Pic4Carto-library](https://framagit.org/Pic4Carto/Pic4Carto.js), so this issue is best fixed over there.

**Comment by thibaultmol** [comment]
Issue created upstream https://framagit.org/Pic4Carto/Pic4Carto.js/-/issues/41

**Comment by PanierAvide** [comment]
Well in fact this must be solved on your side, as Pic4Carto.js already offers a parameter to filter out some pictures fetchers :

```js
var picManager = new P4C.PicturesManager({ ignorefetchers: ["wikicommons"] })
```

Best regards

**Comment by thibaultmol** [comment]
@PanierAvide Doesn't that just filter out all of Commons?
Commons has useful imagery to tie to osm. But I was asking more about filtering out specific categories of Commons imagery

**Comment by PanierAvide** [comment]
Alright, we can discuss on Pic4Carto repo then, a good solution to this would be to add a new parameter to choose categories to filter out of Wikimedia Commons results.
