### ISSUE TITLE
Have a popup or some other indicator to show that OSM is down for maintenance atm

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#880]
Otherwise people might think the tool is broken, while it's just osm that's down.

**Comment by pietervdvn** [comment]
For this, I'd need an API indicating the status.

Would you mind asking if and where such an API is to [the engineering team over here](https://github.com/openstreetmap/operations/issues)?

**Comment by thibaultmol** [comment]
Seems like they just want applications to rely on the error messages.

**Comment by mnalis** [comment]
They [do say](https://github.com/openstreetmap/operations/issues/644#issuecomment-1159368910) that HTTP response codes do come with human-readable message, which could be shown to user without too much work.

On advanced side, https://wiki.openstreetmap.org/wiki/Platform_Status mentions several resources like http://uptime.openstreetmap.org/ which should show if OSM API or tiles services are down (and it seems to use third-party which has API available https://www.statuscake.com/api/v1/)

**Comment by thibaultmol** [comment]
I didn't know osm had an uptime page. Btw, that info page is provided by Statuscake, which does on it's own have an api: https://www.statuscake.com/api/

**Comment by mmd-osm** [comment]
Just came across this somewhat related discussion with JOSM: https://josm.openstreetmap.de/ticket/22138

**Comment by pietervdvn** [comment]
This can be mimicked by using uMatrix. Note that, if the OSM-API-tilefetcher is enabled, the application will loop and hang the browser.

**Comment by mmd-osm** [comment]
NB: We typically only consider endpoints underneath api.openstreetmap.org to be part of the osm api. Tiles are served by another url, therefore are not part of the osm api.
