### ISSUE TITLE
Be able to limit postfixes/prefixes to given language/country

### ISSUE THREAD

**Issue by Codain** [pietervdvn/MapComplete#893]
Background: Etymology theme.

Today prefixes and postfixes are a long list shared with all languages, which can make difficult to maintain and avoid conflicts (where something can be a postfixe in a language but not in another one). The idea would be to be able to split pre/post fixes in lists per language.

Option 1: Compare with editing language. Not ideal but probably the easiest option and a good compromise.
Option 2: Define areas/countries where a list of pre/post fixes applies.
Option 3: Use default_language value of any way/relation which include this object when available. Not sure it is widely used and how to manage multiple official languages or ways overlapping.

**Comment by pietervdvn** [comment]
I went for option 1
