### ISSUE TITLE
Use dropdown list instead of freeform field for "school:language" in new school theme

### ISSUE THREAD

**Issue by OliNau** [pietervdvn/MapComplete#898]
Hello,

Currently the "school:language" theme uses a freeform field to enter the language being used by the school. This causes problems because it isn't clear in what format the language should be entered. I, for example, mistakenly first entered a shortened language code (nl,fr,etc) instead of the full language name in English. 

Besides this, it is very tempting to enter the language in the local language if the user uses a translated version of mapcomplete. For example:
![taal](https://user-images.githubusercontent.com/19350388/175439680-83524cc6-e71b-4096-a41e-c4b304dd06c2.PNG)

To prevent users from entering bad values, I think a dropdown list with the most used languages should be presented. Besides this a freeform field could be shown if the wanted language is not in the list, but clear formatting guidelines should be shown (i.e. in English and all lower caps.)

**Comment by pietervdvn** [comment]
A new fancy selection tool showing the appropriate languages has been implemented.
