### ISSUE TITLE
Add icon for equestrian sport in sport pitch layer

### ISSUE THREAD

**Issue by Hufkratzer** [pietervdvn/MapComplete#920]
It seems that there is an icon missing in the sport pitch layer for sport=equestrian.

I made one for you: https://gist.github.com/Hufkratzer/81abcfe749ce8f99257e38f58633dd72

I tried to make it in a similar style like the other icons in that layer.

Feel free to change/adapt/improve it if you like.

**Comment by pietervdvn** [comment]
Hi,

That is really nice of you!

Before I'll add it in, I'd like to know what license your icon is. That way, if some other project would like to reuse your icon, they know if they can or not.

The rest of these icons are CC-BY-SA - the creative commons license which requires anyone using your icon to also mention your name and -if they make modifications to your icon- to share these modification under CC-BY-SA as well.

**Comment by Hufkratzer** [comment]
This is public domain; anyone can use or change it without mentioning me.

**Comment by pietervdvn** [comment]
![image](https://user-images.githubusercontent.com/1466478/177569552-a7d49157-1e29-4048-9d48-c5bb56f7b143.png)
Here you go!

**Comment by pietervdvn** [comment]
Thanks for your contribution!

The icon has been pulled in and is in the pipeline, it should be live in ~20 minutes. (Note that service-worker-caching is quite aggressive, open MC in a private tab if it doesn't seem to update)
