### ISSUE TITLE
Adding a layer showing doctors

### ISSUE THREAD

**Issue by pietervdvn** [pietervdvn/MapComplete#921]
What relevant information is there to know about a doctor?

- [x] Opening hours
- [x] Contact information (phone, email, website)
- [x] [Speciality](https://wiki.openstreetmap.org/wiki/Key:healthcare:speciality) such as: 
  * [healthcare:speciality=general](https://wiki.openstreetmap.org/wiki/Tag:healthcare:speciality%3Dgeneral) for a general doctor
  * healthcare:speciality=[gynaecology](https://wiki.openstreetmap.org/wiki/Tag:healthcare:speciality%3Dgynaecology) for a gyn
  * healthcare:speciality=[psychiatry](https://wiki.openstreetmap.org/wiki/Tag:healthcare:speciality%3Dpsychiatry) or [healthcare](https://wiki.openstreetmap.org/wiki/Key:healthcare)=[psychotherapist](https://wiki.openstreetmap.org/wiki/Tag:healthcare%3Dpsychotherapist)
  * healthcare:speciality=[paediatrics](https://wiki.openstreetmap.org/wiki/Tag:healthcare:speciality%3Dpaediatrics)
- [x] Set the name of the doctors
- [x] Add presets

**Comment by thibaultmol** [comment]
Just a brainstorm question: general healthcare (so also hospitals, pharmacies, dentists etc) theme instead?

**Comment by pietervdvn** [comment]
Add presets

**Comment by pietervdvn** [comment]
@thibaultmol This was a first issue to get the OSOC-students to know how to work with MapComplete. Some more medical items will be added soon.
