### ISSUE TITLE
Artwork: Show name (and other tags) in popups

### ISSUE THREAD

**Issue by plepe** [pietervdvn/MapComplete#93]
You commented on my blog post https://www.openstreetmap.org/user/skunk/diary/393826, that you have this artwork viewer. Very nice, indeed!

What I miss, is further information in the popup, e.g. the name of the object, and maybe other information.

Would it be possible to add this?

**Comment by pietervdvn** [comment]
I've added a textfield that asks the wikidata-entry. (One day I'll have full search and linking).

If you want to, have a look at [ŧhe theme definition](https://github.com/pietervdvn/MapComplete/blob/master/assets/themes/artwork/artwork.json) to add another question, rendering or translations to your favourite language.

**Comment by plepe** [comment]
What I mean: This is the popup for object https://osm.org/node/3513154212: 
![Screenshot_2020-08-31 Open Artwork Map](https://user-images.githubusercontent.com/249012/91695977-374e5880-eb6f-11ea-91d0-2a5ff41d9bf6.png)
It has the name "Irene-Harand-Denkmal". It would be nice to show this to users ...

**Comment by pietervdvn** [comment]
I've added the name in the title.

I'm a bit afraid of creating a question with name too, as these get typically filled with a description (and not a name).

![image](https://user-images.githubusercontent.com/1466478/92051446-2b3fe200-ed8d-11ea-8be1-1e1adaec0556.png)

**Comment by plepe** [comment]
Yes! I like it a lot :-)

I think that a question for a name is not necessary. I would think, that the name is one of the first things which are mapped. But there are many pieces of artwork which do not have a name ...

**Comment by pietervdvn** [comment]
Hey,

Glad that you like it!

Most pieces do have a (really obscure) name. Also keep in mind that MapComplete can be used to easily _add_ new pieces of artwork on the road (I've done it a few times now), then a question for a name isn't out of place.

**Comment by plepe** [comment]
True. Maybe first ask for a description and then for a name?

**Comment by LennertSchepers** [comment]
Hi @pietervdvn I came across this issue, and want to mention that miss an (optional) question to add a name. Some artworks do have an official name (e.g. https://www.veilig9040.be/slowlife/). My current workflow would is to add an artwork with mapcomplete on mobile phone, but to add a name I have to open my laptop to add the name in ID.

Would you agree adding the name as a question? Is that something you can add, or should I look to open a pull request (that would take me quite some time).
