### ISSUE TITLE
Cyclofix: send email notification to operator when bicyclepump is broken for example

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#957]
Just idea I had. Obv a lot of work and tricky to implement well. But yeah.
Maybe a mailto link to report it, with prefilled subject and body could be a good way to easily report it, without having the 'liability' of sending emails as mapcomplete

**Comment by pietervdvn** [comment]
This is already implemented:

![image](https://user-images.githubusercontent.com/1466478/179207988-fb558593-6df4-4e2c-a708-7544645a35ad.png)
![image](https://user-images.githubusercontent.com/1466478/179208036-9ce47de6-c25f-4538-af6c-098eab008aea.png)

This message will appear if the operator email address is known and if the pump is defective.

**Comment by thibaultmol** [comment]
Whoops, sorry. Cool that it's already a thing, i'd never looked at a broken one to actually see this yet. 
Nice!
