### ISSUE TITLE
Allow to zoom beyond basemap constraints

### ISSUE THREAD

**Issue by joostschouppe** [pietervdvn/MapComplete#97]
When adding a POI, it is hard to put the marker in the exact space. Just being able to zoom in more makes it a lot easier, if it makes the map a little blurry

**Comment by thibaultmol** [comment]
+1 on this
and maybe to add to that: show a tooltip for new users when they are at that deep blurry zoomlevel that "there might be better layers available" and in Belgium's case that could GRB
