### ISSUE TITLE
'Zoom in to see this layer' should maybe be a button 

### ISSUE THREAD

**Issue by thibaultmol** [pietervdvn/MapComplete#976]
I realized I never made a github issue on this. Originally when I used mapcomplete, I thought that the 'zoom in to see this layer' text was a button that auto zooms to the zoom level that I can see that layer. But it doesn't do that, it just toggles the layer.

![image](https://user-images.githubusercontent.com/1010226/179939079-bd0cfae9-7a4e-4075-ad30-522561c3d08a.png)

**Comment by pietervdvn** [comment]
When using on mobile, the layers panel will open full screen. The 'zoom in to see this layer'-button will seemingly do nothing then.

Furthermore, it should also toggle the entire layer when pressed, so this behaviour will not change.

**Comment by thibaultmol** [comment]
hmmm, I personally would imagine the UX to actually close the layers panel when you click "zoom into see this layer".
