### ISSUE TITLE
Missing fountains on https://mapcomplete.osm.be/drinking_water.html

### ISSUE THREAD

**Issue by kaipankrath** [pietervdvn/MapComplete#979]
The current view for "Drinking Water" includes amenity=drinking_water nodes and ways only. However there are amenity=fountain nodes having the additional tag drinking_water=yes and they should be included. Overpass example for the area I live in:
```

[out:json][timeout:90];
(area["name"="Basel-Stadt"][admin_level=4]; )->.city;
(
  way["amenity"="fountain"]["drinking_water"= "yes"](area.city);
  node["amenity"="fountain"]["drinking_water"= "yes"](area.city);
);
(._;>;);
out meta;
```

That reveals six additional sources for drinking water - not much, but it might be even more in other areas. It might be worth considering node and ways having amenity=drinking_water or drinking_water=yes (for the latter I found "toilets" as another example).

**Comment by pietervdvn** [comment]
Hi,

Thanks for your report. Currently, I'm very busy and I'm trying to get as much people to help me to make the presets. The more helping hands, the better.

You can update the [specification of what tags to query too](https://github.com/pietervdvn/MapComplete/blob/develop/assets/layers/drinking_water/drinking_water.json). Then, open a pull request. The [format of the tags can be seen here](https://github.com/pietervdvn/MapComplete/blob/develop/Docs/Tags_format.md)

**Comment by pietervdvn** [comment]
Fixed by PR
