### ISSUE TITLE
Photo attribution is rendered black on black

### ISSUE THREAD

**Issue by Discostu36** [pietervdvn/MapComplete#984]
Photo attribution for Wikimedia Commons images is rendered black on black and is therefore illegible.

![grafik](https://user-images.githubusercontent.com/30999326/180409279-17df981d-c873-4469-a558-c21914f311b3.png)

**Comment by pietervdvn** [comment]
I cannot reproduce this issue.
What browser are you using?

![image](https://user-images.githubusercontent.com/1466478/185456356-814ba3d9-107b-4d8a-bfba-fa6ba8c65996.png)
https://mapcomplete.osm.be/playgrounds?z=20&lat=54.32848&lon=10.12224&language=nl#way/12386405

**Comment by Discostu36** [comment]
Firefox. There seem to be multiple CSS issues. The popup is also rendered full screen in contrast to Chrome rendering.

**Comment by pietervdvn** [comment]
What is the version and what is your screen size and default zoom?

**Comment by Discostu36** [comment]
Not fixed for me.

**Comment by pietervdvn** [comment]
> Not fixed for me.

Not yet on master, should be fixed on pietervdvn.github.io/mc/develop
