### ISSUE TITLE
cycle_infra: Don't use undocumented tags (or document them)

### ISSUE THREAD

**Issue by Discostu36** [pietervdvn/MapComplete#985]
The cycle_infra theme uses the tag `separation` that is not documented on the wiki. Undocumented tags are not very useful for the project. Please document the tag and its values, or remove it from the theme.

**Comment by tordans** [comment]
About the documentation: The best wiki page for this tag is https://wiki.openstreetmap.org/wiki/Proposed_features/separation for now. The tag is experimental (as in, people are still figuring out how to best tag what we want to tag … and document what we learn). The wiki page changed quite a bit in recent days to incorporate what we learned until now. [We](https://wiki.openstreetmap.org/wiki/Berlin/Verkehrswende) are collecting more feedback and doing more experiments with this.

**Comment by Discostu36** [comment]
Thanks, I have created two redirects on wiki to make this proposal more visible.

**Comment by RayBB** [comment]
@Discostu36 can this be closed now?

**Comment by Discostu36** [comment]
Yes.
